app/routes/overview/components/LatestReadme.css, app/routes/overview/components/Overview.css, app/routes/overview/components/Overview.tsx
Fixes the styling of the large readme on the frontpage
By moving the style to a new class smallReadme, now looks as in #3794 
---
Resolves ABA-419
=> Fix big readme style on public frontpage

app/routes/events/EventDetailRoute.ts
It causes big issues with loading. For some reason the history
replacement produces hundreds of LOCATION.CHANGE events.
Please write a summary of the changes, and please include relevant motivation and context. Remember to label your pull request properly; e.g. **bug-fix**, **new-feature** or **docs**.
If you've made visual changes, please include **before** and **after** images, preferably with a description. Make sure they do not contain any real user information.
---
=> Temporarily disable event slug rerouting

app/routes/surveys/SubmissionsRoute.ts, app/routes/surveys/components/AdminSideBar.tsx, app/routes/surveys/components/Submissions/SubmissionPage.tsx, app/routes/surveys/index.tsx
The exact same problem as in this PR: https://github.com/webkom/lego-webapp/pull/3803
It no longer crashes.
Before:
After:
---
Resolves ABA-425
=> Fix crash on survey results page

app/routes/events/components/EventEditor/index.tsx
Link to the [arrangementskalender](https://abakus.no/pages/arrangementer/86-arrangementskalender) page from checkbox in `EventEditor` for easy access. Links are added both in the label and tooltip.
**Before**
**After**
**Before**
**After**
Clicked the links and created an event just to be sure, even though the only changes are in the label and tooltip.
---
Resolves ABA-383
=> Link to arrangementskalender page from checkbox

app/components/EventItem/index.tsx, app/components/Icon/Icon.css, app/components/Icon/index.tsx, app/components/Upload/ImageUpload.tsx, app/components/Upload/UploadImage.css, app/components/UserValidator/Validator.css, app/components/UserValidator/index.tsx, app/routes/admin/groups/components/GroupMembersList.css, app/routes/admin/groups/components/GroupMembersList.tsx, app/routes/admin/groups/components/GroupPermissions.tsx, app/routes/bdb/components/BdbDetail.tsx, app/routes/bdb/components/SemesterStatusContent.tsx, app/routes/bdb/components/SemesterStatusDetail.tsx, app/routes/bdb/components/bdb.css, app/routes/polls/components/PollEditor.tsx, app/routes/surveys/components/SurveyEditor/Question.tsx, app/routes/users/components/UserSettingsOAuth2.css, app/routes/users/components/UserSettingsOAuth2.tsx
There is a lot of custom styling for different looks of icons. Now we have the option of using the danger, edit or success prop, which adds common styling for the icons with this prop.
Mostly, the changes are not visual except some changes of sizes and the fact that the icons in FontAwesome and IonIcons are different. Some of the visual changes are provided below, but check out the branch if you want to see them all, or let me know in the comments.
The following change affects Abacard:
**Before**
**After**
**Before**
**After**
Examples of changes because of the icon library used:
**Before**
**After**
**Before**
**After**
This pencil icon is not the nicest imo., but the only other possible option I find on IonIcons is this one:
I have visually compared all the changes with prod.
--- …
=> Extend Icon component with more props

app/actions/EventActions.ts, app/components/Chart/PieChart.tsx, app/reducers/events.ts, app/routes/events/EventListRoute.ts, app/routes/events/components/Event.css, app/routes/events/components/EventAdministrate/Statistics.tsx, app/routes/events/components/EventAttendeeStatistics.css, app/routes/events/components/EventAttendeeStatistics.tsx, app/store/models/Event.d.ts
[Implement Plausible analytics into event statistics](https://github.com/webkom/lego-webapp/pull/3840/commits/134dfc9e8f77ec1ea58ed28ab8765717f25e116c)
Very useful for publicity.
Considering removing "event duration" later since it doesn't really make sense.
Might also implement "bounce rate", but not sure how useful that is.
Since it's a new feature, it should not break anything else.
=> Implement Plausible analytics into event statistics

.drone.yml
=> Add dummy Plausible api key to drone step

app/routes/overview/IndexRoute.ts
There is a bug where the frontpage doesn't reload after logging in, so some data is missing. The poll doesn't show results, and the quotes-component looks like it is perpetually loading.
This fixes it by adding `props.loggedIn` to the dependency array of the `withPreparedEffect` responsible for loading the frontpage. This means the frontpage will reload every time that prop changes.
After the fix, the frontpage loads normally after logging in:)
---
=> Fix frontpage not loading correctly after logging in

app/components/Modal/ConfirmModal.tsx, app/routes/surveys/components/SurveyEditor/SurveyEditor.tsx, app/routes/surveys/components/surveys.css, app/utils/validation.ts
This was very buggy. It was calling a function `destroy()` that didn't exist, that I couldn't even find it in old code, so idk how that has ever worked. The template picker dropdown also has a hidden button, that it was still possible to hit, causing the dropdown to be toggled twice and instantly close again. This is a super hacky workaround and should definitely be refactored later on, but for now I set the height and width to 0 so that it is impossible to hit.
It is actually possible to use the survey templates again.
Seems to work locally:)
---
Resolves ABA-465
=> Fix survey template picker

app/components/Header/Header.css, app/components/Header/ToggleTheme.tsx
- Adds background hover effect to the theme change button in the drop down menu.
- Fixes clicking on the toggle theme button in the header not changing the icon of the button in the drop down and vice versa.
- Adds debounce to theme changing to prevent "glitchy" behaviour.
| -- | -- |
| ![image](https://user-images.githubusercontent.com/33326578/236696847-69148430-d9bc-40f9-96ab-f62f3e1a9405.png) | ![image](https://user-images.githubusercontent.com/33326578/236696824-bdc0133b-e890-4d14-9093-5684e7c53297.png) |
| Without background hover | With background hover |
| ![image](https://user-images.githubusercontent.com/33326578/236696963-50b69161-2b83-4239-abb9-7410ae99fefe.png) | ![image](https://user-images.githubusercontent.com/33326578/236696890-b5cd6163-165a-4987-8d49-0b …
=> Fix theme toggle button bugs

app/reducers/__tests__/reactions.spec.ts, app/reducers/reactions.ts
The added reaction didn't get the correct ID in the redux store. This made it impossible to un-react before reloading the page. 
It works now
Reacted and un-reacted
---
Resolves ABA-461
=> Fix bug where added reactions could not be removed before reloading

app/components/Image/Image.tsx, app/routes/overview/components/PublicFrontpage.tsx
Add support for dark theme source on the custom Image component using the new "darkThemeSource" argument.
Implement this for the Public Frontpage on the main sponsor.
---
Resolves ABA-390
=> Add support for dark theme source on images.

app/routes/meetings/MeetingCreateRoute.ts, app/routes/meetings/components/MeetingEditor.tsx, cypress/e2e/create_meeting_spec.js
When creating a new meeting one often have to set the date multiple times, both for the end time field and start time field. This commit changes the form to work similar to a lot of other meeting forms in changing the end time if one moves the start time past the end time. Also changes the default time to something more probable.
---
Resolves ABA-438
=> Move meeting end when setting start time after end

app/routes/surveys/components/Submissions/Results.tsx
The onChange function on our chart select was mutating the redux state it recieved as props. Sometime ago it looks like someone made the state read only, so this is no longer possible. Solved by simply making a deep copy of the objects we were mutating.
No visual changes(apart from making the button work again)
resolves ABA-240
=> Fix error with changing chart type

app/components/UserAttendance/AttendanceStatus.css
Somehow introduced in https://github.com/webkom/lego-webapp/pull/3876
But the weird part is that it only affects this one event shown below, and I can't find any other event where the bug occurs ... Nevertheless, this change fixes the bug and does not introduce any other bug, so ...
Tested on mobile, tablet and computer viewports.
=> Stop attendance box from growing

app/components/Chart/utils.tsx, app/routes/events/components/EventAttendeeStatistics.tsx, app/routes/users/components/passwordStrengthVariables.ts, app/styles/variables.css
[Update the chart colors](https://github.com/webkom/lego-webapp/pull/3977/commits/c1f5d38efe8de906c847c8eaf79a221ed7b15bc3)
They are now based entirely on our color palette, and will therefore both match the rest of the webapp better and work better on dark mode.
Also introduce a yellow and purple color palette. I did not spend too much time picking out these colors, so they might need to be iterated on. Nevertheless they seem fine.
---
[Update colors on the password strength bar](https://github.com/webkom/lego-webapp/pull/3977/commits/14ba5d8ab60d1ad7dde835e66dc8b1e1fa103fe6)
Overall I think it looks better - here's an average example:
<video src="https://github.com/webkom/lego-webapp/assets/69514187/d0bb36e5-ff32-4 …
=> Update the chart and password bar colors

config/webpack.server.js, server/index.ts
The main point of this is to remove the ReactRefreshWebpackPlugin that I unnecessarily added to the webpack server config a while back, but I figured I could also remove the hot reloading code from the server as it doesn't seem to be working. I removed instead of fixing it as I don't really see the need to have hot reload on the server, it is rarely changed much.
Removed some code from webpack config and server code
Hot reload still works in client-code.
=> Remove broken webpack hot reload from server

app/components/PhotoUploadStatus/index.tsx, app/components/Poll/index.tsx, app/components/Tooltip/Tooltip.css, app/components/Tooltip/index.tsx, app/components/UserGrid/index.tsx, app/routes/articles/components/ArticleEditor.tsx, app/routes/companyInterest/components/CompanyInterestList.tsx, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/events/components/EventAdministrate/AttendeeElements.tsx, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/EventEditor/index.tsx, app/routes/events/components/JoinEventForm.tsx, app/routes/events/components/RegisteredSummary.tsx, app/routes/photos/components/GalleryPictureEditModal.tsx, app/routes/polls/components/PollEditor.css, app/routes/polls/components/PollEditor.tsx, app/routes/users/components/StudentConfirmation.tsx, app/routes/users/components/UserSettingsOAuth2.tsx, app/styles/variables.css, cypress/e2e/poll_spec.js, package.json, yarn.lock
It is now no longer super buggy!
Firstly it will not overflow out of view when there is no space.
Through the `popper` library, it will find the most suitable postion.
No more need for the `renderDirection` prop and hacky calculations.
Another nice feature is that it will point to the right direction even
when the trigger component is flexed, which it often is. This is most
noticeable on tables.
Some minor styling changes as well, but that's not really the important
part of this change. Worth noting that there is no longer an annoying
buggy line between the arrow and the tooltip whenever there's a bad
render.
https://github.com/webkom/lego-webapp/assets/69514187/9a7480c8-7a5c-4220-8008-8252171098a0
Went through all uses of tooltips. Tried all viewports, hard refreshes and other "stress …
=> Greatly improve the tooltip component

app/components/Header/Header.css, app/routes/overview/IndexRoute.ts, app/routes/overview/components/CompactEvents.tsx, app/routes/overview/components/LatestReadme.css, app/routes/overview/components/LatestReadme.tsx, app/routes/overview/components/Overview.css, app/routes/overview/components/Overview.tsx, app/routes/overview/components/Pinned.tsx, app/routes/overview/components/PublicFrontpage.css, app/routes/overview/components/PublicFrontpage.tsx, app/routes/overview/components/utils.tsx, app/styles/overlay.css, cypress/e2e/home_page_spec.js
Small changes here and there that I believe improves it. Firstly it resembles the "private" overview page a lot more by using the same components. It feels less "square" without the heavy use of cards. I do not think this is perfect, but I thought the page needed some love, especially before next semester. I don't want to spend too much time on it right now.
Tested on different viewports. It now actually works better on mobile imo.
=> Slightly improve the public overview

app/routes/overview/components/Overview.tsx, app/routes/overview/components/PublicFrontpage.tsx
Add banner for fp-23, and change public fb-card from linking to an article to linking to ny.abakus.no.
I believe that the site is now good enough that it is better to publish it than wait, and rather iterate on the minor stuff later. Also starting to be about time that new students can find some sort of info.
Banner is now visible
---
=> Add banner and update public frontpage for fp-23

app/components/Tooltip/index.tsx
When there is space, I prefer to have it on top. It's also the more "common" placement.
https://github.com/webkom/lego-webapp/assets/69514187/da5203d5-2db7-40f1-87a5-942ea8aee087
It still works. See video above.
=> Set default tooltip placement to be top

app/components/Feed/types.ts, app/components/Header/index.tsx, app/components/HeaderNotifications/HeaderNotifications.css, app/components/HeaderNotifications/index.tsx, app/routes/app/AppRoute.tsx
[Rewrite NotificationsDropdown to a functional component](https://github.com/webkom/lego-webapp/commit/fda94f290f7671b00b05e21e515d79351a8ef465) 
And correctly type its props.
---
[Show a loading indicator when fetching notifications](https://github.com/webkom/lego-webapp/commit/332989da97f088aa47f5b187c2706ec62c619daa) 
Gives better feedback to the user, than stating that there are no
notifications. The content is now also centered properly.
https://github.com/webkom/lego-webapp/assets/69514187/4db47b0c-1381-46ce-9343-50d318c83983
See video above.
=> Show a loading indicator when fetching notifications

app/components/Header/FancyNodesCanvas.tsx
`addEventListener` and `removeEventListener` are methods provided by the `window` object in the browser, but not on the `global` object in a Node environment. This was causing a TypeError.
The fancy nodes still work.
---
Resolves https://github.com/webkom/lego/issues/3434
=> Replace `global` with `window` and ensure its existence

app/routes/pages/components/Sidebar.css, app/routes/pages/components/Sidebar.tsx
- Refactor the Sidebar component to utilize a hook
- The previous JSX and CSS was a mess. This looks much cleaner imo <3
- Make the sidebar fixed in mobile view in order to remove dead space.
- Fix a bug where the sidebar in mobile view would overflow vertically if too many tabs where opened
This sidebar looks basically the same for desktop view.
Proof that they look about the same:
**Before**
**After**
By making the sidebar fixed, you remove the "dead space" that would appear if a page was too long. This makes it so that the user doesn't have to scroll to the top of the page when opening the sidebar. It preserves the scroll of the page between opening and closing the sidebar.
**Before**
[Screencast1](https://github.com/webkom/lego-webapp/assets/66320400/c7b820ee-d9e4-4405-9bbe-5be017478d1 …
=> Refactor Sidebar

app/routes/events/components/EventEditor/index.tsx, cypress/e2e/create_event_spec.js, cypress/e2e/event_editor_spec.js
I don't see how the location has anything to do with the registration type. I have personally created an event where I knew the location but not the registration type, so this restriction is just annoying.
Tested that it works to create an event with a location but without any specified registration type.
=> Let users set event location before registration type

app/components/Button/Button.css, app/components/Button/index.tsx, app/components/Modal/ConfirmModal.tsx, app/components/Upload/ImageUpload.tsx, app/routes/admin/email/components/RestrictedMailEditor.tsx, app/routes/articles/components/ArticleEditor.tsx, app/routes/bdb/components/AddSemester.tsx, app/routes/bdb/components/CompanyContactEditor.tsx, app/routes/bdb/components/CompanyEditor.tsx, app/routes/brand/components/BrandPage.tsx, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/events/components/EventEditor/index.tsx, app/routes/events/components/JoinEventForm.tsx, app/routes/events/components/Toolbar.tsx, app/routes/events/components/UpdateAllergies.tsx, app/routes/joblistings/components/JoblistingEditor.tsx, app/routes/joblistings/components/JoblistingRightNav.tsx, app/routes/meetings/components/MeetingEditor.tsx, app/routes/pages/components/PageButtons.tsx, app/routes/photos/components/GalleryDetail.tsx, app/routes/photos/components/GalleryEditor.tsx, app/routes/photos/components/GalleryEditorActions.tsx, app/routes/photos/components/GalleryPictureEditModal.tsx, app/routes/polls/components/PollEditor.tsx, app/routes/surveys/components/SubmissionEditor/SubmissionEditor.tsx, app/routes/surveys/components/SurveyEditor/SurveyEditor.tsx, app/routes/users/components/GroupChange.tsx, app/routes/users/components/StudentConfirmation.tsx, app/routes/users/components/UserProfile.tsx, app/routes/users/components/__tests__/UserProfile.spec.tsx
[Introduce a secondary button type](https://github.com/webkom/lego-webapp/commit/147a3232bebfba4b8a6bddced1e3aa6d92790f0a) 
And make the `ghost` type look more like this.
The secondary button shares the color of the default text color, and it looks much more sharp with the darker color. It replaces a lot of success buttons, as it doesn't really make sense for submit buttons to be of type success. In my eyes it should be used on submit buttons and other buttons with "significant value" that should pop out more on pages.
---
[Update buttons across the webapp](https://github.com/webkom/lego-webapp/commit/8eed84dc11b49d3b232d0ed36320306652635593) 
Employ both the `flat` and `secondary` types more.
<table>
<tr>
<td>After</td>
<tr>
<td><img width="561" alt="image" …
=> Introduce a `secondary` button type and update buttons

app/components/Header/Header.css, app/components/NavigationTab/NavigationLink.css, app/routes/meetings/components/MeetingDetail.tsx, app/routes/meetings/components/MeetingList.tsx, app/routes/polls/components/PollsList.tsx, cypress/e2e/poll_spec.js, cypress/e2e/router_spec.js
[Update the look of navigation tabs](https://github.com/webkom/lego-webapp/commit/caf96b99c7e9aec6c2f6288b5c29640d1760b0dd) 
It now resembles the button's sharp and modern look.
---
[Show correct meeting details](https://github.com/webkom/lego-webapp/commit/94a8b5be08514a1728cf0ff762f2d0c3cff6384d) 
The user object may not be `undefined`, but rather empty; which
causes the field to not show anything.
Also, getting the meeting status is a promise; which means the field
will show `null` while waiting for it to be resolved.
<table>
<tr>
<td>After</td>
<tr>
<tr>
<td><img width="1266" alt="image" src="https://github.com/webkom/lego-webapp/assets/69514187/c1a86b7c-b978-48d6-b6e8-7d574f7a8dbe"></td>
<td><img width="1266" alt="image" …
=> Update the look of navigation tabs

app/components/Card/Card.css, app/components/Card/index.tsx, app/components/CommentForm/CommentForm.css, app/components/CommentForm/index.tsx, app/components/Comments/Comment.css, app/components/Comments/Comment.tsx, app/components/Comments/CommentTree.css, app/components/Comments/CommentTree.tsx, app/components/Comments/CommentView.tsx, app/components/Form/LegoFinalForm.tsx, app/components/Tags/Tag.css, app/components/Tags/Tag.tsx, app/routes/articles/components/ArticleDetail.tsx, app/routes/events/components/Event.css, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/JoinEventForm.tsx, app/routes/meetings/components/MeetingDetail.tsx, cypress/e2e/event_visit_spec.js
[Improve the styling of comments](https://github.com/webkom/lego-webapp/commit/0ef2005375e97d2d8c693618119c9e0c7303eaeb) 
Reposition and align elements, slightly change some styling and also greatly clean up the css.
---
[Replace editor in comment form with text input](https://github.com/webkom/lego-webapp/commit/73ad4225258954c79237087d79953294bfdfb0b8) 
It's less buggy, and will probably work on mobile .. once and for all.
---
[Allow LegoFinalForm to only validate on submit](https://github.com/webkom/lego-webapp/commit/60fa7989c8d9ec3b3fcd0a21272d896a7c6c8649) 
Useful for forms that don't really need to give users real-time
feedback on inputs, such as on comments.
---
[Ability to add icons to tags through props](https://github.com/webkom/lego-webapp/commit/edc4b20a1f6d93225902fbf1bb87c23 …
=> Give comments a retouch

app/components/NavigationTab/NavigationLink.css, app/routes/photos/components/GalleryDetail.tsx
They would sometimes lose their height, making it look like they had no padding.
<table>
<tr>
<td>After</td>
<tr>
<td><img width="1144" alt="image" src="https://github.com/webkom/lego-webapp/assets/69514187/d353897e-61d0-4af1-b7aa-42f1bbb55c83"></td>
<td><img width="1144" alt="image" src="https://github.com/webkom/lego-webapp/assets/69514187/9c1ea189-818d-40a3-9019-beaf839c179c"></td>
</table>
Navigation tabs that were previously not affected still work as expected.
=> Explicitly give navigation tabs a height

app/components/Tags/Tag.css, app/routes/articles/components/Overview.tsx, app/routes/overview/components/Overview.css, app/routes/overview/components/Pinned.css, app/routes/overview/components/utils.tsx
The display property was removed from the tag component since it could not be inline for it to work with the recent introduction of the author highlight on comments, but this broke the alignment of tags on the overview's pinned component.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
The author tag is still aligned properly:
And other places where tags are used seem fine:
---
Resolves ABA-511
=> Vertically align tag component on overview

app/components/Button/Button.css, app/components/CollapsibleDisplayContent/CollapsibleDisplayContent.css, app/components/CollapsibleDisplayContent/index.tsx, app/components/Icon/Icon.css, app/components/Icon/index.tsx, app/components/Modal/Modal.css, app/components/Modal/index.tsx, app/components/NavigationTab/NavigationLink.css, app/components/RandomQuote/RandomQuote.css, app/components/RandomQuote/RandomQuote.tsx, app/components/Search/Search.css, app/components/Search/index.tsx, app/routes/overview/components/CompactEvents.css, app/routes/overview/components/Overview.css, app/routes/overview/components/Overview.tsx, app/routes/polls/components/PollEditor.tsx, app/routes/surveys/components/SurveyEditor/SurveyEditor.tsx, app/routes/surveys/components/surveys.css, cypress/e2e/router_spec.js
Not really a visual change, but rather an accessibility improvement and a reduction in technical debt. An icon can now behave like either buttons or links, which lets users focus on it and then trigger it by pressing enter.
Me tabbing around
https://github.com/webkom/lego-webapp/assets/69514187/48d79097-5743-4e4c-8e3d-b6142293ea85
Went through icons with `onClick` events and things seems to work fine like before, just better heh.
=> Make icons behave like buttons and links

app/components/Form/ImageUploadField.css, app/components/Upload/ImageUpload.tsx, app/components/Upload/UploadImage.css, app/routes/articles/components/ArticleEditor.css, app/routes/pages/components/PageEditor.css, cypress/e2e/create_event_spec.js, cypress/e2e/event_editor_spec.js, cypress/e2e/event_payment_spec.js, cypress/support/utils.js
Not an important feature, just a tiny cool one.
Make some minor styling changes as well, including removing the pitch black background on some cover image drop areas.
https://github.com/webkom/lego-webapp/assets/69514187/4bfd17c7-e00f-4044-b2d0-2d876c73dcfb
---
The old pitch black background:
Uploading images still works.
=> Listen for `isDragActive` on image drop

app/components/Upload/ImageUpload.tsx
lego doesn't support webp images, causing an error when you attempt to upload one
Before: (after attempting to upload)
Now: (when dropping the image into the upload field)
=> Remove webp from accepted filetypes in ImageUpload

app/routes/events/components/EventEditor/index.tsx
Now looks like this  
instead of this  
Looks good on various screen sizes
---
Resolves ABA-517
=> Fix overflowing text in tooltip on event creator page

app/actions/ActionTypes.ts, app/actions/UserActions.ts, app/reducers/auth.ts, app/reducers/users.ts, app/routes/users/StudentConfirmationRoute.tsx, app/routes/users/components/StudentConfirmation.tsx, app/routes/users/components/UserConfirmation.css, app/routes/users/components/UserProfile.css, app/routes/users/components/UserProfile.tsx, app/routes/users/components/UserSettingsIndex.tsx, cypress/e2e/router_spec.js, cypress/support/utils.js
Feide verification :grimacing: 
[Screencast from 2023-07-30 18-12-10.webm](https://github.com/webkom/lego-webapp/assets/42850232/498b87c6-ce7a-4a6c-9d84-788d3ab67fc6)
Notice that the result from the previous verification is still present. The user may re-verify with correct data to get the proper result.
[Screencast from 2023-07-30 18-14-34.webm](https://github.com/webkom/lego-webapp/assets/42850232/8f975db5-9e5a-47e4-ae4d-b435db9dfa37)
---
Resolves ABA-521
=> Replace verification form with FEIDE auth

.drone.yml
The production server won't run without it.
The drone pipeline should work now.
---
=> Add OAUTH_CACHE env var to drone api step

Dockerfile
Soo, yarn workspaces creates a symlink from `lego-bricks` to `node-modules`. This doesn't work if we don't copy the actual files into the docker image.
I don't love this solution, but I couldn't find a way to make yarn actually copy the files. I think perhaps a good solution would be to just build `lego-bricks` into the bundle using webpack, but it wasn't suuper simple, so I might do that later.
It works now:)
Built the image locally, and ran it successfully locally
=> Fix production docker image

app/components/Dropdown/Dropdown.css, app/components/Dropdown/index.tsx, app/components/Footer/Footer.css, app/components/Icon/Icon.css, app/components/Poll/Poll.css, app/components/Poll/index.tsx, app/routes/admin/groups/components/GroupView.tsx, app/routes/events/components/EventEditor/EventEditor.css, app/routes/events/components/EventEditor/index.tsx, app/routes/interestgroups/components/InterestGroup.css, app/routes/interestgroups/components/InterestGroupDetail.tsx, app/routes/overview/components/ArticleItem.css, app/routes/overview/components/ArticleItem.tsx, app/routes/overview/components/LatestReadme.css, app/routes/overview/components/LatestReadme.tsx, app/routes/quotes/components/Quote.tsx, app/routes/quotes/components/Quotes.css, app/routes/surveys/components/AdminSideBar.tsx, app/routes/users/components/UserSettingsOAuth2.tsx, app/styles/variables.css, packages/lego-bricks/src/components/Button/Button.module.css, packages/lego-bricks/src/components/Button/index.tsx
[Update some icons to behave better](https://github.com/webkom/lego-webapp/commit/2a5b580deed3c16fd4d339173510b4e96a40580c) 
They will now act as buttons, so you can tab on them.
---
[Give icons and buttons the same "active" look](https://github.com/webkom/lego-webapp/commit/30e43adfe94702519791c268f321258b1e466fc4) 
The translate(-1px) felt less modern and the icons did not have any
active styling.
---
[Handle copy button timeouts better](https://github.com/webkom/lego-webapp/commit/1c8c866791bc86a962fdb9ee9c5522cd0e5f56c0) 
Less glitchy by clearing out old timeouts when creating new ones.
---
[Fix random bits and pieces, again](https://github.com/webkom/lego-webapp/commit/98de2dfa66cbdd342b933c72ac98845b8ad912b4) 
* Remove some use of italic fonts
* Fix glitchy render on footer
* Remove …
=> Random bits and pieces 5

app/routes/overview/components/Overview.tsx, app/routes/overview/components/PublicFrontpage.tsx
Replace buddy-week banner with admissions banner.
A little late, so we should get this out asap:)
Opened the page and looked at the banner.
---
=> Update banner for admissions 2023

app/components/Form/DatePicker.css, app/components/Form/DatePicker.tsx, app/components/Form/Field.tsx, app/components/Form/TimePicker.tsx, app/routes/meetings/components/MeetingEditor.tsx, app/utils/parseDateValue.ts, app/utils/validation.ts, cypress/e2e/create_meeting_spec.js, cypress/support/utils.js
Small refactor of the DatePicker thingy. Shouldn't change too much, but rewrote to functional components and simplified the logic a bit. ~100 fewer lines of code:)
Some minor changes in appearance:
<table>
<tr>
<td>After</td>
<tr>
<td><img width="351" alt="Screenshot 2023-05-27 at 18 54 41" src="https://github.com/webkom/lego-webapp/assets/8343002/edc577da-6a80-4ed7-a05b-737699d7ff54"></td>
<td><img width="351" alt="Screenshot 2023-06-10 at 10 25 07" src="https://github.com/webkom/lego-webapp/assets/8343002/287e7b3a-fbf0-4e59-86c4-08b8e7828ef1"></td>
</table>
~~I have changed the behaviour slightly to simplify the logic. In the meeting editor we would previously automatically move the end time forward if it was set before the start time, but this didn't play well with the …
=> Refactor DatePicker- and TimePicker-component

app/utils/themeUtils.tsx
The theme value accessed through `getTheme()` didn't get set on initialization, so the value was set to the default value (light). On dark mode, this would cause certain bugs, like the graph artwork in the background to disappear and the netcompany logo to use its light color variant.
**before**
**after**
It just works
---
Resolves ABA-550
=> Fix unset theme on initialization

app/actions/UserActions.ts, app/models.ts, app/routes/users/components/UserProfile.css, app/routes/users/components/UserProfile.tsx, app/routes/users/components/UserSettings.tsx, app/store/models/User.d.ts, app/utils/validation.ts
Implement github username on profile. Addable from the user settings.
---
Resolves ABA-479
Depends on: https://github.com/webkom/lego/pull/3389
=> Implement github usernames on profiles.

app/routes/events/components/StripeElement.tsx
Previously, the content of the card number, expiration date and cvc input fields were hard too see when using dark mode. This PR makes the content color white when using dark mode to improve contrast.
| Before: Dark text on dark background | After: Light text on dark background |
| -- | -- |
| ![image](https://github.com/webkom/lego-webapp/assets/33326578/37474f15-bfdb-43d8-bbdf-760aa526e679) | ![image](https://github.com/webkom/lego-webapp/assets/33326578/67370be4-3fb9-4019-80f7-647f45d1b947) |
Checked that the contrast is correct in both dark and light mode.
=> Fix incorrect stripe input color

app/components/EventItem/index.tsx, app/components/JoblistingItem/index.tsx, app/models.ts, app/reducers/articles.ts, app/reducers/joblistings.ts, app/routes/announcements/components/AnnouncementItem.tsx, app/routes/articles/ArticleDetailRoute.ts, app/routes/articles/components/ArticleDetail.tsx, app/routes/articles/index.tsx, app/routes/events/EventDetailRoute.ts, app/routes/events/components/Admin.tsx, app/routes/events/components/EventAdministrate/index.tsx, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/EventEditor/index.tsx, app/routes/joblistings/JoblistingDetailedRoute.ts, app/routes/joblistings/components/JoblistingDetail.tsx, app/routes/joblistings/components/JoblistingEditor.tsx, app/routes/joblistings/index.tsx, app/routes/overview/components/CompactEvents.tsx, app/routes/overview/components/utils.tsx, app/store/models/Article.d.ts, app/store/models/Event.d.ts, app/store/models/Joblisting.ts
- Fix the infinite loop when redirecting from /{id}
- Add slugs to joblistings and articles
- Use slugs in common links and on frontpage
No visual changes except for url
Seems to work fine now
---
Resolves ABA-212
=> Add slugs to joblistings and articles and use them in common places

packages/lego-bricks/src/Global.d.ts, packages/lego-bricks/src/Globals.d.ts, packages/lego-bricks/src/Modules.d.ts, packages/lego-bricks/src/components/Icon/IonIcons.ts, packages/lego-bricks/src/components/Icon/index.tsx, packages/lego-bricks/src/index.ts
The ion-icon can be used as a normal HTML-element as it is a web component. Typescript doesn't know this though, unless we add type definitions for it.
There are now type definitions, meaning we don't need to use ts-ignore in the Icon-component anymore:)
Only typscript changes. 
---
=> Type ion-icon web component

app/components/Form/DatePicker.css, app/components/Form/DatePicker.tsx, app/components/Form/TextInput.css, app/components/Form/TextInput.tsx, app/components/Form/TimePicker.css, app/components/Form/TimePicker.tsx, cypress/e2e/create_event_spec.js, cypress/e2e/create_meeting_spec.js, cypress/support/utils.js
[Highlight current day in date picker](https://github.com/webkom/lego-webapp/commit/ad00c24445eaa197046e006a4f2394a117b6bdbd)
---
[Give datepicker component a retouch](https://github.com/webkom/lego-webapp/commit/743c3ac9e36f238a570a5b78f2044368523f6728) 
- Center time input fields
- Let users change time with up and down keys!
- Remove the old school borders
- Label the weekdays
- Update arrow icons with transitions :)
- Un-disable dates from previous or next month
**Before**
<p align="center">
</p>
**After**
<p align="center">
</p>
https://github.com/webkom/lego-webapp/assets/69514187/0acae3d2-43f8-4466-bb23-d7c1692f8cb6
Setting and updating dates still work.
=> Give datepicker a retouch

cypress/e2e/create_event_spec.js
Is there some new validation here? How does this code from 2019 just suddenly cause all cypress runs to fail?? Well anyways I fixed it by always using the date tomorrow as merge-time, this avoid merge time being before the registration time.
Cypress doesn't fail.
---
=> Use date-relative merge time in event cypress test

.drone.yml, app/routes/bdb/components/AddSemester.tsx, app/routes/bdb/components/CompanyEditor.tsx, app/routes/bdb/components/SemesterStatusContent.tsx, app/routes/companyInterest/components/CompanySemesterGUI.tsx, app/routes/companyInterest/components/Translations.ts
After last nights updates to the company interest page, a few other pages that used `MultipleSelectGroup` broke. This was because a `FormSpy` was added to `MultipleSelectGroup`, and as that is a `react-final-form` feature, all non-`react-finial-form`-forms that used `MultipleSelectGroup` broke. So, this PR rewites all these forms to `react-final-form` (as well as rewiting one of them to a functional component). 
This PR also adds and removes some events from the company interest page as requested by Bedkom:)
No visual results, except that the forms are now working again.
=> Refactor forms using MultipleSelectGroup to react-final-forms

app/components/Tooltip/index.tsx, app/routes/companyInterest/components/CompanyInterestList.tsx
Fixes a bug where the "Eksporter til CSV"-button on the company interest list disappears when choosing a semester. Previously you would set the Tootltip to `display: none` when not wanting to show the helper text, but this would also hide all child components. The bug is fixed by introducing a new `disabled` prop to the Tooltip component.
When not having a semester selected the button is disabled and a tooltip is shown:
When choosing a semester the button disappears:
=> Fix invisible export to CSV button

app/components/NavigationTab/NavigationLink.css, app/components/NavigationTab/NavigationTab.css
Give navlinks vertical distance when they wrap.
Smol visible change
Visited a few places they were used on mobile and desktop sizes - seems okidoks to me
---
=> Update navlinks to use gap instead of margin

app/components/Form/SelectInput.tsx, app/routes/companyInterest/components/CompanyInterestPage.tsx
I think the refactor to react-final-form must have broken the feature where one could add a new company in the company interest form, if it wasn't already in our database.
I made some small front-end only changes to make it send the new company name in the correct format.
I have sent in a few company interest forms to test. It works well when creating new company interests. It's a teensy bit buggy when editing the name, but do we ever do that?
I think it's fine for a quick fix.
---
=> Fix adding new company through interest form

app/routes/admin/groups/components/GroupPage.tsx, app/routes/photos/components/GalleryDetail.tsx
Realized that I missed two places when I checked the effect of replacing margins with gap in #4157. Namely group admin site and gallery details. Searched through all occurrences of NavLink now, and these were the only ones wrapped in extra divs I could find - so all else should be good.
<table>
<tr>
<td>
<td>Before
<td>After
<tr>
<td>Admin group-details
<td><img width="508" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/ca55752e-4e2e-4de6-9930-38ee2fb1678a">
<td><img width="529" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/a9dd08d8-de0a-4631-9732-0b26800c916b">
<tr>
<td>Gallery detail
<td><img width="251" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/c4dfe2f2-604f-4abf-9834-e1e44beaaabe">
<td><img width="262" …
=> Remove extra divs wrapping NavLinks

app/components/Upload/ImageUpload.tsx
Small thing to make cropper take as much as possible of the image (width-wise).  
Seemingly all aspect ratios were already correct
Good boy
Looked through all usages of ImageUpload
---
Resolves ABA-450
=> Make react-cropper take up the full width of picture

app/routes/companyInterest/components/CompanyInterestPage.tsx
Accidentally broke the interest form. This fixes it.
Turns out the companyId is actually a string that needs to be parsed to a number.
It works now.
The form now submits, and the resulting interest seems correct.
---
=> Fix validation of existing company in interest form

app/components/Header/Header.css
Changes:
* Add `flex-shrink: 0;` to prevent profile picture to shrink to an oval when it doesn't have enough space. This rather forces the Abakus-logo to scale down if the screen is too small (however with screens that small we have bigger problems than the logo..).
* Add padding to the button element wrapping header icons, as it was not defined (aka left up to the browser to decide). Thus caused Safari to have twice the paddings that Chrome has, and as such the header looked very off on iPhones.
Chrome's default padding for buttons is `1px 6px`, so the added `0 7px` looks quite similar to what it looks like in my browser - except that it's now the same across browsers.
Note that the before-version doesn't look *that* off in this preview, but that is only because I couldn't login - and …
=> Define padding for header icons

cypress/e2e/event_visit_spec.js
I don't know why it didn't work, but waiting a bit fixes it.
Cypress no logner fails. It consistently failed without the wait.
---
=> Add wait to fix cypress comment test

app/components/Tooltip/Tooltip.css
Fixes the bug where the tooltip on the frontepage for "Festet event" would not wrap to multiple lines. Occurred due to inheriting styling from the compactEvent element.
---
Resolves ABA-585
=> Add white-space attribute to tooltip

app/components/MazemapEmbed/MazemapEmbed.css, app/components/MazemapEmbed/index.tsx, app/components/Search/mazemapAutocomplete.tsx, app/styles/variables.css, cypress/e2e/create_meeting_spec.js, mazemap/package.json, yarn.lock
Bumps mazemap from 2.0.63 to 2.0.96
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://api.mazemap.com/js/v2.0.106/docs/#release">mazemaps api docs</a>.</em></p>
<blockquote>
version 2.0.96
May 5, 2023
Update a console error to include missing error information
version 2.0.95
March 21, 2023
Minor change in the [JSAPI as NPM Module + React](https://api.mazemap.com/js/v2.0.106/docs/#ex-jsapi-module-import-react-project) example.
version 2.0.94
February 28, 2023
Fixed bug where icon images could sometimes have wrong offset.
version 2.0.93
January 25, 2023
Make the Mazemap.Config.getSearchApiBaseUrl() include /search by default. Should not affect any existing integrations unless you are manually setting the search api base url using …
=> Bump mazemap from 2.0.63 to 2.0.96

app/components/CommentForm/index.tsx, app/components/Form/TextInput.tsx, cypress/e2e/event_visit_spec.js
Removes the wait introduced in #4176 
`CommentField`s were set to have a random key (why I do not know), that would make it re-render excessively (and thus clear the focus and content of the new comment). This removes the key, and rather handles form resetting by using the `form.change()` method.
Changes done to `TextInput.ts` were done to avoid bugs that were discovered while trying another approach.
* When `inputRef` was used as a parameter in `useRef()`, it did not update `inputRef` when `newInputRef` was used. Thus it was not possible to pass a ref through to the component.
* Small typescript errors
When run on my machine this works quite well, and I can start writing comments before all the content of the page has been loaded - which was not the case previously.
To see if this …
=> Remove random key from comment field

app/components/Form/CheckBox.css, app/components/Form/RadioButton.css
A pointer cursor indicates to the user that the input fields can be interacted with, and should therefore be changed accordingly when they are disabled.
Cursor now behaves as expected.
Tested both input fields as both disabled fields and normal fields.
=> Use default cursor on disabled checkboxes and radio buttons

app/components/Form/DatePicker.css
It is bad feedback to not highlight the current day like you would for other dates.
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
See images above of working changes.
Highlighting the current day still works like before.
=> Highlight current day appropriately when selected in datepicker

app/components/Form/TextInput.css, app/components/Form/TextInput.tsx
Also fix wrong styling on prefix icon given by the recent changes to the Icon component.
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
- Text inputs now have a correct text color. 
- Tested with and without a `prefix`, and `centered` inputs.
- `prefix` still works as expected, by focusing on the input when clicked.
---
Resolves ABA-602
=> Fix wrong color in text inputs

app/components/Form/Field.css, app/components/Form/Field.tsx, app/components/Form/ObjectPermissions.tsx, app/components/GroupForm/index.tsx, app/routes/admin/email/components/EmailListEditor.tsx, app/routes/articles/components/ArticleEditor.tsx, app/routes/events/components/EventEditor/index.tsx, app/routes/photos/components/GalleryPictureEditModal.tsx
[Fix the description styling on fields](https://github.com/webkom/lego-webapp/commit/777abf74d476d55758593db65a7cf19fee568a1e)
[Refactor fields to use description prop](https://github.com/webkom/lego-webapp/commit/a2abc2a0770b1880f33bdda2eaa7f580dee2d4ae)
The icons makes the page more "cluttered", but easier/better to use. It's a trade-off. Note that the event editor is the only page with a ton of field descriptions, so given that it's an anomaly I wouldn't say it's a big deal.
All fields still look as expected.
=> Fix and use the `description` on fields

app/components/Form/Field.tsx, app/components/Form/SelectInput.tsx, app/routes/admin/email/components/EmailUserEditor.tsx, app/routes/admin/groups/components/AddGroupMember.tsx, app/routes/contact/components/ContactForm.tsx, app/routes/events/EventCreateRoute.ts, app/routes/events/components/EventEditor/index.tsx, app/routes/surveys/components/SurveyEditor/SurveyEditor.tsx
Much better than the default "Select..."
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
Specified placeholders still override, and it works with both `inlineLabel` and `noLabel`.
=> Give input selectors a default placeholder

app/components/NavigationTab/index.tsx, app/routes/users/components/UserSettingsIndex.tsx, cypress/e2e/router_spec.js
I missed a spot when I updated the styling of the navtab component previously - so with this, I hope there are no more occurrences that are not working..
NavLink elements missed spacing in user profile page, now it has spacing.
=> Remove extra div from settings navtab

app/actions/EventActions.ts, app/components/UserValidator/Validator.css, app/components/UserValidator/index.tsx, app/routes/events/EventAbacardRoute.ts, app/routes/events/components/EventAdministrate/Abacard.tsx, app/routes/userValidator/ValidatorRoute.tsx
Changes in how abacard handles responses
* Avoids using `alert()` or other elements that require the user to interact with them (`Modal` is used, but it is set to close by itself)
* Remove custom overlay code and replace it with `Modal` component
* Search by username: Displays responses using Modal and Toast
* Scan by ABAID: Displays responses in a list displaying the 5 most recent responses
* Displays a different feedback when it is used through `/validator` route than through `Abacard` route to emphasize what the result actually means.
This does nothing to solve the double-scanning, but it handles it quite a bit more gracefully - which was the main problem to be solved. If someone wants to ratelimit the amount of times requests for the same user is sent - feel free, it's a pretty …
=> Replace abascan popups with a list of recent scans

app/components/TextWithIcon/TextWithIcon.css, app/components/TextWithIcon/index.tsx
Fixed wrapping of TextWithIcon component, thus also fixing the alignment of icons. Did this by wrapping the content (the text) in a span, and adding a div wrapping the span with "width: max-content".
**before**
**after**
- I have thoroughly tested my changes.
Tested locally on both laptop, desktop and mobile views.
---
=> Fix TextWithIcon icon alignment

app/routes/events/components/EventAttendeeStatistics.css, app/routes/events/components/EventAttendeeStatistics.tsx
Add title and description to the two main sections of the event statistics to make it clearer what the different sections are based on.
<table>
<tr>
<th>
<th>Before
<th>After
<tr>
<td>No signups
<td><img width="1024" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/a4d79b70-2277-4101-91e3-36725ede9d7f">
<td>
<tr>
<td>After signups
<td><img width="1012" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/8f6c1a12-9ef1-44aa-ac65-3ffd94da3798">
<td><img width="1014" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/854492c2-3bd5-4c69-a464-0a628c82769e">
</table>
=> Add section-dividers and titles to event statistics

app/routes/surveys/AddSurveyRoute.ts, app/routes/surveys/utils.tsx
This was requested by the arranging komitees a few weeks ago to avoid conflicts with event registrations, which are usually on the hour. It sets default activation time to 14:30 the day after the event end time, or tomorrow at 14:30 if no event is selected.
See how it says 14:30(the event is 23. Oct):
Have tested both with and without a connected event, and with templates.
---
Resolves ABA-612
=> Change default survey activation time to 14:30

app/components/Search/index.tsx, app/components/Search/utils.tsx
Add a few highlighted external links to the nav menu, and a link to AbaBart where users can find the rest of them.
---
Resolves ABA-614
=> Add external links to nav menu

app/actions/CompanyActions.ts, app/components/CommentForm/CommentForm.css, app/components/CommentForm/index.tsx, app/components/Form/SubmissionError.css, app/components/Form/SubmissionError.tsx, app/components/Form/SubmitButton.tsx, app/components/LoginForm/LoginForm.tsx, app/routes/bdb/components/AddSemester.tsx, app/routes/bdb/components/CompanyEditor.tsx, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/companyInterest/components/CompanySemesterGUI.tsx, app/routes/meetings/components/MeetingEditor.tsx, app/routes/polls/components/PollEditor.tsx, app/routes/quotes/components/AddQuote.tsx, app/routes/users/components/UserSettings.tsx
Note: this PR builds on #4220 because I created the `<SubmitButton>`-component there, only 59a86e130a788453b4123a4979d6f9bff7752729 is relevant.
The `<SubmitButton>`-component just reduces some boilerplate, with the bonus that it enforces consistency in submit-buttons. 
`<SubmissionError>` shows any errors that arise when submitting the form, meaning that the forms that were missing this would simply not show the error message.
I also did a bit of refactoring in `CompanySemesterGUI` because the previous structure made no sense.
Some forms had green or grey submit-buttons, now they are all black. 
The login-form had a custom error-component which was simply red text, it now uses `<SubmissionError>`:
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="362" alt="Screenshot 2023-10-21 at …
=> Improve final-form submit-button and submission-error consistency

app/routes/events/components/EventAttendeeStatistics.css, app/routes/events/components/EventAttendeeStatistics.tsx
- Displays the statistics charts as two grid columns instead of one.
- Adds card background to all charts.
| -- | -- |
| ![Screenshot from 2023-09-27 12-22-54](https://github.com/webkom/lego-webapp/assets/33326578/825f56a8-1269-4134-a96e-2cf0eacbc4c4) | ![Screenshot from 2023-09-27 12-22-16](https://github.com/webkom/lego-webapp/assets/33326578/f59ff2a0-0b7f-4de3-9ff9-d091f99f9a61) |
1. Navigate to an event and click on "Se påmeldinger".
2. Click on "Statistikk".
3. Verify that the new design uses a two column grid and that all charts have a card background.
Resolves [ABA-497](https://linear.app/abakus-webkom/issue/ABA-497/improve-the-statistics-page)
=> Fix statistics positions

app/components/Tooltip/Tooltip.css
Change Tooltip content styling from flex to block, so that content will behave as they are inline elements and not be adjusted by the flex styling.
Haven't searched that much - but within the places I found it made no difference that the align-items wasn't set (and it wont work without flex), so removed that as well.
The other tooltips I've visited (mainly the welcome page and the rest on the event detail page) behave the same before and after.
---
Resolves ABA-609
=> Remove flex from tooltip content

app/components/Header/Header.css, app/components/Header/Navbar/AboutDropdown.tsx, app/components/Header/Navbar/CareerDropdown.tsx, app/components/Header/Navbar/EventsDropwdown.css, app/components/Header/Navbar/EventsDropwdown.tsx, app/components/Header/Navbar/Item.css, app/components/Header/Navbar/Item.tsx, app/components/Header/Navbar/ItemGrid.css, app/components/Header/Navbar/ItemGrid.tsx, app/components/Header/Navbar/ItemList.tsx, app/components/Header/Navbar/Navbar.css, app/components/Header/Navbar/Navbar.tsx, app/components/Header/index.tsx
Adds a simple dropdown menu that appears when you hover over the navbar. 
It lacks animations, like in Ivar's original PR, but I was told to be agile so I'm just throwing this PR out there. I tried to add an identical animation, but it was literally mission impossible ;(
**Before**
[Screencast from 2023-10-13 22-53-19.webm](https://github.com/webkom/lego-webapp/assets/66320400/ede42d98-12dc-40ac-b256-ef42e99bd3a8)
**After**
Light mode:
[Screencast from 2023-10-14 11-13-56.webm](https://github.com/webkom/lego-webapp/assets/66320400/d1de229d-bc89-4f33-baa0-99293737b7ba)
Dark mode:
[Screencast from 2023-10-14 11-14-16.webm](https://github.com/webkom/lego-webapp/assets/66320400/162b7dc9-f334-4210-bdbb-4736a4a3d641)
Everything works... EXCEPT this tiny …
=> Add dropdown menu to navbar

app/components/Tags/Tag.css, app/routes/overview/components/Overview.css
Ivar found out that some of the tags were slightly unaligned, so with this, all the tags should be perfectly aligned(:
When the linkSpacing thingy was inline, it added some more space on top of itself, which it does not when it is inline-flex(:
TODO
I've tested this checking the alignment in;
- article overview taglist
- bottom of article
- admin > email > lists
- admin > email > users
- pinned article on overview
=> Update Tag alignment

app/components/Header/Navbar/Navbar.css
Because of poor testing on my part, I didn't notice that the navbar was still visible on mobile view with the new changes in #4188. This is fixed now.
**before**
**after**
I've tested it for both desktop and mobile view this time :)))))
=> Hide navbar in mobile view

app/routes/bdb/components/bdb.css
reason: problems with darkmode
ABA-615
=> Changed backgroundcolor for interested on bdb interestpage

app/routes/pages/components/PageHierarchy.tsx
The correct page group was only expanded when the component was rendered (e.g. when navigating from another part of the webapp). When navigating through hyperlinks within the flatpages however, the component was already loaded and as such did not change. Now it does.
For a video showcasing the issue, check out the linear issue
Works on my machine ™️ 
---
Resolves ABA-606
=> Listen to changes in current page to expand category

app/routes/overview/components/CompactEvents.css, app/routes/overview/components/Overview.tsx
Aaand remove the excessive margin top from compactevents on mobile that has been bugging me for ages.
Desktop view is unchanged.
<table>
<tr>
<th>
<th>Before
<th>After
<tr>
<td>
<td><img width="355" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/beec212b-0060-490a-a97d-a3078a8ae39b">
<td><img width="357" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/b887102a-78d1-4ef1-82b2-584e388c760d">
</table>
---
Resolves ABA-460
=> Move pinned over poll and quote on mobile

app/routes/pages/components/LandingPage.tsx
Fixed the italic issue on landingpage. fixed issue were "Datateknologi was written normally, but "Cybersikkerhet og datakommunikasjon" were written in italics.
**bug-fix**
**before** 
**after**
I've tested for different sizes: Issue
It may be difficult to differentiate which to words do correspond to one thing. It may also look like it's one study programme or three
---
ABA-631
=> Fix Italic issue

app/components/Header/Navbar/Navbar.tsx, app/reducers/meetings.ts, app/routes/meetings/components/MeetingList.tsx
Old meetings are fetched by default if there are no upcoming meetings.
Added two new groups of meetings for the meeting list, which makes the total groupings;
Ordered ascendingly
- Denne uken
- Neste uke
- Senere i semesteret
Ordered descendingly
- Tidligere denne uken
- Forrige uke
- Semestere
Updated the name of the semester groupings from "V2023" and "H2023" to "Våren 2023" and "Høsten 2023".
Visually, the headers are added but otherwise it remains the same.
---
Resolves ABA-506
=> Load old meetings if no upcoming, and refactor the reducer

app/routes/events/components/EventDetail/index.tsx
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
---
Resolves https://github.com/webkom/lego/issues/3512
=> Fix spacing issue on event author

app/components/EventItem/index.tsx, app/components/EventItem/styles.css, app/routes/events/components/CalendarCell.tsx
Update `EventItem` component to also include the time the event registration opens.
Also includes a tooltip
Due to some styling differences, it was better to not combine the `TimeStamp` and `TimeStartAndRegistration` components
<hr/>
<hr/>
<hr/>
---
Resolves ABA-588
=> Add registration activationTime to default EventItem card in eventlist

app/routes/contact/ContactRoute.ts, app/routes/contact/components/ContactForm.tsx
Adds "RevyStyret" to the dropdown in the contact form. Only the leader will get contacted, like for committees.
It works with the new backend changes [see this](https://github.com/webkom/lego/pull/3511)
---
Resolves ABA-617
=> Add revue board to contact form

app/routes/meetings/components/MeetingList.tsx
Currently it changes to gray before the meeting has ended, which in my opinion is "wrong" behaviour. Especially considering the `endTime` is used in the filtering.
This meeting that I'm currently attending has not ended:
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
This should not affect anything besides what is shown above.
=> Change meeting color indicator on meeting list

app/routes/pages/components/PageDetail.tsx, app/routes/pages/components/PageHierarchy.tsx, app/routes/pages/components/Sidebar.tsx
Found out that the variable I relied on for my last fix was incorrectly typed :'( so it turns out the variable wasn't set for groups or main pages, so now it's rather fetched straight from the sauce.
Should work better now
---
Resolves ABA-646
=> Use param instead of inconsistent variable for accordion expansion

app/components/Form/CheckBox.css, app/components/Form/CheckBox.tsx, app/components/Form/RadioButton.css, app/components/Form/RadioButton.tsx
With the changes, it is possible to tab through checkboxes and select them.
Turned out to be impossible to do for radio buttons, as essentially according to W3C; a radio button is a group that functions as a single element since it retains only a single value. Tabbing to a radio group will bring you to the first item and then using the arrow keys you navigate within the group.
However, I did add the similar logic for radio buttons in case there is no default value to the radio button group (e.g. in the company interest form). Despite this being bad practice.
Notice how the cursor does not move:
<video src="https://github.com/webkom/lego-webapp/assets/69514187/293907e1-13a8-46bb-a0cb-19b52a8483ff" />
Checkboxes still behaves like before, but you can now focus on them by tabbing 🎉
=> Make checkboxes focusable

packages/lego-bricks/package.json
We want these to be automatically installed by the consuming project, instead of just being hinted.
Haven't tested, but prob flawless
=> Move some lego-bricks' peer deps to be regular deps

app/components/Table/index.tsx, app/routes/admin/email/EmailListsRoute.ts, app/routes/admin/email/EmailUsersRoute.ts, app/routes/admin/email/components/EmailLists.tsx, app/routes/admin/email/components/EmailRoute.tsx, app/routes/admin/email/components/EmailUsers.tsx, app/routes/articles/ArticleListRoute.ts, app/routes/articles/components/Overview.tsx, app/routes/events/components/EventList.tsx, app/routes/joblistings/JoblistingRoute.ts, app/routes/joblistings/components/JoblistingPage.tsx, app/routes/joblistings/components/JoblistingRightNav.tsx, app/routes/overview/components/CompactEvents.tsx, app/routes/quotes/QuoteDetailRoute.ts, app/routes/quotes/QuotesRoute.ts, app/routes/quotes/components/QuotePage.tsx, app/utils/__tests__/useQuery.spec.ts, app/utils/useQuery.ts
The main attraction is the new `useQuery`-hook. It handles reading, parsing and updating of query parameters automatically! It just takes some default values for the relevant query parameters, and fixes the rest for you. These default values also provide typescript types for the parameters:)
In addition I added the helper functions `parseQueryString` and `stringifyQuery`, which allows you to parse and stringify queries in the same format as the hook does, outside of a function-component. Very useful for the higher order component routes.
Other than this I rewrote some class-components to function components, and did some other minor cleanup and refactoring.
Simpler and more consistent query handling in all pages that use the new functions.
There are some routes still doing query handling …
=> Refactor query parameter handling

app/models.ts, app/routes/events/EventCreateRoute.ts, app/routes/events/EventEditRoute.ts, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/EventEditor/index.tsx, app/routes/events/utils.ts, app/store/models/Event.d.ts
Implement checkbox to mark event as foreign language, as well as display this in the event detail.
---
Resolves: ABA-649
=> Implement marking events as foreign language as well as displaying

app/routes/events/components/EventAttendeeStatistics.css
Fixes the cards on the statistics page not wrapping properly when in mobile view.
| -- | -- |
| ![Screenshot from 2023-11-07 15-32-22](https://github.com/webkom/lego-webapp/assets/33326578/b01dcd44-99b7-4f73-9246-1e3f188a944c) | ![Screenshot from 2023-11-07 15-32-10](https://github.com/webkom/lego-webapp/assets/33326578/4d0d101a-334a-4d81-b6d4-892183590853) |
1. Navigate to an event and click on "Se påmeldinger".
2. Click on "statistikk".
3. Verify that the graph cards wrap correctly in mobile view.
Resolves [ABA-644](https://linear.app/abakus-webkom/issue/ABA-644/make-pie-charts-wrap-on-the-statistics-page-for-mobile)
=> Fix event statistics not wrapping on mobile

app/routes/bdb/components/CompanyEditor.tsx, app/store/models/Article.d.ts, app/store/models/Autocomplete.ts, app/store/models/Company.ts, app/store/models/Event.d.ts, app/store/models/Gallery.d.ts, app/store/models/Group.d.ts, app/store/models/Meeting.d.ts, app/store/models/Page.d.ts, app/store/models/Tag.d.ts, app/store/models/User.d.ts
The CompanyEditor would freeze up if you attempted to submit with an invalid link. While fixing this I got a bit lost in the types 😅
It no longer freezes, and instead gives correct feedback.
---
Resolves ABA-660
=> Fix validation bug in CompanyEditor and improve types

app/components/Form/TextEditor.css, app/components/Form/TextInput.css, app/routes/company/components/CompaniesPage.css, app/routes/events/components/EventEditor/index.tsx
* Fix wrong font
* Fix bad padding
* Fix bad font-size
* Prevent editor from growing out of its parent (you can currently drag and resize it out of your screen in all directions if you want)
* Add min-height
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
The added min-height does not break editors where the height has been specified, such as on the company interest form.
=> Make text editor input similar to other text inputs

app/components/Content/ContentSection.css, app/components/Content/ContentSection.tsx, app/components/Content/ContentSidebar.css
This changes the sidebar positioning from using flex-wrap to changing layout direction at a set breakpoint `--medium-viewport`. The reason for this change is that there is no way to create the border line between main content and sidebar, only when the content is not wrapped. (I don't think this has ever happened entierly in sync).
Before:
After:
Have clicked through most of the pages using sidebar, and checked that they look good on mobile.
---
Resolves ABA-672
=> Fix sidebar position on mobile

app/actions/EventActions.ts, app/routes/events/components/EventEditor/index.tsx
Typo in create event, "avregistregistreringsfrist", and "fremmedspråk" popping up between chosen groups.
=> Fix create event typo and bug

app/utils/__tests__/useQuery.spec.ts, app/utils/useQuery.ts
The new query parameter parsing I added in #4259 would parse parameters like "?grades=2" as a string, even if the defaultValue, and thus the typescript type is an array of strings.
It now parses them correctly by checking the type of the default value, and ensuring the parsed value is an array if the default value is.
I also changed the array param format to drop the square brackets, because I think they are ugly. Array parameters will look like this "?grades=1&grades=2" now instead of this "?grades[]=1&grades[]=2".
Have tested with multiple different array parameter formats on the joblisting page. Filtering works well with all of them:)
---
Resolves ABA-675
=> Ensure array query parameters are always parsed as arrays

app/components/JoblistingItem/index.tsx
These damn tags ..
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
Should not affect any other tags or things.
Looks fine without the tag as well:
=> Fix misaligned "New" tag on joblisting items

app/components/Header/Navbar/Navbar.tsx
- Prevents navbar dropdown to be displayed when there is no dropdown content
- Previously, when clicking on a navbar link and then hovering over another navbar link, the dropdown would stay hidden. This is now fixed.
**before**
[Screencast from 2023-11-06 22-20-37.webm](https://github.com/webkom/lego-webapp/assets/66320400/d78a60bb-9d13-49f7-b57e-1fe3cf28d389)
**after**
[Screencast from 2023-11-06 22-20-59.webm](https://github.com/webkom/lego-webapp/assets/66320400/eeba955b-d1e0-4804-8f45-8922ad203873)
---
Resolves ABA-636
=> Fix navbar dropdown visibility issue

app/routes/app/AppRoute.tsx
The users upcoming meetings were only fetched once when loading the page, so if you weren't logged in already they never get fetched, and the icon did not appear. 
The fix is to add a dependency to the meeting fetch call, so that it is run again every time the `loggedIn` state changes.
The icon now appears a few seconds after logging in:)
---
Resolves ABA-674
=> Fix bug where meeting icon in header does not appear after logging in

app/routes/events/EventCreateRoute.ts, app/routes/events/utils.ts, cypress/e2e/create_event_spec.js
Allows you to select a location for an event even if the registration type is TBA
Attempting to add a location to a TBA event works now, instead of the location just becoming "TBA".
Have created a bunch of events
---
Resolves ABA-677
=> Allow location on TBA evnets

app/components/PhotoUploadStatus/index.tsx
It says no photos were uploaded, even though it did in fact upload successfully. The card is even green!
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
=> Give correct feedback when uploading photo to gallery

app/routes/overview/components/CompactEvents.css, app/styles/utilities.css
Fixes the alignment on medium screens and makes them stack vertically on mobile
Looks better
---
Resolves ABA-683
=> Fix header alignment on frontpage

app/actions/AnnouncementsActions.ts, app/actions/ArticleActions.ts, app/actions/CommentActions.ts, app/actions/CompanyActions.ts, app/actions/CompanyInterestActions.ts, app/actions/ContactActions.ts, app/actions/EventActions.ts, app/actions/FileActions.ts, app/actions/MeetingActions.ts, app/actions/ReactionActions.ts, app/actions/UserActions.ts, app/actions/callAPI.ts, app/components/CommentForm/index.tsx, app/routes/announcements/components/AnnouncementItem.tsx, app/routes/announcements/components/AnnouncementsList.css, app/routes/meetings/components/MeetingEditor.tsx, app/routes/userValidator/ValidatorRoute.tsx, app/store/createStore.ts, app/store/middleware/promiseMiddleware.ts, app/store/models/File.d.ts, app/store/models/Reaction.d.ts, app/store/models/entities.ts, app/types.ts, app/utils/fetchJSON.ts, app/utils/index.ts, package.json, yarn.lock
[Properly type the callAPI and promise middleware](https://github.com/webkom/lego-webapp/commit/7814e68d4752729ef70e559b169d571bea2e18b3) 
It is now possible to type API request!
---
[Type announcement, article, comment and company actions](https://github.com/webkom/lego-webapp/commit/6996a217d16b060daf41de4ea2a6e1fb95bd76ef)
No visual changes except this tiny fix:
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</table>
Tested all actions that were typed, even though that should not have broken anything.
=> Properly type actions

app/reducers/__tests__/announcements.spec.ts, package.json, yarn.lock
It is only used for one reducer test, so not really needed.
Test still works.
=> Remove `timekeeper` dependency

app/actions/GroupActions.ts
Re-added descendants as part of the query.
We don't use it, buuuuuuuuuuuuuuuuuuuuuuuuut selectors are tracked using that query, and since it mismatched the selector in `pages.ts`, the state was not retrieved successfully.
They're back, i promise:)
---
Resolves ABA-706
=> Re-add descendants

package.json, yarn.lock
See https://github.com/webkom/react-prepare/pull/33, almost fixes ABA-686
Forms will acutally still usually not render, because `lego-editor` cannot be rendered on the server, but the bug with `react-prepare` is fixed:)
=> Bump react-prepare to v1.0.1

app/Root.tsx, app/actions/FeedActions.ts, app/actions/GroupActions.ts, app/actions/SearchActions.ts, app/actions/UserActions.ts, app/components/Footer/index.tsx, app/components/Header/Navbar/Navbar.tsx, app/components/Header/ToggleTheme.tsx, app/components/Header/index.tsx, app/components/HeaderNotifications/index.tsx, app/components/Search/index.tsx, app/reducers/frontpage.ts, app/reducers/meetings.ts, app/reducers/routing.ts, app/render.tsx, app/routes/app/AppRoute.tsx, app/routes/contact/ContactRoute.ts, app/routes/index.tsx, app/store/createRootReducer.ts, app/utils/joinReducers.ts, app/utils/withPreparedDispatch.ts, server/ssr.tsx
Refactor global app-components like `<App>` and `<Header>` to use hooks instead of connect and props. I think this makes the code more readable and hopefully easier to maintain.
Have tested a bit, with and without ssr. Stuff still works.
=> Refactor AppRoute and related components to use redux hooks

cypress/support/utils.js
There was a small error in the selector, causing cypress to not find the arrow for selecting next month in the date selector. It only attempts to switch month on the last day each month, which is why it started failing now.
This one: 
No more error!
If cypress works on this PR it means i fixed it:)
=> Fix changing month of date selector in cypress

app/components/AuthSection/AuthSection.css, app/components/AuthSection/AuthSection.tsx
Issue described in https://github.com/webkom/lego/issues/3532
Also improve some minor styling.
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
The components now wrap as they should.
---
Resolves https://github.com/webkom/lego/issues/3532
=> Fix weird overflow on auth dropdown

app/components/Form/SelectInput.tsx, app/components/Tooltip/index.tsx, app/routes/admin/groups/components/AddGroupMember.tsx, app/routes/admin/groups/components/GroupMembersList.tsx, app/routes/companyInterest/components/CompanyInterestList.tsx, app/routes/events/components/EventList.tsx, app/routes/quotes/components/QuotePage.tsx, app/routes/surveys/components/Submissions/Results.tsx, app/routes/users/components/GroupChange.tsx, app/routes/users/components/PhotoConsents.tsx
A lot of components used the "wrong" select input instead of the wrapper
component with the correct styling and functionality.
---
Also, fix the tooltip by not showing it if it is disabled.
<table>
<tr>
<td>After</td>
<tr>
<td>
<td>
<tr>
</table>
Select inputs were tested and still work.
=> Employ the correct SelectInput everywhere

app/components/LegoReactions/index.tsx, app/components/Reactions/Reaction.tsx, app/routes/meetings/components/MeetingDetail.tsx
Fixes tooltip on reactions showing that "<Your name> reagerte med <emoji>" when reacting with an emoji on articles and quotes.
Resolves [#ABA709](https://linear.app/abakus-webkom/issue/ABA-709/fix-incorrect-reaction-tooltip-label)
=> Fix incorrect tooltip for reactions

app/actions/callAPI.ts
The pagination would load endlessly when there's nothing left to load. Can for example be encountered [when searching for an email that doesn't exist](https://abakus.no/admin/email/users?enabled=true&userFullname=test)
It is fixed
Resolves ABA-725
=> Fix pagination loading endlessly when there's nothing left to load

app/actions/SearchActions.ts, app/components/Search/index.tsx
The searchbar was slow, as in it only registered characters once you stopped typing
Fixed by wrapping the debounce-logic outside `setQuery`
The debounce-function also has to be memoized (`useCallback`), otherwise it will loose track of the previous callback
> I checked the [`useDispatch`-documentation](https://react-redux.js.org/api/hooks#usedispatch) and they say it is fine to not pass `dispatch` as a dependency to the memoized function the way we implement it:))
You can now search on things
---
Resolves ABA-771
=> Fix debounce on search

app/routes/events/components/EventList.css, app/routes/events/components/EventList.tsx
Fixes event filter overflow under `/events`
**before**
**after**
Works on both mobile and desktop
---
Resolves ABA-726
=> Fix event filter overflow

app/reducers/events.ts, app/routes/events/components/EventDetail/index.tsx, app/routes/pages/components/PageDetail.tsx, app/routes/polls/components/PollsList.tsx, app/routes/search/SearchPageWrapper.tsx, app/routes/userValidator/WrappedValidator.tsx
Undefined objects for non-authorized users.
Missing location invocations.
Now it doesn't crash for those specific issues.
Went through the webapp in most routes as both authenticated and non-authenticated user. Now these two issues appear to be resolved.
---
Resolves ABA-737
=> Resolve some router-v6 bugs

app/routes/pages/components/PageDetail.tsx
styrer, komiteer and revy are now shown in the sidebar for non-authenticated users.
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>
---
Resolves ABA-745
=> Display sections with group members in sidebar

app/components/Reactions/ReactionPicker.tsx
The check was for `null` values, but after the refactor the value was set to undefined - which is correct typewise, but fucked up the search function.  
Removed the null-value check as a null-value should not be allowed with the current type (`string | undefined`).
No crash
---
Resolves ABA-746
=> Fix bug where search was performed on undefined string causing crash

app/routes/interestgroups/components/InterestGroupDetail.tsx
Page will not crash on load, and it looks like it should.
This is not actually related to the react-router v6 migration, as this is actually a bug in prod as well.
Technically the user would only see the second before photo for half a second, but this illustrates the changes made - such as the "Admin" header always being shown to the user despite not being an admin at all ..
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<tr>
</table>		
---
Related to ABA-744
=> Allow non-logged in users to view interest group details

app/routes/users/components/UserConfirmation.tsx, app/utils/validation.ts
We actually had 4 users with one of the "invalid" allergies, which I have now removed. But while snooting around I also found a bunch of other bad allergies, so I added those to the list 
See image above.
=> Validate allergies in user registration form

app/components/CommentForm/index.tsx, app/routes/admin/groups/components/AddGroupMember.tsx, app/routes/admin/groups/components/AddGroupPermission.tsx, app/routes/announcements/components/AnnouncementsCreate.tsx, app/routes/companyInterest/components/CompanySemesterGUI.tsx, app/routes/contact/components/ContactForm.tsx, app/routes/events/components/EventAdministrate/AdminRegister.tsx
[Fix form for adding user to group](https://github.com/webkom/lego-webapp/commit/7b940be40770ecbabc00dc36391654592a8fcfac) 
Values sent as body were incorrect
---
[Only validate on submit for forms that reset on submit](https://github.com/webkom/lego-webapp/commit/0d61eb6fb016debfe2b19734e787210d81866c0e) 
These forms are reset on submit with `forms.reset()`, which causes all
the fields to be "touched" (?), which then causes them to be validated,
even though the user just submitted something. This is not really a
problem for all other forms.
Also update some submit buttons to use the `SubmitButton` component.
Adding users now works, but it clears out the membership table below ..
=> Fix form for adding user to group

app/components/LegoReactions/index.tsx, app/components/Reactions/Reaction.css, app/components/Reactions/Reaction.tsx, app/components/Reactions/index.tsx, app/routes/quotes/components/Quote.tsx, app/routes/quotes/components/QuoteList.tsx, app/routes/quotes/components/QuotePage.tsx, app/store/models/Reaction.d.ts
This has been bugging me for a long time - having to wait for the promise to resolve each time I react to something. This is the normal way of doing it, but it's not foolproof since the state update itself is async as well. I guess we'll have to wait for `useOptimistic`.
**Before**
The gray screen is due to an uncaught error
https://github.com/webkom/lego-webapp/assets/69514187/5248e8c1-6322-4c84-9dbe-5336ce8be735
**After**
https://github.com/webkom/lego-webapp/assets/69514187/0588eb6f-722c-4e95-b4d3-d65cbc411718
Reactions still work fine, both adding and removing. Also tested that users are still shown as expected on meetings.
=> Optimistically update reactions

app/routes/users/components/Confetti.css, app/routes/users/components/Confetti.tsx, app/routes/users/components/UserConfirmation.tsx, package.json, yarn.lock
Thought this was kinda fun
Also fix a bug :)
https://github.com/webkom/lego-webapp/assets/69514187/5e0a5cc2-eff1-42ba-8296-efd316287102
The confetti works?
---
This resolves nothing. Not needed at all.
=> Show confetti after registering a user

app/components/Table/BodyCell.tsx, app/components/Table/HeadCell.tsx, app/components/Table/index.tsx, app/routes/admin/groups/components/GroupMembersList.tsx
Refactor Table component to functional and split it over multiple files
* Change checkbox to radio button
* The behaviour has always been corresponding to Radio buttons, so I have no idea why they were checkboxes in the first place.
* I have a PR out that was intended to change the behaviour to match checkboxes (#4257) - but on second though I'd rather refactor first (this PR) - then touch up the code in the other PR to support checkbox/radiobutton depending on the table and column, as not all filters are suited to be checkboxes
* Prevent autoscroll on open searchbar
* If you go to prod/staging and scroll a little bit down before you click the search-icon on tables, you will be scrolled to the top of the page. This was annoying. This is gone.
* Members list seemed to have a bug in dev …
=> Refactor table component to functional

app/routes/events/utils.ts
Fix wrong text color for 'Annet' and 'Kid' calendar entries on dark mode.
**before**
**after**
Works like normal on light mode
---
=> Fix text color for calendar entries on dark mode

app/components/Table/BodyCell.tsx, app/components/Table/HeadCell.tsx, app/components/Table/index.tsx, app/routes/admin/groups/components/GroupMembersList.tsx
Replacement PR for https://github.com/webkom/lego-webapp/pull/4257, which is now obsolete.
Add a `filterOptions` attribute to columns, where they can be set to allow selecting multiple elements in the filter.
All filters are handled as arrays to simplify the divide between the two functionalities.
It wasn't possible to de-select radio-items by clicking them again, so I changed that.
If you're testing this locally, note that https://github.com/webkom/lego/pull/3518 might not be in prod/staging yet - and if it isn't you need to run the backend locally to verify that it works for membership lists in groups.
Before
https://github.com/webkom/lego-webapp/assets/13599770/229ec033-1092-4943-a140-b5bd7d524213
After
https://github.com/webkom/lego-webapp/assets/13599770/771016f0-dff8-4bbb-b088-741d00 …
=> Configure filtering to support multiselect

app/components/Header/Header.css
Resolve issue with screens between 940px and 1040px where the logo would not have any padding to the side of the screen
This lack of padding has been bugging me for a while so lets get it outta here
The logo is now indented by 20px on the left for big screens - which means it is flush with the events under instead of being 20px to the left
<table>
<tr>
<td>
<th>Before
<th>After
<tr>
<td>Width about 1000px
<td>
<td>
<tr>
<td>Wider screens
<td>
<td>
<tr>
<td>Smol screen
<td>No changes
<td>
</table>
---
=> Add padding-left to header

app/components/RandomQuote/RandomQuote.tsx
It appears that https://github.com/webkom/lego-webapp/commit/b959dfb7ea094e7ba4d5601c5109c01ee3e48984 might have introduced a possible state where null/undefined values are loaded into the `seen` array that is passed to the backend - rendering arrays such as `[,254]` - which the backend very much does not like.
This should resolve that.
Errors can be found in sentry. Seemed to only affect a few people for some weird reason, so I couldn't reproduce - but this seems to fix it.
Could probably also be resolved with a
```
if (!quoteId) return;
```
but I don't have that big of a preference.
I tried inserting invalid values locally and they were stripped - so I'm assuming it works ™️  …
=> Filter seenQuotes to only allow numbers

app/routes/users/components/UserConfirmation.tsx, app/utils/validation.ts
This error caused the validator on the register page to fail when the user did not provide an allergy (just like we want them to), making it impossible to register a new user.
Also added validators for first and last name, as they are required by the backend but weren't validated in the frontend.
The validator works
---
Resolves ABA-771
=> Check if allergies are undefined in validator

app/components/UserAttendance/AttendanceStatus.tsx, app/reducers/events.ts, app/routes/events/components/EventDetail/index.tsx
It would seem we missed another bug in the react-router migration.
As can be seen in LEGO https://github.com/webkom/lego/blob/master/lego/apps/events/models.py#L131, it's not enough to be logged in to be able to see registrations, you have to be either a member of abakom, creator of the event, or the event has to be in the future and you are allowed to sign up.
This became a problem when using the hook - as the return value would never become `undefined`, just an empty array - which made it seem like the user had permission even though it didn't -> crash
First reported by ludde in slack, but now it's been reported to sentry by 214 times by 94 users in the last 7 days - so it's about time to get this out of here
I've tested it locally through the staging backend where I got to reproduce it …
=> Store registrations as undefined if user has no access

app/actions/GroupActions.ts, app/routes/meetings/components/MeetingEditor.tsx
The feature that preloads users to allow them to be used as secretary before creating the meeting is beautiful with sudo permissions, but it crashes the page with a 403 error if you want to invite a group you don't have permission to load the members of (typically a group you're not part of)
Works on staging after demoting myself. Now the little popup on the bottom left of the screen appears to inform the user that the members were not loaded, but that's all. If you invite some groups you're a member of and some you're not the functionality is still intact for the groups you have permission to access.
---
Resolves ABA-772
=> Catch inviting groups you can't access members of

app/routes/admin/groups/components/AddGroupMember.tsx
A bug was recently implemented where the table over all the members of a group under `/admin/groups` would be cleared after adding a new member. Only a hard refresh could fix that problem. This has now been fixed.
**before**
**after**
---
Resolves ABA-751
=> Fix group table being cleared after adding a new member

app/routes/joblistings/components/JoblistingRightNav.tsx, app/routes/joblistings/constants.ts
Not sure why this stopped working? Or how it ever worked before
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>    
</td>
</tr>
</table>
Filtering still works like before.
=> Use "correct" label on grade checkboxes on joblistings page

app/components/EventItem/index.tsx, app/components/Poll/Poll.css, app/components/Poll/index.tsx, app/components/Upload/UploadImage.css, app/routes/bdb/utils.tsx, app/routes/events/components/EventAdministrate/Administrate.css, app/routes/events/components/Stripe.css, app/routes/photos/components/Overview.css, app/routes/polls/components/PollsList.css, app/routes/polls/components/PollsList.tsx, app/routes/users/components/Penalties.css, app/styles/variables.css, packages/lego-bricks/src/components/Button/Button.module.css, packages/lego-bricks/src/components/Icon/Icon.module.css, packages/lego-bricks/src/variables.css
This gives for a slightly better look on dark theme.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
A <i>slightly</i> different color on dark theme.
</td>
<td>
</td>
<td>         
</td>
</tr>
</table>
Works on both light and dark theme. This should not break anything else - even updated both duplicate variable files.
=> Standardize a success color

app/routes/events/components/EventAdministrate/Allergies.tsx, app/routes/events/components/EventAdministrate/AttendeeElements.tsx, app/routes/events/components/EventAdministrate/Attendees.tsx, app/routes/events/components/EventAdministrate/RegistrationTables.tsx
It takes up unecessary space in an already crowded table
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
All empty feedbacks are still shown if feedback is required (which technically will only happen if there are no registrations). 
---
Resolves ABA-784
=> Only show user registration feedback when relevant

app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/companyInterest/components/Translations.ts, app/routes/companyInterest/utils.tsx
Option requested by Inter
[Relevant backend PR](https://github.com/webkom/lego/pull/3552)
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested the creation and editing of interest forms with the new option picked.
=> Include social media profiling to company interest form

app/components/EventListCompact/index.tsx, app/reducers/__tests__/events.spec.ts, app/reducers/events.ts, app/routes/users/components/UserProfile.tsx
`state.event.fetching` is not really accurate, and it's so annoying that it always says there are no events even though they exist. [Try it yourself](https://abakus.no/users/me), but it's mostly only noticeable without SSR hehe
The new type of the event state is currently wrong, but will (can) be fixed with https://github.com/webkom/lego-webapp/pull/4224
Loading indicators now actually load appropriately.
Seems to work fine, can't imagine it breaking anything.
=> Appropriately show loading indicators for events on user profile

app/routes/pages/components/PageDetail.tsx
Only applies to some pages, so this was not previously caught
No visual changes - it just doesn't crash while fetching
No crashing!
=> Prevent page from crashing when no page is selected

app/components/Table/Table.css, app/components/Table/index.tsx, app/routes/admin/groups/components/GroupMembersList.tsx, app/routes/events/components/EventAdministrate/Abacard.tsx, app/routes/events/components/EventAdministrate/Allergies.tsx, app/routes/events/components/EventAdministrate/Attendees.tsx, app/routes/events/components/EventAdministrate/index.tsx, app/routes/users/components/UserSettingsOAuth2.tsx
Not only does it now resemble the other skeleton components, but it now also actually works
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
The changes look very little in this example. They are most noticeable (and look the best) on the event admin pages, but I can't show that here.
</td>
<td>
<video src="https://github.com/webkom/lego-webapp/assets/69514187/70b70bce-2814-4e45-920d-64ba0f8f2f8f" />
</td>
<td>
<video src="https://github.com/webkom/lego-webapp/assets/69514187/241ff81c-8b21-4167-841e-0b95a002ab6c" />
</td>
</tr>
</table>
Tested that table does not show skeleton when not needed.
=> Update table component's skeleton look

app/routes/overview/components/Overview.tsx, app/routes/overview/components/PublicFrontpage.tsx
Add banner to promote Abakusrevyen.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
---
=> Add revybanner

app/components/HeaderNotifications/index.tsx, app/routes/admin/email/components/EmailUsers.tsx, app/routes/admin/groups/components/GroupPage.tsx, app/routes/articles/components/Overview.tsx, app/routes/bdb/components/AddSemester.tsx, app/routes/bdb/components/BdbDetail.tsx, app/routes/company/components/CompanyDetail.tsx, app/routes/companyInterest/components/CompanyInterestList.tsx, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/contact/components/ContactForm.tsx, app/routes/events/components/EventAdministrate/Statistics.tsx, app/routes/events/components/EventEditor/index.tsx, app/routes/interestgroups/components/InterestGroupDetail.tsx, app/routes/meetings/MeetingDetailWrapper.tsx, app/routes/overview/components/Overview.tsx, app/routes/overview/components/PublicFrontpage.tsx, app/routes/pages/components/PageEditor.tsx, app/routes/photos/components/GalleryDetail.tsx, app/routes/photos/components/GalleryEditor.tsx, app/routes/photos/components/GalleryPictureEditModal.tsx, app/routes/photos/components/GalleryPictureModal.tsx, app/routes/polls/components/PollDetail.tsx, app/routes/quotes/components/QuotePage.tsx, app/routes/users/components/UserProfile.tsx, app/routes/users/components/UserSettingsNotifications.tsx, app/routes/users/components/UserSettingsOAuth2.tsx
`Promise.resolve()` will not reject upon any of the input promises rejecting, which can cause promises to never stop on the client if the server sends unhandled promises. Simply replacing with a `Promise.all()` fixes this issue.
Spamming hard refreshes does not put page in limbo 👍🏼 
https://github.com/webkom/lego-webapp/assets/69514187/d271c68e-f5ad-450a-9775-0dd1d0726691
=> Properly reject promises on server

app/routes/admin/email/components/EmailListEditor.tsx
Field was disabled when creating new email listings ;-;
[Screencast from 02-19-2024 10:29:05 AM.webm](https://github.com/webkom/lego-webapp/assets/42469466/000c0efa-160f-4a89-9f66-937643c4ce8f)
- Attempted to use field when creating new email lists, and checked that you cannot edit with existing email listings
---
Resolves ABA-831
=> Fix unintended disabled email list field

app/routes/users/components/UserProfile.tsx
Under change classes on profile page the classes weren't presented in ascending order, more like in random order. I sorted the groups presented by id. And now they are in ascending order.
**Before:**
**After:**
- [ x] Changes look good on both light and dark theme.
- [ x] Changes look good with different viewports (mobile, tablet, etc.).
- [x ] Changes look good with slower Internet connections.
- [ x] I have thoroughly tested my changes.
---
Resolves ABA-526
=> Made the gradelist in ascending order

app/routes/bdb/components/OptionsBox.tsx, app/routes/events/components/EventList.tsx
The default checked value of these checkboxes when visiting /events would be incorrect if you visit with query params, e.g. through the links on the frontpage "Bedpres og kurs" and "Arrangementer".
https://github.com/webkom/lego-webapp/assets/69514187/e10356c3-4c59-46e6-a682-0353dbccf61d
The checkboxes are now given default values when visiting the page with query params.
=> Accurately check checkboxes on /events filter

app/routes/surveys/components/SurveyEditor/SurveyForm.tsx
Previously, you couldn't change the ordering of questions on surveys. This is now fixed (in a slightly hacky way).
**before**
**after**
I've tested for several surveys and it works.
---
Resolves ABA-792
=> Fix ordering of questions on survey

app/components/Banner/Banner.css, app/components/Banner/index.tsx, app/routes/overview/components/ArticleItem.css, app/routes/overview/components/ArticleItem.tsx, app/routes/overview/components/CompactEvents.css, app/routes/overview/components/CompactEvents.tsx, app/routes/overview/components/LatestReadme.css, app/routes/overview/components/LatestReadme.tsx, app/routes/overview/components/NextEvent.css, app/routes/overview/components/Overview.css, app/routes/overview/components/Overview.tsx, app/routes/overview/components/Pinned.css, app/routes/overview/components/PublicFrontpage.tsx, app/store/models/Event.ts, packages/lego-bricks/src/components/Layout/Flex.tsx
Implemented the styling of the frontpage through CSS grid. The goal of this implementation is twofold;
1.  The overview both looks like a grid and smells like a grid - so imo it should be a grid
2. Plus this separates the components from the styling between them - facilitating moving components around and replacing them with improved versions without affecting the rest of the page.
Removed the two containers used for desktop and mobile and rather merged them into one responsive container.
Also updated some of the styling to add a little bit more space to the page, and make the spacing more consistent (e.g. adding padding to the right side of the screen and not only the left).
If you've made visual changes, please check the boxes below and include images showing the changes. Descriptions …
=> Implement overview-styling with grid

app/actions/ActionTypes.ts, app/actions/ForumActions.ts, app/components/Comments/Comment.tsx, app/components/Search/utils.tsx, app/reducers/forums.ts, app/reducers/index.ts, app/reducers/threads.ts, app/routes/articles/components/ArticleEditor.tsx, app/routes/forum/components/ForumDetail.tsx, app/routes/forum/components/ForumEditor.tsx, app/routes/forum/components/ForumList.css, app/routes/forum/components/ForumList.tsx, app/routes/forum/components/ForumListEntry.tsx, app/routes/forum/components/ThreadDetail.tsx, app/routes/forum/components/ThreadEditor.tsx, app/routes/forum/components/ThreadList.tsx, app/routes/forum/components/ThreadListEntry.tsx, app/routes/forum/index.tsx, app/routes/index.tsx, app/store/createRootReducer.ts, app/store/models/Forum.ts, app/store/models/entities.ts, app/utils/getEntityType.ts
Create abaquery forum, now working MVP.
There is still more I want to add, refer to linear. For now this is a very basic working forum (Like the notification on @ someone, subscribe to threads, and better content options beside just text)
Styling is not my strong suit, so all the sideborder colors on the threads are blue, which is kind of ugly, but I wasn't sure what to put because it should probably be different from the forums.
Maybe the color can be defined for each thread/forum? But that could also create a lot of chaos.
For now I added it to the hamburger menu. Maybe it should be more visible like in the top bar, but we also don't want too much clutter there.
I added a hover effect on comments that shows when they were created:
(If you're wondering why I'm using edge as my dev …
=> Create abaquery forum

app/routes/overview/components/Overview.tsx, app/routes/overview/components/PublicFrontpage.tsx
Revy 2024 is finished and a banner to the revy page is not needed anymore and is therefore commented out. Was removed from both front-pages, when logged in and not.
No performance changes
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Not logged in, light mode
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
Not logged in, Dark mode
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
Logged in, light mode
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
Logged in, Dark mode
</td>
<td>           
</td>
<td>
</td>
</tr>
<tr>
<td>
Mobile, not logged in, Dark …
=> Removed banner from front-page and overview

app/actions/EmojiActions.ts, app/components/Feed/renders/event_register.tsx, app/reducers/__tests__/announcements.spec.ts, app/reducers/announcements.ts, app/reducers/articles.ts, app/reducers/auth.ts, app/reducers/emailLists.ts, app/reducers/emailUsers.ts, app/reducers/emojis.ts, app/reducers/restrictedMails.ts, app/reducers/users.ts, app/routes/admin/email/components/EmailListEditor.tsx, app/routes/admin/email/components/EmailUserEditor.tsx, app/routes/admin/email/components/RestrictedMailEditor.tsx, app/routes/admin/email/components/RestrictedMails.tsx, app/utils/legoAdapter/createLegoAdapter.ts
Instead of rebasing my previous legoAdapter PRs I have just put the simple stuff into this PR and I will do the complicated (company and event) rebasing later. This refactors the following slices to use legoAdapter instead of createEntityReducer:
- announcements
- auth
- emailLists
- emailUsers
- restrictedMails
Nothing should change except that I reversed the sorting of the restricted mail list. Now the newest restricted mails are on the top, which makes it easier to find your relevant restricted mail if you have created a lot:)
- [no visual changes] Changes look good on both light and dark theme.
- [no visual changes] Changes look good with different viewports (mobile, tablet, etc.).
- [no visual changes] Changes look good with slower Internet connections.
I have tested basic …
=> Refactor some simple redux-slices to use legoAdapter

app/components/Poll/Poll.css, app/components/Poll/index.tsx, app/routes/overview/components/Overview.tsx, app/routes/polls/components/PollDetail.tsx, cypress/e2e/poll_spec.js
Shame to see updated components go to waste because of inactivity, so I have started scavenging what I could from https://github.com/webkom/lego-webapp/pull/2707 and updating it ever so slightly to merge it to master:)
With this update, no poll options are displayed until it is triggered, so the issue of showing all options while the component loads is no longer an issue.
> [!CAUTION]
https://github.com/webkom/lego-webapp/assets/13599770/bc07415c-7225-4a75-a0a2-fefd98ac2c9f
https://github.com/webkom/lego-webapp/assets/13599770/4b5e1472-0b3b-4c9a-8400-9f560ce27bb6 …
=> Redesign poll component

app/routes/polls/components/PollEditor.tsx, app/routes/polls/index.tsx
Kind of unpractical and not really something we do anywhere else on the
webapp, but when you edit a poll you render the same component as when
you create one. This caused the editor to lose its background since it
was technically not its own page ..
<table>
<tr>
<td width="13%">Description</td>
<td>After</td>
</tr>
<tr>
<td/>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>No changes here</td>
<td>
</td>
<td>
</td>
</tr>
</table>
See images above. Tested that both editing and creating polls works (i guess you never really know these days huh)
=> Give poll editor a background

app/routes/admin/groups/components/AddGroupMember.tsx, app/routes/admin/groups/components/GroupMembers.tsx, app/routes/admin/groups/components/GroupMembersList.tsx
Previously the pagination on the group members page was not working. This would also cause the members table to become empty when editing roles. 
Changes:
- Fixed paging on the group members table
- Fixed group members table becoming empty when editing user roles 
Previously:
[Screencast from 20. feb. 2024 kl. 13.18 +0100.webm](https://github.com/webkom/lego-webapp/assets/33326578/96dc148f-73be-4cb6-bdcc-1a3f8a61a9b5)
Fixed:
[Screencast from 20. feb. 2024 kl. 13.39 +0100.webm](https://github.com/webkom/lego-webapp/assets/33326578/804d8ade-44c3-4c5b-927d-f5bfa84957c1)
- Navigate to `/admin/groups/11/members`
- Change the role of one of the members.
- Verify that the table does not become empty and that the role is correctly updated.
- Navigate to `/admin/groups/3/members`.
- Scroll down …
=> Fix paging and members table becoming empty

app/actions/ArticleActions.ts, app/routes/articles/components/Overview.tsx
**bug-fix**
Article page continuously fetched due to usePreparedEffect being called on query variable change. Added useMemo to query variable such that it changes when location variable is updated, i.e. webpage.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
In old version simply being on the articles page and looking at the network tab you can see continuous fetch calls, …
=> Fix Article fetching forever

app/components/Content/ContentHeader.css, app/components/Content/ContentHeader.tsx, app/routes/events/components/Admin.css, app/routes/events/components/Admin.tsx, app/routes/events/components/EventDetail/EventDetail.css, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/EventEditor/index.tsx, app/routes/joblistings/components/JoblistingDetail.tsx, app/routes/surveys/components/AddSubmission/AddSubmissionPage.tsx
* Hide event type on mobile, as it took up unnecessary space
* Show skeleton components for registrations appropriately, as registrations are separated in the store
* Hide responsible group mail address in a tooltip
* Make admin buttons only clickable on the actual buttons
* Employ the actual text input component for the delete event field
* Clean up other minor stuff
Things look as expected, and deleting events still work.
---
Resolves ABA-866
Resolves ABA-865
Resolves ABA-817
Resolves ABA-721
=> Minor changes to event detail page

app/actions/AnnouncementsActions.ts, app/routes/announcements/components/AnnouncementItem.tsx, app/routes/announcements/components/AnnouncementsCreate.tsx, app/routes/announcements/components/AnnouncementsList.css, app/routes/announcements/components/AnnouncementsList.tsx, app/store/models/Announcement.d.ts
[Related backend changes](https://github.com/webkom/lego/pull/3565)
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Most of the "testing" is done on the backend, but things seem to work fine here as well.
=> Let users filter announcement recipients further

app/routes/frontpage/components/AuthenticatedFrontpage.tsx
Added a up button to the bottom of the shown events on front page. When clicked the button takes user to top of front-page and sets the shown events and articles to standard. 
Before:
https://github.com/webkom/lego-webapp/assets/145492323/4d4851c8-339c-4a22-ba1e-efb7b30b5e25
After:
https://github.com/webkom/lego-webapp/assets/145492323/490a48b5-bf6a-4507-be64-0e56da8f7a86
=> Add up button at the end of events on front page

app/components/Form/DatePicker.css, app/components/Form/ImageUploadField.css, app/components/Form/SelectInput.tsx, app/components/Upload/ImageUpload.tsx, app/components/Upload/UploadImage.css, app/routes/admin/email/components/EmailListEditor.tsx, app/routes/admin/groups/components/GroupForm/index.tsx, app/routes/articles/components/ArticleEditor.tsx, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/events/components/EventEditor/EditorSection/Descriptions.tsx, app/routes/events/components/EventEditor/EditorSection/Details.tsx, app/routes/events/components/EventEditor/EditorSection/Header.tsx, app/routes/events/components/EventEditor/EditorSection/Registration.tsx, app/routes/events/components/EventEditor/EditorSection/index.tsx, app/routes/events/components/EventEditor/EventEditor.css, app/routes/events/components/EventEditor/index.tsx, app/routes/photos/components/GalleryEditor.tsx, app/routes/photos/components/GalleryPictureEditModal.tsx, app/routes/surveys/components/SurveyEditor/Question.tsx, app/styles/overlay.css, app/styles/variables.css, cypress/e2e/create_event_spec.js, cypress/support/utils.js, packages/lego-bricks/src/components/Modal/Modal.module.css, packages/lego-bricks/src/variables.css
At this point the event sidebar is getting quite cramped as we have tons of configurations. Thus this is my initial suggestion at making it more pleasant to look at.
The styling with `sticky` headers and shadows is not really consistent with the rest of the webapp, but then again we have very few places where it would be relevant - and I believe this is one of them.
The main objective with the toggle sections is to display all information on create, but initially only display the desription on edit - as I imagine that is what's used most frequently.
No changes in functionality - only ordering and styling.
Minor changes:
* `location`
* It bugs me that the mazemap checkbox is over the location label, so I tried to implement it as a more unified field. For users it should make no difference …
=> Redesign event edit page

app/components/Reactions/ReactionPicker.css
Prevent it from appearing under poll component
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Werks
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
=> Add z-index to reaction picker

app/routes/companyInterest/components/CompanyInterestList.tsx
Current functionality limits filtering options for interest form responses to only active semesters. This restriction can be inconvenient for users wishing to review interest form answers from past semesters, as it necessitates setting those semesters to active status. - ChatGPT
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>Note: Høst 2024 and Høst 2023 are set as active semesters
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
It works
---
Resolves ABA-841
=> Add previous semesters to the filter under company interest

app/actions/EventActions.ts, app/models.ts, app/routes/events/components/EventAdministrate/Administrate.css, app/routes/events/components/EventAdministrate/AttendeeElements.tsx, app/routes/events/components/EventAdministrate/RegistrationTables.tsx, app/routes/events/components/RegistrationMeta.tsx, app/store/models/Registration.ts
[Related backend changes](https://github.com/webkom/lego/pull/3564)
Neither ion-icons or font-awesome had a turtle icon (which I thought was the most fitting), so I extracted one from Lucide (which we're planning on migrating to). I'm very open to design suggestions, as I'm not sure what I feel about this. The padding feels a bit much, so I might refactor the Icon component - but that will probably have to wait.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
The icons are much thinner and less "visible", but at the same time they are now Ionicons and therefore match all our other icons - so in that sense they are …
=> Introduce "too late" presence option to event attendees

app/routes/articles/components/ArticleDetail.css, app/routes/articles/components/ArticleDetail.tsx
This has bugged me for a long time
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See images above. Works when there's just one author as well
---
Resolves https://github.com/webkom/lego/issues/3497
=> Separate multiple article authors only by a comma

app/components/Upload/UploadImage.css
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested that this does not break the image upload in e.g. the event editor.
=> Fill placeholder background on image upload

app/components/LoginForm/RegisterForm.css, app/components/LoginForm/RegisterForm.tsx
This has been talked about for far too long
https://github.com/webkom/lego-webapp/assets/69514187/08a57f14-7aea-4cc7-ab69-5465dc35ea3e
You can still continue the registration with a student mail, and warnings are not given on normal mails.
=> Warn users about using their student mail when registering

app/components/MazemapEmbed/MazemapEmbed.css
Add a background to the MazeMap embed so you can see where it's supposed to appear while it is loading.
Right now there is an ugly empty area where the mazemap embed is supposed to load for a short while while it is loading. I think this would make it look a little smoother.
&nbsp;
I'm not able to reproduce this locally, so we're gonna have to go for a "trust me bro" and rather revert it if it is not a success - or deploy it to staging before merging it
---
=> Add background color to mazemap embed

app/components/Toast/ToastContainer.tsx, app/routes/photos/components/GalleryPictureModal.css
Upping the z-index so that we have more numbers to play with to conf lower laying items. Setting it pretty high as these should always be on top.
---
Resolves ABA-889
=> Up z-index for toast and gallery dropdown

app/actions/callAPI.ts
Because of a bug with the `callAPI` function used for fetching data, the public survey results page got stuck loading forever.
When fetching a list of things, LEGO will return an object containing a field named "results" that contains all the requested entities. Because of this `callAPI` will look for this field and put only it's contents into the redux-action which will be used to add the data to the state. This caused an issue with the public results page, as the survey-object used on this page contains a "results"-field that is not the list of all entities, but rather just the corresponding survey-submissions to the survey. This made `callAPI` return only these survey-submissions when we were expecting a survey object.
I think this was introduced in some refactoring a few months back, …
=> Fix bug in callAPI() breaking public survey results page

app/routes/admin/email/components/EmailListEditor.tsx
Adds form validation requiring at least one recipient field to be filled out to avoid email lists with no repients and mirror the backend behaiviour introduced here: https://github.com/webkom/lego/pull/3578
---
Resolves ABA-897
=> Add front end validation for email list recipients

app/actions/UserActions.ts
This bug was introduced in https://github.com/webkom/lego-webapp/pull/4540
A small difference in how legoAdapter works compared to createEntityReducer caused the logged in user to not get added to the redux state. The page then crashed when trying to read user data.
legoAdapter does a bit more validation than createEntityReducer to make sure that the redux action is actually a `callAPI()` action. This was a problem when the login code made a fake `User.FETCH.SUCCESS` action to add the user data to the state. In this PR I just made the fake more realistic, but I think I will refactor this a bit later.
No more crash:)
I have verified manually that the bug happens before this change, and not after.
=> Fix crash on login

app/routes/joblistings/components/JoblistingEditor.tsx
Resolves this issue:
<details>
<summary>Click to see Email</summary>
Heei, det har dukket opp et lite problem knyttet til jobbannonser på Abakus. Hvis vi trykker "rediger" på en jobbannonse for å gjøre noen endringer, endres type jobb og klassetrinn automatisk til "sommerjobb" og "1. - 5. klasse" selv om vi hadde skrevet noe annet der. Har du mulighet til å høre med WebKom om de kan se på det? Det er et nylig oppstått problem
</details>
Resolves ABA-901
- [ x] Changes look good on both light and dark theme.
- [ x] Changes look good with different viewports (mobile, tablet, etc.).
- [ x] Changes look good with slower Internet connections.
> [!CAUTION]
> Make …
=> Fix initialvalues for joblisting editor

app/reducers/users.ts
After updating an event, it is broadcast to all active users through websockets. This dispatches the same action as a user registering, but does not include a list of registered users.
I made a small mistake in #4540 causing an error to be logged in the console whenever you are on the event page, and the event is updated. I assumed that the update object would always include the registered users, turns out it only does when the update is a new registered user.
Updated event in staging and after fixing.
---
Resolves https://abakus.sentry.io/issues/5093947048/
=> Fix error when updating event

app/components/Form/SelectInput.tsx, app/components/Pill/index.tsx, app/routes/events/components/EventEditor/EventEditor.css, app/routes/events/components/EventEditor/PoolSuggestions.tsx, app/routes/events/components/EventEditor/renderPools.tsx
Added some suggestions of frequently used group combinations to make life simpler for event organizers.
The group combinations disable if more comprehensive groups have been selected, ensuring the the minimum amount of groups required is stored, while maintaining the group overlap and so on.
The functionality does not at all affect the input, so the users can still use it as they used to, but I believe this could resolve the errors of adding the wrong groups as this is simpler than typing them in.
The suggestions listen to the content of the list, so even if it is not used to select the groups, it can be used as an indicator of what groups you've already selected.
If you've made visual changes, please check the boxes below and include images showing the changes. Descriptions are …
=> Add pool suggestions displaying frequently used groups

app/actions/ActionTypes.ts, app/actions/FrontpageActions.ts, app/reducers/__tests__/readme.spec.ts, app/reducers/readme.ts
`createAsyncThunk` is redux-toolkits way to do asynchronous actions like fetching data. It is very similar to how `callAPI` does it and readme fetching used to do it, but fully typed. Since `fetchReadmes` doesn't use `callAPI`, I could type it using `createAsyncThunk`:)
Improves type safety
Readmes are still fetched successfully
=> Use createAsyncThunk to fully type readme fetch action

app/routes/users/components/Penalties.tsx, app/routes/users/components/PenaltyForm.tsx
Very small styling error that has bugged me for some time. If the user is missing the action grant and does not have a "add penalty" button, the divider is not needed.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See images above. Works fine with (multiple) penalties as well
=> Remove penalty divider for users missing action grant

app/actions/GroupActions.ts, app/actions/callAPI.ts, app/models.ts, app/reducers/selectors.ts, app/routes/admin/email/components/EmailUsers.tsx, app/routes/events/components/EventAdministrate/Statistics.tsx, app/utils/createQueryString.ts
Currently there are a lot of emails with active users that look as if they weren't supposed to have them, because only committees are shown in the list. This is stoopid - and should hereby be banished.
This shows
* committees
* boards
* ordained
and should give a more accurate view of who should have their email activated and not
Also added the option to fetch groups from multiple group types at the same time.
Relies on https://github.com/webkom/lego/pull/3577
Don't have too many visuals, as the changes require a fresh backend - and the groups I would need to display to preview it don't exist in the backend.
The only visual change is just that more groups are …
=> Extend email-user view to show more groups

app/routes/interestgroups/components/InterestGroupDetail.tsx
I noticed this little bug while refactoring some other stuff. The missing dispatch definition makes it impossible to join or leave interest groups. 
It is once again possible to join or leave interest groups.
It previously threw an error when attempting to join or leave, it now doesn't.
=> Fix joining and leaving interest groups

app/reducers/index.ts
The schema key needs to be exactly equal to the entity name in redux (EntityType) for createEntityReducer and legoAdpapter-slices to work, so I think using the enum is a good idea.
See diff. The enum should contain the exact same strings as were used previously, so nothing should change.
It will, however, make refactorings like changing entity names easier and safer.
Did some quick testing on some random pages, but as stated earlier the enum contains the exact same strings, so nothing should change.
=> Use EntityType enum for schema keys

app/reducers/__tests__/notificationSettings.spec.ts, app/reducers/notificationSettings.ts
Refactor the notificationSettings reducer/slice to use `createSlice`, and fully type the state (not the actions unfortunately).
See diff. Slightly better type safety, and easier to improve typing in the future.
Have tested the notification settings page manually, it seems to both display and update correctly.
---
ABA-688
=> Type and refactor notificationSettings redux slice

app/reducers/comments.ts, app/reducers/groups.ts, app/reducers/restrictedMails.ts, app/reducers/users.ts, app/routes/admin/email/components/EmailListEditor.tsx, app/routes/admin/email/components/EmailUserEditor.tsx, app/routes/admin/email/components/RestrictedMailEditor.tsx, app/routes/admin/groups/components/GroupForm/index.tsx, app/routes/admin/groups/components/GroupPage.tsx, app/routes/admin/groups/components/GroupPermissions.tsx, app/routes/articles/components/ArticleDetail.tsx, app/routes/articles/components/ArticleEditor.tsx, app/routes/forum/components/ForumDetail.tsx, app/routes/forum/components/ForumList.tsx, app/routes/forum/components/ThreadDetail.tsx, app/routes/interestgroups/components/InterestGroupDetail.tsx, app/routes/interestgroups/components/InterestGroupEdit.tsx, app/routes/meetings/components/MeetingDetail.tsx, app/routes/tags/components/TagCloud.tsx, app/routes/tags/components/TagDetail.tsx, app/routes/users/components/UserSettingsOAuth2Form.tsx, app/store/models/RestrictedMail.d.ts, app/store/models/entities.ts, app/utils/legoAdapter/buildPaginationReducer.ts, app/utils/legoAdapter/createLegoAdapter.ts
The entities contained in the redux-store are of unknown type, meaning a meeting might f.ex. either be from a meeting list or the detailed model used on the meeting page. When selecting them we usually know what type we are expecting, meaning we will need to typecast it (or do some insane type checking to make typescript infer it). With this new API this typecast is easier, and less error-prone as you can't forget to include the possibility of `undefined`!
```typescript
const detailedMeeting = useAppSelector((state) => selectMeetingById<DetailedMeeting>(state, meetingId));
const listMeetings = useAppSelector(selectAllMeetings<ListMeeting>);
```
These will get the following types:
```typescript
detailedMeeting: DetailedMeeting | undefined
listMeetings: ListMeeting[]
```
`selectById()`  now …
=> Improve lego adaptor selectors

app/actions/PollActions.ts, app/reducers/polls.ts, app/routes/frontpage/components/AuthenticatedFrontpage.tsx, app/routes/polls/components/PollsList.tsx, app/store/models/Poll.d.ts
One more slice down. This one is fairly straigtforward, but I did have to change from using old `pagination` to `paginationNext` in poll list.
I fixed a bug where there would be two loading indicators when fetching more polls in the poll list:
Have tested poll list, poll detail page, creating a new poll and voting in the poll.
---
ABA-688
=> Use createSlice and legoAdapter for polls slice

app/routes/events/components/EventFooter.tsx
Removed the link to settings for the events calendar as the settings had no function. Instead added text to for user to click on one of the links to add to their calendar. 
Before (1. events calendar, 2. settings):
1:
2:
After:
---
Resolves ABA-882
=> Remove link to settings in calender for events

app/routes/events/components/EventDetail/index.tsx
Removed {registrations} over the modal that shows how many are registered for an event when not logged. It just showed "ingen er påmeldt" no matter what. Now it is removed. Still works as normal when logged in. 
Before: 
After: 
---
Resolves ABA-881
=> Remove 'ingen er påmeldte' from registrations when not logged in

app/reducers/__tests__/surveySubmissions.spec.ts, app/reducers/surveySubmissions.ts, app/reducers/surveys.ts, app/routes/surveys/components/AddSubmission/AddSubmissionPage.tsx, app/routes/surveys/components/AddSubmission/AlreadyAnswered.tsx, app/routes/surveys/components/AddSubmission/SurveySubmissionForm.tsx, app/routes/surveys/components/StaticSubmission.tsx, app/routes/surveys/components/Submissions/Results.tsx, app/routes/surveys/components/Submissions/SubmissionPublicResultsPage.tsx, app/routes/surveys/components/Submissions/SubmissionsPage.tsx, app/routes/surveys/components/SurveyDetail.tsx, app/routes/surveys/components/SurveyEditor/EditSurveyPage.tsx, app/routes/surveys/components/SurveyList/SurveyItem.tsx, app/routes/surveys/components/SurveyList/SurveyList.tsx, app/routes/surveys/components/SurveyList/SurveyListPage.tsx, app/routes/surveys/index.tsx, app/store/models/Survey.d.ts, app/store/models/entities.ts
Refactored `surveys` and `surveySubmissions`-slices in redux to use `legoAdapter` and `createSlice`.
Changed the survey-selector so that it no longer puts the relevant event into the survey. This can instead be selected separately if necessary. This is mainly to simplify and reduce the number of different types.
No visual or functional changes
Reduces number of typescript errors by 7
I did all the survey things and they still work. 
Some survey things don't well for non-admins, but that's unrelated to this PR. F.ex. the page for reviewing your survey submission gets a 403 error from the backend. 
---
ABA-688
=> Refactor and type surveys state and components

app/components/Header/ToggleTheme.tsx
I hate to have to wait 200ms every time I want to update the theme. Only debouncing the requests to the server should be enough.
This also prevents unnecessary requests and responses, because now if the user spams the switch button, the user will only receive one toast feedback instead of 1000. I increased the debounce time to 300ms since the wait is fine now - could probably do more but meh
I'd say this is a bug fix
<details>
<summary>Before</summary>
https://github.com/webkom/lego-webapp/assets/69514187/fd2a5bcc-daea-4fbd-85ca-7ce2befd6171
</details>
<details>
<summary>After</summary>
https://github.com/webkom/lego-webapp/assets/69514187/c1e016f2-a35d-4b30-bac6-b29c98e039bf
</details>
See videos above.
=> Do not debounce local theme change

app/components/Search/Search.css, app/components/Search/SearchPageResults.css, app/components/Search/SearchPageResults.tsx, app/components/Search/SearchResults.tsx, app/routes/surveys/components/SurveyEditor/SurveyForm.tsx
Use standardized spacing, remove use of non-existing variables and resolve a bug on mobile Safari where links at the bottom were not visible.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See images above. Tested on my actual iPhone
=> Update and fix search and menu styling

app/actions/UserActions.ts, app/reducers/penalties.ts, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/JoinEventForm.tsx, app/routes/events/components/__tests__/JoinEventFormCountdownProvider.spec.tsx, app/routes/users/components/Penalties.tsx
Simple refactoring PR. Refactored from `createEntityReducer` to `legoAdapter` and `createSlice`. I also removed the need for custom logic when deleting penalties by using correct field-name for `id` in the `DELETE` action.
No functional or visual changes.
I tested creating and deleting penalties.
---
ABA-688
=> Refactor redux penalites

app/components/Form/TextEditor.tsx, app/routes/events/components/EventEditor/EditorSection/Descriptions.tsx, app/routes/events/components/EventEditor/index.tsx
Currently only required on the server - which caused issues for some
See image above - it now requires it!
=> Require event content in editor

app/actions/callAPI.ts, app/reducers/pages.ts, app/reducers/selectors.ts, app/routes/admin/email/components/EmailLists.tsx, app/routes/admin/email/components/EmailUsers.tsx, app/routes/admin/groups/components/GroupMembers.tsx, app/routes/articles/components/ArticleList.tsx, app/routes/company/components/CompaniesPage.tsx, app/routes/meetings/components/MeetingList.tsx, app/routes/polls/components/PollsList.tsx, app/routes/quotes/components/QuotePage.tsx, app/routes/surveys/components/SurveyList/SurveyListPage.tsx, app/utils/createQueryString.ts, app/utils/legoAdapter/__tests__/buildPaginationReducer.spec.ts, app/utils/legoAdapter/__tests__/createLegoAdapter.spec.ts, app/utils/legoAdapter/buildPaginationReducer.ts
This is a small improvement that might gives us a bit more accurate fetching states. Basically on some pages we might fetch multiple queries for the same entity type simultainiously, f.ex. upcoming and previous meetings. Using the normal `fetching` state we have no idea which one is fetching (and it is sometimes wrong). Instead we can use the pagination system, and save for each separate pagination query if it is fetching or not.
I added this functionality in `legoAdapter`, and changed most paginated pages to use this `fetching`-state instead of the general one for the entity type.
Currently it should function fairly similarily, but it should be easy to refactor pages to provide more accurate loading indicators if someone wants to do that.
I have tested many of the affected pages, and the …
=> Add fetching state to legoAdapter pagination

app/components/Table/HeadCell.tsx, app/routes/admin/email/components/EmailUsers.tsx, app/utils/legoAdapter/createLegoAdapter.ts
Added subgroups to email-user list view - as some of them have @abakus.no emails as well.
Also fixed a 'lil bug I introduced to the `Table` component way back when I refactored it that made the filter stuff look active even when it wasn't. Now it works the way it's supposed to again, properly tested(:
---
=> Resolve bug showing active style and add subgroup to email

app/reducers/galleries.ts, app/routes/photos/components/GalleryDetail.tsx, app/routes/photos/components/Overview.tsx
There were some small mistakes in #4641, that I have fixed here:)
- Photo album order was reversed (ish). It is now sorted by the `takenAt` attribute.
- The now unused `GalleryEntity` was not removed.
- Loading indicator was not shown on the initial fetch (this was already a problem before #4641)
No image because of personal data, but it's now sorted the same as in prod.
Compared sort order to prod, and tested the loading indicator both on inital fetch and fetching more.
---
ABA-688
=> Fix some issues with photo gallery page

app/components/Form/CheckBox.css, app/components/Form/CheckBox.tsx, app/components/Form/Field.tsx, app/components/Form/MultiSelectGroup.tsx, app/routes/meetings/components/MeetingEditor.tsx
Reduce click-area and margin of mazemap checkbox label as reported in https://github.com/webkom/lego/issues/3567.
Also reduces the click area of all checkboxes that are wrapped in the Field component across the webapp.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Reduced size and margin
</td>
<td><img width="478" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/32014ee4-f54c-46e0-98eb-de4327867356"></td>
<td><img width="371" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/6d0d3f66-abbd-406c-9b …
=> Reduce click-area of mazemap checkbox label

app/components/ErrorBoundary/index.tsx
We get a lot of screenshots of the same component - which really gives us no information at all. And some times it is quite hard to find the error in sentry to get the debugging going.
This should resolve this problem, by encouraging users to report persisting issues that we haven't resolved in an orderly fashion, and requesting them to provide the sentry event id that we can search for to find more details on sentry.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td><img width="837" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/f8345d98-29fb-4a75-b3a …
=> Improve description in error boundary

app/actions/EventActions.ts, app/reducers/imageGallery.ts, app/routes/events/components/EventEditor/index.tsx, app/store/models/ImageGalleryEntry.d.ts, app/store/models/entities.ts
This is the slice for saved cover images that can be used on new events. The refactoring was fairly straightforward, except for the fact that some types were missing for the redux state.
More types, less usage of `createEntityReducer`
---
ABA-688
=> Use legoAdpater and createSlice for imageGalleryEntries slice

app/routes/polls/components/PollEditor.tsx
The frontend validation when creating/editing a poll did not check for the length of each, where as in the backend that field can max be 30 characters.
If you tried to create a poll with a option longer than 30 char. you would only get a message that the creation failed, and no reason why. 
---
Resolves ABA-907
=> Match poll validation to backend

app/routes/admin/groups/components/AddGroupPermission.tsx, app/routes/admin/groups/components/GroupPage.tsx, app/routes/admin/groups/components/GroupPermissions.tsx
In the state, we store all groups in a long list together - more or less like so;
```
groups: {
entities: [a lot of group objects],
fetching: false,
...
}
```
This is used both for fetching the list of groups that are in the sidepanel of abakus.no/admin/groups and the individual groups. Thus the type of entities is UnknownGroup[] (consisting of DetailedGroup, PublicGroup, +++)
Thus, when you're navigating /admin/groups, the state will contain all the groups, because they are fetched to be in the sidebar. Those groups however are PublicGroup instances (not very detailed, as they're not needed to be for the list.  
That means that they do not have e.g. `permissions` and `parentPermissions`.
When you navigate to another group, it will try to display the group, and as it already exists, it …
=> Ensure permissions are present to display list

app/components/Feed/index.tsx
Timeline page is blank in prod. I think it must have broken during some rebase, it's just a wrong prop name.
It works now:)
Typescript no longer complains, and the page renders in local dev.
---
Resolves https://abakus.sentry.io/issues/5098383302/events/a37e703bacb746e5b9d191ac36f62821/
=> Fix incorrect prop name in timeline acitivity

app/actions/EmailListActions.ts, app/routes/admin/email/components/EmailListEditor.tsx
With the changes in routing the param is undefined rather than "new". This fix makes it possible to create email lists again.
Also added some successMessages as the mail-list views suffer from a huge lack of feedback on creation/editing lists.
Before: no feedback on success
After:
---
Resolves ABA-933
=> Fix isNew-bug and add successMessages to mail-list

app/routes/companyInterest/components/CompanyInterest.css, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/companyInterest/components/Translations.ts
I gladly take input on text to the tooltip, which are mostly cooked from interestText in utils.tsx or other comments
add some tooltip for events in interesseform to more clearly convey what an event means . All the event types have some form of tooltip now.
**new-feature**
- [?] Changes look good with slower Internet connections.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Darkmode, computer
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
Lightmode, mobile
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Please describe what and how the changes …
=> add some tooltip for events in interesseform

app/actions/EventActions.ts, app/routes/events/components/Analytics.tsx
It was reading the payload wrong. See diff.
Sentry issue: https://abakus.sentry.io/issues/5086404761/events/bac5f1520a344e3d9b2305e0977fa641/
The page view analytics on the event statistics page now works again:) 
It didn't work, now it does.
=> Fix error when reading plausible analytics data

app/components/Comments/Comment.tsx, app/components/Comments/__tests__/CommentTree.spec.tsx, app/reducers/comments.ts, app/store/models/Comment.d.ts, app/utils/getEntityType.ts
Adds reactions to comments.
I faced a small issue and came up with a "hacky" solution: Models that can be reacted on, like articles and meetings, have a contentTarget property that determines what model the reaction should be added to. This property points to the model itself, so that if you react to an article, the reaction is added to that article. I imagined that I could to the same thing for comments: adding a contentTarget property that points back to the comment itself. However, comments already have a contentTarget property that is used to link to the parent model, like an article, causing reactions to be added to the article instead of the comment (never really tested that this actually happened, but it's my guess). My workaround was to add a contentSelf property and pass it to …
=> Add reactions to comments

app/utils/themeUtils.tsx
Allow the site to set the previously selected theme before it is overridden by the backend
Werks
> [!CAUTION]
Run some reloads and hard reloads in dark mode and it seems to work as expected
---
Resolves ABA-788
=> Cache theme in localStorage

app/routes/events/components/JoinEventForm.tsx
When people are getting off the waitlist on a paid event the payment form is not visible, even though the person has to pay. Currently this forces the money-people to setup manual payments and manually keep track of whether those payments have been received outside the system.
This change enables waitlisted attendees to pay as soon as they are marked as present. In this way, payments will show up in the overview along all the other payments and no manual workarounds should be needed to receive the payment.
This could also allow the hosting groups to receive the payment at the start of the event instead of having to hunt them down later on.
The payment-form is now presented if you're on the waitlist and attended.
---
Resolves ABA-943
=> Show payment-form if event was attended

app/components/Image/Image.tsx, app/routes/frontpage/components/AuthenticatedFrontpage.css, app/routes/frontpage/components/LatestReadme.tsx, app/routes/frontpage/components/Pinned.css, app/routes/frontpage/components/PublicFrontpage.css, app/routes/frontpage/components/PublicFrontpage.tsx
As our beloved prod-testers have reported through the proper channels, the readmes do not display properly on the public frontpage.
Turns out that the ref used to get the proper size of the container does not update the component state (which makes sense), and the only reason this works locally and when authenticated is that the component is always re-rendered after the images are fully loaded (either locally from being slow or when logged in by toggling the component).
Also added some long-awaited padding and styling to the public frontpage to match the authenticated one.
Minor changes
* Update fp-2023->2024
* Minor styling of the public frontpage
> [!CAUTION] …
=> Resolve readme container missing height on public frontpage

app/routes/frontpage/components/LatestReadme.tsx
Although you can click on the entire component to expand it, I think it's good for the icon to "act" (or, look) as a button since the user may assume (s)he should click on it.
Also, this lets the user "tab" to and use the component. So I suppose that's a "yay" for universal design
https://github.com/webkom/lego-webapp/assets/69514187/462ee059-ce03-439b-b6a5-72f6540db8f4
See video above
=> Make icon on latest readme comp "act" as a button

app/components/UserGrid/index.tsx, app/routes/interestgroups/components/InterestGroupDetail.tsx
im back
See linear issue for context
It works, but I don't want to show members here. Check out http://localhost:3000/interest-groups/201 if you don't believe me 😝 
Hard refresh, and no skeleton. Added a default value of false to prevent any other similar bugs
=> Prevent endless skeleton for interest groups with < 10 members

app/routes/bdb/utils.tsx, app/routes/companyInterest/components/CompanyInterest.css, app/routes/companyInterest/components/CompanyInterestList.tsx, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/companyInterest/components/CompanySemesterGUI.tsx
The "editor" is also used when you just want to view the submitted form, so I believe saying you're "editing it" may sound scary and is in most cases "wrong". Does that make sense?
Also add a back button, and change all urls to point to `company-interest` instead of `companyInterest` (both are supported) since urls should be kebab-case.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
I removed some unnecessary css, but that was tested. Urls were also tested
=> Reword header on company interest editor

app/components/UserAttendance/AttendanceModalContent.css, app/components/UserAttendance/AttendanceStatus.css
Technically, this also applies to event details, but the pool names there are rarely named something with multiple words.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See image above. Tested with ssr as well due to css cascading behaving a bit weird here
=> Fix overflow issues on meeting details

app/actions/CompanyActions.ts, app/routes/joblistings/components/JoblistingEditor.tsx
Two issues fixed here. When creating a new joblisting, the company contacts would not be fetched since the company id would be in `company.value` instead of `company.id`. Secondly, once you've managed to fetch, you would also get an error since it was trying to map over the payload instead of the results.
Also, 
Editing and creating joblistings now work without any errors.
=> Fix fetching of company contacts in joblisting editor

tsconfig.json
`commonjs` is not an allowed module when `moduleResolution` is set to `bundler`. Read more about this here https://www.typescriptlang.org/tsconfig/#module
@eikhr you'll have to verify this since you recently changed it
`yarn tsc` now works, and everything seems to bundle and work fine?
=> Change ts compiler option "module" to `preserve`

app/routes/events/components/EventAttendeeStatistics.tsx, app/store/models/User.ts
Gender is not required in the backend. The statistics page assumed it was, causing a crash whenever a user had `gender=undefined`.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Behaiviour of statistics page
</td>
<td>
Crash
</td>
<td>
Works
</td>
</tr>
</table>
In the testing fixtures, one user has gender `undefined`. It now works with the testing fixtures.
---
=> Fix crash on statistics page

app/routes/companyInterest/components/CompanyInterest.css, app/routes/companyInterest/components/CompanyInterestPage.tsx
This is already supported in the field component through the `description` prop. I noticed the translations could be refactored as well since most of them are used elsewhere, but some times with slight different text .. I'll spare that to later
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See image above
=> Refactor tooltips on company interest form

app/components/Header/Header.css, app/components/Header/index.tsx, app/components/UserAttendance/Attendance.tsx, app/routes/bdb/components/OptionsBox.tsx, app/routes/events/components/EventDetail/EventDetail.css, app/routes/events/components/Registrations.css, cypress/e2e/router_spec.js, packages/lego-bricks/src/components/Icon/Icon.module.css, packages/lego-bricks/src/components/Layout/Page/Page.module.css, packages/lego-bricks/src/components/Layout/Page/Page.tsx
I don't believe these things should be "red". Also, re-implement the
transition on the back link on pages hehe :see-no-evil:
---
Also fix a unrelated minor bug; [Show skeleton user cells when fetching registrations](https://github.com/webkom/lego-webapp/commit/25384b1e6469219e94453795b1171023332dd23a)
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>Back link, notification badge and hamburger icon</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Looked at the changes - and they looked alright 👍🏼
=> "Blackify" parts of the webapp

app/components/ErrorBoundary/ErrorBoundary.css, app/components/ErrorBoundary/index.tsx, packages/lego-bricks/src/components/Card/Card.module.css, packages/lego-bricks/src/components/Card/index.tsx
This bug still confuses me .. I'm still not sure why the overflow actually happens
<table>
<tr>
<td width="13%">Description</td>
<td>After</td>
</tr>
<tr>
<td>
iPhone 12 Pro (390x844)
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested on larger viewports as well hehe
=> Prevent text overflow on error boundary

app/components/EventItem/index.tsx, app/components/EventItem/styles.css, app/components/Form/CheckBox.css, app/components/Form/CheckBox.tsx, app/components/Form/Field.css, app/components/Form/Field.tsx, app/components/Form/MultiSelectGroup.css, app/components/Form/RadioButton.css, app/components/Form/RadioButton.tsx, app/components/Header/Header.css, app/components/Poll/Poll.css, app/components/Upload/UploadImage.css, app/routes/app/AppRoute.tsx, app/routes/events/components/Calendar.css, app/routes/forum/components/ForumEditor.tsx, app/routes/pages/components/subcomponents/Statistic/Statistic.css, app/routes/pages/components/subcomponents/Statistic/index.tsx, app/routes/users/components/UserSettings.css, packages/lego-bricks/src/components/Layout/Page/filterSidebar.tsx
There's some buggy behaviour where our webapp inherits the `line-height` from the `lego-editor` of `1.8`. I've tried to update most places that are affected by this if we ever update `lego-editor` with the latest `lego-bricks` variables ..
Most changes are barely noticeable.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
All changes were tested. That's why there's not that many ...
=> Update various spacings

app/routes/bdb/SortCompanies.ts
Among other things we now check for `null`, which prevents an error when sorting on student contacts.
It's now possible to sort on all kinds of things, both ascending and descending.
=> Handle more edge cases when sorting companies

app/components/Form/Field.tsx, app/routes/announcements/components/AnnouncementItem.tsx, app/routes/announcements/components/AnnouncementsCreate.tsx, app/routes/announcements/components/AnnouncementsList.css, app/routes/announcements/components/AnnouncementsList.tsx, packages/lego-bricks/src/components/Card/Card.module.css
Improved ux, with a slightly updated list design
* Title is changed, and helmet moved
* Some sub headers and placeholders are also updated
* Exclude waiting list checkbox is disabled (with a tooltip) when no event has been chosen
* Info card is moved and rephrased to avoid any confusion
* Announcement list is retouched
* General spacing improvements
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
I think it's worth noting that it's pretty rare for people to have sent many announcements
See images above. Minor changes to the field and card components were tested with other use cases.
=> Slight improvements to the announcements page

app/components/Form/TextInput.css, app/components/Form/TextInput.tsx
Applies to all fields of type `password`
<video src="https://github.com/user-attachments/assets/ebb486d3-d809-4b53-b775-574f35cfc6e5" />
Logging in still works fine 😎 
---
Resolves ABA-966
=> Add toggle for password visibility in field

app/components/Tags/Tag.css, app/components/Tags/Tag.tsx, app/components/Tags/index.tsx, app/routes/articles/articles.css, app/routes/articles/components/ArticleList.tsx, app/routes/frontpage/components/AuthenticatedFrontpage.css, app/routes/frontpage/components/utils.tsx
Made some general clean ups as well
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested wrap on mobile.
Tested various tag lines; on front page, articles list, comments (author tag).
=> Fix bad spacing between article tags

app/components/Content/ContentSidebar.tsx, app/components/Form/CheckBox.css, app/components/Form/CheckBox.tsx, app/components/Form/Field.tsx, app/components/Form/RadioButton.css, app/components/Form/RadioButton.tsx, app/routes/joblistings/components/JoblistingDetail.tsx, app/routes/joblistings/components/JoblistingEditor.tsx, app/routes/joblistings/components/JoblistingList.css, app/routes/joblistings/components/JoblistingList.tsx, app/routes/joblistings/components/JoblistingPage.tsx
Saying there are no joblistings out at all is wrong when the user has only filtered out all, imo.
The improved spacing on the detailed joblisting page is very subtle, but it's there
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>    
</td>
</tr>
</table>
Looks good on mobile as well.
=> Improve empty state message on joblisting list

app/routes/photos/components/GalleryPictureEditModal.tsx
The modal would close when tagging users, causing changes to not be saved.
Tagging now works. Closing the modal like normal still works fine.
=> Prevent picture edit modal from closing when tagging

app/components/Poll/Poll.css, app/components/Poll/index.tsx, app/components/Search/utils.tsx, app/routes/polls/components/PollsList.css, app/routes/polls/components/PollsList.tsx, cypress/e2e/poll_spec.js
Minor clean ups here and there, better alignments and less "custom" css. It still feels a bit out-of-place, but I think it's improved (especially the items in the poll list).
It has annoyed me for a long time that the border radius did not match the rest on the front page.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Works on mobile. Border radius does still not work on Safari though ..
=> Slightly refactor and retouch poll styling

app/actions/GalleryPictureActions.ts, package.json, yarn.lock
It was only used one place, so I figured it could be removed. We still have a ton of outdated and pretty much unused deps we should remove.
Images are still uploaded in sequential batches.
=> Remove `es6-promise-pool` dependency

app/components/UserAttendance/Attendance.tsx, app/routes/events/components/EventDetail/EventDetail.css, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/Registrations.css
kind of subtle, but annoying
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See image above.
=> Fix bad spacing on event details

app/components/Header/Navbar/ItemList.tsx, app/components/InfoList/styles.css, app/routes/joblistings/components/JoblistingDetail.tsx, app/routes/joblistings/components/JoblistingEditor.tsx
* Check for duplicate mails
* Turn contact mail into an anchor element
* Wrap mails on @ for readability
* Only show "Kontaktperson" sub header if needed
* Better widths, wrappings and look
* Let editor fields be clearable
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>Duplicate mails</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
<p>Different mails</p>
<div>Notice that the first contact mail is not wrapping on "@", since it's not needed
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
See images above
=> Improve contact info on joblistings

app/components/Header/Header.css
oops
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Fix z-index issue on registration warning

app/components/Form/Field.css, app/routes/admin/groups/components/GroupForm/index.css, app/routes/admin/groups/components/GroupForm/index.tsx
Two seperat fixes
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See images above. Tested with ssr
---
Resolves ABA-1010
=> Fix bad field widths

app/components/Table/index.tsx, app/routes/admin/groups/components/GroupMembers.tsx, app/routes/admin/groups/components/GroupMembersList.tsx
The problem was that the Table-component was filtering on all the things that were passed in through the `filters`-prop. This may sound correct, but I think we only want it to filter on the ones that are also defined as columns in the table. These are the ones with filters in the table UI.
I think this is the best way to do it, as we often pass all query parameters to the table filters even though not all of them should directly filter the table contents.
Group members now appear.
The filters on group member list page now works as intended, and I also tested some filtering in BDB to ensure I didn't break that.
---
Resolves ABA-1008
=> Fix bug in table filtering breaking group member list

app/routes/pages/components/PageEditor.tsx
Resolves a bug where when you go directly into the edit-page it won't fetch anything - as the `page` object is only populated on fetch - and the fetch call was not executed as page was undefined.
Werks
=> Resolve reload bug on page edit

app/components/JoblistingItem/Items.tsx, app/components/JoblistingItem/index.tsx
Two minor improvements to joblisting items. The tags make the list much easier to quickly go through. Not entirely sure about the colors
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See images above. Only 23:59 is filtered out (see second item)
=> Minor improvements to joblisting items

app/components/Tooltip/Tooltip.css
In case of sub-pixels rendering in the browser or rounding errors when positioning the arrow, a small space between content and arrow might appear. This fixes this glitch by adding a small border.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Try zooming in the browser, and the glitch will likely appear. Sometimes difficult to reproduce hehe.
=> Fix spacing glitch for tooltips

app/components/Comments/Comment.css
Happened in a recent meeting with a long url
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See images above. Removed some old lego-editor specific css, but that was also tested, in the sense that I double-checked we don't have any left-over lego-editor stuff in comments
=> Wrap comments to prevent buggy shifted pages

app/components/UserAttendance/AttendanceModalContent.css, app/components/UserAttendance/AttendanceModalContent.tsx, cypress/e2e/joblistings_specs.js, cypress/support/utils.js
The sizing of the Modal component was changed without updating the sizing of AttendanceModal.
This solution is still kinda hacky - but with the current flexibility of the Modal components size it's kinda tricky to flex the sizing of this one properly, and at least now the calculations are explained better..
> [!CAUTION]
Works fine in Chrome and Safari
Resolves ABA-957
=> Fix sizing of attendance modal

app/routes/events/components/EventList.tsx, app/routes/events/utils.ts, app/routes/frontpage/components/CompactEvents.tsx, app/store/models/Event.ts
Renames KiD to NEXUS and updates colors to match the company logo.
[Backend PR](https://github.com/webkom/lego/pull/3629)
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Calendar
</td>
<td>
</td>
<td>
<tr>
<td>
Event details
</td>
<td> <img src="https://github.com/user-attachments/assets/9420e911-0eba-43ba-a929-1a8be361ea7c"/> </td>
<td> <img src="https://github.com/user-attachments/assets/44181f08-b9d4-4a9b-8ea1-3571aa112caa"/>
</td>
</tr>
</table>
Resolves [ABA-1027](https://linear.app/abakus-webkom/issue/ABA-1027/update-name-from-kid-nexus)
=> Rename KiD to NEXUS

config/webpack.dll.js, mazemap/package.json
Bumps mazemap to v2.2.1
Changes to webpack caused by internal changes from mazemap, hopefully nothing breaks 👉👈
Map looks the same
---
=> Bump mazemap to v2.2.1

app/routes/events/components/EventAdministrate/AdminRegister.tsx, app/routes/events/components/JoinEventForm.tsx
ArrKom requested that the tag for "Melding til arrangør" be changes to "Kommentar" to better reflects its purpose, as it does not send the message to the Host, but rather to ArrKom who also gets no notfication. 
> [!CAUTION]
Event page visible to normal users before:
Event page visible to normal users after:
Admin registration page before:
Admin registration page after:
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
Please describe what and how the changes have been tested, and provide …
=> Changed 'Melding til Arrangør' to 'Kommentar' at request from ArrKom

app/styles/globals.css
For some dumb reason, any inputs with a smaller font size than `16px` will cause the browser on mobile (I think only Safari) to "zoom" in on the field when focusing on it. On the event registration modal, this causes annoying bugs when trying to search for attendees.
[Read more here.](https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone)
Not actually tested, other than that I have confirmed that the font-size is `16px` on mobile viewports.
---
Resolves ABA-1068
=> Set input font size to be 16px on mobile

app/routes/events/components/EventEditor/EditorSection/Registration.tsx
The little text in the editor was using a variable that was not set - and therefore always showed the current time.
Now it uses the same function as is used when it is displayed, and works better.
---
=> Display correct registrationDeadline in event editor

packages/lego-bricks/package.json, packages/lego-bricks/src/components/Layout/Page/Page.tsx
Fixes `lego-bricks` breaking when used in a project without `react-router`. 
Tested on the `lego-editor` project
---
Resolves [ABA-1025](https://linear.app/abakus-webkom/issue/ABA-1025/lego-bricks-doesnt-work-without-react-router-dom)
=> Fix lego-bricks not working without react-router

app/components/Header/Header.css, app/components/Header/Navbar/Navbar.css, packages/lego-bricks/package.json, packages/lego-bricks/src/components/Button/Button.module.css, packages/lego-bricks/src/components/Icon/Icon.module.css, packages/lego-bricks/src/global.css
The latest version of `lego-bricks` incorrectly styles buttons, adding a gray background and border. This is likely caused by the recent removal of the global css import from `lego-webapp`. This PR fixes the styling.
| -- | -- |
| ![Screenshot from 2024-09-22 17-17-49](https://github.com/user-attachments/assets/4246bad7-4b59-49a4-a553-0bd7aaf49a09) | ![Screenshot from 2024-09-22 17-17-58](https://github.com/user-attachments/assets/a38140d8-cab0-4308-8da5-0ff76eb10b89) |
| ![Screenshot from 2024-09-22 17-27-25](https://github.com/user-attachments/assets/b32aafbc-3d8c-431e-9808-acc3388eebb1) | ![Screenshot from 2024-09-22 17-27-33](https://github.com/user-attachments/assets/fe12cdb3-c9b3-4a8e-822d-325bf4150749) |
Navigate through the application and ensure all buttons, …
=> Fix button styling in bricks

app/components/Table/Table.css
This has annoyed me for quite a while, especially when working on the updated BDB. This PR hides the horizontal scroll bar in the `Table` component when it's not needed. The bar will still appear if the content becomes scrollable.
| Before | After
| -- | -- | 
| ![Screenshot from 2024-09-22 22-15-08](https://github.com/user-attachments/assets/3c62c9e8-1f92-445a-821f-57e30a92ca8c) | ![Screenshot from 2024-09-22 22-15-28](https://github.com/user-attachments/assets/1bcdcd89-5ece-4a54-a510-1215fdc5ff67) |
Verify that the horizontal scroll bar is hidden in all tables when the content is not horizontally scrollable.
=> Remove horizontal table scroll

app/reducers/comments.ts, app/reducers/reactions.ts, app/utils/legoAdapter/buildActionGrantReducer.ts, app/utils/legoAdapter/buildDeleteEntityReducer.ts, app/utils/legoAdapter/buildEntitiesReducer.ts, app/utils/legoAdapter/buildFetchingReducer.ts, app/utils/legoAdapter/buildPaginationReducer.ts
These were imported from the src folder of rtk because they weren't exported normally in earlier versions of rtk. 
```typescript
import type { EntityState } from '@reduxjs/toolkit/src/entities/models';
```
Seems like some new config makes this cause an error, but they have been added to exports so we can just import them normally.
```typescript
import type { EntityState } from '@reduxjs/toolkit';
```
Fixes 10 typescript errors in the places where stuff was imported incorrectly.
Fewer type-errors = good. This code is only used for type-checking.
=> Fix imports of redux-toolkit types

app/reducers/events.ts, app/routes/events/components/EventDetail/AttendeeSection.tsx, app/routes/events/components/EventDetail/getWaitingListPosition.ts, app/routes/events/components/EventDetail/usePools.ts, app/routes/events/components/RegistrationMeta.tsx, app/store/models/User.ts
DEPENDS ON BACKEND PR: https://github.com/webkom/lego/pull/3642 (that is why cypress fails)
Show waiting list position for each applicable pool if there are multiple pools in the event.
The waitlist position is calculated for each pool by looping through the waiting list and counting how many people before you are applicable for the given pool. This depends on a backend change, that includes the ids of all groups (including inherited) for each registration on the waiting list. https://github.com/webkom/lego/pull/3642
> [!CAUTION]
**Before:**
**After:**
This user is first on the waiting list and has access to only the "Abakus" pool:
This user is second on the waiting list, but is the only one with access to the "Webkom" …
=> Show waiting list position even if there are multiple pools

app/routes/events/components/EventDetail/getWaitingListPosition.ts
Doing this loads the event with the "Administrate"-serializer, which is without the "allAbakusGroupIds"-field in users. Everything gets loaded once the page is entered, but we need to avoid a crash in the meantime.
Fixes [LEGO-WEBAPP-25G](https://abakus.sentry.io/issues/5920611469/)
No more crash:)
=> Fix error when entering event detail page after /administrate

app/components/UserAttendance/AttendanceModalContent.css, packages/lego-bricks/src/components/Modal/Modal.module.css
The previously used `100vh` became bigger than the `var(--visual-viewport-height)` that was introduced to the overlay 5 months ago, which caused the page to overflow when visual-viewport-height shrinked when users opened their keyboards to search (on mobile).
This is now fixed, so the div does not move when you search for attendants.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
---
=> Fix attendance modal overflowing when searching on mobile

app/routes/articles/components/ArticleEditor.tsx, app/routes/events/components/EventEditor/EditorSection/Header.tsx
Add warning under "fest til forsiden" to make i clear you need permission to pin.
Applies to article- and event-editing.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves: ABA-1077
=> Add warning to pin to frontpage

app/routes/pages/components/LandingPage.tsx
Changed Hovedstyret's e-mail from abakus@abakus.no to hs@abakus.no under Info om Abakus.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Changed e-mail.
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1093
=> Change HS e-mail

app/routes/events/components/RegisteredSummary.tsx
Correct the display of the attendee count when hovering over "andre" in the UI. This change ensures that users see the accurate number of additional attendees, and no longer see -1/0 others. The indexing was also wrong, it said two more others than it should. 
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td width="25%">Changed indexing and removed -1</td>
<td>
</td>
<td>       
</td>
</tr>
</table>
Tested the "critical number" of attendees, 13-17 where the error occured. 
---
Resolves: 
ABA-1114
=> Fix  1 other attendees

app/routes/frontpage/components/CompactEvents.css, app/routes/frontpage/components/CompactEvents.tsx, cypress/e2e/home_page_spec.js
Better spacing, look and the entire thing is now clickable!
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/b7cd367a-9ab4-4623-bce6-fb8ea5e09522" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/5a7a8de6-39a4-4ec7-8814-aab25adb32f1" />
</td>
</tr>
</table>
Checked different viewports and themes (and with skeleton components on slower connections).
=> Improve event items on frontpage

app/models.ts, app/routes/events/components/EventEditor/index.tsx, app/routes/events/utils.ts, app/routes/users/components/UserProfile/UserInfo.tsx, app/routes/users/components/UserProfile/index.tsx, app/store/models/Event.ts, app/store/models/User.ts
For users without access to other users email, an empty field was shown. This bug was because I used the wrong user-type in the ProfilePage. Type is fixed and an added check ensured the entire field is hidden when the user doesn't have access to see the email.
Also I removed the `DetailedUser` type. It is (almost) never actually used, and with my upcoming backend PR it will be removed completely.
This no longer happens:
It is still shown when I am logged in as an admin, and not shown when I am logged in as a normal user.
=> Fix bug where empty email info field is shown

app/components/EmptyState/EmptyState.css, app/components/EmptyState/index.tsx, app/components/Poll/Poll.css
Not sure when or why these suddenly became uncentered.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
These only broke with ssr - so this was tested with ssr :)
=> Center suddenly uncentered stuff

app/actions/CompanyActions.ts, app/routes/bdb/components/BdbDetail.tsx, app/routes/bdb/components/BdbPage.tsx, app/routes/bdb/components/SemesterStatus.tsx, app/routes/bdb/utils.tsx
[Related backend PR](https://github.com/webkom/lego/pull/3645)
- Update to refactored backend bdb endpoint
- Only show one semester at a time
- (Coming soon: student contacts for a company should be distinct for each semester. Waiting for other PRs first)
TODO:
- The viewed semester can be changed by the `semester` query in the URL. We should probably add a dropdown for this at some point
- BDB looks trash on mobile
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Changing semester statues still work
The detailed bdb route still works
--- …
=> Only show one semester at a time on BDB

app/routes/bdb/components/BdbDetail.tsx
Slight ui changes
* Don't show empty company description
* Semester status fills entire table cell
* Better empty state on missing student contact
* Better spacing between all elements on page
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Just slight changes. Company description is still shown if it is given.
=> Clean up bdb company details

app/styles/globals.css
At least the stylings we don't want - I've e.g. kept outline and font-weights.
This looks much worse on mobile, where a blue color is added as well. It's not "that" noticeable on laptop
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Looks good now, both with and without ssr.
---
Resolves ABA-1118
=> Globally remove default styling from regular buttons

app/routes/events/components/EventDetail/AttendeeSection.tsx, app/routes/events/components/EventDetail/SidebarInfo.tsx, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/RegisteredSummary.tsx, app/routes/events/components/RegistrationMeta.tsx
People (backup) were complaining that abakus.no, especially the event detail page has been very slow lately. I believe it just feels slower because skeleton loading broke after #4974
This fixes skeleton loading:)
https://github.com/user-attachments/assets/e09ebb44-201a-46e6-8445-09e82d14c7a4
It now adds the correct skeleton components when entering event detail from frontpage and event list
---
Resolves ABA-1128
=> Improve skeleton when fetching partially loaded detailed event

app/components/Tags/Tag.tsx, app/routes/bdb/components/AddSemester.tsx, app/routes/bdb/components/SemesterStatus.tsx, app/routes/bdb/components/SemesterStatusContent.tsx, app/routes/bdb/utils.tsx
Replaces the filled cell semester status with tags representing the semester statuses of the company.
| Before | After | 
| -- | -- |
| ![image](https://github.com/user-attachments/assets/f10e43fd-dc6c-43a9-adc6-35fbc2f46b6c) | ![image](https://github.com/user-attachments/assets/26620f65-d9ce-4dfa-ac9d-45781c720dbc) |
| ![image](https://github.com/user-attachments/assets/147c086e-484b-45dc-9f05-12182a3b6eaa) | ![image](https://github.com/user-attachments/assets/dc003c54-a515-4409-9350-9c55eec0c2cc) |
Open bdb and verify the table has tags.
Resolves [ABA-1120](https://linear.app/abakus-webkom/issue/ABA-1120/turn-semester-statuses-into-pills-on-bdb)
=> Make semester statuses tags

app/routes/users/components/UserProfile/index.tsx
Add frame for winner of veldedighetsfest auction object "Ramme".
(It was quite cheap actually :money_mouth_face: )
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Frame for user 7325
</td>
<td>
It wasn't there
</td>
<td>
It is there now
</td>
</tr>
</table>
No testing needed. I have verified that the user ID (7325) is correct for the winner of the auction
---
=> Add frame for winner of veldedighetsfest auction object "Ramme"

app/components/MazemapEmbed/MazemapEmbed.css, app/components/MazemapEmbed/MazemapLink.tsx, app/components/MazemapEmbed/index.tsx
Annoying to always get an error when going into meetings
You end up with an empty map, but why would you need that in dev mode 🤷🏼‍♂️ 
MazeMap works fine with ssr (prod)
=> Prevent error with MazeMap on dev

app/routes/admin/email/index.tsx
Selected tab was not highlighted in email admin pages when in an edit page.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Edit e-mail list page
</td>
<td><img width="502" alt="Screenshot 2024-10-23 at 18 36 13" src="https://github.com/user-attachments/assets/3b20b2e3-5a80-4293-84d6-0791fb52ebf0"></td>
<td><img width="502" alt="Screenshot 2024-10-23 at 18 36 33" src="https://github.com/user-attachments/assets/4d3f5ead-b810-4492-a3d2-d7d095b6bd10"></td>
</tr>
</table>
---
Resolves ABA-1139
=> Fix current tab highlighting on email admin pages

app/components/HeaderNotifications/index.tsx, app/reducers/notificationsFeed.ts
Solved by optimistically marking all as read and seen (not sure what the difference is?)
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/ba568008-2a40-4eea-9326-7747b9f38555" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/1b427c4c-98bf-48c7-91b4-b1109acf30c9" />
</td>
</tr>
</table>
See videos above
=> Avoid flickering when toggling notifications dropdown

app/routes/pages/components/PageDetail.tsx
When not logged in and trying to view pages that normally contains memberships, a 401 error would occur.
The previous approach using `toString()` does not work with SSR as it minimizes / bundles the code so the actual function name becomes something like `d(e)` not `fetchAllMemberships`. 
Resolves ABA-1129
=> Fix errors when loading members on pages when unauthorized

app/actions/ActionTypes.ts, app/actions/LendableObjectActions.ts, app/components/Search/utils.tsx, app/reducers/index.ts, app/reducers/lendableObjects.ts, app/routes/index.tsx, app/routes/lending/components/LendableObjectCreate/index.tsx, app/routes/lending/components/LendableObjectDetail/index.tsx, app/routes/lending/components/LendableObjectEdit/index.tsx, app/routes/lending/components/LendableObjectEditor.tsx, app/routes/lending/components/LendableObjectList/LendableObjectList.module.css, app/routes/lending/components/LendableObjectList/index.tsx, app/routes/lending/index.tsx, app/routes/lending/useFetchedLendableObject.ts, app/store/createRootReducer.ts, app/store/models/LendableObject.ts, app/store/models/ObjectPermissionsMixin.d.ts, app/store/models/entities.ts
Adds a simple MVP for the lending system. Currently you can only set description, location and image on the lendable objects. It also supports setting view-permissions per object for specific groups.
Added to the navigation menu
Empty state:
List:
Detail:
Detail as admin without view-rights (lending-rights) to this object (admins can see everything):
Create/edit form
Detail page on mobile:
List page on mobile:
It works:)
---
Resolves ABA-1046
=> Add lending system MVP

app/routes/photos/components/GalleryPictureModal.module.css, app/routes/photos/components/GalleryPictureModal.tsx
yet another ssr issue
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested with ssr
---
Resolves ABA-1145
Resolves ABA-1146
=> Prevent album cover image from growing large

app/routes/events/components/EventDetail/AttendeeSection.tsx, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/JoinEventForm.tsx, app/routes/events/components/RegistrationMeta.tsx, app/routes/frontpage/components/CompactEvents.tsx
Also fix and improve skeleton components on frontpage and event detail sidebar
<div>
<video src="https://github.com/user-attachments/assets/e8009d0e-8621-4853-bb92-4e6c228f4ee6" />
</div>
It's difficult to reproduce the button move on dev fro some reason - might have something to do with the websocket
---
Resolves ABA-1148
=> Prevent registration button from moving

app/routes/events/components/Event.module.css, app/routes/events/components/EventAdministrate/Allergies.tsx, app/routes/events/components/JoinEventForm.tsx, cypress/e2e/event_visit_spec.js, packages/lego-bricks/src/components/LoadingIndicator/LoadingIndicator.module.css
Just takes up unnecessary space
[This is needed for cypress to pass](https://github.com/webkom/lego/pull/3663)
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Registering with and without `event.feedbackRequired` still works fine. I also tested that the logic for submitting a registration through the comment form still works as expected
---
Resolves ABA-1150
=> Remove comment field from join event form when not required

app/components/Toast/Toast.module.css, app/components/Toast/Toast.tsx, app/components/Toast/ToastProvider.tsx, app/components/Toast/ToastRegion.tsx, app/reducers/toasts.ts, app/store/createStore.ts, app/store/middleware/messageMiddleware.ts
Much faster and better feedback. Currently only support `success` and `error` (and the default `undefined`) - I don't think we'll need any more.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td> 
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1147
=> Support toast types

app/routes/events/components/EventAdministrate/AttendeeElements.tsx, app/routes/events/components/EventAdministrate/RegistrationTables.tsx, app/routes/events/utils.ts, packages/lego-bricks/src/components/Icon/Icon.module.css, packages/lego-bricks/src/components/Icon/index.tsx
I've lost count of all the times someone has mailed Webkom because they can't unregister users after the deadline has ran out
The Icon component's `disabled` prop did nothing, so that was also fixed 
See image above. It is not disabled before the unregistration deadline 😄 
---
Resolves ABA-1149
=> Disable unregistration button after unregistration deadline

app/routes/pages/components/subcomponents/EmailItem/EmailItem.module.css, app/routes/pages/components/subcomponents/EmailItem/index.tsx
Fixed spacing issues with recipient and e-mail under Kontakt oss under Info om Abakus.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Changed spacing.
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1140
=> Fix spacing under Info om Abakus

app/components/Comments/__tests__/CommentTree.spec.tsx, app/components/LoginForm/LoginForm.spec.tsx, app/components/LoginForm/LoginForm.tsx, package.json, yarn.lock
In [v1.5.5](https://github.com/webkom/lego-webapp/pull/5113) it officially deprecated the `configureStore` method.
Tests pass. Manually tested the login form as well, and it catches errors fine.
=> Remove deprecated `redux-mock-store` dep

app/routes/users/components/UserProfile/UserProfile.module.css
Changed achievement profile view from flex to grid
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>	<img src="https://github.com/user-attachments/assets/123163c2-24a9-4908-841b-1236a7949197"></img></td>
<td>	<img src="https://github.com/user-attachments/assets/7bfef6a8-f95c-409b-b070-d82d59694c43"></img></td>
</tr>
<tr>
<td>	<img src="https://github.com/user-attachments/assets/9ad542d9-2fbc-4f12-b963-a2835a666101"></img></td>
<td>	<img src="https://github.com/user-attachments/assets/ea6fc2ec-89bd-448d-8172-ed0940448cdd"></img></td>
</tr>
</table>
Tested manually
=> Update achievement styling to be better

app/routes/events/components/EventDetail/getWaitingListPosition.ts, app/store/models/Pool.d.ts, app/store/models/User.ts
Appearently my code in https://github.com/webkom/lego/pull/3642 caused "significant performance issues" and "increased loading times" on the event detail page. This is true, my bad.
I believe the issue getting the fairly expensive inherited groups for each person in the waiting list. Instead we can just get child-groups for all the applicable groups in the pools. This should be cheaper because there are fewer pools.
---
=> Update waiting list placement calculation for more performant backend

app/reducers/events.ts
Whoops! I forgot about merged pools in #5141 
The whole page crashed whenever the pools are merged
No longer crashes 😅
Previously crashed, no longer crashes
=> Fix crash on event page whenever pools are merged

app/routes/surveys/components/AdminSideBar.tsx, app/routes/surveys/components/Submissions/SubmissionsPage.tsx, app/routes/surveys/utils.tsx
Depends on: https://github.com/webkom/lego/pull/3668
Adds PDF download to surveys
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/ff569a2d-1dce-4261-91c7-7a700c97025c"></td>
<td><img src="https://github.com/user-attachments/assets/30317082-8e85-4106-8147-a7d499066a65"></td>
</tr>
</table>
- [ x] I have thoroughly tested my changes.
Tested manually
---
Resolves: ABA-1102
=> Add PDF download to surveys

app/routes/events/components/EventDetail/UnansweredSurveys.tsx
I heard from a non-admin that they can see all the admin options at `/surveys/<id>`, and go here every time they press the button to answer a survey. Instead of seeing this page, they can be directed to the `/surveys/<id>/answer` directly.
=> Navigate directly to survey answer page from UnansweredSurveys

app/routes/events/components/EventDetail/AttendeeSection.tsx, app/routes/events/components/EventDetail/SidebarInfo.tsx, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/JoinEventForm.tsx
More fine-grained control over what components are shown as skeletons. See images below.
This page could still use a bit more work to make the skeletons actually match the real components.
> [!CAUTION]
Event page entered from the frontpage:
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Event without registration yet        </td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
Event with registration        </td>
<td>
</td>
<td>
</td>
</tr>
</table>
I have loaded a bunch of events a bunch of times, and it looks less wrong than it did before:)
---
Resolves ABA-1164
=> Improve skeleton components on event detail page

app/routes/users/components/UserProfile/AchievementsBox.tsx, app/store/models/User.ts, app/utils/achievementConstants.ts
Adds front-end part of the penalty achievements.
See previous PR on achievements for visuals.
These look exactly the same with no changes except the text (name/description)
---
=> Add new achievements for penalty count and update rarity color mapping

app/routes/users/components/UserConfirmation.tsx
Because of the redux upgrades done a while back, FETCH.SUCCESS actions without an endpoint get ignored... This broke the hacky way we add the current user to the redux state after registering, causing the student confirmation (FEIDE login) button to not appear unless the page is reloaded.
It now works as intended.
It is in my backlog to do some more refactoring to make this less hacky
---
Resolves ABA-1024
=> Fix automatic login after registering new user

app/components/Form/Field.module.css, app/components/Form/Field.tsx, app/components/Form/FieldSet.module.css, app/components/Form/FieldSet.tsx, app/components/Form/Label.module.css, app/components/Form/Label.tsx, app/components/Form/MultiSelectGroup.module.css, app/components/Form/MultiSelectGroup.tsx, app/routes/bdb/components/AddSemester.tsx, app/routes/bdb/components/CompanyEditor.tsx, app/routes/companyInterest/components/CompanyInterest.module.css, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/companyInterest/components/CompanySemesterGUI.tsx, app/routes/companyInterest/components/Translations.ts, app/routes/events/components/EventEditor/EditorSection/Details.tsx, app/routes/events/components/EventEditor/EventEditor.module.css, app/routes/meetings/components/MeetingEditor.tsx, app/routes/pages/components/PageEditor.tsx, app/routes/users/components/UserConfirmation.tsx, app/routes/users/components/UserSettings/UserSettings.tsx
Refactored form labels to be a reusable component. This allows for less duplicated code and more consistency when using stand-alone labels outside of the `Field`-component.
Also added lots of missing required-stars (*) to various forms.
- Minor changes to label styling and spacing
- Added missing required stars
- Replaced info-tooltip icon
----
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Company interest form
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
I have tested a lot of forms and different field types. Normal fields still work and focus as expected when clicking the label. Checkboxes and radio buttons select option when label is clicked, but nothing when the …
=> Create Label component and improve radio/checkbox labels

app/routes/users/components/UserProfile/AchievementsBox.tsx
This commit changes the text when you hover over an achievement badge on a user's profile. Has changed the text from "Opnådd den ..." to "Oppnådd den ...", fixing a small spelling error :)
**bug-fix**
---
Resolves ... (Too minor to create an issue? Just changed one letter...)
=> Fix spelling error in achievement at profile page

app/components/Toast/Toast.tsx
Changes the icon on toast success to a checkmark. X can be confused with errors. Green/red distinction is not always a clear indication for red/green colorblind people.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Changes the icon to checkmark for success
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Visually
---
Resolves ... My personal grudge
=> Fix toast icon mark for success

app/components/Form/SelectInput.tsx, app/routes/companyInterest/components/CompanyInterestList.tsx
Makes the selected semester under company interest  the current semester by default.
https://github.com/user-attachments/assets/7ef7bc5f-8e3a-449a-a438-6d2a2b85c55c
Resolves [ABA-1048](https://linear.app/abakus-webkom/issue/ABA-1103/the-selected-semester-under-company-interest-should-be-the-current)
=> Add semester auto select to interest page

app/routes/events/components/JoinEventForm.tsx
Fixed one of the card stylings as well
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See images above
=> Prevent endless skeleton loading on event details

app/routes/bdb/components/BdbDetail.tsx
Increases the company table widths to utilize more screen estate.
| -- | -- |
| ![image](https://github.com/user-attachments/assets/434a078c-6a5a-47dd-aa34-241e7136c24d) | ![image](https://github.com/user-attachments/assets/21f1b351-1ff0-48fb-8a36-6471cda67566) | 
Resolves [ABA-1048](https://linear.app/abakus-webkom/issue/ABA-1190/increase-table-width-on-company-page)
=> Make tables wider

app/routes/companyInterest/components/CompanyInterestPage.tsx
The back link was visible for all users all the time, despite normal users not being able to view the page that it directs to. 
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
It is now only shown when editing a submission.
---
Resolves ABA-1195
=> Hide back link on company interest page when not editing

app/actions/CompanyActions.ts, app/actions/CompanyInterestActions.ts, app/actions/ContactActions.ts, app/actions/QuoteActions.ts, app/components/Toast/Toast.module.css, app/components/Toast/Toast.tsx, app/routes/bdb/components/CompanyEditor.tsx, app/routes/contact/components/ContactForm.tsx, app/routes/quotes/components/AddQuote.tsx, app/store/middleware/websocketMiddleware.ts
[Fix icon color on default toast types](https://github.com/webkom/lego-webapp/commit/521bdaa7268690f69500c7d045b6c3aa76799ffc)
---
[Refactor actions to use toasts the proper way](https://github.com/webkom/lego-webapp/commit/166b6be48f721f76169a02815879187903937343) 
These toasts were missing types since they were added in a "custom" way
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested that toasts are still shown as expected (with the correct type) in the cases where it was moved to be handled elsewhere.
---
Resolves ABA-1194
=> Clean up toasts

app/components/Toast/Toast.module.css
Not a fan of the lack of spacings
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested on my iPhone (see images above)
---
Resolves ABA-1199
=> Improve look of toasts on smaller viewports

app/components/EmptyState/EmptyState.module.css, app/components/HeaderNotifications/index.tsx, app/routes/forum/components/ForumList.tsx, app/routes/meetings/components/MeetingList.module.css, app/routes/meetings/components/MeetingList.tsx
Just some here and there that has bothered me
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Fix various empty states

app/components/EventItem/RegistrationStatusTag.tsx, app/components/EventItem/index.tsx, app/components/EventItem/styles.module.css, app/components/Tags/Tag.tsx, app/routes/events/components/EventList.tsx, app/routes/users/components/UserProfile/index.tsx, app/store/models/Event.ts
Makes it much easier to differentiate between the list of dates in the items.
There's no need to show the activation time for registrations if the user has
already registered.
Besides, people prefer to use the event list on /events rather than the
one on the user profile to view upcoming events.
Look at _Deloitte AS_ and _Fadderpåmelding Kommunikasjonsteknologi_ to see event items with 2 dates ... difficult to differentiate between the two:
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested all event types, and the three different registration statuses (unregistered, waiting list and registered/admitted)
=> Include registration statuses to event items

.drone.yml, app/components/Form/DatePicker.module.css, app/components/Form/DatePicker.tsx, app/components/Form/TextInput.tsx, app/components/Form/TimePicker.tsx, app/components/Table/Table.module.css, app/models.ts, app/routes/events/components/EventAdministrate/Statistics.tsx, app/routes/events/components/EventEditor/EditorSection/Details.tsx, app/routes/events/components/EventEditor/index.tsx, app/routes/events/utils.ts, app/routes/joblistings/components/JoblistingEditor.tsx, app/routes/meetings/components/MeetingEditor.tsx, app/styles/globals.css, app/utils/parseDateValue.ts, app/utils/validation.ts, cypress/e2e/create_event_spec.js, cypress/e2e/create_meeting_spec.js, cypress/support/utils.js
Better than having to use two separate date pickers to simulate it. The plan is to use this to filter on events on /events.
Notice how the regular dropdown does not update which month is shown as default according to the value it is given (unlike the new range version 😎):
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
- Tested when start date and end date are the same days (but different times of the day)
- Tested as both fields and regular components (see images above)
- Tested that changes to global table styles does not affect the Table component
- Tested that it looks good on smaller viewports:
- Tested that the regular date picker still works :)
=> Extend DatePicker to support ranges

app/components/EventItem/RegistrationStatusTag.tsx, app/components/Form/ToggleSwitch.module.css, app/components/Form/ToggleSwitch.tsx, app/routes/bdb/components/CompanyEditor.tsx, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/companyInterest/components/Translations.ts, app/routes/events/components/EventList.module.css, app/routes/events/components/EventList.tsx, app/routes/joblistings/components/JoblistingList.module.css, app/routes/photos/components/GalleryPictureModal.tsx, app/routes/users/components/UserSettings/UserSettings.tsx, app/store/models/CompanyInterest.ts, cypress/e2e/company_interest_spec.js
Specialisation project has finally been delivered! 🥳
This feature has been highly requested by various people. 
In addition, introduce a `ToggleSwitch` component for binary values (yes/no).
<p>
<video src="https://github.com/user-attachments/assets/db50da38-ce08-4c6d-81db-b097b63a9f73" />
</p>
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Previous events are still paginated properly.
The toggle switch has bene tested as both a field and a "normal" component.
---
Resolves ABA-492
=> Support previous events on event list (and a toggle switch!)

app/routes/users/components/UserProfile/UserProfile.module.css, app/routes/users/components/UserProfile/index.tsx
No need for a duplicate settings button
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Remove duplicate settings button

packages/lego-bricks/src/components/Tabs/TabContainer.module.css, packages/lego-bricks/src/components/Tabs/TabContainer.tsx
The tabs now overflow nicely, with both a fade and arrow to indicate the scroll behaviour.
The tabs are now also scrolled into view if clicked on.
- [yes] Changes look good with different viewports (mobile, tablet, etc.).
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Same as before when all tabs fit into view
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
At the beginning
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
At the end
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
https://github.com/user-attachments/assets/18876979-2987-4056-894c-0bfb338a5c7c
Tested quite extensively on smaller views. A lot of edge cases have been tested, e.g. that arrows and shadows disappear when they should etc.
=> Improve and fix navigation tabs on smaller viewports

app/routes/events/components/EventEditor/index.tsx
The date of the payment deadline was validated even though the event was not priced. As such, the warning that the date had to be changed was not shown, even though the event was not correctly validated if the unregistration deadline was later than a week after the creation date of the event (which is the default value for the payment deadline it seems).
Now the validation is only applied if isPriced is true.
Werks as expected.
---
Resolves ABA-1211
=> Only validate payment deadline if event is priced

app/routes/bdb/components/BdbPage.tsx, app/routes/bdb/utils.tsx
Adds arrows to each side of the semester dropdown in BDB to easily go to the next/previous semester.
https://github.com/user-attachments/assets/31cc1518-41dd-4d8b-b058-72793c9f9540
Open BDB and verify that the semester arrows work correctly.
---
Resolves [ABA-1048](https://linear.app/abakus-webkom/issue/ABA-1216/add-semester-navigation-buttons)
=> Add semester arrows to BDB

app/components/Table/BodyCell.tsx, app/components/Table/HeadCell.tsx, app/components/Table/Table.module.css, app/components/Table/index.tsx, app/routes/events/components/EventAdministrate/Attendees.tsx, app/routes/events/components/EventAdministrate/RegistrationTables.tsx
For tables that are not paginated, it's good to be able to collapse them
to prevent long render times
=> Introduce a collapsableAfter prop to the table component

app/components/Form/DatePicker.tsx, app/components/Form/ToggleSwitch.tsx, app/routes/events/components/EventList.tsx, app/routes/events/components/EventsOverview.tsx, app/utils/parseDateValue.ts, app/utils/useQuery.ts, cypress/e2e/create_event_spec.js, cypress/e2e/joblistings_specs.js
Highly requested and very useful!
Had to make some changes to the date picker and query hook.
Tested on hard refreshes, many different date ranges, together with the `query.showPrevious` and the "Load more" button.
=> Support date range filtering on events

app/routes/events/components/EventEditor/EditorSection/Registration.tsx, app/routes/events/utils.ts
The description is supposed to show the time for when registering closes by subtracting x hours to starting time. 
Previously it calculated this using the current time (when creating new event) or the previously set starting time (when editing) and did not update when choosing a new starting time.
This was confusing and negated the point of having the description at all imo so I fixed it.
Unsure of the implementation so feedback is appreciated:)
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Red = :(
Green = :)
</td>
<td>
</td>
<td>
</td> …
=> Update event register deadline on start time selection

app/routes/events/components/EventEditor/EditorSection/Registration.tsx
Changed labels for deadlines when creating/editing events. 
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
'Avregistreringsfrist' changed to 'Frist for prikk'.
'Avregistrering' and 'Registrering' changed to 'Avmelding' and 'Påmelding'.
More consistent with wording elsewhere
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
Easier to what separate deadlines means
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
More concise tooltips
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1151
=> Rename event deadlines

packages/lego-bricks/src/components/Layout/Page/Page.module.css
Event Type text and buttons were positioned wrong. Aligned it correctly by changing JustifyComponent to flex-end in the ButtonGroup. 
before:
after:  
---
Resolves ABA-1230
=> bug-fix css for eventType name

cypress/e2e/event_payment_spec.js
Decided to give the good 'ol Stripe stuff a go again.
The tests that actually use stripe are a bit hard to test locally as they seem to depend on websockets (at least it appears so to me) which make them hard to run as websockets dont work locally - but I did get this test case to work out, and now it runs fine locally with the current state of the webapp.
Have run the changes locally through cypress and the test case succeeds.
=> Update paid event spec to match new developments

app/actions/AchievementActions.ts, app/actions/ActionTypes.ts, app/reducers/users.ts, app/routes/achievements/components/Leaderboard.tsx, app/routes/achievements/components/Overview.module.css, app/routes/achievements/components/Overview.tsx, app/routes/achievements/components/index.tsx, app/routes/achievements/components/utils.tsx, app/routes/achievements/index.tsx, app/routes/index.tsx, app/routes/users/components/UserProfile/AchievementsBox.tsx, app/routes/users/components/UserProfile/index.tsx, app/store/models/User.ts, app/utils/achievementConstants.ts
Adds achievement overview and leaderboard.
> [!CAUTION]
---
=> Add achievement overview and leaderboard

app/components/UserValidator/Validator.module.css, app/components/UserValidator/index.tsx
Add color code and icons to the scan result
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
På venteliste
</td>
<td>
<td>
</td>
</tr>
<tr>
<td>Registrert</td>
<td>
</td>
<td>
</td>
</tr>
</table>
I've tested all the new error codes, and they work
---
Resolves ABA-1235
=> Improve abacard design

app/routes/users/components/UserSettings/UserSettings.module.css, app/routes/users/components/UserSettings/UserSettings.tsx, cypress/e2e/password_change_spec.js
Added a toggle button for changing of password in settings profile. This makes the page less messy.
<table>
<tr>
<td width="25%">Now a toggle button for changing of password and deletion of account</td>
<td><img width="1128" alt="Screenshot 2025-01-22 at 20 54 36" src="https://github.com/user-attachments/assets/fa9cfa82-4248-4622-a012-83d26e182d01" /></td>
<td>
</td>
</table>
---
Resolves ABA-1242
=> Add: A new toggle button for advanced settings

app/routes/users/components/UserProfile/Penalties.module.css, app/routes/users/components/UserProfile/Penalties.tsx
Added a information button about "prikk". Just a link to in-depth information about prikk-system (/arrangementsregler). Thought it would be nice to have a shortcut.
Please take a look at my css, I think it may be a bit clumsy. The button currently does not look good in dark mode because its black. What do you think about the placement of the button? Tried to get it next to "Prikker" title, but that was hard, because of profileSection-comp does not allow Icon, i think.
> [!CAUTION]
<table>
<tr>
<td width="25%">Add information button</td>
<td><img width="371" alt="Screenshot 2025-01-31 at 11 22 25" …
=> Add: information about prikk

app/components/Chart/BarChart.tsx, app/components/Chart/Chart.module.css, app/components/Chart/PieChart.tsx, app/routes/surveys/components/Submissions/Results.tsx, app/routes/surveys/components/Submissions/SubmissionsIndividual.tsx, app/routes/surveys/components/Submissions/SubmissionsPage.tsx, app/routes/surveys/components/Submissions/SubmissionsSummary.tsx, app/routes/surveys/components/SurveyList/SurveyItem.tsx, app/routes/surveys/components/SurveyList/SurveyList.tsx, app/routes/surveys/components/SurveysWrapper.tsx, app/routes/surveys/components/surveys.module.css, app/routes/surveys/index.tsx
For larger events, the survey page is suffers from performance issues since there is a large amount of submissions. This PR aims to improve user feedback. 
Also make each submission into accordions for better usability but also remove the content (the answers) from the virtual dom when they are not expanded to improve performance. This requires disabling animations for the accordions, but I think that is fine. 
There was an idea to paginate the page with individual answers, however since the result/summary needs all submissions anyways that solution does not make  much sense.
Images of skeleton components are not included, but they are added to the following places:
- /surveys
- PieChart, BarChart and TextAnswers (used on /surveys/<id>/submissions/summary and on …
=> Add skeletons and accordions to survey result and submissions

app/components/Tooltip/Tooltip.module.css, app/components/Tooltip/index.tsx
Pretty self-explanatory, was under mazemap controls, now its in front of it (applied to all popovers, but seems to be fine)
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
---
=> Move z-index of pizza reactions higher

app/routes/achievements/components/index.tsx, app/routes/achievements/components/utils.tsx, app/routes/achievements/index.tsx, app/routes/users/components/UserProfile/Achievements.tsx, app/routes/users/components/UserProfile/UserProfile.module.css, app/routes/users/components/UserProfile/index.tsx
Fixed some bugs in the achievements
* The location check used to toggle the sidebar was above the component, which caused it to only be reloaded when you refresh the page, not when navigating
* The location check is sorta suboptimal, but at least now it covers both `/achievements` and `/achievements/`
* The overview page was accessible from both `/achievements` and `/achievements/overview`. The user page used the former, and the internal navigation links used the latter, and the nav-link active state only listened to the latter. Now they all use `/achievements`
* The "Topplister" button used to be placed next to the badges, now it is displayed under the trophies - which makes more sense imo
Resolved the bugs mentioned above.
> [!CAUTION]
> Make sure your images do not contain any real …
=> Fix sidebar bug in achievements and move link

app/routes/events/components/Stripe.module.css, app/routes/events/components/StripeElement.tsx
`StripeElement.tsx` was missing some types, and it appeared to have some errors originating from faulty refactoring and packages being bumped without updating the implementation. These should now be rectified to match the official docs🤞.
Card payments have always been working, but apple pay has not worked in a while. It's handled through Stripes' `Payment Request Button` (where I've located and hopefully fixed the stuff that seemed erroneous), and that seems pretty hard to test properly outside of a production environment.. soo we might have to deploy and try to use it for the next signup with payments - although I'll keep searching for ways to test it.
The way we do this (using `Payment Request Button`) is deprecated, but with these changes I think Apple Pay and the likes should work for …
=> Cleanup StripeElement implementation

app/routes/bdb/components/companyInterest/components/Translations.ts
Added an option under other events on company interest page that got requested by bedkom: 
But not sure if this little change is all that is needed?
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1271
=> Add 'Wish event thursday' to other events on company interest page

app/routes/events/components/EventAdministrate/Administrate.module.css, app/routes/events/components/EventAdministrate/AttendeeElements.tsx, packages/lego-bricks/src/components/Icon/Icon.module.css, packages/lego-bricks/src/components/Icon/index.tsx
Requested by Fagkom
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Improve presence icons on event administrate page

app/actions/ActionTypes.ts, app/actions/GroupActions.ts, app/components/Image/CircularPicture.tsx, app/reducers/users.ts, app/routes/users/components/UserProfile/GroupMemberships.tsx, app/routes/users/components/UserProfile/UserProfile.module.css
I made it possible for users to remove inactive interest group from their profile. 
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
When pressing on the minus button it will trigger a confirmation modal.
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1260
=> FEAT: Option to remove inactive interest groups

cypress/e2e/create_event_spec.js
Simple fix for cypress testing of formatting of text in /events/create
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
---
Resolves ABA-1295
=> FIX: Cypress create event test

app/components/UserAttendance/AttendanceModalContent.module.css, app/components/UserAttendance/AttendanceModalContent.tsx, app/components/UserAttendance/GroupFilter.tsx
Add buttons to filter registrations by membership in groups. Makes it easier to find friends attending events.
> [!CAUTION]
Filter buttons:
With filter active:
The groups shown are only groups you are a member of, sorted by the number of attendees in each group.
Works pretty well:)
---
Resolves ABA-1246
=> Add group filters to attendance modal

app/routes/meetings/components/MeetingDetail.module.css, app/routes/meetings/components/PizzaAccordion.tsx
Show count for how many users want pizza and not in `PizzaAccordion`. Small change, but I want this. When the meeting report is long the reactions count is far away from the accordion.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<td>
</td>
<td>
</td>
</tr>
</table>
---
=> Add user count to PizzaAccordion

app/components/Table/index.tsx
A fix for an edge case in BDB filtering accidentally broke inline search. This has been resolved while keeping the original fix intact.
https://github.com/user-attachments/assets/0ce38b6b-7891-4797-b22f-6731a529c221
Previously, changing semester and then editing the filter would cause the semester to reset due to synchronization issues between the internal table component filter and the external url filter.
https://github.com/user-attachments/assets/866eaf12-ec7a-47e7-b7fd-dcd123ad671f
Verify that search and BDB filtering works.
---
Resolves [ABA-1307](https://linear.app/abakus-webkom/issue/ABA-1307/fix-searching-in-tables)
=> Fix search in table

app/components/MazemapEmbed/MazemapEmbed.module.css, app/components/MazemapEmbed/MazemapLink.tsx, app/components/MazemapEmbed/index.tsx, app/routes/events/components/EventEditor/EditorSection/Details.tsx, app/routes/meetings/components/MeetingEditor.tsx
Minor visual changes
| ---- | ---- |
| ![Skjermbilde 2025-01-29 kl  20 51 16](https://github.com/user-attachments/assets/8d155d0f-e07e-4b9d-8af8-5dc7d4cf1acf)|![Skjermbilde 2025-01-29 kl  20 51 33](https://github.com/user-attachments/assets/9e3a89c9-a69f-4844-a1ad-8f9e7c5c2bcc)|
| ![Skjermbilde 2025-01-29 kl  20 50 37](https://github.com/user-attachments/assets/7447954a-b13d-4847-9001-08e5a22afb06) | ![Skjermbilde 2025-01-29 kl  20 53 46](https://github.com/user-attachments/assets/4a9ac65f-38bc-410e-9893-fa4a28482d1c)|
=> Minor styling improvements to mazemap link

app/routes/frontpage/components/LatestReadme.tsx, app/routes/surveys/components/Submissions/SubmissionsIndividual.tsx, app/routes/users/components/UserSettings/UserSettings.tsx, packages/lego-bricks/src/components/Accordion/index.tsx
Adding an option to remove the Accordion children from the DOM when it is closed.
This is an option that may improve performance, but it may impact the smoothness of the animation if they are combined.
Using the approach with `useCallback` and `ResizeObserver` also fixes issues where the content of an accordion in other ways may be changing, such as loading images.
---
Resolves ABA-1166 and ABA-1264
=> Add Accordion option for removing children when closed

Dockerfile
I tested the Dockerfile with node_modules installed locally, making it work locally even though it copied the node_modules from the `setup`-step into the wrong directory.
=> Fix Dockerfile not working without locally installed node_modules

lego-webapp/components/Search/index.tsx, lego-webapp/components/Search/utils.tsx
Finding pages in the menu is very hard because there are so many links, now the search also filters the links:)
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Searching for "Utlån"
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
It works:)
---
Resolves ABA-1329
=> Filter quick links when searching

Dockerfile
Sooo, it still didn't work after #5408. I think all the `packages` folders also have their own `node_modules` which were not copied over. It should work now, as now EVERYTHING from the installation stage is still there when we build:)
It also simplified the Dockerfile a bit. And it works locally for me even with all the node_modules deleted.
EDIT: This one frfr actually works. I realized it doesn't need to me in master to test building in drone (or deploying?), so it should be deployed to staging soon
=> Fix dockerfile by simplifying stages

Dockerfile, lego-webapp/server/index.ts
Healthcheck was failing, making it impossible to deploy... Appearently the docker image needs curl in order to do the check
Also I accidentally broke the /healthz endpoint a while ago
I'm not 100% sure it works, so I will try deploying to staging before merging
=> Fix docker healthcheck

lego-webapp/app/routes/frontpage/components/AuthenticatedFrontpage.tsx
Add banner
> [!CAUTION]
<table>
<tr>
<td>Dark</td>
<td>Light</td>
</tr>
<tr>
<td>
Add Banner
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Previous PR for some reason used the path: 
app/routes/frontpage/components/AuthenticatedFrontpage.tsx
instead of: 
lego-webapp/app/routes/frontpage/components/AuthenticatedFrontpage.tsx
which made it unable to merge, sorry for the bother
=> Add banner for Revue (Original PR used wrong path thus failed to merge)

lego-webapp/components/UserGrid/UserGrid.module.css
Same thing as #5420 
Before:
After:
=> Fix css priority for attendee section skeleton

lego-webapp/app/routes/hiddenAdmin/components/BannerEditor.tsx, lego-webapp/app/routes/hiddenAdmin/components/BannerOverview.module.css, lego-webapp/app/routes/hiddenAdmin/components/BannerOverview.tsx
Display the banner and improve UX for selecting public/private banners
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Complete overhaul of the design
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Improve UX for banner admin page

lego-webapp/components/Form/ObjectPermissions.tsx, lego-webapp/components/errors/HTTPError.tsx, lego-webapp/cypress/e2e/router_spec.js, lego-webapp/pages/admin/banners/+Page.tsx, lego-webapp/pages/admin/banners/@bannerId/edit/+Page.tsx, lego-webapp/pages/admin/banners/BannerEditor.tsx, lego-webapp/pages/admin/featureflags/+Page.tsx, lego-webapp/pages/admin/featureflags/@featureFlagId/+Page.tsx, lego-webapp/pages/admin/featureflags/@featureFlagId/edit/+Page.tsx, lego-webapp/pages/admin/featureflags/FeatureFlagEditor.tsx, lego-webapp/pages/admin/featureflags/new/+Page.tsx, lego-webapp/pages/lending/+Page.tsx, lego-webapp/pages/sudo/+Page.tsx, lego-webapp/redux/actionTypes.ts, lego-webapp/redux/actions/FeatureFlagActions.ts, lego-webapp/redux/models/FeatureFlag.ts, lego-webapp/redux/models/LendingRequest.ts, lego-webapp/redux/models/entities.ts, lego-webapp/redux/rootReducer.ts, lego-webapp/redux/schemas.ts, lego-webapp/redux/slices/featureFlags.ts, lego-webapp/utils/useFeatureFlag.ts
This adds feature flags and i added one to lending.
Reloads is only required for the allowed part of this. The hook only part will still work. This is only due to fetchMeta not being called after editing so is really only a thing for admins. For regular users who did not refresh within the span of the activation, there is no way to force them to refetch meta either. The hook part will again still work. This is a minor edgecase.
Also improve design of sudo page
[Screencast_20250308_141059.webm](https://github.com/user-attachments/assets/2114fb1b-1e45-4240-b5e8-7d18a823d8d6)
> [!CAUTION]
Please …
=> Feat add feature flags

lego-webapp/components/Banner/Banner.module.css, lego-webapp/pages/admin/banners/BannerEditor.tsx, lego-webapp/pages/admin/banners/BannerOverview.module.css, lego-webapp/pages/sudo/+Page.tsx, lego-webapp/pages/sudo/SudoAdmin.module.css
Add a preview of the banner to the `BannerEditor`.
Dome banner design suggestions, the ones there before look bad.
Also fix bug where css is not applied correctly (after Vite/Vike)
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
`BannerPreview`
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
Banner redesigns
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Add BannerPreview to editor and redesign banners

lego-webapp/pages/index/CompactEvents.module.css, lego-webapp/pages/index/CompactEvents.tsx
Truncating the compact event titles by a fixed amount of characters makes it horribly static.
There are probably better ways to do this that depend less on hardcoded max-widths, but I believe this is an aight improvement for now.
The `6.5rem` are an approximated width of the colored circle and the date, and thus might have to be adjusted at some point if I'm incorrect - although it seems to work for march, which is one of the longer months, as it's not shortened to three letters.
`text-overflow: ellipsis;` appears to be well supported (https://caniuse.com/?search=text-overflow%3A%20ellipsis). In the case that you use a browser that does not support it, `max-width` and `overflow: hidden` should still be supported so you just won't get the "..." at the end.
If you've made visual changes, …
=> Truncate compact elements dynamically

lego-webapp/components/Header/ToggleTheme.tsx, lego-webapp/components/Header/index.tsx, lego-webapp/pages/lending/@lendableObjectId/request/@lendingRequestId/+Page.tsx, lego-webapp/utils/themeUtils.tsx
Currently the implementation of theme changing uses debounce to prevent spamming the server. This results in slow feedback (toast) for the user. Using throttling instead it sends a request instantly but does not allow further updates until after a delay. 
This way it is still kind of possible to spam the server (only 2s between each request), if we want to eliminate that too I did try out a custom function which combines the functionality of throttling and debounce (instant feedback on first click, then debounce rest of calls), its okay, but i might prefer the user feedback with just throttle.
Also moved more logic to themeUtils, both to make this PR work and its more clean imo. 
The custom event allows updates to the theme to not send a API request to the backend and only be used for …
=> Throttle theme changes instead of debouncing

lego-webapp/app/models.ts, lego-webapp/pages/events/@eventIdOrSlug/+Page.tsx, lego-webapp/pages/events/src/EventEditor/EditorSection/Descriptions.tsx, lego-webapp/pages/events/utils.ts, lego-webapp/redux/models/Event.ts
Added a checkbox to let people easily add company descriptions to event descriptions.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Added a checkbox in the event editor which enables/disables an extra box with a description of the company related to the event.
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1364
=> Add company description to events with checkbox

lego-webapp/pages/events/@eventIdOrSlug/+Page.tsx
Fix event description showing "om bedriften" even when not toggled 
Fix event description showing "om bedriften" even when not toggled 
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
Fix event description showing "om bedriften" even when not toggled 
---
=> Fix event description showing "om bedriften" even when not toggled

lego-webapp/components/errors/HTTPError.tsx, lego-webapp/pages/sudo/+Page.tsx, lego-webapp/pages/sudo/achievements/+Page.tsx, lego-webapp/pages/sudo/achievements/SudoAchievements.module.css, lego-webapp/redux/actionTypes.ts, lego-webapp/redux/actions/AchievementActions.ts
Allow recheck trophies from the sudo panel
> [!CAUTION]
---
Resolves ABA-1386
=> Allow recheck trophies from sudo

packages/lego-bricks/package.json, packages/lego-bricks/src/components/Modal/Modal.module.css
This has annoyed me for quite some time...
Previously, when zooming in using two finger pinch, the modal height would shrink. This has now been fixed in `lego-bricks`.
| -- | -- |
| ![image](https://github.com/user-attachments/assets/fced5bdc-d561-45fd-85c4-75d799c53145) | ![image](https://github.com/user-attachments/assets/943f461c-3764-424e-a15b-375cb27d8723) |
Resolves [ABA-1365](https://linear.app/abakus-webkom/issue/ABA-1365/incorrect-modal-height-on-zoom)
=> Fix modal height

packages/lego-editor/src/Editor.module.css, packages/lego-editor/src/extensions/diff.ts, packages/lego-editor/src/extensions/strike.ts, packages/lego-editor/src/index.tsx, pnpm-lock.yaml
Forgot about this feature in #5471 . Meeting repot diff now works again:)
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Meeting report diff
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1380
=> Add support for diff using <ins> and <del> tags in lego-editor

lego-webapp/pages/users/@username/+Page.tsx, lego-webapp/pages/users/@username/_components/UserProfile.module.css
I got annoyed by the increasing spacing between the profile picture and info boxes caused by the space taken up by achievements to the right of it.
Doing the layout using css grid allows it to take up all the available space while still allowing the correct layout on both desktop and mobile:)
The spacing between profile picture and info boxes is now independent of each other, allowing all available space to be utilized.
Mobile should be unaffected.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
My profile page
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
My profile page (mobile)
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Use css grid for profile page layout

lego-webapp/pages/users/@username/+Page.tsx
Fixed a mismatch between the listed events and the event count displayed in user profiles and in shell.
- The number of events listed now correctly matches the displayed count.
---
Resolves ABA-1399
=> Fix eventcount in userprofiles

lego-webapp/pages/events/@eventId/administrate/attendees/RegistrationTables.tsx, lego-webapp/pages/users/@username/_components/PhotoConsents.tsx, lego-webapp/utils/index.ts
Resolves the last remaining point of ABA-16, defining the strings for photo consent domains, "abakus.no" and "sosiale media", in a single constant.
I have verified that all the usages of the strings still work.
---
Resolves ABA-16
=> Define consent domain strings in one place

pnpm-lock.yaml, pnpm-workspace.yaml
Simple version update, tests still work fine on v3:)
Should have been done when we bumped vite to v6, as I believe the main change is compatibility with that.
=> Bump vitest to v3

lego-webapp/cypress/e2e/home_page_spec.ts, lego-webapp/cypress/support/utils.ts, lego-webapp/pages/index/AuthenticatedFrontpage.tsx
New datepicker displays two months instead of one, which means running tests on the end of a month makes it pick the wrong date.
---
=> Use new behavior in datepicker test

packages/lego-editor/src/extensions/image.ts
Editing editor-content with images didn't work because of a mistake with parsing the `data-file-key` needed by the backend.
This fixes the parsing, so that it is preserved when editing content containing images.
Tested editing events in dev mode, and verified that the `data-file-key` is correct after editing the event.
=> Fix issue with image file-key when editing with lego-editor

lego-webapp/components/Form/ToggleSwitch.tsx
IDK why, but it somehow the ToggleButtom becomes a type="submit" button when used in forms. Overriding it fixes the behaviour.
It no longer submits forms when toggling the button.
I have tried it in the Joblisting form which used to have the bug.
---
Resolves ABA-1331
=> Prevent ToggleButton from submitting form

lego-webapp/pages/users/@username/settings/notifications/+Page.tsx
With https://github.com/webkom/lego/pull/3791 notifications for new comments are no longer a thing, so we don't need this string in the frontend anymore
=> Remove notification setting string for removed comment notification

lego-webapp/components/Search/utils.tsx, packages/lego-editor/src/Editor.module.css, packages/lego-editor/src/components/ImageMenu.module.css, packages/lego-editor/src/components/ImageMenu.tsx, packages/lego-editor/src/components/Toolbar.tsx, packages/lego-editor/src/extensions/figure.tsx, packages/lego-editor/src/index.tsx
Since the new editor was released, we have received a few complains about the missing caption-feature on images. This PR re-adds it as an optional toggle on images, via a bubble-menu (see below).
It also centers images on the page, which generally looks better:)
Image when selected in lego-editor:
After clicking the caption button:
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Article with images
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
I have tested both in lego-editor dev and in lego-webapp on staging. So I'm pretty sure it works:)
---
Resolves ABA-1407
=> Improve image support in lego-editor

lego-webapp/pages/bdb/company-interest/CompanyInterestForm.tsx, lego-webapp/pages/bdb/company-interest/Translations.ts, lego-webapp/redux/models/CompanyInterest.ts, lego-webapp/redux/slices/companyInterest.ts
Makes the thursday button more visible.
Backend PR: https://github.com/webkom/lego/pull/3807
> [!CAUTION]
Works for new events. Old events also get migrated properly.
---
=> Improve visibility of thursday button

packages/lego-bricks/src/components/Icon/Icon.module.css
Examined cypress and found 3 reasons for why ionicons are not rendered:
a: The ionicons.js endpoint is down (or returns 500)
b:  The ionicons.js is blocked by cors (which also returns 500, and the reason why it does not show in dev)
c:  The ionicons.svg endpoint is down (or returns 500)
In case a and b, a clickable icon receives a width/height of 0px, which causes cypress to fail if it interacts with it.
Even though we are phasing ion out, buttons should not depend on a visual endpoint to be interactable.
Added min-width and min-height to `.clickable`. Uses a small `em` to be relative to the `size`-property
Made sure the `min` is only applied when it is `clickable`
---
=> Add minimum size for icons

lego-webapp/pages/lending/admin/+Page.tsx, lego-webapp/redux/actions/LendingRequestActions.ts, lego-webapp/redux/models/LendingRequest.ts
Adds status filtering to the lending admin page. 
[Backend](https://github.com/webkom/lego/pull/3819)
https://github.com/user-attachments/assets/e83b5ab5-9626-4678-ad36-98bad9bd4c57
Resolves [ABA-1352](https://linear.app/abakus-webkom/issue/ABA-1352/add-filtering-to-admin-panel-in-lending-system)
=> Add filters to lending admin

lego-webapp/components/Feed/activity.module.css, lego-webapp/components/Feed/activity.tsx, lego-webapp/components/Feed/index.tsx, lego-webapp/pages/sudo/achievements/+Page.tsx, packages/lego-bricks/src/components/Card/BaseCard.tsx, packages/lego-bricks/src/components/Card/Card.module.css
Timeline styling broke at some point, likely because of changes to the `Card`-component. I fix.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Timeline
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Looked at it:)
=> Fix and refactor timeline styling

README.md
In the previous version of the README (ever since swapping out yarn for pnpm) there was a mistake in the command for installing dependencies. This command was just `pnpm` instead of `pnpm i` or `pnpm install`. This is likely because with yarn you could installing using simply `yarn`.
In this PR I have updated the command in `README.md` to reflect the correct usage of the pnpm installation command `pnpm i`.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Quick start section of README.md
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Tried running `pnpm`, noted how it didn't install depenencies. After updating the README, I tried running the new command `pnpm i`, and verified that it now runs the installation of dependencies using pnpm.
=> Fix dependency installation command in README

packages/lego-bricks/src/components/Card/Card.module.css, packages/lego-bricks/src/components/Layout/Flex.module.css, packages/lego-bricks/src/components/Layout/Page/Page.module.css, packages/lego-bricks/src/components/Layout/Page/PageContainer.module.css, packages/lego-bricks/src/components/Layout/Page/Sidebar.module.css, packages/lego-bricks/src/custom-media.css, pnpm-workspace.yaml
Custom media query variables allow us to write `@media (--medium-viewport)` instead of `@media (max-width: 45em)`, this fixes them in `lego-bricks`.
It is kind of hacky, but I import the media query definition from `lego-webapp` into `lego-bricks` using the file path `'../../../lego-webapp/styles/custom-media.css'`. This is the same way we import global variables so I think it's ok.
No visual changes, just defines all media query values in one place.
They all still work after building.
---
Resolves ABA-965
=> Fix custom media query variables in lego-bricks

lego-webapp/components/Footer/index.tsx, lego-webapp/components/Search/utils.tsx, lego-webapp/pages/index/AuthenticatedFrontpage.module.css, lego-webapp/pages/index/AuthenticatedFrontpage.tsx
As discussed in a meeting, this PR aims to improve the visibility of our blog. This has been done by including a link on the authenticated front page as well as in the footer. 
Resolves [ABA-1280](https://linear.app/abakus-webkom/issue/ABA-1280/make-utviklarbloggen-more-visible-at-abakusno)
=> Make the blog more visible

lego-webapp/components/Feed/activity.module.css, lego-webapp/components/Feed/index.tsx, lego-webapp/components/Feed/renders/penaltyNotification.tsx, lego-webapp/components/HeaderNotifications/index.tsx, lego-webapp/pages/users/@username/settings/notifications/+Page.tsx, lego-webapp/redux/models/FeedActivity.ts, pnpm-lock.yaml
Made penalty notifications visible in notification feed.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Made penalty notification display, with penalty weight and reason.
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1424
=> Display penalty notification in feed

lego-webapp/components/Countdown/Countdown.module.css, lego-webapp/components/Countdown/index.tsx, pnpm-lock.yaml
Design update to countdown: Now time unit is under the time. Beware the time is in monospace to keep the characters the same width so the time dont move when seconds tick (I dont know if this is good, but it looks better I think). All time units will still appear even if it hits 0. Like if there are no days or hours, it still shows 00 : 00 : xx : xx
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
https://github.com/user-attachments/assets/680ee948-26c2-4875-81ee-73e3bbf5437c 
</td>
<td> …
=> STYLE: Design update to countdown banner

lego-webapp/pages/lending/LendableObjectList.module.css
Small style update for lending index page for small (mobile) viewports. Change to smaller gap between cards and two columns on smaller viewports instead to one. Felt it was a little awkward to scroll one by one card - would take a long time to find your lending object.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Change gap size (less) and 2 fr instead of 1 fr (mobile)
</td>
<td>
https://github.com/user-attachments/assets/15ac20ba-00c0-4b7d-a6c6-b17eac7cbf22
</td>
<td>
https://github.com/user-attachments/assets/754d202c-59fe-4580-98ce-829decaf5fa6
</td>
</tr>
</table>
Resolves ABA-1455
=> Style update: lending mobile

lego-webapp/components/Countdown/Countdown.module.css
Countdown banner time font is different on mobile compared to laptops
Resolves ABA-1460
=> FIX: font difference mobile

lego-webapp/pages/lending/@lendableObjectId/LendingCalendar.module.css, lego-webapp/pages/lending/@lendableObjectId/LendingCalendar.tsx, lego-webapp/pages/lending/@lendableObjectId/request/@lendingRequestId/+Page.tsx, lego-webapp/pages/lending/@lendableObjectId/request/new/+Page.tsx, lego-webapp/redux/actionTypes.ts, lego-webapp/redux/actions/LendableObjectActions.ts, lego-webapp/redux/models/LendableObject.ts, lego-webapp/redux/slices/lendableObjects.ts
Adds a calendar to show unavailable time slots given a lendable object, as well the time slots chosen for the current lending request. The calendar is added to both the new lending request and lending request detail pages. 
Next step will be to make the calendar function as the date and time picker for new lending requests.
[Backend PR](https://github.com/webkom/lego/pull/3836)
https://github.com/user-attachments/assets/9dd8f7ed-3d3a-45b8-bf9c-d5eca973b277
Create and approve a lending request. Verify that the calendar displays unavailable and selected time slots correctly.
Resolves [ABA-1438](https://linear.app/abakus-webkom/issue/ABA-1438)
=> Add lending calendar

lego-webapp/pages/+config.ts
The current slug `/pages/organisasjon/46-fondstyret`, contains the old outdated spelling of Fondsstyret, and the page is not really about the board but rather the fund itself. We thus want to rename it to `/pages/organisasjon/46-fondet`. This change adds a redirect to ensure backwards compatability and no broken links.
Tested locally with staging backend, seemed to work just fine.
---
Resolves ABA-1467
=> Redirect url to account for slug change

lego-webapp/components/Analytics/index.tsx
If you went in to the statistics page multiple times without refreshing it would double the metrics values. This was due to the initial value being updated. 
I went in and out of the statistics page multiple times and it now does not increment it like it used to :)
---
Resolves ABA-1485
=> Fix incrementing metrics bug

lego-webapp/components/JoblistingItem/JoblistingItem.module.css, lego-webapp/components/JoblistingItem/index.tsx
Added a pin for pinned job listings
> [!CAUTION]
---
Resolves ABA-1488
=> Add pin icon for job listings

lego-webapp/components/Form/ImageUploadField.tsx, lego-webapp/pages/lending/LendableObjectEditor.module.css, lego-webapp/pages/lending/LendableObjectEditor.tsx
A bug (that I made heh) made it so that the cropper when uploading an image wasn't forced to have the correct aspectRatio.
before:
after:
notice that in the after, the cropper is always square
=> fix: aspectRatio for ImageUploadField

lego-webapp/components/UserAttendance/RegistrationMeta.tsx
Make description for picture consent on events shorter
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Resolves ABA-830
=> Make picture consent text shorter
