app/components/Modal/ConfirmModal.js
app/reducers/companies.js
app/routes/bdb/AddSemesterRoute.js
app/routes/bdb/BdbDetailRoute.js
app/routes/bdb/BdbRoute.js
app/routes/bdb/EditCompanyContactRoute.js
app/routes/bdb/EditCompanyRoute.js
app/routes/bdb/components/AddSemester.js
app/routes/bdb/components/BdbDetail.js
app/routes/bdb/components/BdbPage.js
app/routes/bdb/components/CompanyContactEditor.js
app/routes/bdb/components/CompanyEditor.js
app/routes/bdb/components/CompanyList.js
app/routes/bdb/components/OptionsBox.js
app/routes/bdb/components/SemesterStatusDetail.js
app/routes/bdb/utils.js

- Adds "Delete company" to the NavigationTab
- Sorts comments on bdb from newest to oldest (Fixes #768, barring the pagination issue)
- Fixes both the `active` and `studentContact`filters
- Fixes broken "delete semester status"
- Fixes broken Add Company Contact reducer
- Fixes adding and editing of student contacts (Fixes #773)
- Adds confirmation modal to all deleting

Post-launch BDB fixes

---

app/routes/app/AppRoute.js

Add a red development header to prevent us from making mistakes in prod

---

app/reducers/events.js
app/reducers/forms.js
app/routes/events/components/EventAdministrate/index.js
app/routes/events/components/EventDetail/index.js
app/routes/events/components/JoinEventForm.js

- Handle non existing waiting registrations gracefully
- Fix loading indicator hiding on other users registrations

Fix waiting registration and loadingindicator

---

app/reducers/events.js
app/reducers/forms.js

Follow up on #830 
Fixes an error that occurs when no state exist in form as well.

Fix incrementing and decrementing beyond max cap

---

app/components/Time/Time.spec.js
app/components/Time/index.js
app/routes/events/components/EventDetail/index.js

Datetime formatting

---

app/routes/photos/components/GalleryDetail.js
app/routes/photos/components/GalleryPictureModal.js
app/routes/photos/components/Overview.css

Added a back button to the when browsing albums. Also fixed the width of the comment form when watching a image. 
Fixes #829  
Fixes #827

Back button and comment form

---

.drone.yml
Dockerfile
config/webpack.client.js
config/webpack.server.js
package.json
scripts/release.js
server/render.js
yarn.lock

Upload source maps to sentry

---

app/routes/events/components/EventAdministrate/AdminRegisterForm.js
app/routes/events/components/EventEditor/index.js
app/routes/joblistings/components/JoblistingEditor.js
app/routes/meetings/components/MeetingEditor.js
app/routes/photos/components/GalleryPictureEditModal.js
app/routes/quotes/components/AddQuote.js
app/routes/users/components/StudentConfirmation.js
app/routes/users/components/UserConfirmation.js
app/routes/users/components/UserSettings.js

Fixes #605
This is not a complete fix for #605, but a most of it, the things that i where unable to fix are now in #871

Add labels and add translations

---

app/actions/JoblistingActions.js

This fixes issues with data flow when changing a joblisting. This is a general problem all over the app..

Disable cache in joblistings to fix mutation issue

---

app/routes/overview/components/PublicFrontpage.css

Fix login box styling on small screens

---

app/routes/events/components/EventList.css
app/routes/events/components/EventList.js

Fix #750
Only display the EventListGroup if there are events to display

Hide EventListGroup if there are no events in group

---

app/reducers/pages.js
app/routes/pages/PageDetailRoute.js
app/routes/pages/PageEditRoute.js
app/routes/pages/components/PageDetail.js

This also moves a lot of the logic to selectors

Fix issues in pages for unauthorized users

---

app/reducers/meetingInvitations.js

Change meeting invitation reducer to work with the new idAttribute of
user.
This fixes https://sentry.abakus.no/webkom/lego-webapp/issues/3821/

Fix meeting invitation reducer

---

app/actions/PageActions.js

Fiexs https://sentry.abakus.no/webkom/lego-webapp/issues/3605/

Fix pages api endpoint

---

app/routes/overview/components/Overview.css

Fix frontpage wordbreak

---

app/routes/joblistings/components/JoblistingDetail.css
app/routes/joblistings/components/JoblistingDetail.js

There are still a couple of things that need fixing, but that can be done in separate PRs.
Other issues:
* Use `ContentHeader` by moving `Rediger` into the sidebar
* Style the sidebar info in the same way as event (need a separate component for this)

Use Content components for joblistings

---

app/components/Form/CheckBox.css

Change style on checkbox

---

app/routes/events/components/JoinEventForm.js

This should be done in a more clever way after https://github.com/webkom/lego-webapp/pull/806 is merged,

Add basic modal to event unregister button

---

app/routes/errors/HTTPError.js

Change error messages

---

app/actions/ArticleActions.js
app/routes/articles/components/ArticleEditor.js
app/routes/overview/components/Overview.js
app/types.js

Follows the same structure as `OverviewItem`, which already works for both types of objects

Rewrite pinned item to allow for articles as well

---

server/render.js

try-catches `renderToString` so we avoid 504 on errors like https://github.com/webkom/lego-webapp/commit/aff37ec81b53965f35f4668f1e8de35068aa05fa

Skip server-side rendering on errors

---

app/routes/interestgroups/components/InterestGroup.css
app/routes/interestgroups/components/InterestGroupDetail.js
app/routes/interestgroups/components/InterestGroupList.js
app/styles/globals.css

Use Content components for interest groups

---

app/components/InfoList/index.js
app/routes/events/components/Event.css
app/routes/events/components/EventDetail/EventDetail.css
app/routes/events/components/EventDetail/index.js
app/routes/joblistings/components/Items.js
app/routes/joblistings/components/JoblistingDetail.css
app/routes/joblistings/components/JoblistingDetail.js
app/utils/joinValues.js

Currently used by event and joblistings.

Add an InfoList component for sidebars

---

server/render.js

Fix server-side rendering

---

app/components/InfoBubble/InfoBubble.css
app/routes/bdb/components/BdbDetail.js
app/routes/bdb/components/SemesterStatusDetail.js
app/routes/bdb/components/bdb.css

Add functionality to delete files in semester statuses

---

app/actions/AnnouncementsActions.js
app/components/AnnouncementInLine/AnnouncementInLine.css
app/components/AnnouncementInLine/index.js
app/models.js
app/routes/announcements/AnnouncementsRoute.js
app/routes/announcements/components/AnnouncementItem.js
app/routes/announcements/components/AnnouncementsCreate.js
app/routes/announcements/components/AnnouncementsList.css
app/routes/announcements/components/AnnouncementsList.js
app/routes/events/components/Admin.js
app/routes/interestgroups/components/InterestGroupDetail.js
app/routes/meetings/components/MeetingDetail.js

Text type:
Button type:
When clicked:
Meetings:
Interest groups:
Events:

Announcements - make announcements directly from events, meetings and interest groups

---

app/routes/events/components/JoinEventForm.js
app/routes/users/components/StudentConfirmation.js
app/utils/validation.js

Quickfix when entering full email, like `abcd@stud.ntnu.no` when we require username only. 
Add stripe remember cookie as well

Verify student email

---

app/actions/CompanyActions.js
app/reducers/companySemesters.js
app/routes/bdb/components/AddSemester.js
app/routes/bdb/components/BdbDetail.js
app/routes/bdb/components/BdbPage.js
app/routes/bdb/components/CompanyContactEditor.js
app/routes/bdb/components/CompanyEditor.js
app/routes/bdb/components/bdb.css
app/routes/bdb/utils.js
app/routes/company/components/CompanyDetail.js
app/routes/companyInterest/CompanyInterestEditRoute.js
app/routes/companyInterest/CompanyInterestRoute.js
app/routes/companyInterest/components/CompanyInterestList.js

~~Requires https://github.com/webkom/lego/pull/886~~
And show companyInterest in BDB navigation.

Fix semester handling in CompanyInterest

---

app/components/Card/index.js
app/components/Feed/activity.js
app/routes/users/components/Penalties.js
app/routes/users/components/UserProfile.css
app/routes/users/components/UserProfile.js

Can probably make it look better as part of the user profile re-design, but better than nothing. Also realigns things a bit and fixes the mobile view.

Show penalties in user profile

---

app/reducers/frontpage.js

Sort by IDs first in frontpage

---

app/components/Form/RadioButton.css
app/components/Form/RadioButton.js

Fixes #887. Also fixes the slight hover effect that seemed to have disappear.

Don't use global styling for RadioButton

---

app/models.js
app/routes/interestgroups/components/InterestGroupDetail.js

Use actionGrant for interest group edit

---

app/actions/ActionTypes.js
app/actions/RoutingActions.js
app/actions/UserActions.js
app/components/Footer/index.js
app/reducers/fetchHistory.js
app/routes/errors/HTTPError.js
app/routes/events/CalendarRoute.js
app/routes/events/EventDetailRoute.js
app/routes/events/EventListRoute.js

This fixes login bug when HTTPError is rendered, and the bug when
navigation between 404 pages that doesn't have a router entry. It also
clears the fetchHistory on login.

Fix login bugs

---

app/routes/joblistings/components/JoblistingDetail.js

Ved å merge denne pr'en anerkjenner dere meg som et fullverdig medlem av Webkom som samtidig innebærer at jeg får tilgang til Sahara med mitt adgangskort.
Godtar også delvis medlemskap såfremt jeg får tilgang til Sahara.
Takk.

Fix typo in JoblistingDetail

---

app/routes/events/components/JoinEventForm.js

Feedback was not prefilled when using required feedback.

Fix feedback initialValue when feedbackrequired

---

styleguide.config.js

All errors will still be printed via stderr

Suppress warnings in styleguidist

---

app/routes/events/components/EventDetail/index.js

Show company logo if company event has no cover

---

app/Root.js
app/assets/sentry-aw-snap.svg
app/components/ErrorBoundary/ErrorBoundary.css
app/components/ErrorBoundary/index.js
app/routes/app/AppRoute.js
config/webpack.client.js
config/webpack.server.js

Report to sentry and support the sentry report dialog.

Catch errors with react 16 errorboundary

---

app/reducers/index.js
app/reducers/meetings.js
app/routes/meetings/MeetingDetailLoginRoute.js
app/routes/meetings/MeetingDetailRoute.js
app/routes/meetings/components/MeetingDetail.css
app/routes/meetings/components/MeetingDetail.js
app/utils/getEntityType.js

Added comments section and refactored layout to use Content.

Meeting comments

---

app/components/Modal/ConfirmModal.js
app/routes/events/components/JoinEventForm.js

Adds notice when trying to unregister when event heeds penalties and has passed unregistration deadline

Add penalty notice

---

app/routes/events/components/EventEditor/index.js
app/routes/events/utils.js

Adds options to heed penalties in the editor
We should add better descriptions why registrations gets delayed, but we can add this to the editor in the meantime.

Add heedPenalties

---

app/components/Header/FancyNodesCanvas.js
app/styles/globals.css

This fixes the bad scrolling performance (especially on slow phones).

Fix scrolling and resize performance

---

app/routes/overview/components/LatestReadme.js

And YES, we should talk with `readme` to automate/force them to do this this..

Add the new readme release

---

app/components/Search/SearchPage.js
app/components/Search/SearchPageInput.js
app/reducers/events.js
app/routes/events/components/EventAdministrate/Abacard.js
app/routes/events/components/EventAdministrate/index.js

Fixes a few random issues with Abacard:
* Makes sure that the input is always in focus
* Adds a custom placeholder prop to SearchPage
* Changes the title of the admin page to the event title
* Caps `selectedIndex` to `0 <= index <= results.length`

Abacard fixes

---

app/routes/joblistings/components/JoblistingEditor.js

This will help bedkom to avoid creating 10+ duplicates of a joblisting

Disable submit button in joblistings when working

---

app/routes/interestgroups/InterestGroupListRoute.js
app/routes/interestgroups/components/InterestGroupList.js

Uses `actionGrant` for groups.

Only show the create interest group button for those with permission

---

app/routes/company/components/CompaniesPage.js
app/routes/company/components/Company.css
app/routes/company/components/CompanyDetail.js
app/routes/events/components/EventList.js
app/routes/joblistings/components/JoblistingList.css
app/routes/joblistings/components/JoblistingList.js

Fix image rendering

---

app/Root.js
app/routes/resolveAsyncRoute.js

Add graceful error handling for chunk loading

---

app/routes/users/components/Penalties.js
app/routes/users/components/UserProfile.js

Penalties improved

---

app/utils/__tests__/urlifyString.spec.js
app/utils/urlifyString.js
package.json
yarn.lock

This is still a temporary solution.. :upside_down_face:

Fix urlify

---

app/reducers/companySemesters.js

We have discussed the topic and think that this is a valid solution to the problem #831

Add filter for previous semesters

---

app/routes/events/EventCreateRoute.js

- Add penalties by default on event creation

Heed penalties by default

---

app/components/Search/SearchPageInput.css
app/components/Search/SearchPageResults.css
app/components/Search/SearchPageResults.js

Small screen:
Medium screen:
Big screen:

Improve appearance of search page and improve responsiveness

---

app/routes/users/UserProfileRoute.js

https://github.com/webkom/lego/pull/1020

Don't fetch user feed for now

---

app/routes/events/components/EventDetail/index.js

Depends on https://github.com/webkom/lego/pull/1019

Add a field that displays the event creator and make company name a link

---

app/routes/overview/components/Feed.css
app/routes/overview/components/Feed.js

Add style for wordbreaking in feed

---

app/routes/joblistings/components/JoblistingDetail.js
app/routes/joblistings/components/JoblistingEditor.js
app/routes/joblistings/constants.js

Add contact email functionality in frontend.

Joblistings contact email

---

app/actions/EmailUserActions.js
app/components/Form/index.js
app/components/Form/legoForm.js
app/components/Form/utils.js
app/components/GroupForm/index.js
app/routes/admin/email/components/EmailListEditor.js
app/routes/articles/components/ArticleEditor.js
app/routes/bdb/components/CompanyEditor.js
app/routes/events/components/EventEditor/index.js
app/routes/joblistings/components/JoblistingEditor.js
app/routes/meetings/components/MeetingEditor.js
app/routes/pages/PageEditRoute.js
app/routes/pages/components/PageEditor.js
app/routes/quotes/components/AddQuote.js
app/routes/quotes/components/__tests__/AddQuote.spec.js
app/routes/users/components/ChangePassword.js
app/routes/users/components/UserSettings.js

This is much better than having this in each form.
It would also be much easier to refactor later.
This fixes #746

Add legoForm

---

app/routes/overview/components/PublicFrontpage.js

I think its time to remove this...

Remove the 'obs click reset pw' text on our login screen

---

app/routes/joblistings/components/JoblistingList.js

Style job listing detail

---

app/utils/configureStore.js

This will fix the styleguide :fire:

Make raven option when configuring store 

---

app/reducers/frontpage.js
app/reducers/index.js
app/routes/overview/IndexRoute.js
app/routes/overview/components/Overview.js
app/utils/createEntityReducer.js

(doesn't happen with the server side render, so usually you won't see it) - fixes #1053

Show a loading indicator on the frontpage

---

app/components/UserAttendance/AttendanceStatus.js
app/models.js
app/reducers/events.js
app/reducers/fetchHistory.js
app/reducers/pools.js
app/routes/events/CalendarRoute.js
app/routes/events/EventCreateRoute.js
app/routes/events/EventDetailRoute.js
app/routes/events/EventListRoute.js
app/routes/events/components/EventDetail/index.js
app/routes/events/components/EventEditor/index.js
app/routes/events/components/JoinEventForm.js
app/routes/events/utils.js

Add initial support for public events

---

app/components/Search/Search.css
app/components/Search/SearchResults.js
app/reducers/search.js

This is a bit WIP, but i wanted to get some feedback, working on #1045
Events in the list of results will now show information about when it starts

Make the autocomplete search more user friendly

---

app/actions/ActionTypes.js
app/actions/SurveySubmissionActions.js
app/reducers/index.js
app/reducers/surveySubmissions.js
app/reducers/surveys.js
app/routes/surveys/AddSubmissionRoute.js
app/routes/surveys/EditSurveyRoute.js
app/routes/surveys/SubmissionsRoute.js
app/routes/surveys/SurveyDetailRoute.js
app/routes/surveys/SurveyRoute.js
app/routes/surveys/components/AdminSideBar.js
app/routes/surveys/components/SubmissionEditor.js
app/routes/surveys/components/SubmissionIndividual.js
app/routes/surveys/components/SubmissionPage.js
app/routes/surveys/components/SubmissionSummary.js
app/routes/surveys/components/SubmissionsPage.js
app/routes/surveys/components/SurveyDetail.js
app/routes/surveys/components/surveys.css
app/routes/surveys/index.js
app/routes/surveys/utils.js

Adds submission handling to surveys: Users can answer surveys and admins can view them.
Continues the Survey project #986: 
Also does some general fixes to surveys, such as moving admin functionality from the navigation menu to a sidebar.
Pictures not representative of the finished product.

Survey submissions

---

app/routes/users/components/UserConfirmation.js

Use legoForm in UserConfirmation

---

app/utils/__tests__/urlifyString.spec.js
app/utils/urlifyString.js

Add support for trailing dot and comma in urlify

---

app/routes/admin/groups/components/AddGroupMember.js

Need to fix the red border around selects, but that's a separate issue.

Show an error when adding existing group members, fixes #600

---

app/routes/events/components/EventFooter.js

This error ruined the booking round completely, as no one would take us seriously 🤑

Fix huge iCal error 😱

---

app/models.js
app/reducers/groups.js
app/reducers/search.js
app/routes/interestgroups/components/InterestGroup.js
app/routes/interestgroups/components/InterestGroupDetail.js
app/routes/interestgroups/components/InterestGroupList.js
app/routes/users/components/UserProfile.js

This will remove all search results that doesn't lead to a valid url. It also adds links to user badges, aka. fixing #823.
This fixes #823

Search filter

---

app/components/UserAttendance/AttendanceModal.js
app/components/UserAttendance/withModal.js
app/models.js
app/reducers/events.js
app/routes/events/components/EventDetail/index.js
app/routes/events/utils.js

Front-end for https://github.com/webkom/lego/pull/1105

Sort event registrations by number of shared memberships

---

app/components/Form/CheckBox.css
app/components/Form/Field.css
app/components/Form/SelectInput.js
app/routes/admin/email/components/RestrictedMailEditor.js
app/styles/variables.css

Adds new style for disabled forms and disabled buttons

---

app/routes/companyInterest/components/CompanyInterestList.js

Added confirm modal to prevent accidental deletion of company interests. This should have been added way earlier, but better late than never 💯🥇

Add confirm modal for deletion

---

app/components/DisplayContent/index.js

Maybe not the cleanes way to do it, but it temporary does the job.

Force remount of DisplayContent

---

app/actions/ActionTypes.js
app/actions/UserActions.js
app/models.js
app/reducers/index.js
app/reducers/penalties.js
app/routes/users/UserProfileRoute.js
app/routes/users/components/Penalties.js
app/routes/users/components/PenaltyForm.js
app/routes/users/components/UserProfile.js

This fixes #343 by adding penalty button.

Add penalty button

---

app/components/EmptyState/index.js
app/components/Feed/activity.js
app/components/Feed/context.css
app/components/Feed/context.js
app/components/Feed/renders/adminRegistration.js
app/components/Feed/renders/announcement.js
app/components/Feed/renders/comment.js
app/components/Feed/renders/comment_reply.js
app/components/Feed/renders/event_register.js
app/components/Feed/renders/group.js
app/components/Feed/renders/meetingInvitation.js
app/components/Feed/renders/registrationBump.js
app/components/Feed/renders/restrictedMail.js
app/components/Feed/renders/utils.js
app/components/Feed/types.js
app/components/HeaderNotifications/HeaderNotifications.css
app/components/HeaderNotifications/index.js
app/routes/overview/components/Feed.css
app/routes/overview/components/Feed.js

Notifications
Feed
Should the red text in the feed be links as well (clicking webkom webkom links to its profile etc.)? They are in the feed, but not in notifications now, but not sure if it's better to be consistent.

Clickable notifications field

---

app/routes/pages/PageCreateRoute.js
app/routes/pages/PageEditRoute.js
app/routes/users/components/PenaltyForm.js
app/routes/users/components/UserSettings.js

Will create an issue with a list of all the forms that doesn't use `legoForm`.
This fixes a few bugs (see commits).

Fix a few forms by adding legoForm

---

app/components/EmptyState/index.js
app/components/Feed/activity.js
app/components/Feed/context.css
app/components/Feed/context.js
app/components/Feed/renders/adminRegistration.js
app/components/Feed/renders/announcement.js
app/components/Feed/renders/comment.js
app/components/Feed/renders/comment_reply.js
app/components/Feed/renders/event_register.js
app/components/Feed/renders/group.js
app/components/Feed/renders/meetingInvitation.js
app/components/Feed/renders/registrationBump.js
app/components/Feed/renders/restrictedMail.js
app/components/Feed/renders/utils.js
app/components/Feed/types.js
app/components/HeaderNotifications/HeaderNotifications.css
app/components/HeaderNotifications/index.js
app/routes/overview/components/Feed.css
app/routes/overview/components/Feed.js

Reverts webkom/lego-webapp#1040
This causes a bug in production, resulting in a crash in the main page.
Sentry report: https://sentry.abakus.no/webkom/lego-webapp/issues/4920/

Revert "Clickable notifications field"

---

app/actions/ArticleActions.js
app/actions/callAPI.js
app/components/Tags/index.js
app/reducers/articles.js
app/routes/articles/ArticleListRoute.js
app/routes/articles/components/ArticleDetail.js
app/routes/articles/components/ArticleEditor.js
app/routes/articles/components/Overview.css
app/routes/articles/components/Overview.js
app/utils/createEntityReducer.js

* Fix broken tag field (lowecase values)
* Fix actionGrant issue that caused a crash at article create
* Article pagination
* Atricle tags and creator in article list
* Use backend ordering in createEntityReducer

Article fixup

---

app/components/EmptyState/index.js
app/components/Feed/activity.js
app/components/Feed/context.css
app/components/Feed/context.js
app/components/Feed/renders/adminRegistration.js
app/components/Feed/renders/announcement.js
app/components/Feed/renders/comment.js
app/components/Feed/renders/comment_reply.js
app/components/Feed/renders/event_register.js
app/components/Feed/renders/group.js
app/components/Feed/renders/meetingInvitation.js
app/components/Feed/renders/registrationBump.js
app/components/Feed/renders/restrictedMail.js
app/components/Feed/renders/utils.js
app/components/Feed/types.js
app/components/HeaderNotifications/HeaderNotifications.css
app/components/HeaderNotifications/index.js
app/routes/overview/components/Feed.css
app/routes/overview/components/Feed.js

This caused a bug in production, resulting in a crash in the main page.
Sentry report: https://sentry.abakus.no/webkom/lego-webapp/issues/4920/
The problem is from here: https://github.com/webkom/lego-webapp/compare/revert-1173-revert-1040-clickable_notifications?expand=1#diff-6a444fe17f1557293c9558c9644b9d1cR54

Revert "Revert "Clickable notifications field""

---

app/actions/GalleryActions.js
app/actions/GroupActions.js
app/components/Table/index.js
app/reducers/groups.js
app/reducers/memberships.js
app/routes/admin/groups/components/AddGroupMember.js
app/routes/admin/groups/components/AddGroupPermission.js
app/routes/admin/groups/components/GroupMembers.css
app/routes/admin/groups/components/GroupMembers.js
app/routes/admin/groups/components/GroupMembersList.js
app/routes/admin/groups/components/GroupPermissions.js
app/routes/admin/groups/components/__tests__/GroupMembers.spec.js
app/utils/createEntityReducer.js

The table looks shitty, but atleast it has got some pagination... :smile: 
The filtering is just in the frontend as of now, but works more or less ok. The performance for the bigges groups (grades) works well.
Also did some changes to the pagination part of `createEntityReducer`. :smile:

[WIP] Group admin stuff

---

app/routes/companyInterest/components/CompanyInterestPage.js

fix #1139 by expanding the comment field size in interestform.

Expand comment field size

---

app/actions/ActionTypes.js
app/actions/EventActions.js
app/reducers/events.js
app/reducers/index.js
app/utils/__tests__/createEntityReducer.spec.js
app/utils/createEntityReducer.js

- Allow fetch to be passed as array
- Moves fetchUpcoming logic to event reducer

Make createEntityReducer handle fetchTypes as array

---

app/actions/CompanyInterestActions.js
app/routes/companyInterest/CompanyInterestListRoute.js
app/routes/companyInterest/components/CompanyInterestList.js

Add pagination for company interests. Use `<Table>` instead of `<table>` and cleaner code in general.

Add pagination and refactor code

---

app/actions/GroupActions.js
app/routes/pages/PageDetailRoute.js

Make Bedkom happy. They need pagination because they have too many members :laughing:

Force fetch all pagination

---

app/routes/overview/components/LatestReadme.css
app/routes/overview/components/LatestReadme.js

This also fixes the aspect ratio...

Add latest readme and fix styling

---

app/actions/ActionTypes.js
app/actions/ArticleActions.js
app/actions/TagActions.js
app/components/Search/utils.js
app/components/Tags/Tag.css
app/reducers/articles.js
app/reducers/index.js
app/reducers/search.js
app/reducers/tags.js
app/routes/articles/ArticleListRoute.js
app/routes/articles/components/Overview.js
app/routes/index.js
app/routes/tags/TagDetailRoute.js
app/routes/tags/TagsListRoute.js
app/routes/tags/components/TagCloud.js
app/routes/tags/components/TagDetail.css
app/routes/tags/components/TagDetail.js
app/routes/tags/index.js
package.json
yarn.lock

Tags frontend and article filtering

---

app/components/Tags/Tag.js
app/models.js
app/reducers/frontpage.js
app/routes/overview/components/Overview.css
app/routes/overview/components/Overview.js

Render more information about articles on the frontpage

---

app/actions/GalleryPictureActions.js
app/routes/photos/GalleryDetailRoute.js
app/routes/photos/GalleryListRoute.js
app/routes/photos/GalleryPictureRoute.js
app/routes/photos/components/GalleryDetail.js
app/routes/photos/components/GalleryPictureModal.js
app/routes/photos/components/Overview.js

Solves 2 out of total 5 issues in #1155. Solves "Action Grants for both list, pictures and so forth" and "Add "confirm delete" modal". 😄 
Closes #1086.

Add actionGrant on actions and deletion confirmation on deletePicture

---

app/actions/GroupActions.js
app/actions/InterestGroupActions.js
app/components/Form/ImageUploadField.js
app/routes/admin/groups/components/AddGroupPermission.js
app/routes/admin/groups/components/GroupPermissions.js
app/routes/articles/ArticleListRoute.js
app/routes/articles/components/Overview.js
app/routes/users/components/UserSettings.js

This fixes #1014.
https://github.com/webkom/lego/pull/1167

Remove unnccecary code in ImageUploadField

---

app/actions/ArticleActions.js
app/actions/GalleryActions.js
app/components/Form/ObjectPermissions.js
app/routes/articles/ArticleEditRoute.js
app/routes/articles/components/ArticleEditor.js
app/routes/photos/GalleryCreateRoute.js
app/routes/photos/GalleryEditRoute.js
app/routes/photos/components/GalleryEditor.js

Add proper permission handling for galleries :tada: :taco: 
This require https://github.com/webkom/lego/pull/1171

Gallery permissions

---

app/components/Content/Content.css

Fix content cover image height

---

app/components/ReadmeLogo/index.js
app/components/ResolveLink.js
app/components/Search/utils.js

Fix mission critical failure

---

app/routes/surveys/components/Submissions/SubmissionPage.js
app/routes/surveys/components/Submissions/SubmissionSummary.js
app/routes/surveys/components/surveys.css
app/routes/surveys/utils.js
package.json
yarn.lock

Requires https://github.com/webkom/lego/pull/1192 for event info

Add event info and pie charts to the survey result page

---

app/models.js
app/routes/events/EventAbacardRoute.js
app/routes/events/components/EventAdministrate/Abacard.css
app/routes/events/components/EventAdministrate/Abacard.js

fix #1079 Lets users see the stats about the attendees.
before:
after:

Abacard stat counter

---

app/routes/photos/components/GalleryEditor.js
app/routes/photos/components/GalleryPictureModal.js

Should fix the 'Warning when deleting a album' part of #1221 , and some other small stuff.

Pr album improvments

---

app/routes/events/components/EventAdministrate/Abacard.css
app/routes/events/components/EventAdministrate/Attendees.js

Add a stat counter on attendees page.
Before:
After:

Attendees stat counter

---

app/models.js
app/routes/events/components/Admin.js
app/routes/surveys/components/SurveyList/SurveyList.js

Requires https://github.com/webkom/lego/pull/1205

Link to existing survey instead of to /add if it exists in events

---

app/actions/ActionTypes.js
app/actions/SurveyActions.js
app/routes/surveys/SubmissionsRoute.js
app/routes/surveys/components/AdminSideBar.js
app/routes/surveys/components/Submissions/SubmissionPage.js

Requires https://github.com/webkom/lego/pull/1206

Add option to share and hide survey, controlling the backend token

---

app/actions/ActionTypes.js
app/actions/SurveySubmissionActions.js
app/reducers/surveySubmissions.js
app/routes/surveys/SubmissionsRoute.js
app/routes/surveys/components/Submissions/SubmissionSummary.js
app/routes/surveys/components/surveys.css

Based on #1219, merge that first.
Requires https://github.com/webkom/lego/pull/1204.
Adds functionality described in https://github.com/webkom/lego/pull/1204 to the front-end.

Survey hide answers

---

app/utils/__tests__/createEntityReducer.spec.js
app/utils/createEntityReducer.js

Cherry-picked from #1218, written by @SmithPeder.

 Check if primary key is true in addition to checking if resultIds is an array

---

app/routes/overview/components/LatestReadme.js

Update readme på forsiden hehe ;) ;) ;)

---

app/components/Editor/Blocks/ImageBlock.css
app/components/Footer/index.js
app/routes/overview/IndexRoute.js
app/routes/overview/components/Overview.js
app/routes/overview/components/PublicFrontpage.js

Creative corner & Add FP 2k18 to frontpage

---

Dockerfile
package.json
server/render.js
yarn.lock

div stuff
This should fix the `n is not a function` caused by `<React.Fragment />` since it isn't (wasn't) supported in `@webkom/react-prepare`. :smile:

Source maps

---

app/reducers/events.js

This should fix https://sentry.abakus.no/webkom/lego-webapp/issues/5519 :100:

Fix event selector

---

app/components/ReadmeLogo/index.js
app/routes/pages/components/PageDetail.js
app/routes/pages/components/PageHierarchy.js

This fixes #1242
Only applies on title and page hierarchy, content
has to be handeled by the editor using a custom block

Add readmeIfy

---

app/actions/ArticleActions.js

Save all the information. Previously permission-stuff was omitted.

Fix bug when creating article

---

app/routes/overview/components/CompactEvents.js

Add no events support to CompactEvents

---

app/routes/companyInterest/components/CompanyInterest.css
app/routes/companyInterest/components/CompanyInterestPage.js

Fix #1261 
Has no visual impact, just makes the everything click-worthy

Wrap the Fields and spans in a label to make them 'Clickable'

---

app/routes/users/components/GroupChange.js

Because of stupid serializer/selector :upside_down_face:

Fix bug going from administrate to user

---

app/models.js
app/routes/events/EventCreateRoute.js
app/routes/events/EventEditRoute.js
app/routes/events/components/EventEditor/index.js
app/routes/events/utils.js

Add fee label and checkbox

---

app/routes/overview/components/CompactEvents.css
app/routes/overview/components/CompactEvents.js
app/routes/overview/components/PublicFrontpage.css
app/routes/overview/components/PublicFrontpage.js

New frontpage

---

app/routes/overview/components/PublicFrontpage.css

I chose the wrong color, this matches the color used for cards displayed when logged in

Wrong color

---

app/actions/CompanyActions.js
app/reducers/companyInterest.js
app/reducers/index.js
app/routes/company/components/Company.css
app/routes/companyInterest/CompanyInterestListRoute.js
app/routes/companyInterest/components/CompanyInterest.css
app/routes/companyInterest/components/CompanyInterestList.js
app/routes/companyInterest/components/CompanyInterestPage.js
app/routes/companyInterest/components/CompanySemesterGUI.js
app/routes/companyInterest/utils.js

Add a filter for company interests based on semester. Only a single semester can be chosen at the moment, but this will be a later feature =)
Works with pagination

Filter company interests based on semester and year

---

app/components/Form/legoForm.js
app/routes/surveys/components/SubmissionEditor/SubmissionEditor.js

This also scrolls the user to the question that isn't answered.
We have a few strange issues, so this should report all the things to sentry :tm:

Add sentry reporting to surveys

---

app/routes/companyInterest/CompanyInterestListRoute.js

Small fix for company interest

Remove inactive company semesters from filter alternatives 

---

app/routes/companyInterest/components/CompanyInterest.css
app/routes/companyInterest/components/CompanyInterestPage.js

Add event in company interest and fix style

---

app/routes/overview/components/Pinned.css
app/routes/overview/components/Pinned.js

Bad css on phone, the img would get stretched

---

app/actions/EventActions.js
app/routes/events/components/EventAdministrate/AdminRegister.js

Add support for multiselect when doing admin-reg. :small_airplane:

Add support for bulk admin register

---

app/routes/articles/components/Overview.css

Quick fix to put this view out of its misery

---

app/components/Search/SearchPage.js
app/routes/events/components/EventAdministrate/Abacard.js
app/routes/events/components/EventAdministrate/Attendees.js

Fix #1224 by not include waitinglist in count on Abacard and attendees.

Fix count on abacard and attendees

---

app/components/Search/SearchPage.js
app/routes/events/components/Calendar.css
app/routes/events/components/CalendarCell.js
app/routes/events/components/EventAdministrate/Abacard.js
app/routes/events/components/EventAdministrate/Attendees.js

Fix #1298 by view current day and enlighten upcoming events.
Before:
After:

Fix display current day in calendar

---

app/actions/EventActions.js
app/routes/events/components/EventAdministrate/AdminRegister.js

Reverts webkom/lego-webapp#1301

Revert "Add support for bulk admin register"

---

app/actions/ActionTypes.js
app/actions/ArticleActions.js
app/reducers/articles.js
app/routes/articles/ArticleEditRoute.js
app/routes/articles/components/ArticleEditor.js
app/routes/articles/components/Overview.css
app/routes/overview/components/ArticleItem.css

Add delete function for articles

---

app/components/GroupForm/index.js
app/models.js
app/routes/users/components/UserProfile.js

Depends on https://github.com/webkom/lego/pull/1295

Add old member badges

---

app/components/Form/TimePicker.js

Solves #1282. Fix keyboard input handling in the time picker 🎉

Fix time picker

---

app/routes/events/components/EventEditor/index.js

Add null checks for event editor

---

app/components/Banner/Banner.css
app/components/Banner/index.js
app/routes/overview/components/Overview.css
app/routes/overview/components/Overview.js

Still looks the same, but you can switch color/link/text using props

Create banner as a component

---

app/routes/events/components/Admin.js

To make sure no one deletes an event by accident, add a few extra steps to the process

Add extra steps to deleting an event

---

app/routes/quotes/components/QuoteList.js

Fix undefined quotes causing error

---

Dockerfile

FIxed s3 in sentry. https://github.com/webkom/sentry/commit/77dcaa3d4683d65f9aa2026ab46687607a1de92e

Sourcemaps are back <3

---

app/components/GroupMember/GroupMember.css
app/components/GroupMember/index.js
app/models.js
app/routes/pages/components/PageDetail.css
app/routes/pages/components/PageDetail.js

Style members list at om Abakus

---

.drone.yml

This fixes #1378.
https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

Fix CI docker build args

---

app/routes/events/components/JoinEventForm.js

Change present/past tense according to time

---

app/routes/overview/components/ArticleItem.js
app/routes/overview/components/CompactEvents.css
app/routes/overview/components/LatestReadme.js
app/routes/overview/components/Overview.css
app/routes/overview/components/Overview.js
app/routes/overview/components/Pinned.css

Rewrote frontpage to use css grid on mobile and a more responsive flexbox layout on full size screens. Also changed so only one weekly article is shown.

Redo frontpage to be more responsive

---

app/routes/overview/components/NextEvent.css
app/routes/overview/components/NextEvent.js
app/routes/overview/components/Overview.js

Add next event to frontpage

---

app/routes/events/EventCreateRoute.js
app/routes/events/components/EventEditor/index.js
app/routes/events/components/EventEditor/renderPools.js

Change default activation date to 1200 one week before 

---

app/components/EventItem/index.js
app/routes/events/components/EventList.js

Fix event-sorting / filtering bugs

---

app/components/Form/DatePicker.js

Solves autoscroll to error in editors

Add name prop to date picker

---

app/routes/companyInterest/components/CompanyInterestPage.js

https://github.com/webkom/lego/pull/1359 needs merge first 👍

Add new event to company interest

---

app/routes/events/EventCreateRoute.js
app/routes/events/EventEditRoute.js
app/routes/events/utils.js
app/routes/joblistings/JoblistingCreateRoute.js
app/routes/joblistings/components/JoblistingEditor.js
app/utils/time.js
yarn.lock

Closes #1112
Sets visibleFrom to todays date at 12:00, deadline to 30 days from now at 23:59 and visibleTo to 31 days from now at 23:59. From what I could tell, most joblistings are visible one extra day after the deadline expires, and most deadlines are at 23:59. 
I also moved a time util from events to global utils, to avoid duplication.

Set default values for dates when creating a new joblisting

---

app/utils/configureStore.js

Fix https://github.com/webkom/lego/issues/1379

Update redux devtools naming

---

README.md
config/webpack.client.js
package.json
yarn.lock

`BUNDLE_ANALYZER=true yarn build`
Fun with flags :100:

Add bundle analyzer

---

app/routes/overview/components/Overview.css
app/routes/overview/components/Overview.js

Use media query instead of window to render mobile so SSR doesn't break.
Fix https://sentry.abakus.no/webkom/lego-webapp/issues/6209/?query=is:unresolved

Fix server-side render on frontpage

---

Dockerfile
Dockerfile.minimal

Upgrade both files to node 11. Tried building both locally and it works just fine.

Upgrade to node 11

---

app/reducers/search.js
app/routes/companyInterest/components/CompanyInterestPage.js
app/routes/events/components/EventDetail/index.js
app/routes/interestgroups/components/InterestGroupList.js
app/routes/overview/components/PublicFrontpage.js
app/routes/pages/components/PageEditor.js

Fix broken urls around abakus.no and fix routing issues when saving or creating article.
https://github.com/webkom/lego/issues/1461

Fix url issues connected to Om Abakus

---

app/routes/users/components/UserProfile.js

Little mishap in https://github.com/webkom/lego-webapp/pull/1436

Add field translation to profile page

---

app/routes/companyInterest/components/CompanyInterestList.js

Add null check for semester filter

---

app/actions/CompanyActions.js
app/routes/company/CompanyDetailRoute.js
app/routes/company/components/CompanyDetail.js

Add pagination and sorting to events on company detail route.

Company detail events pagination

---

yarn.lock

Fix dtrace error on osx

---

app/components/AnnouncementInLine/index.js
app/components/Feed/activity.js
app/components/Gallery/index.js
app/components/Header/index.js
app/components/HeaderNotifications/index.js
app/components/LoginForm/LoginPage.js
app/components/Paginator/index.js
app/components/ProgressiveImage/index.js
app/components/Search/SearchPage.js
app/components/Search/index.js
app/components/Table/index.js
app/components/Upload/index.js
app/routes/admin/email/components/EmailLists.js
app/routes/admin/email/components/EmailUsers.js
app/routes/admin/email/components/RestrictedMails.js
app/routes/photos/components/GalleryDetail.js
app/routes/photos/components/GalleryEditor.js
app/routes/photos/components/GalleryPictureModal.js
app/routes/surveys/components/AdminSideBar.js
app/routes/surveys/components/SurveyDetail.js
app/routes/surveys/components/SurveyEditor/SurveyEditor.js
app/routes/users/components/PenaltyForm.js

First commit fixes https://sentry.abakus.no/webkom/lego-webapp/issues/6413/?query=is:unresolved (and sourcemaps still works, yay!), but i cannot understand why... Worked well in babel 6.

Babel why???

---

app/routes/pages/PageDetailRoute.js

This removes the duplicated (5x) fetching of pages, and adds flow types to the sections.

Add flowtypes and reduce fetching

---

app/components/GroupMember/GroupMember.css
app/components/GroupMember/index.js
app/components/NavigationTab/NavigationTab.css
app/reducers/pages.js
app/routes/admin/groups/components/GroupMembersList.js
app/routes/interestgroups/components/InterestGroupMemberList.js
app/routes/pages/components/PageDetail.css
app/routes/pages/components/PageDetail.js
app/utils/constants.js

Fix the layout of the comittee members, and move the Change and New button to the right side of the page.

Issi about fixes

---

app/routes/pages/components/PageDetail.css
app/routes/pages/components/PageDetail.js

…space between the logo and title of page, so it looks good for both regular pages and committee pages.

Mobile view of leader/co-leader and logo/title adjustments

---

app/routes/interestgroups/components/InterestGroup.css
app/routes/pages/components/PageDetail.js
yarn.lock

Change the logo height to 50%.

Fix sidebar setup in Interest Groups

---

package.json
yarn.lock

Upgrade assets-webpack-plugin

---

config/webpack.client.js

Not that slow anymore. Waaaay better sourcempas when debugging.
We can test this and see how it works. :smile:

Add better sourcempas in dev

---

app/components/Poll/Poll.css
app/components/Poll/index.js
app/components/Tooltip/index.js
app/routes/polls/PollsDetailRoute.js
app/routes/polls/PollsListRoute.js

Add total votes to the component and move percentage text after bar if it cant fit inside.
Fixes https://github.com/webkom/lego/issues/1493

Polls hotfixes

---

package.json
yarn.lock

Bump jest to make tests pass

---

app/actions/EventActions.js
app/routes/events/EventDetailRoute.js

Dependent on https://github.com/webkom/lego/pull/1485

Change how following is checked

---

app/components/EventItem/index.js

Fixes https://github.com/webkom/lego/issues/1506

Fix timestamp format for EventItem

---

app/actions/EmailListActions.js
app/routes/admin/email/components/EmailListEditor.js

Add notice about roles in email form

---

app/components/Form/Field.css
app/components/Form/Field.js

- Enable warnings for redux-forms 💯 🔥 🗡

Enable redux-form warnings :')

---

app/actions/ActionTypes.js
app/actions/CommentActions.js
app/components/Comments/Comment.css
app/components/Comments/Comment.js
app/components/Comments/CommentTree.css
app/components/Comments/CommentTree.js
app/components/Comments/CommentView.js
app/models.js
app/reducers/comments.js
app/reducers/quotes.js
app/routes/articles/ArticleDetailRoute.js
app/routes/articles/components/ArticleDetail.js
app/routes/bdb/BdbDetailRoute.js
app/routes/bdb/components/BdbDetail.js
app/routes/events/EventDetailRoute.js
app/routes/events/components/EventDetail/index.js
app/routes/meetings/MeetingDetailRoute.js
app/routes/meetings/components/MeetingDetail.js
app/routes/photos/GalleryPictureRoute.js
app/routes/photos/components/GalleryPictureModal.js
app/routes/quotes/QuoteDetailRoute.js
app/routes/quotes/components/Quote.js
app/routes/quotes/components/QuoteList.js
app/routes/quotes/components/QuotePage.js
app/utils/index.js

Adds an option to delete a comment. Also improves comment styling on mobile.
Resolve https://github.com/webkom/lego/issues/1465
Resolve https://github.com/webkom/lego/issues/1398

Add ability to delete comment & mobile improvements

---

app/routes/events/components/EventList.js
app/routes/overview/components/ArticleItem.js
app/routes/overview/components/EventItem.js
app/routes/overview/components/Overview.js
app/utils/eventStatus.js

- Move section headers into the `if` checks for the overview, so the header don't appear with no content.
- Create new `eventStatus` util and use it to display event info

Use event status type

---

app/routes/users/components/UserProfile.js

fixes https://github.com/webkom/lego/issues/1360

Remove duplicates of badges on profile

---

README.md

https://david-dm.org/webkom/lego-webapp

Show dependency badge

---

app/routes/events/components/StripeElement.js

Use norwegian locale on payment button

---

.drone.yml

These changes seem to eliminate the issue where chromium crashes in drone. There are still some other issues with the editor tests which I am looking into. One test also had elasticsearch not respond. 
This branch had 8/8 runs in a row where chromium didn't crash, so it seems to fix that issue.
https://github.com/cypress-io/cypress/issues/350
https://github.com/cypress-io/cypress-docker-images/issues/87

Drone kubernetes limits and shm volume mount for cypress

---

README.md

Add DevDependecy status

---

app/actions/FileActions.js
app/actions/GalleryPictureActions.js
app/actions/callAPI.js
package.json
yarn.lock

Make gallery upload 3 files concurrently (not pooled), and add a sweet `3min` timeout on the file upload. Uploading large jpegs (10M+) takes quite some time on slow connections.

Fix all the image things 🤷 ⛑

---

app/actions/EventActions.js
app/reducers/events.js
app/utils/websockets.js

Solves https://github.com/webkom/lego/issues/1482 🎉

Fix follow/unfollow event on register/unregister bug

---

app/components/Search/SearchPage.js
app/components/Search/index.js
app/reducers/pages.js
app/reducers/search.js
app/routes/pages/components/PageEditor.js
app/routes/search/SearchRoute.js
app/utils/helmet.js

THis fixes https://github.com/webkom/lego/issues/1406

Search stuff

---

app/routes/quotes/QuotesRoute.js

Fixes an issue where you could not delete a comment on the quote list route.

Fix deleting comments on quotes list route

---

.drone.yml
app/components/Header/index.js
cypress/integration/router_spec.js
cypress/support/utils.js

This will press all links in the navbar, and then press something within
the page they land on. This will also press on the extended menu and
check every(none admin) page.

E2E tests for basic routing around the webapp

---

.drone.yml
app/routes/podcasts/components/PodcastList.js

Cypress has put us on the open source plan, so we can use their test recording service again.

Re-enable cypress recordings

---

app/routes/events/components/Admin.js

Clicking enter submits the form. No good :tm:

Remove unnecessary form tag

---

app/routes/app/AppRoute.js
app/routes/company/CompaniesRoute.js
app/routes/company/CompanyDetailRoute.js
app/routes/events/EventAbacardRoute.js
app/routes/events/EventEditRoute.js
app/routes/interestgroups/InterestGroupDetailRoute.js
app/routes/interestgroups/InterestGroupEditRoute.js
app/routes/interestgroups/InterestGroupListRoute.js
app/routes/joblistings/JoblistingDetailedRoute.js
app/routes/joblistings/JoblistingEditRoute.js
app/routes/joblistings/JoblistingRoute.js
app/routes/meetings/MeetingEditRoute.js
app/routes/meetings/MeetingListRoute.js
app/routes/pages/PageListRoute.js
app/routes/quotes/QuotesRoute.js
app/routes/timeline/TimelineRoute.js
app/routes/userValidator/ValidatorRoute.js
app/routes/users/StudentConfirmationRoute.js
app/routes/users/UserConfirmationRoute.js
app/routes/users/UserSettingsNotificationsRoute.js
app/routes/users/UserSettingsOAuth2EditRoute.js
app/routes/users/UserSettingsOAuth2Route.js
app/routes/users/UserSettingsRoute.js
app/utils/configureStore.js
app/utils/prepare.js
server/render.js

Stop using dispatched as it isn't supported with the new `react-redux` connector. :smile:

Stop using dispatched

---

app/actions/AnnouncementsActions.js
app/actions/ArticleActions.js
app/actions/CompanyInterestActions.js
app/actions/GalleryActions.js
app/actions/InterestGroupActions.js
app/actions/MeetingActions.js
app/actions/OAuth2Actions.js
app/actions/PodcastAction.js
app/actions/PollActions.js
app/actions/QuoteActions.js
app/actions/SurveySubmissionActions.js
app/reducers/announcements.js
app/reducers/articles.js
app/reducers/companies.js
app/reducers/companyInterest.js
app/reducers/galleryPictures.js
app/reducers/joblistings.js
app/reducers/memberships.js
app/reducers/oauth2.js
app/reducers/penalties.js
app/reducers/podcasts.js
app/reducers/polls.js
app/reducers/quotes.js
app/utils/__tests__/createEntityReducer.spec.js
app/utils/createEntityReducer.js

- Rewrite all reducers/actions to use "delete" from `CER`
- Fix pagination bug in CER
- Write some more tests
- Rename `updateEntities` to `createAndUpdateEntities`

More reducer refactoring

---

app/routes/bdb/BdbDetailRoute.js
app/routes/bdb/components/BdbDetail.js

bdb detail Currenty Gives 404 error when fetching events for company. This adds pagination to fix this.

Add pagination to bdb detail events

---

app/models.js
app/reducers/events.js
app/routes/events/components/EventAdministrate/Administrate.css
app/routes/events/components/EventAdministrate/RegistrationTables.js
app/utils/constants.js
package.json

**WAIT FOR MERGE!** Wait for https://github.com/webkom/lego/pull/1608 to be merged.
Display the user that admin registered an attendee to an event (see `webkom`):
Also adds a sneaky icon if both user and admin is in the `Webkom` AbakusGroup :smirk::

Add admin registration user for events, and a sneaky icon :)

---

app/reducers/companyInterest.js
app/routes/companyInterest/components/CompanyInterestPage.js

This has been fully agreed on by both sides.

Remove option

---

app/routes/users/components/UserProfile.js

Fixes https://github.com/webkom/lego/issues/1595
Me:
Not me:

Only show previous events for your user

---

app/routes/admin/email/components/RestrictedMails.js

Temporary out of order. Will need some infra work to get it working again.
Run `git revert 3c62601556b309db1cda58cf908c31df4e6d02ab` when this is good to go again.

Add note about restricted mail doesn't work

---

app/routes/events/EventCreateRoute.js

Reverts webkom/lego-webapp#1584

Revert "Change unregistration deadline to 24 hours before event"

---

app/actions/PollActions.js

Fixes https://github.com/webkom/lego/issues/1546 (hopefully)

Fix poll fetch

---

app/components/Search/SearchPage.js
app/components/Search/withAutocomplete.js
app/routes/events/EventAbacardRoute.js
app/routes/events/components/EventAdministrate/Abacard.js

Fixes the letters disappearing when searching, both the main search and abacard.

Debouce on leading edge on search

---

app/actions/SurveyActions.js
app/routes/surveys/AddSubmissionRoute.js
app/routes/surveys/EditSurveyRoute.js
app/routes/surveys/SubmissionsRoute.js
app/routes/surveys/SurveyDetailRoute.js
app/routes/surveys/components/AdminSideBar.js
app/routes/surveys/components/Submissions/SubmissionPage.js
app/routes/surveys/utils.js

I could not get this to work with a simple <a> tag as the endpoint requires an auth token in the header, so you have to first click a button to make the request with the header and get a blob, and then press a link to actually save the file. It should work just fine, but let me know if you have a better solution.

Add button to download survey as csv

---

app/routes/overview/components/CompactEvents.js

Fixes https://github.com/webkom/lego/issues/1662

Include alternative presentations in compact events

---

app/components/HeaderNotifications/HeaderNotifications.css

Fix text overflow in notifications

---

.drone.yml

Re-enable cypress

---

app/reducers/companies.js
app/routes/company/components/CompaniesPage.css
app/routes/company/components/CompaniesPage.js
app/routes/company/components/Company.css
app/routes/company/components/CompanyDetail.js

Redo the cards on the company list page and add features and changes as requested by Bedkom.

Redesign company list page and add requested features to company detail

---

app/components/Editor/Blocks/ImageBlock.js
app/components/ErrorBoundary/index.js
app/components/Gallery/index.js
app/components/GroupMember/index.js
app/components/Header/index.js
app/components/Image/CircularPicture.js
app/components/Image/ProfilePicture.js
app/components/PhotoUploadStatus/index.js
app/components/ProgressiveImage/index.js
app/components/Reactions/ReactionPicker.js
app/components/Search/SearchPageResults.js
app/components/Upload/ImageUpload.js
app/routes/brand/components/BrandPage.js
app/routes/companyInterest/components/CompanyInterestPage.js
app/routes/overview/components/PublicFrontpage.css
app/routes/overview/components/PublicFrontpage.js
app/routes/pages/components/LandingPage.js
app/routes/pages/components/PageDetail.js
app/routes/pages/components/subcomponents/EmailItem/index.js
app/routes/photos/components/GalleryPictureEditModal.js
app/routes/photos/components/GalleryPictureModal.js

- Switched (almost) every `<img />` to our `<Image />` component
- Closes https://github.com/webkom/lego/issues/1641 , now you need a 155px screen before you get SKVIIIIS

Use the Image component

---

app/components/Reactions/index.css
app/reducers/quotes.js
app/routes/articles/components/ArticleDetail.css
app/routes/articles/components/ArticleDetail.js
app/routes/quotes/QuoteDetailRoute.js
app/routes/quotes/QuotesRoute.js
app/routes/quotes/components/Quote.js
app/routes/quotes/components/QuoteList.js
app/routes/quotes/components/QuotePage.js
app/routes/quotes/components/Quotes.css
app/routes/quotes/components/__tests__/AddQuote.spec.js
app/routes/quotes/components/__tests__/SingleQuote.spec.js
app/routes/quotes/components/__tests__/fixtures/quotes.js

Reverts webkom/lego-webapp#1622

Revert "Add Reactions to Quotes"

---

app/routes/admin/email/EmailListRoute.js
app/routes/admin/email/EmailListsRoute.js
app/routes/admin/email/components/EmailListEditor.js
app/routes/admin/email/components/EmailLists.js
app/utils/validation.js

Make it possible to add emails for people outside of abakus to email lists manually

Add possibility for additional email fields in email lists

---

app/styles/globals.css

Should have been done years ago 🙃

Wrap Links

---

app/routes/bdb/components/BdbDetail.js
app/routes/bdb/components/bdb.css

Fix css styling in bdb company description, and red x.

---

cypress/integration/create_event_spec.js

Select 15th of next month instead of tomorrow as date

Fix bug in datepicker integration test

---

app/routes/pages/components/subcomponents/EmailItem/EmailItem.css

- Make the images always square
- Reduce padding to fit 3 elements per row

Fix about-abakus visual bug

---

app/routes/joblistings/components/JoblistingEditor.js
app/routes/overview/components/Pinned.js
cypress/integration/home_page_spec.js
cypress/integration/joblistings_specs.js

Have to make tests for browsing joblistings also

tests on frontpage and joblistings

---

app/components/ErrorBoundary/index.js

Update sentry notice

---

package.json
yarn.lock

Add resolution for set-value in order to force dependencies to use correct version as sub-dependency

Add resolution for set-value

---

yarn.lock

Upgrade some dependencies

---

app/components/EventItem/index.js

Changed event starting time message to 'startet' if they have already started

---

app/utils/eventStatus.js

Display already admitted on events

---

app/index.js

Add crucial important critical console information

---

app/reducers/companies.js
app/routes/company/CompaniesRoute.js

Solves https://github.com/webkom/lego/issues/1702. Merge https://github.com/webkom/lego/pull/1701 first.

Only show active /companies

---

cypress/integration/home_page_spec.js
cypress/integration/poll_spec.js

Update tests to match new fixtures introduced by: https://github.com/webkom/lego/pull/1681
https://dashboard.cypress.io/#/projects/niikbo/runs/447/failures

Update cypress tests

---

app/routes/surveys/AddSurveyRoute.js
app/routes/surveys/EditSurveyRoute.js
app/routes/surveys/components/SurveyEditor/SurveyEditor.js
app/routes/surveys/components/surveys.css

Add template name to inform what template you are using.

Add template name for surveys

---

app/routes/bdb/components/BdbDetail.js
app/routes/bdb/components/bdb.css

Related to: https://github.com/webkom/lego/issues/1388

Add link to event-survey from bdb-page

---

app/utils/helmet.js

This fixes https://github.com/webkom/lego/issues/1720

Fix helment null ptr exception

---

app/routes/events/components/EventList.js

This is causing annoying flashes

Fix bad react-key usage

---

app/routes/events/EventDetailRoute.js

Fix bug with isuserfollowing causing error when going directly to an event

Dispatch isUserFollowing after fetchEvent is completed

---

app/routes/overview/components/ArticleItem.js
app/routes/overview/components/Pinned.js

fixed issue from: https://github.com/webkom/lego/issues/1683

Changed paragraph to div to fix error

---

app/routes/photos/components/GalleryPictureEditModal.js

Solves https://github.com/webkom/lego/issues/1691 
Before:
After:

Fix broken tooltip when editing picture

---

app/routes/events/components/EventEditor/index.js

Displays an error message when users tries to set start time after end time in events.

Fixed start-end time issue

---

package.json
yarn.lock

Remove is-hotkey

---

app/reducers/groups.js

closes https://github.com/webkom/lego/issues/1692

Fix memberships-group-reducer

---

server/ssr.js

Just got rekt by react-redux using react context
Someone pls fix the types.
Just verify that it works, but not ask why, how and for how long. :man_shrugging:

Fix react-redux Provider in SSR for `redux-bumps`

---

app/routes/photos/components/GalleryPictureModal.css

Remove annoying blinking when browsing gallery pictures

Add min height to gallery pictures

---

app/routes/admin/groups/components/GroupPermissions.js
app/routes/users/components/UserProfile.js

Show permissions for groups and users

---

app/actions/GroupActions.js
app/reducers/memberships.js
app/reducers/pages.js
app/routes/admin/groups/components/GroupMembers.js
app/routes/admin/groups/components/GroupMembersList.js
app/routes/admin/groups/components/GroupPage.js
app/routes/admin/groups/components/__tests__/GroupTree.spec.js
app/routes/pages/PageDetailRoute.js
app/routes/users/components/UserProfile.js

Add support for implicit-members in admin panel

---

app/routes/admin/groups/components/GroupPermissions.js
app/routes/users/components/UserProfile.js

Only show the subset of perms that matters, since wider permissions
implicitly include all the stricter ones.
This is only done for the sum in order to avoid ambiguity.

Reduce perms when summing for all groups

---

app/actions/SurveyActions.js
app/reducers/surveys.js
app/routes/surveys/SubmissionsRoute.js
app/routes/surveys/components/Submissions/Results.js
app/routes/surveys/components/Submissions/SubmissionPublicResults.js
app/routes/surveys/components/Submissions/SubmissionSummary.js
app/routes/surveys/components/SurveyEditor/Question.js
app/routes/surveys/components/SurveyEditor/SurveyEditor.js
app/routes/surveys/components/surveys.css
app/routes/surveys/utils.js
package.json
yarn.lock

Example pie-chart:
Added dropdown-menu:
Example bar-chart:
Mobile version:

Add ability to change graph type for results in  surveys

---

app/actions/UserActions.js
app/components/Upload/ImageUpload.js
app/routes/users/UserSettingsRoute.js
app/routes/users/components/RemovePicture.css
app/routes/users/components/RemovePicture.js
app/routes/users/components/UserProfile.js
app/routes/users/components/UserSettings.js

Needed for issue: https://github.com/webkom/lego/issues/1801
Backend: https://github.com/webkom/lego/pull/1807

Add buttons to remove profile picture

---

app/routes/joblistings/components/JoblistingRightNav.js

Everything is fully implemented, both backend and frontend support the "annet" tag, only the filtering did not support it
Solves https://github.com/webkom/lego/issues/1784

Could not filter on other

---

app/utils/themeUtils.js

Fix sentry error

---

package.json
server/index.js
yarn.lock

This hopefully fixes the issue where sentry fails when finding source files for issues created on the server.﻿

Hopefully fix server-side source-maps on sentry

---

app/routes/surveys/components/SurveyEditor/Question.js
app/routes/surveys/components/SurveyEditor/SurveyEditor.js
app/routes/surveys/components/surveys.css

Add button to reorder questions in surveys.

Add reordering of questions in surveys

---

app/routes/articles/components/Overview.js
app/routes/bdb/BdbRoute.js
app/routes/quotes/QuoteDetailRoute.js
app/routes/surveys/AddSurveyRoute.js
app/routes/surveys/EditSurveyRoute.js
app/routes/surveys/components/SurveyEditor/Question.js
app/routes/surveys/components/SurveyEditor/SurveyEditor.js
app/routes/surveys/index.js

Change some of the old react router v3 code that slipped through the cracks. Should fix this [issue](https://github.com/webkom/lego/issues/1853)

Remove all instances of location.query and fix some other bugs

---

app/routes/photos/components/Overview.css
package.json
yarn.lock

https://github.com/nkbt/react-collapse#migrating-from-v4-to-v5

Upgrade react-collapse v4 to v5

---

app/routes/events/EventDetailRoute.js
app/routes/events/components/Event.css
app/routes/events/components/EventDetail/index.js
app/routes/events/components/JoinEventForm.js
app/routes/events/utils.js

Fix https://github.com/webkom/lego/issues/1420

Add explenation for registrationdeadline when user has penalty

---

app/routes/admin/groups/components/AddGroupMember.js
app/routes/admin/groups/components/GroupMembers.js
app/routes/admin/groups/components/GroupMembersList.js

Fix a bug preventing new users to be added to groups in the frontend

Fix adding members to groups

---

app/actions/GalleryPictureActions.js
app/routes/photos/GalleryPictureRoute.js

Actually fix going directly to a picture without going via the gallery, as well as improve 404 handling on pictures

Fix picture direct access bug again

---

app/routes/bdb/components/BdbDetail.js

Make the latest contact appear first

---

app/routes/companyInterest/index.js
app/routes/index.js

This will fix issue where events, semesters and others disappear when
changing lang. This also persists the form values when lang is changed.

Fix company interest form lang switcher

---

app/components/Search/utils.js
app/reducers/__tests__/allowed.spec.js
app/reducers/allowed.js

Also add polls to initial state.

Correct galleries permission mapping

---

app/routes/events/components/StripeElement.js

I was sure stripe worked with SSR before, but apparantly not :upside_down_face: 
This fixes the new stripe elements that was just merged, as stripe is not loaded when you server-side render the payment form.

Stripe SSR fix

---

app/components/Banner/Banner.css
app/components/Banner/index.js
app/routes/events/components/EventEditor/index.js
app/routes/overview/components/Overview.js

Add OpptakBanner

---

app/routes/events/components/EventEditor/index.js

Fix an issue where the mergeTime could be before the pool activation time

---

server/pageRenderer.js

Remove Segment

---

.drone.yml
README.md

Add ssh key to ansible

---

app/components/Form/DatePicker.css
app/components/Form/DatePicker.js
app/components/Form/TimePicker.css
app/components/Form/TimePicker.js

Solves https://github.com/webkom/lego/issues/1919

Fix date picker arrows in dark mode

---

app/components/Banner/Banner.css
app/components/Banner/index.js
app/routes/overview/components/Overview.js
app/styles/variables.css

Endret farge ref diskusjon på Abakus Media-Slack

Change color of abakusrevy-banner

---

package.json
yarn.lock

Bump style lint config to version 20.0.0, and add exception for the composes keyword used by CSS-loader.

Bump stylelint-config

---

app/components/PhotoUploadStatus/index.js
package.json
yarn.lock

Bump **ESLint** and remove _addUploadStatusCard_ (Unused component, producing lint errors)

Bump ESLint

---

app/routes/pages/PageEditRoute.js
app/routes/pages/components/PageEditor.js

Fixes https://github.com/webkom/lego/issues/1727
Related to https://github.com/webkom/lego/pull/1931

Add objectpermissons to pages form

---

app/routes/interestgroups/InterestGroupDetailRoute.js

Interestgroup did not refetch when navigating from one interestgroup to another

fix refetcherror in interestgroup

---

app/components/Header/Header.css
app/components/Header/index.js
app/routes/app/AppRoute.js

Add shortcut to most recent meeting in header bar

---

app/routes/joblistings/JoblistingRoute.js
app/routes/joblistings/components/JoblistingDetail.js
app/routes/joblistings/components/JoblistingRightNav.js

Should we use `createdAt` as default instead of the current `deadline`?

Add support for filtering on date published

---

app/routes/overview/components/Overview.css

**Problem with overflow next to tags:**
**Fixed:**

Fix overflow issue

---

app/components/LegoReactions/index.js
app/components/RandomQuote/RandomQuote.js
app/components/Reactions/Reaction.css
app/components/Reactions/Reaction.js
app/components/Reactions/index.js
app/routes/articles/components/ArticleDetail.js
app/routes/quotes/components/Quote.js

Closes webkom/lego#1861
Passes down loggedIn to Reaction component and disable clicking if not logged in.

Disable reaction buttons when not logged in

---

app/routes/joblistings/components/JoblistingDetail.js
app/routes/overview/components/Overview.css

Individual title on job listings

---

app/routes/interestgroups/components/InterestGroupList.js

Sorts ÆØÅ incorrectly :upside_down_face:

Sort interest groups in alphabetical order

---

app/components/Footer/Footer.css
app/components/Footer/index.js

Add copyright and link to cookie article

Add cookie link to footer.

---

app/routes/companyInterest/components/CompanyInterestPage.js

Hide bedex checkbox in form as requested by bedkom

hide bedex as option

---

app/routes/overview/components/PublicFrontpage.css
app/routes/overview/components/PublicFrontpage.js

Closes webkom/lego#1496
chrome:
mobile:

Facebook fix

---

app/routes/companyInterest/components/CompanyInterestPage.js

Reverts webkom/lego-webapp#1986

Revert "hide bedex as option"

---

.drone.yml
server/server.js

Add simple config endpoint

---

.drone.yml
Dockerfile

Seems to be no issues :shipit:

Bump node to v14-alpine

---

app/actions/EventActions.js
app/actions/callAPI.js
app/models.js
app/reducers/__tests__/events.spec.js
app/reducers/events.js
app/reducers/followers.js
app/reducers/index.js
app/routes/events/EventDetailRoute.js
app/routes/events/components/EventDetail/index.js
app/utils/createEntityReducer.js

With fancy optimistic loading, since it looks shitty without it...

Add proper following support

---

Dockerfile

Appanently healthchecks run inside the container using curl :upside_down_face:

Add curl to dockerimage

---

app/routes/events/components/EventList.css
app/routes/events/components/EventList.js

Filter events in list view based on event type

---

app/routes/events/components/EventDetail/index.js

fixes: https://sentry.io/organizations/abakus/issues/1568744031/events/a6e45a7445754805b9c0de73bf8e9ddc/?project=5018548&query=is%3Aunresolved

Don't allow fav stuff when unauthed

---

app/components/Content/Content.js
app/components/Feed/renders/event_register.js
app/components/Reactions/ReactionPickerContent.js
app/components/Time/Time.spec.js
app/routes/admin/email/components/EmailLists.js
app/routes/admin/email/components/EmailRoute.js
app/routes/admin/email/components/EmailUsers.js
app/routes/companyInterest/components/CompanyInterestList.js
app/routes/companyInterest/components/CompanyInterestPage.js
app/routes/events/components/EventList.js
app/routes/events/components/JoinEventForm.js
app/routes/events/components/StripeElement.js
app/routes/interestgroups/components/InterestGroupCreate.js
app/routes/joblistings/components/JoblistingRightNav.js
app/routes/overview/components/CompactEvents.js
app/routes/overview/components/Overview.js
app/routes/overview/components/PublicFrontpage.js
app/routes/photos/components/GalleryDetail.js
app/routes/photos/components/GalleryEditor.js
app/routes/users/components/UserProfile.js

sed -ri  "s/=\{'([^']*)'\}/=\"\1\"/g" {app,config,lib,server,testing}/**/*.js

Set string all component attrs to normal strings

---

app/components/Gallery/index.js
app/routes/photos/components/GalleryEditor.js
app/routes/photos/components/GalleryEditorActions.js
app/routes/photos/components/Overview.css

fixes https://github.com/webkom/lego/issues/1528

improve galleryeditor

---

app/routes/company/CompanyDetailRoute.js
app/routes/company/components/Company.css
app/routes/company/components/CompanyDetail.js
app/routes/overview/components/EventItem.css
app/routes/overview/components/EventItem.js
app/routes/overview/components/Overview.js
app/routes/overview/components/utils.js
app/utils/eventStatus.js

Change the layout for company events: ![image](https://user-images.githubusercontent.com/43182013/93390442-fabc7580-f86d-11ea-845c-86f68522b018.png)
so that they look like events on frontpage:

Use same event template on company page and frontpage

---

app/routes/users/UserProfileRoute.js
app/routes/users/components/UserProfile.js

**Before (notice the "feed"):**
**After:**

Comment out feed from user profile

---

config/webpack.server.js
package.json
yarn.lock

Had some issues last time around. I Assume it was just Cypress being a jerk...

Bump webpack-node-externals | Second attempt

---

app/routes/events/components/EventList.css
app/routes/events/components/EventList.js

Make it possible to toggle checkbox when clicking on label

---

app/actions/TagActions.js
app/actions/callAPI.js
app/reducers/__tests__/fetchHistory.spec.js
app/reducers/fetchHistory.js
app/utils/__tests__/getCachedRequest.spec.js
app/utils/getCachedRequest.js
yarn.lock

Add some more checks to verify fetchHistory works as expected

---

app/components/Header/FancyNodesCanvas.js
app/components/Header/drawFancyNodes.js

Add movement to gray nodes in background
Light theme
https://user-images.githubusercontent.com/42469466/103674506-21b6c880-4f7f-11eb-9361-189b0ca609f4.mp4
Dark theme
https://user-images.githubusercontent.com/42469466/103674538-28ddd680-4f7f-11eb-9621-1702febfed85.mp4
Reloading page, resizing and mobile
https://user-images.githubusercontent.com/42469466/103674673-5165d080-4f7f-11eb-878a-cdf1e14c85b7.mp4

add movement to background nodes

---

app/components/Form/EditorField.js
cypress/integration/create_event_spec.js
cypress/integration/event_editor_spec.js
package.json
yarn.lock

Bump lego-editor to v1.3.2.
resolves https://github.com/webkom/lego/issues/2005

Bump lego-editor to v1.3.2

---

app/components/Form/Captcha.js

Fix invalid captcha import caused by #2088.

ReCaptcha Hotfix

---

app/components/Header/FancyNodesCanvas.js
app/components/Header/drawFancyNodes.js

Reverts webkom/lego-webapp#2085
Animation led to poor performance on phones and older computers.

Revert "add movement to background nodes"

---

app/routes/users/UserProfileRoute.js
app/routes/users/components/UserProfile.js

Add support for showing email lists

---

app/routes/admin/email/components/RestrictedMails.js

This reverts commit 3c62601556b309db1cda58cf908c31df4e6d02ab.
Depends on https://github.com/webkom/lego/pull/2058

Revert "Add note about restricted mail doesn't work"

---

.drone.yml

To not break the slack step in ansible

Change deploy user env to SLACK_USER

---

app/components/Form/RadioButton.css

Fixes https://github.com/webkom/lego/issues/1483 (hopefully)

Fix radio buttons again

---

config/webpack.client.js

Fixes: https://github.com/webkom/lego/issues/2124

Fix Buffer polyfill

---

.drone.yml

Add concurrency limit to drone pipeline

---

app/routes/users/components/ChangePassword.js
app/routes/users/components/RemovePicture.js
app/routes/users/components/UserSettings.js
cypress/integration/password_change_spec.js
cypress/integration/profile_spec.js
cypress/support/utils.js

Change language and casing on user settings

---

app/components/Tags/Tag.css
app/routes/joblistings/components/JoblistingList.js
cypress/support/index.js

:) takk for meg klem fra gruppeansvarlig Media ❤️

Made tag for new job listing

---

app/routes/overview/components/Overview.js
app/routes/overview/components/PublicFrontpage.js

Update link FP info page,
due to FP cancellation 😞

Update link to FP page

---

app/components/Banner/Banner.css
app/components/Banner/index.js
app/routes/overview/components/Overview.js

Switch to itdagene banner

---

app/routes/overview/components/Overview.js

itDAGENE is over, so there's no need for the banner anymore

remove itdagene banner

---

app/routes/events/components/JoinEventForm.js

This makes the "we are processing your registration" box only pop up if
the regisitration takes longer than 2 seconds AND shows it for at least 2
seconds. Similarly for the stripe success message, it will be shown for
at least 2 seconds. This makes it possible for the user to actually read
the contents of the messages.
Solves https://github.com/webkom/lego/issues/2319

Show event registration and stripe popups for at least 2 seconds

---

app/assets/manifest.json

big important change

---

app/routes/surveys/components/SurveyEditor/SurveyEditor.js

Apparently, a **minor**, yet destructive, bug was recently introduced, by someone, now if only there was a way to find out by who ... Anyhow, this PR should fix things 😃

Fix a bug someone made

---

server/pageRenderer.js

This fixes an issue where, most of the time, hydration would fail, and
the entire app would re-render on the client. This was caused by an
incorrect order of calls to the loadable chunk extractor when rendering
the page on the server.

Fix an issue where hydration failed

---

app/components/Poll/Poll.css
app/components/Poll/index.js
app/routes/overview/components/Overview.js
app/routes/polls/components/PollDetail.js

Fixed the issues from #2193 and added some styling fixes, which are included here.

Show hidden poll results

---

package.json
yarn.lock

Tree shaking and minimizer in webpack removed these imports from the build

Add all static files as side effects

---

app/utils/configureStore.js

Nothing to see here

---

app/components/RandomQuote/RandomQuote.js
app/routes/quotes/QuoteEditorRoute.js
app/routes/quotes/components/AddQuote.js
app/routes/quotes/components/Quotes.css

This is the most useless feature ever, but people keep creating quotes "wrong". This will show them how their quote will look

Add qoute preview

---

app/routes/overview/components/NextEvent.js

Recent regression with redo of <Image> component. This is just an svg,
and doesn't need the logic from that component.

Fix css for alarm icon on frontpage

---

app/components/Modal/Modal.css

Solves: https://github.com/webkom/lego/issues/2526
before
after

Increase modal z-index due to mazemap z-index

---

app/routes/companyInterest/components/CompanyInterestPage.js
app/routes/companyInterest/utils.js

Bedkom wanted a few updates in the company interest form for this spring, so i implemented them in this PR

Update company interest form

---

app/components/UserAttendance/AttendanceStatus.js
app/models.js
app/routes/events/components/EventDetail/index.js

Before user (webkom) deletion: 
After user (webkom) deletion:

Add anonymous attendance for deleted users

---

app/components/Reactions/assets/AddReactionEmoji.js
app/routes/articles/components/ArticleEditor.js
app/routes/overview/components/ArticleItem.css
app/routes/overview/components/ArticleItem.js
app/routes/overview/components/CompactEvents.css
app/routes/overview/components/NextEvent.css
app/routes/overview/components/Pinned.css
app/routes/overview/components/utils.js

There have always been small CSS things that bug me every day. This fixes some of them.
I know the new frontpage will eventually fix this, but I just need something temp

General small style changes

---

app/routes/overview/components/ArticleItem.css

Not sure how this was merged in?

Stylelint hotfix

---

app/components/Search/Search.css

Remove double search icon on ios

---

app/components/UserAttendance/AttendanceStatus.js

Don't show "0" character when legacyRegistrationCount is 0

---

app/components/GroupMember/GroupMember.css
app/components/GroupMember/index.js
app/routes/interestgroups/components/InterestGroupMemberList.js
app/routes/pages/components/PageDetail.css
app/routes/pages/components/PageDetail.js

Fix disappearance of co-leader from committee page

---

app/components/Button/Button.css

The current button design is quite poor. It needs more difference between the disabled and clickable button. (Especially in dark mode) Therefore, I suggest making the following changes.
Feel free to suggest changes to the colours / shadows etc! 🧑‍🎨

Improve button class design

---

app/routes/pages/components/LandingPage.js
app/routes/pages/components/subcomponents/EmailItem/EmailItem.css
app/routes/pages/components/subcomponents/TextWithTitle/TextWithTitle.css

Update flex-basis calc() to include mandatory unit in the first part of
the calculation
From:  
To:

Add bankkom to committee contact overview + fix flex-basis

---

app/routes/admin/groups/components/AddGroupMember.js

Fix another bug introduced by bumping react select.

Fix bug in select field for group members

---

app/routes/photos/components/GalleryPictureModal.js
package.json
yarn.lock

Bump react-swipeable to v6.2.1 and fix swiping in the process.
Closes: #2574

Fix swiping

---

package.json
yarn.lock

* This is a dependency of react-router-dom, and is not supposed to be
added as a direct dependency.
* Remove styleguide command as this does not exist anymore

Remove react-router direct dependency

---

package.json

Revert "Add bullshit"

---

app/components/Search/utils.js
cypress/integration/router_spec.js

It's broken, and has been for ages... :/

Remove podcasts from main menu

---

app/routes/events/EventDetailRoute.js

Fixes; https://github.com/webkom/lego/issues/2694
```
$ git blame
Author: Odin Ugedal <odin@ugedal.com>
```

Fix event following on events without registation access

---

.github/workflows/auto-merge.yml

Bugged me that it ran on all PRs, and looked weird on slack

Only run action on dependabot PRs

---

app/routes/overview/components/ArticleItem.css
app/routes/overview/components/utils.js

Don't git blame plz. Fix the shitty frontend css

When you finally the bastard who have ruined your life

---

server/pageRenderer.js

This ensures that the correct theme is applied _before_ the SSR content is show to the user. That removes the blinking for users using the auto theme and are using dark mode.
https://user-images.githubusercontent.com/1467188/166219820-aab09c44-d834-4803-bc3b-74285f9e808d.mp4
PS: This also adds 'auto' as the selected theme for unauthenticated users.

Fix dark mode detection on SSR to avoid blinking 

---

app/components/Upload/ImageUpload.js
app/components/Upload/UploadImage.css

Slight miscommunication, so this is kinda duplicate of @erlingfn PR. But this also adds a nice small
preview of the images next to the filename so that it's easier to see what is selected and what you
want to delete before uploading.

BETTER fix bug with multiple image upload

---

app/components/Upload/ImageUpload.js

I found some more bugs in the ImageUpload component :upside_down_face:

Fix bad index in ImagePreview in ImageUpload

---

app/routes/events/EventDetailRoute.js

- Fix a bug where event detail could crash

event followers fix

---

app/routes/pages/components/LandingPage.js

La bare til link for den nye instagrammen, ikke noe mer

Added @abakusbedrift to "Info om Abakus"

---

app/components/Upload/ImageUpload.js
app/components/Upload/UploadImage.css

Fix overflow bug on ImageUpload

---

package.json
yarn.lock

In theory no API-changes and seems to work well

Bump react-redux from version 6 to version 8

---

app/components/Banner/index.js
app/routes/overview/components/Overview.js
app/routes/overview/components/PublicFrontpage.js

- Add prop destructuring
- Add fadderperioden banners to public and internal frontpage

fadderperioden 2022

---

app/routes/overview/components/PublicFrontpage.js

Forgot to update the banner on the public front page in #2864 ...

Update banner color on public front page

---

package.json
yarn.lock

This should fix the SSR issues we have seen.

Bump lego-editor from 2.0.2 to 2.0.3

---

app/routes/events/components/Admin.js
app/routes/events/components/EventDetail/index.js
cypress/e2e/event_visit_spec.js

Change allergy/preferences link to go directly to the users' settings
Preview when logged in
Preview when not logged in

Relocate event rules and allergy/preferences link

---

app/routes/events/components/EventAdministrate/RegistrationTables.js
app/routes/events/components/EventDetail/index.js
app/routes/events/components/EventEditor/index.js
app/routes/events/components/UpdateAllergies.js
app/routes/users/components/UserConfirmation.js
app/routes/users/components/UserSettings.js

Renamed with the purpose of making it more intuitive exactly what info we are requesting to prevent storing more sensitive info than we use.

Rename allergies to 'matellergier/preferanser'

---

app/components/Comments/Comment.js
app/components/Comments/__tests__/Comment.spec.js

Change the name that shows on comments to full name :)

change showing usernames to fullnames on comments

---

app/routes/overview/components/Overview.js
app/routes/overview/components/PublicFrontpage.js

fix banner typo

---

app/actions/EventActions.js
app/actions/UserActions.js
app/models.js
app/reducers/users.js
app/routes/events/EventAbacardRoute.js
app/routes/events/components/Event.css
app/routes/events/components/EventAdministrate/Abacard.js
app/routes/events/components/EventAdministrate/Administrate.css
app/routes/events/components/EventAdministrate/AttendeeElements.js
app/routes/events/components/EventAdministrate/RegistrationTables.js
app/routes/events/components/EventDetail/index.js
app/routes/events/components/JoinEventForm.js
app/routes/events/components/RegistrationMeta.js
app/routes/events/utils.js
app/routes/users/UserProfileRoute.js
app/routes/users/components/PhotoConsents.css
app/routes/users/components/PhotoConsents.js
app/routes/users/components/UserProfile.js

Adds improved photo consents to lego.
Depends on [#1979](webkom/lego/pull1979)

Improved Photo Consents

---

app/routes/events/components/EventDetail/index.js
app/routes/events/components/RegistrationMeta.js
app/routes/users/components/PhotoConsents.css
app/routes/users/components/PhotoConsents.js

Disable when the option is already selected, and remove the border when
selected.
Also fix some event link issues.

Make the PhotoConsent buttons more legible

---

app/routes/events/components/EventAdministrate/RegistrationTables.js

Photoconsents are now on the registration and not under the user

Change administrate page to use new API

---

app/routes/overview/components/Overview.js
app/routes/overview/components/PublicFrontpage.js

Not needed right now, but merge this when the time comes

Update front page banner to Abakusrevyen admissions

---

app/components/Header/Header.css

Not a very invasive change although I believe it contributes a lot to both the look and feel of the webpage. The animations feel smoother (expands only on the x-axis and not upwards) and the border is not rounded (why would that make sense?). Screenshots are provided under. I've also changed the colour of the navigator which is more controversial 😬.

Give indicator styling a more modern look

---

app/components/Feed/activity.js
app/components/Poll/index.js
package.json
yarn.lock

Linkify and truncate links in announcements

---

app/routes/overview/components/Overview.js
app/routes/overview/components/PublicFrontpage.js

The revy admission application deadline was 2 days ago, so it's time to remove this banner...

Remove revy banner

---

app/routes/surveys/components/SubmissionEditor/SubmissionEditor.js

Add disclaimer about anonymous surveys

---

app/routes/pages/components/LandingPage.js

Replace torsdag with tirsdag on About Abakus

---

app/routes/companyInterest/components/CompanyInterest.css
app/routes/companyInterest/components/CompanyInterestPage.js
app/routes/companyInterest/utils.js

Related to https://github.com/webkom/lego/pull/2980
Additional comments are for breakfast talk and course events.
Also update from for 2023 booking:
- Remove "digital presentation" option
- Remove "BedEx" option
- Add "Revy" collab option

Ask company for additional comments on interest form

---

app/components/NavigationTab/NavigationLink.css

Closes https://github.com/webkom/lego/issues/2895

Stop hovering over links on flatpages shifting the rest of the content downwards

---

app/routes/events/components/EventAdministrate/Attendees.js

Halla Webkom, håper dere koser dere på hyttetur💕 Jeg syns det hadde vært nyttig for arrangører å se hvor mange på arrangementet som har betalt, på samme måte som man kan se hvor mange som er adminpåmeldt/registrert! 
Kos og klem,
Eirik

Added counter for paid attendees

---

app/routes/quotes/QuotesRoute.js
app/routes/quotes/components/QuotePage.js
app/routes/quotes/components/Quotes.css

Added sorting selector for quotes which now enables users to sort after Imojis 🤌

Add sorting selector for quotes

---

app/components/HeaderNotifications/HeaderNotifications.css
app/components/HeaderNotifications/index.js

* Moved the icons to the top of each notification
* Added a separator between each notification
* Decreased line height from 1.8 to 1.5
* Increased the height of the dropdown by 100 pixels
Screenshot:

improved styling of the notification dropdown

---

app/routes/surveys/components/SurveyEditor/SurveyEditor.js

Closes #https://github.com/webkom/lego/issues/2867

Fix title when editing/creating surveys

---

app/components/Form/ObjectPermissions.js

Fix Typo On EditorPage

---

app/routes/company/components/Company.css
app/routes/overview/components/Pinned.css

Changed pinned and company detail to white background. Eik forgot these in #2975

Changed pinned and company detail to white background.

---

app/routes/events/components/JoinEventForm.js

https://ordbokene.no/bm/16889/forskyve

Fix typo in event penalties warning

---

app/routes/users/components/UserProfile.js

Add charity-party 2022 frame winner

---

app/models.js
app/reducers/events.js
app/routes/events/components/EventAdministrate/RegistrationTables.js
app/routes/events/components/EventDetail/index.js
app/routes/events/components/JoinEventForm.js
app/routes/events/components/RegistrationMeta.js
app/routes/events/utils.js

LEGO now passes the required photo consent objects for the user in the
event object.

Check required photo consents from events

---

app/components/Search/SearchPage.js
app/components/Search/SearchPageInput.js
app/components/UserValidator/Validator.css
app/components/UserValidator/index.js
app/routes/events/components/EventAdministrate/Abacard.js
app/routes/users/components/UserProfile.css
app/routes/users/components/UserProfile.js
package.json
yarn.lock

Made it possible to scan QR codes instead of searching for the user's name. The QR code is available on all users profiles, and is just their username encoded.

ABA-19: Add the possibility to scan QR codes instead of searching for users in Abacard

---

app/routes/events/components/EventDetail/index.js

Add an if-check to see if the author of the event is an existing user. If not, author will be set to "Anonym".

Event author set to Anonym

---

app/components/Modal/Modal.css
app/components/UserValidator/Validator.css
app/components/UserValidator/index.js
app/routes/users/components/UserProfile.css
app/routes/users/components/UserProfile.js

* Styling fixes
* Only display the ABA-ID button on your own profile
* Move ABA-ID button down if you have a FRAME
* Eliminate double scans after a successful scan

ABA-110: QR attendance fixes

---

app/routes/events/components/EventList.js
app/routes/overview/components/CompactEvents.js

closes https://github.com/webkom/lego/issues/2890 
closes ABA-95

Changed the "bedpres og kurs" button to have preset filters.

---

app/components/Button/Button.css
app/components/Icon/index.js

Fix icon alignment in buttons

---

app/routes/overview/components/utils.js

Show year on events where year != current year

---

app/components/Header/ToggleTheme.js
app/components/Header/index.js

The theme icon was wrong if you entered the site in darkmode

Theme icon displays sun when first opening site in darkmode

---

app/routes/events/components/EventEditor/EventEditor.css

Closes https://github.com/webkom/lego/issues/3056 and ABA-134

Fix alignment bug on event editor

---

app/routes/interestgroups/components/InterestGroupMemberList.css
app/routes/interestgroups/components/InterestGroupMemberList.tsx
yarn.lock

Closes https://github.com/webkom/lego/issues/2880 
*Bildet er bare broken på min lokale versjon

Improve Styling On Interestgroup Leaders

---

app/components/Button/index.tsx
app/components/Footer/index.tsx
app/components/Header/index.tsx
app/components/HeaderNotifications/index.tsx
app/components/Icon/Icon.css
app/components/Icon/index.tsx
app/components/Image/Image.tsx
app/components/Image/ProfilePicture.tsx
app/components/Layout/Flex.tsx
app/components/Search/index.tsx
app/components/Time/index.tsx
app/globals.d.ts
app/models.ts
app/reducers/users.ts

The notifications badge was behind the notification bell icon, most
likely as a result of the recent ion-icon upgrade. This fixes that so
that it's in front. Also reduces the padding a bit in the badge.

Fix plenty of TS errors & icon badge z-index

---

app/components/Image/ProfilePicture.tsx
app/components/Search/SearchPage.tsx
app/components/Search/SearchPageInput.tsx
app/components/Search/SearchPageResults.tsx
app/components/Search/SearchResults.tsx
app/components/Search/utils.tsx
app/components/Search/withAutocomplete.tsx
app/components/UserAttendance/withModal.tsx
app/models.ts
app/reducers/search.ts
app/routes/events/EventEditRoute.ts
app/routes/events/components/EventEditor/index.tsx
app/routes/events/components/EventEditor/renderPools.tsx
app/routes/events/utils.ts
app/utils/helmet.tsx
app/utils/loadingIndicator.tsx

Round 2!!!! :runner:
- Add and fix types for search reducer and components
- Fix types for helmet and loadingIndicator HOCs
- Type the EventEditor component

Type Search, EventEditor & more

---

app/components/Form/Field.tsx
app/components/Form/Form.tsx
app/components/Form/LegoFinalForm.tsx
app/components/Form/RadioButton.tsx
app/reducers/users.ts
app/routes/users/components/UserSettings.tsx
cypress/e2e/profile_spec.js

Migrate the user settings form to use react final form. Also includes migrating the radiobutton field to work with react final form, as well as fixing the typescript errors.

Migrate user settings to react final form

---

.drone.yml

Update Drone signature

---

app/actions/CompanyInterestActions.ts
app/actions/EmailListActions.ts
app/actions/EmailUserActions.ts
app/actions/EmojiActions.ts
app/actions/EventActions.ts
app/actions/GalleryActions.ts
app/actions/GalleryPictureActions.ts
app/actions/GroupActions.ts
app/actions/PollActions.ts
app/actions/RestrictedMailActions.ts
app/actions/SurveyActions.ts
app/actions/TagActions.ts
app/actions/UserActions.ts
app/actions/__tests__/SearchActions.spec.ts
app/actions/callAPI.ts
app/types.ts
app/utils/createQueryString.ts

Just some quick and easy type fixes in app/actions/\* (except for `callAPI.ts`).

Fix types in actions/*

---

app/store/createStore.ts

forgot to update this when moving files around in #3287

fix path to rootReducer in when hot reloading

---

cypress/e2e/event_visit_spec.js

Not completely sure why it worked without it beforehand or if it is always required, but it solves the current problem regardless.
Useless commit messages, so I'll squash-merge if you guys don't mind
Solves ABA-193

Add missing cy.visit to e2e event_visit_spec

---

app/config.ts
app/global.d.ts
app/store/createStore.ts
config/Config.d.ts

Fix typescript errors when accessing f.ex. `window.__IS_SSR__`

Fix typescript errors with data on window object

---

LICENSE

Truly a major compliance issue indeed.

Update license to 2023

---

app/routes/users/components/Penalties.tsx

Closes https://github.com/webkom/lego/issues/1940

Fix delete prikk modal close on confirm/cancel

---

.drone.yml

Speeds up the pipeline by a couple of minutes.
Not tested, but it should work :shipit:

Exclude build branch from CI steps

---

app/components/Layout/Flex.tsx
app/components/Poll/index.tsx
app/components/RandomQuote/RandomQuote.css
app/components/RandomQuote/RandomQuote.tsx
app/models.ts
app/reducers/events.ts
app/reducers/frontpage.ts
app/routes/overview/components/EventItem.tsx
app/routes/overview/components/Overview.tsx
app/routes/overview/components/utils.tsx
package.json

Rewrite overview component to be functional, refactor a lot of stuff and fix a bunch of types.
Also :star_struck: :star_struck::
[Screencast from 2023-01-18 13-10-12.webm](https://user-images.githubusercontent.com/42850232/213168103-0b5b0373-9c87-4f11-9bbb-9f8b35c2e9eb.webm)

Rewrite overview to functional component & refactor

---

app/components/EventItem/index.tsx
app/components/EventItem/styles.css
app/routes/users/components/UserProfile.tsx
app/utils/eventStatus.ts

Future Event Components now combines waiting-list events and user-admitted events . Includes tooltip for event attendance status.

Implement new event components for upcoming events on profile page.

---

app/components/Footer/index.tsx

Privacy not go brr haha

---

app/routes/surveys/components/SurveyEditor/Question.tsx

Fix a bug where the questionType selector does not work due to incorrect reference to the value in
the redux-form state.
It works now

Fix bug where questionType selection does not work

---

app/utils/replaceUnlessLoggedIn.tsx

Don't know exactly what's wrong here, but changing the return component
in replaceUnlessLoggedIn to a function component seems to resolve the
issue.
Works.

Fix HMR due to replaceUnlessLoggedIn using class

---

app/routes/events/components/EventAdministrate/Attendees.tsx
app/routes/events/components/EventAdministrate/RegistrationTables.tsx

Add admin info about how many unregistered has paid if any, as well as add it to the list of unregistered people.
Hide payment count if 0.
Before:
After:

Add admin info about how many unregistered has paid

---

app/utils/eventStatus.ts

Not sure why this worked before ..?
:------------------:|:-----------------------------:
See result above. This should not affect anything else.

Show registration count on event cards

---

app/routes/users/components/UserProfile.tsx

Made use of the orderBy function to sort event by startTime on user page. I have thoroughly tested my changes. 
----
before:
After:

Sort incomingEvents on user page

---

app/routes/events/components/EventDetail/index.tsx

Fix type typo in (un)follow events

---

app/routes/companyInterest/utils.tsx

Some of the texts are changed a bit. See the diff
Only the text is changed
I observed the changed texts in the form

Update company interest form text as requested from fagkom

---

app/components/Image/ProfilePicture.tsx
app/components/Search/SearchPageResults.css
app/components/UserValidator/index.tsx
app/routes/events/EventAbacardRoute.ts
app/routes/events/components/EventAdministrate/Abacard.tsx
app/routes/userValidator/ValidatorRoute.tsx

Fix abacard
It now works as expected.
I tested both /validator and abacard on event pages.
---
Resolves ABA-305

Make abacard great again

---

app/routes/companyInterest/components/CompanyInterestPage.tsx

One last text change in the company interest form

---

app/components/Form/CheckBox.css

Also decrease the transition time.
**Before**
https://user-images.githubusercontent.com/69514187/225073099-aa79510e-efdb-4d24-8749-4ea4a69230b3.mov
**After**
https://user-images.githubusercontent.com/69514187/225072971-fc0a703f-41af-4ba6-9967-7154290f2a29.mov
Only styling changes, and the result is shown above.

Make checbox look disabled when it's disabled

---

app/routes/companyInterest/components/CompanyInterest.css
app/routes/companyInterest/components/CompanyInterestPage.tsx
app/routes/companyInterest/utils.tsx
cypress/e2e/company_interest_spec.js

[Minor changes to the interest form](https://github.com/webkom/lego-webapp/commit/08e55cc7bb4036cd624174749fac45ebda5b2337) 
- Add a helmet
- Make header look like other headers
- readmify some text
- Minor changes to some labels (especially the English translations)
---
[Migrate interest form to react-final-form](https://github.com/webkom/lego-webapp/commit/ef674cde678f87efd6735d1d567c79c3a9954248)
Tried to create an interest, also with "extra comments".
---
Resolves ABA-58

General changes to the interest form

---

app/routes/surveys/AddSurveyRoute.ts
app/routes/surveys/SubmissionsRoute.ts
app/routes/surveys/components/AdminSideBar.tsx
app/routes/surveys/components/StaticSubmission.tsx
app/routes/surveys/components/Submissions/SubmissionPage.tsx
app/routes/surveys/components/Submissions/SubmissionSummary.tsx
app/routes/surveys/components/SurveyDetail.tsx
app/routes/surveys/components/SurveyEditor/SurveyEditor.tsx
app/routes/surveys/components/surveys.css
app/routes/surveys/utils.tsx

[Align checkbox and radio buttons with labels on surveys](https://github.com/webkom/lego-webapp/commit/51614857dd3c8b3b9c0797074be2e8f4eca3839a)
---
[Minor improvements to surveys](https://github.com/webkom/lego-webapp/commit/5a7b6388a746180cf42f5cadcab1a62cdad71b7e) 
Mostly type improvements.
Changed how the copy token button handles clicks. It's now less glitchy
if you spam it, so that's nice, I guess ..
<video src="https://user-images.githubusercontent.com/69514187/233858102-39da48ea-618c-4eda-b52a-54f31def5717.mov" /> | <video src="https://user-images.githubusercontent.com/69514187/233858099-9ecc12c6-620d-4311-ba6b-1bd1c8f190d2.mov" />
Labels are now aligned and copy button is flawless.

Align checkbox and radio buttons with labels on surveys

---

package.json
yarn.lock

Bump lego-editor to v2.2.0
Minimal changes. General improvements as described in the release notes of the editor.
Tested most features of the editor. Everything works as it should.

Bump lego editor from v2.1.0 to v2.2.0

---

app/components/Card/Card.css
app/components/Card/index.tsx
app/routes/announcements/components/AnnouncementsCreate.tsx
app/routes/bdb/components/BdbDetail.tsx
app/routes/bdb/components/BdbPage.tsx
app/routes/companyInterest/components/CompanyInterestPage.tsx
app/routes/surveys/components/SurveyEditor/SurveyEditor.tsx
app/routes/surveys/components/surveys.css

[Give the card component an info property](https://github.com/webkom/lego-webapp/commit/3cc4dc46d7942043df2c6040bd21056f6b9ecb72)
---
[Utilize the info card](https://github.com/webkom/lego-webapp/commit/755ba4a654521799790a5883e1778581b352aae8)
---
Also resolves ABA-222

Give the card component an info property

---

app/actions/EmailListActions.ts
app/actions/EmailUserActions.ts
app/actions/UserActions.ts
app/components/Feed/renders/restrictedMail.tsx
app/routes/admin/email/components/EmailListEditor.tsx
app/routes/admin/email/components/EmailUsers.tsx
app/routes/admin/email/components/RestrictedMailEditor.tsx
app/routes/admin/email/components/RestrictedMails.tsx
app/routes/bdb/components/BdbDetail.tsx
app/routes/bdb/components/CompanyContactEditor.tsx
app/routes/events/components/EventAdministrate/Attendees.tsx
app/routes/overview/components/NextEvent.css
app/routes/pages/components/subcomponents/DisplayVision/index.tsx
app/routes/users/components/StudentConfirmation.tsx
app/routes/users/components/UserConfirmation.tsx
app/routes/users/components/UserProfile.tsx
app/routes/users/components/UserSettings.tsx
cypress/e2e/router_spec.js

Why do I keep finding stuff like this ..
Not really any visual changes worth showing.
No breaking changes.

Change random bits and pieces, again

---

app/components/Modal/Modal.css
app/components/Modal/index.tsx

And add a backdrop filter to make it pop out more.
The modal still works.. even on mobile!

Animate the modal appearance

---

app/components/Button/Button.css
app/components/Button/index.tsx
app/components/CommentForm/index.tsx
app/components/Dropdown/Dropdown.css
app/components/Dropdown/index.tsx
app/components/Header/Header.css
app/components/Header/index.tsx
app/components/UserAttendance/AttendanceModalContent.css
app/components/UserAttendance/AttendanceModalContent.tsx
app/routes/companyInterest/components/CompanyInterestPage.tsx
app/routes/events/components/EventAdministrate/Administrate.css
app/routes/events/components/EventAdministrate/AttendeeElements.tsx
app/routes/photos/components/GalleryPictureModal.tsx
app/routes/quotes/components/Quote.tsx
app/routes/surveys/components/AdminSideBar.tsx
app/routes/surveys/components/SurveyEditor/Option.tsx
app/routes/surveys/components/SurveyEditor/Question.tsx
app/routes/surveys/components/SurveyList/SurveyList.tsx
app/routes/surveys/components/surveys.css
app/routes/users/components/Penalties.tsx
app/routes/users/components/PenaltyForm.tsx
app/styles/globals.css
app/styles/overlay.css

[Update the look of buttons](https://github.com/webkom/lego-webapp/commit/07de4885dd82f81c9a29f376ea67bd7e4b8b14e9) 
They were a bit outdated.
`flat` buttons now look (work) somewhat different.
The new buttons are flatter with less shades and depth, and most importantly more round <3 Was inspired by YouTube and Twitter's buttons. 
---
[Clean up surveys code and make small improvements](https://github.com/webkom/lego-webapp/commit/f9daf66364993bf61ea7b36f5f81548e7b6e633a) 
Small step in the right direction. A lot of bad code here to be dealt with.
This is definitely out of scope of this PR - but I didn't bother to do it in a separate PR as it sort of relies on the button changes.
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
All different types still work …

Update the look of buttons

---

app/components/Button/Button.css
app/components/Icon/Icon.css
app/components/Icon/index.tsx
app/components/Modal/Modal.css
app/components/Modal/index.tsx
app/components/NavigationTab/NavigationTab.css
app/components/RandomQuote/RandomQuote.css
app/components/RandomQuote/RandomQuote.tsx
app/components/Search/Search.css
app/components/Search/index.tsx
app/routes/bdb/components/BdbDetail.tsx
app/routes/bdb/components/bdb.css
app/routes/companyInterest/components/CompanyInterestList.tsx
app/routes/overview/components/Overview.css
app/routes/overview/components/Overview.tsx
app/routes/photos/components/GalleryDetail.tsx
app/routes/polls/components/PollsList.tsx
app/routes/surveys/components/SurveyEditor/Question.tsx
app/routes/surveys/components/SurveyEditor/SurveyEditor.tsx
app/routes/surveys/components/surveys.css
app/routes/users/components/UserSettingsOAuth2.css
app/styles/variables.css
cypress/e2e/home_page_spec.js

[Make clickable icons resemble flat buttons](https://github.com/webkom/lego-webapp/commit/7f612fcd049782c3d6f793efd0573a43548da503) 
Also center icons that are used in button components.
https://github.com/webkom/lego-webapp/assets/69514187/9f0b2b10-7820-4433-9473-5ff3b7139d7f
Tested the three icon types; `danger`, `success` and `edit`.

Make clickable icons resemble flat buttons

---

app/components/Poll/Poll.css
app/components/Poll/index.tsx
app/components/Search/utils.tsx
app/routes/interestgroups/components/InterestGroupList.tsx
app/routes/overview/components/ArticleItem.css
app/routes/overview/components/EventItem.css
app/routes/photos/components/GalleryEditor.tsx
app/routes/photos/components/Overview.tsx
cypress/e2e/router_spec.js

[Retouch the poll component](https://github.com/webkom/lego-webapp/commit/5cd5f66fa334a4b2cee9c2ad8d9516824b1298f3) 
It just really looked like it had been created by someone external, and
stood out from the rest of the webapp.
A lot of technical debt.
---
[Fix random bits and pieces 4](https://github.com/webkom/lego-webapp/commit/00a67b74c49dc5f7ed3819346ddd518ef69e178d) 
* Bilder -> Album
* Fix a bug where the event title in the compact event component would
overflow
* Reduce line-height some places
* "Ikke aktive" -> "Ikke-aktive"
It's not that visible, but the code is also a bit cleaner.
<table>
<tr>
<td>After</td>
<tr>
<tr>
<td><img width="428" alt="image" src="https://github.com/webkom/lego-webapp/assets/69514187/8fbc2178-8f0f-420f-a7e5-e7c725b9fd39"></td>
<td><img …

Random bits and pieces 4

---

app/components/CommentForm/index.tsx
app/components/Comments/Comment.tsx
app/components/Comments/CommentTree.tsx
app/components/Comments/CommentView.tsx
app/components/Header/index.tsx
app/components/Image/ProfilePicture.tsx
app/components/Tooltip/Tooltip.css
app/components/UserAttendance/AttendanceModalContent.tsx
app/components/UserAttendance/AttendanceStatus.tsx
app/components/UserGrid/index.tsx
app/models.ts
app/routes/events/components/EventDetail/index.tsx
app/routes/events/components/JoinEventForm.tsx
app/routes/events/components/StripeElement.tsx
app/routes/meetings/components/MeetingDetail.tsx
app/routes/users/components/PhotoConsents.tsx
app/routes/users/components/UserProfile.tsx
app/store/models/Comment.d.ts
app/store/models/Event.d.ts
app/store/models/Registration.d.ts
app/store/models/User.d.ts
cypress/e2e/event_visit_spec.js
cypress/e2e/router_spec.js

Picked up by this crawler:
The content authors object is used for comments to highlight the creator
/ author of the content in the comment section. But this would ultimately
break the event page when it would try to read id off of null.
---
[Fix misalignment of anonymous attendance status](https://github.com/webkom/lego-webapp/commit/d038eba8bc16ac29b1c499d2f860c68356b37b0b) 
It was the tooltip that caused the misalignment, so just repositioning
it fixed the bug. A maximum width was also added to prevent tooltips
with a lot of content text from just becoming one very long line.
Some minor additional styling was added by utilizing the button component,
and disabling it when the user is not authenticated.
---
[Type the event page more …

Fix a bunch of stuff

---

app/components/Card/Card.css
app/components/Card/index.tsx
app/components/PhotoUploadStatus/PhotoUploadStatus.css
app/components/PhotoUploadStatus/index.tsx
app/routes/announcements/components/AnnouncementsCreate.tsx
app/routes/bdb/components/BdbDetail.tsx
app/routes/bdb/components/BdbPage.tsx
app/routes/companyInterest/components/CompanyInterestPage.tsx
app/routes/contact/components/ContactForm.tsx
app/routes/events/components/EventAttendeeStatistics.tsx
app/routes/events/components/EventDetail/index.tsx
app/routes/events/components/JoinEventForm.tsx
app/routes/events/components/StripeElement.tsx
app/routes/photos/components/GalleryEditor.tsx
app/routes/surveys/components/SurveyEditor/SurveyEditor.tsx

Made some minor changes to the photo upload card as well.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
All other types work as before

Introduce a success card type

---

app/components/GroupMember/GroupMember.css
app/components/GroupMember/index.tsx
app/reducers/pages.ts
app/routes/pages/PageDetailRoute.ts
app/routes/pages/components/PageDetail.tsx

[Related backend change](https://github.com/webkom/lego/pull/3461)
Not really any visual changes, except the removal of a big 401 on the screen I guess
Kiiind of tested, but I guess it could be better.
---
Resolves https://github.com/webkom/lego/issues/3050

Only fetch group memberships when logged in on pages

---

app/components/ResolveLink.tsx
app/components/Search/QuickLinks.tsx
app/components/Search/Search.css
app/components/Search/SearchBar.tsx
app/components/Search/SearchResults.tsx
app/components/Search/index.tsx
app/components/Search/utils.tsx
app/components/TextWithIcon/index.tsx
app/reducers/search.ts
cypress/e2e/router_spec.js

- Refactor the code for the search menu. (Although I'm not 100% satisfied with the code as it is now. A lot of wrappers n stuff like that. I got kind of tired of working with this tho so I just wanted to get this PR out there)
- Add icons to the Quick links
- Add back missing icons to search results
- Small styling tweaks
- Small bug fixes
**What's NOT fixed**:
- Still a lot of typescript errors. This is due to the types in `/app/reducers/search.ts` file . I decided not to mess around with that file too much, because many other components (like the validator) depends on it. It'd be too big of a PR to fix them as well.
- 'Fullstendig Søk' still looks like crap. I might fix it in another PR alongside the validator and other similar components (and fix the TS errors).
**Before**
**After** …

Refactor Search menu

---

app/routes/overview/components/Overview.tsx
app/routes/overview/components/PublicFrontpage.tsx

Same procedure as last year...
Abakus ~has~ har opptak
- [eh] I have thoroughly tested my changes.
I trust that a changed text string does not break the website
---

Fix typo in admissions banner

---

app/components/Tags/Tag.tsx
app/routes/articles/components/ArticleDetail.tsx

---
Resolves https://github.com/webkom/lego/issues/3483

Fix bad article author spacing

---

app/routes/articles/components/Overview.tsx
app/routes/events/components/CalendarCell.tsx
app/routes/overview/components/NextEvent.tsx

Changes a few more links to point to slugs instead of ids
They end up in the same place

Replace (more) ids with slugs

---

app/routes/overview/components/Overview.tsx
app/routes/overview/components/PublicFrontpage.tsx

Admissions are over so we can remove the banners

Remove banners

---

app/actions/ActionTypes.ts
app/actions/FileActions.ts
app/components/Header/Readme.md
app/components/Image/Image.tsx
app/models.ts
app/reducers/imageGallery.ts
app/reducers/index.ts
app/routes/events/EventCreateRoute.ts
app/routes/events/EventEditRoute.ts
app/routes/events/components/EventEditor/EventEditor.css
app/routes/events/components/EventEditor/index.tsx
app/store/createRootReducer.ts
app/store/models/Event.d.ts

Implement imagegallery for setting and using preset photos on events.
relies on: https://github.com/webkom/lego/pull/3312
---
Resolves ABA-150

Create image gallery for reusable cover images

---

app/routes/companyInterest/CompanyInterestEditRoute.ts

Fix a bug where a few variables had only been renamed in some files, but not all...
Now the bug is no more:) All files are updated!

Fix renaming bug in company interest page

---

README.md

Mention lego-bricks in main README.md

---

app/routes/events/components/EventAdministrate/Allergies.tsx
app/routes/events/components/EventAdministrate/index.tsx
app/store/models/Event.d.ts
app/store/models/Registration.d.ts

Allow users that are registered in the responsible group of an event to also see allergies.
There are also changes in the backend to support this
---
Dependent on https://github.com/webkom/lego/pull/3495

Update frontend check for allergy viewing permissions

---

app/routes/users/components/UserProfile.tsx

Title
It just works.
It just works (I've tested in staging).
---
Resolves ABA-599

Add frame to charity winner 2023

---

app/routes/surveys/components/SurveyEditor/Option.tsx
app/routes/surveys/components/SurveyEditor/Question.tsx
app/routes/surveys/components/surveys.css
app/routes/surveys/utils.tsx

[Stop survey editor from crashing on certain surveys](https://github.com/webkom/lego-webapp/commit/f7e6ede0f8302643f54362a9c01bbd262adbe8bc) 
Not sure why questionType sometimes becomes undefined
---
[Minor improvements to the survey editor](https://github.com/webkom/lego-webapp/commit/45e61c01ac28d062fc3725dbb80311ec83e58cea) 
/surveys still need a big retouch, but this is something.
A lot of very minor changes not really visible:
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
Editing the survey that previously crashed (e.g. /surveys/511/edit) now works 🥳

Stop survey editor from crashing on certain surveys

---

app/components/Card/Card.css
app/components/Card/index.tsx
app/routes/events/components/EventAttendeeStatistics.tsx
app/routes/events/components/JoinEventForm.tsx
app/routes/users/components/UserConfirmation.tsx

I suppose that's the last severity needed. Changed some cards to employ this new severity.
<p align="center">
</p>
See images above. All other severities still work.

Implement a card severity of warning

---

app/components/Comments/Comment.css
app/components/Comments/Comment.tsx
app/components/Icon/index.tsx
app/routes/articles/components/ArticleEditor.tsx
app/routes/bdb/components/BdbDetail.tsx
app/routes/bdb/components/SemesterStatusContent.tsx
app/routes/bdb/components/SemesterStatusDetail.tsx
app/routes/bdb/components/bdb.css
app/routes/events/components/EventAdministrate/Administrate.css
app/routes/events/components/EventAdministrate/Allergies.tsx
app/routes/events/components/EventAdministrate/AttendeeElements.tsx
app/routes/events/components/EventEditor/EventEditor.css
app/routes/events/components/EventEditor/index.tsx
app/routes/events/components/JoinEventForm.tsx
app/routes/events/components/RegisteredSummary.tsx
app/routes/events/components/Registrations.css
app/routes/photos/components/GalleryPictureModal.tsx
app/routes/quotes/components/Quote.tsx
app/routes/quotes/components/QuotePage.tsx
app/routes/users/components/UserProfile.tsx

[Improve the look of the image gallery](https://github.com/webkom/lego-webapp/commit/eaf62c0a45e5df984f88b6cd587032258c4f901c)
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
---
[Misc updates to comments](https://github.com/webkom/lego-webapp/commit/1061c82737e355a4aa0e5b66993da276576b2c3c) 
* Profile picture is now also a link
* Comments made by deleted users now look "normal"
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
---
[Clean up misc things to bdb](https://github.com/webkom/lego-webapp/commit/d888d9b35a87912c707ea7dd77ab74c5c8bf9ad4) 
Among other things; link icons previously did not get the proper styling.
<table>
<tr>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
---
[Update and fix random …

Random bits and pieces

---

app/assets/manifest.json
app/assets/opensearch.xml
app/routes/app/AppRoute.tsx
app/routes/events/components/EventAttendeeStatistics.tsx
app/routes/overview/components/PublicFrontpage.tsx
app/routes/pages/components/LandingPage.tsx
app/routes/users/components/StudentConfirmation.tsx

Komtek go brrrrrr #cyberdata

---

app/routes/users/UserResetPasswordRoute.ts
app/routes/users/components/ChangePassword.tsx
app/routes/users/components/PasswordField.tsx
app/routes/users/components/UserConfirmation.tsx
app/routes/users/components/UserResetPassword.tsx
app/utils/asyncValidator.ts
app/utils/validation.ts

It used field which were only supported by React-Final-Form, which made it crash.
Solved by migrating it to LegoFinalForm and adding async validation to createValidator, as RFF supports this.
Code could probably be more simplified, but works as solution while we are migrating to RFF.
- Checked that each form submits with expected payload
---

Fix registration form

---

app/routes/meetings/components/MeetingEditor.tsx

The select input field's options did not previously include the memberships of invited groups. Therefore you had to create the meeting first and then edit it to add referents (or alternatively you could invite specific users, but that's just a workaround).
I don't think this is the "cleanest" code, but I'd say it's still nice to have and it doesn't break anything so 🤷🏼‍♂️ 
https://github.com/webkom/lego-webapp/assets/69514187/88f99c0a-a5b9-4f96-8967-04ad1d7c7d25
Tested adding and removing multiple groups, and groups without members as well.

Make it possible to set a referent when creating a meeting

---

app/models.ts
app/routes/events/EventCreateRoute.ts
app/routes/events/EventEditRoute.ts
app/routes/events/components/EventEditor/index.tsx
app/routes/events/utils.ts

I think this is unused and only adds the transaction costs to the price before sending that to the backend
---
Resolves ABA-692

Remove stripe fee from frontend

---

app/actions/PollActions.ts
app/routes/admin/email/components/RestrictedMails.tsx
app/routes/admin/groups/components/GroupPage.tsx
app/routes/announcements/components/AnnouncementsList.tsx
app/routes/articles/components/ArticleDetail.tsx
app/routes/articles/components/ArticleEditor.tsx
app/routes/company/components/CompaniesPage.tsx
app/routes/company/components/CompanyDetail.tsx
app/routes/companyInterest/components/CompanyInterestList.tsx
app/routes/companyInterest/components/CompanySemesterGUI.tsx
app/routes/contact/components/ContactForm.tsx
app/routes/interestgroups/components/InterestGroupList.tsx
app/routes/joblistings/components/JoblistingDetail.tsx
app/routes/joblistings/components/JoblistingPage.tsx
app/routes/polls/components/PollDetail.tsx
app/routes/polls/components/PollEditor.tsx
app/routes/polls/components/PollsList.tsx
app/routes/polls/index.tsx
app/routes/quotes/components/QuotePage.tsx
app/routes/tags/components/TagCloud.tsx
app/store/models/Poll.d.ts

Mainly for them to work with ssr
Tested that ssr works

Refactor misc routes to support `react-router` v6

---

app/actions/UserActions.ts
app/components/Form/SelectInput.tsx
app/components/Time/index.tsx
app/models.ts
app/reducers/penalties.ts
app/routes/events/components/JoinEventForm.tsx
app/routes/events/utils.ts
app/routes/users/components/Penalties.css
app/routes/users/components/Penalties.tsx
app/routes/users/components/PenaltyForm.tsx
app/routes/users/components/UserProfile.tsx
app/store/models/Penalty.d.ts

[Set default messages in select input](https://github.com/webkom/lego-webapp/commit/06c1c33a7d480d175be32c07db5b86391b7b3798)
You can witness these changes in the video below for a brief second hehe
---
[Refactor penalties code](https://github.com/webkom/lego-webapp/commit/1f41ba635bf791558e3123c0a167407e3e4a6cba) 
- Fix and improve validation. Actually, there was previously no validation
at all since the so-called "message" field does not exist.
- Refactor to a functional component.
- Refactor to `react-final-form`.
- Adjust minor styling issues, such as spacing.
- Remove and clean up bad code
- Better ts types
---
[Update the list of penalties when deleting one](https://github.com/webkom/lego-webapp/commit/46221a3c71302c97307d9dc5f81be36775f69cb0) 
The store does not update accordingly, …

Refactor penalties

---

app/routes/interestgroups/components/InterestGroup.css
app/routes/interestgroups/components/InterestGroup.tsx
app/routes/interestgroups/components/InterestGroupList.tsx

Quick fix to make the page look prettier. Took inspiration from the joblistings page. The hover effect especially is the same. 
If you've made visual changes, please include **before** and **after** images, preferably with a description. Make sure they do not contain any real user information.
**before**
https://github.com/webkom/lego-webapp/assets/45620425/69173208-2484-40b9-82ff-7ee8ab3c3a74
**after**
(Note: not all logos is actually the same, this is just for demonstration purposes since very few would load)
https://github.com/webkom/lego-webapp/assets/45620425/6ec44948-7686-4ccb-b522-73257587bc32
---
Resolves ABA-246

Improve design of interestgroup page

---

app/routes/events/components/EventEditor/index.tsx

Call to method that doesn't exist - causing image gallery to be broken
Works on local staging

Resolve call to undefined method

---

app/routes/photos/components/GalleryDetail.tsx

Action was not dispatched, so nothing happened on submit
Uploading images now works

Fix uploading of images to gallery

---

packages/lego-bricks/src/components/Layout/Flex.module.css

Dirty fix - but it resolves the problem. Deployed it to https://webapp-staging.abakus.no/ to preview.
Werks
---

Enforce custom flex styling is prioritized

---

app/components/Form/MultiSelectGroup.tsx
app/routes/companyInterest/components/CompanyInterest.css
app/routes/companyInterest/components/CompanyInterestPage.tsx
app/routes/companyInterest/components/Translations.ts

made the semester field on interest form required by request
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Added required field for "semester"
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested in staging
---
Resolves ABA-794

Fix interresse issue

---

app/routes/companyInterest/components/CompanyInterestPage.tsx

hotfix always fetch semesters for interestform
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
---

Always dispatch the fetchsemestersforinterestform

---

app/routes/companyInterest/components/CompanyInterestPage.tsx

Make usePreparedEffect return promise

---

app/models.ts
app/routes/events/components/EventAdministrate/Attendees.tsx
app/routes/events/components/EventDetail/index.tsx
app/routes/events/components/EventEditor/index.tsx
app/routes/events/components/JoinEventForm.tsx
app/routes/events/utils.ts
app/store/models/Event.ts

This PR removes contact tracing (used during covid) functionality from the frontend. Related to, but not dependent on https://github.com/webkom/lego/pull/3559

Remove contact tracing functionality

---

app/components/Content/ContentHeader.tsx
app/components/Content/ContentSidebar.tsx
app/components/DisplayContent/DisplayContent.css
app/components/DisplayContent/index.tsx
app/components/Form/Field.css
app/components/Form/Field.tsx
app/components/InfoList/index.tsx
app/components/InfoList/styles.css
app/components/TextWithIcon/index.tsx
app/components/UserAttendance/AttendanceStatus.css
app/components/UserAttendance/AttendanceStatus.tsx
app/components/UserGrid/UserGrid.css
app/components/UserGrid/index.tsx
app/models.ts
app/routes/events/components/Event.css
app/routes/events/components/EventDetail/EventDetail.css
app/routes/events/components/EventDetail/index.tsx
app/routes/events/components/JoinEventForm.tsx
app/routes/events/components/RegisteredSummary.tsx
app/routes/events/components/RegistrationMeta.tsx
app/routes/events/components/Registrations.css
app/routes/events/components/__tests__/JoinEventFormCountdownProvider.spec.tsx
app/routes/overview/components/CompactEvents.tsx
cypress/e2e/create_meeting_spec.js
packages/lego-bricks/src/components/Skeleton/Skeleton.module.css
packages/lego-bricks/src/components/Skeleton/index.tsx

This all took more time than anticipated. There's still more to be done - but let's be agile
[Prevent user from accidentally unregistering by pressing enter](https://github.com/webkom/lego-webapp/commit/6ff070d0f36ce4344afec9d997e9c45547d24afe) 
Enter would cause the form to be submitted, which either registers or
unregisters the user.
This was reported to us by mail.
---
[Clean up detailed event page](https://github.com/webkom/lego-webapp/commit/9322008c382e025f81b360829844ee70a7361cba) 
Skeleton components have been implemented as much as I could given that most events are quite different. 
Minor clean difficult for the naked eye to spot have been made, such as spacing the sidebar components less random and more "correct".
Bugs have been fixed, e.g. this one 
If you've made visual …

Clean up detailed event page

---

app/components/Search/utils.tsx
app/routes/forum/components/ForumList.tsx

Nice to have now that there's no content in the forum and missing some wanted features.
https://github.com/webkom/lego-webapp/assets/69514187/04d7db75-ecf9-41dc-9c0f-e103a7baae2c
No breaking changes here 🤞

Add Beta tags to the forum

---

app/components/AnnouncementInLine/index.tsx
app/routes/announcements/components/AnnouncementItem.tsx
app/routes/announcements/components/AnnouncementsCreate.tsx

Forgot about this
State is now correctly passed
https://github.com/webkom/lego-webapp/assets/69514187/e500c964-9430-4623-8e44-2e2c1a712d0f
Tested all uses of the link component; events, interest groups and meetings.
Verified that there are no more of these links with bad state passed

Fix "send announcement" link button

---

app/components/Gallery/Gallery.css
app/components/Gallery/index.tsx
app/components/Paginator/index.tsx
app/routes/photos/components/GalleryDetail.tsx
app/routes/photos/components/GalleryEditor.tsx
app/routes/photos/components/GalleryEditorActions.tsx
app/routes/photos/components/Overview.css
app/routes/photos/components/Overview.tsx

The styling of the gallery component was implemented using javascript - changed it to use css grid.
Changed the grid to scale down to one column on smaller devices (previously it did not go down to 1 on mobile devices - at least not for me).
fetch was not being dispatched, so the infinite scrolling was not working (as reported in https://github.com/webkom/lego/issues/3569). Fixed for both viewing albums and editing albums.
Updated invalid icons for empty albums.
The required fields for creating albums did not match with the backend and the `required` attribute and the validation. Now all three of them should validate the same fields-
> [!CAUTION]
<table>
<tr>
<td>After</td> …

Refactor styling of gallery component and fix dispatch-bug

---

app/actions/SurveySubmissionActions.ts
app/components/Chart/BarChart.tsx
app/components/Chart/Chart.css
app/components/Chart/ChartLabel.tsx
app/components/Chart/PieChart.tsx
app/components/Form/SelectInput.tsx
app/components/HeaderNotifications/HeaderNotifications.css
app/components/JoblistingItem/JoblistingItem.css
app/components/Reactions/ReactionPickerContent.css
app/reducers/surveySubmissions.ts
app/reducers/surveys.ts
app/routes/forum/components/ForumList.css
app/routes/interestgroups/components/InterestGroup.css
app/routes/pages/components/PageHierarchy.css
app/routes/photos/components/Overview.css
app/routes/surveys/components/Submissions/Results.tsx
app/routes/surveys/components/Submissions/SubmissionPublicResultsPage.tsx
app/routes/surveys/components/Submissions/SubmissionsIndividual.tsx
app/routes/surveys/components/Submissions/SubmissionsPage.tsx
app/routes/surveys/components/Submissions/SubmissionsSummary.tsx
app/routes/surveys/components/surveys.css
app/styles/variables.css

Bugs fixed, improved graphs, more responsive, better code and overall cleaner.
There's still much more to be done to our surveys, but I've spent enough time on it for now
I don't really want to show many before / after images of this for obvious reasons, but I've picked out some stuff here and there
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested different surveys and different routes within. 
Tested on most viewports - big improvement.
Tested graphs on the event statistics page, the only other place using these
---
Resolves ABA-858
Resolves ABA-843

Clean up survey results

---

app/components/CountDown/index.tsx
app/routes/frontpage/components/AuthenticatedFrontpage.tsx

Made a countdown clock to add on "abakus.no". Improved the clock based on comments from @falbru and @norbye on my last pr #4557 
**new-feature**
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
</td>
</tr>
</table>
Tested by using staging
---

Improved the countdown with a component

---

app/routes/events/components/EventDetail/index.tsx
app/routes/events/components/JoinEventForm.tsx
app/routes/events/components/RegistrationMeta.tsx
app/routes/events/components/__tests__/JoinEventFormCountdownProvider.spec.tsx

Remove how many spots there are left for an event and add concent for event rules
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-276

Make event rules more visible

---

app/components/CountDown/index.tsx

Update countdown for the last time.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
---

Update countdown for the last time

---

app/actions/CompanyActions.ts
app/actions/JoblistingActions.ts
app/routes/bdb/components/BdbDetail.tsx
app/routes/company/components/CompanyDetail.tsx
app/routes/joblistings/components/JoblistingPage.tsx

[Related backend changes](https://github.com/webkom/lego/pull/3574)
Missing logos on the left side because of dev env
Joblistings are still filtered by time on `/joblistings` and `/company/<id>`

Show previous joblistings for company on bdb

---

app/routes/articles/components/ArticleEditor.tsx

Things like title and description are currently only validated on the backend
Not possible to submit bad forms

Validate article editor

---

app/routes/meetings/components/MeetingDetail.tsx

I have no idea how I missed this when testing. I must have tested the wrong branch or something...
And how did it not break the cypress tests? Very strange
It no longer crashes:)

Fix undefined meeting error in meeting detail page

---

app/routes/interestgroups/components/InterestGroupMemberList.tsx

Just a simple refactoring from class component to function component with hooks.
It should look and function exactly the same as before:)
I just opened the member list and tested the search function. Seems to still work as intended

Make InterestGroupMemberList into a function component

---

app/routes/frontpage/components/AuthenticatedFrontpage.tsx

Removes the countdown. Do you guys think we should remove the component as well?

Remove countdown

---

app/reducers/companies.ts
app/reducers/joblistings.ts
app/routes/joblistings/components/JoblistingDetail.tsx
app/routes/joblistings/components/JoblistingEditor.tsx
app/routes/joblistings/components/JoblistingPage.tsx
app/store/models/Joblisting.ts
app/utils/legoAdapter/createLegoAdapter.ts

Simple and easy redux refactoring. Almost no changes except to the reducer!
One less usage of `createEntityReducer`.
Joblistings seem to work well, except for the fetching of company-contacts in the editor fixed here: #4599
---
ABA-688

Use createSlice and legoAdapter for joblistings slice

---

app/routes/photos/components/GalleryPictureModal.css
app/routes/photos/components/GalleryPictureModal.tsx
app/styles/overlay.css

See bug in abakus-slack #webkom.
Worked sweet in dev-mode, but because of the annoying ordering issue that happened with webpack a while back it's different in prod..
This change affects very few places, and I've tested all of them 🤞 
Should work(:
---

Up z-index of overlays

---

app/components/Comments/Comment.css
app/components/Comments/Comment.tsx

Just a quick fix for the tooltip placement for comments.
| Before | After | 
| -- | -- |
| ![Screenshot 2024-04-15 210917](https://github.com/webkom/lego-webapp/assets/33326578/273470c2-b669-4b50-b59e-1e1520c13093) | ![Screenshot 2024-04-15 210908](https://github.com/webkom/lego-webapp/assets/33326578/29cebed6-aa28-4a7d-ace1-35cdf1eaf459) |
---
[ABA-874](https://linear.app/abakus-webkom/issue/ABA-874)

Fix tooltip placement

---

app/routes/admin/email/components/EmailLists.tsx
app/routes/admin/email/components/EmailUserEditor.tsx
app/routes/admin/email/components/EmailUsers.tsx
app/routes/admin/email/components/RestrictedMails.tsx

Move it to the form where it actually matters
Also set active email as default, as there would be no reason to make a new personal email that is deactivated..
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>Remove info from here</td>
<td><img width="940" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/5cbcc846-f397-423e-ab39-c8ddc06c8164"></td>
<td><img width="916" alt="image" src="https://github.com/webkom/lego-webapp/assets/13599770/71287cbc-5a34-4c14-a5d3-2ff04f9f3644"></td>
</tr>
<tr>
<td>Add warning card …

Move info about personal emails to create-form

---

app/components/Feed/activity.css
app/routes/companyInterest/components/CompanyInterest.css
app/routes/events/components/EventList.css
app/routes/events/components/EventList.tsx
app/routes/meetings/components/MeetingList.css
app/routes/pages/components/PageDetail.css
app/routes/pages/components/PageDetail.tsx
app/routes/surveys/components/surveys.css

Especially the ones on the event and meeting lists.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>         
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Made sure removed classes were not used elsewhere.

Update various headers to resemble each other more

---

app/routes/admin/email/components/EmailLists.tsx
app/routes/brand/components/BrandPage.tsx
app/routes/users/components/PhotoConsents.tsx
app/routes/users/components/StudentConfirmation.tsx

I believe I went through all cases. One of them wasn't even correct
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
See image above

Make sure all written mail addresses are anchor links

---

app/components/EventItem/index.tsx
app/components/Header/Navbar/CareerDropdown.tsx
app/components/Header/Navbar/EventsDropwdown.tsx
app/components/Header/Navbar/Item.tsx
app/components/Header/Navbar/ItemList.tsx
app/components/Header/ToggleTheme.tsx
app/components/Header/index.tsx
app/components/HeaderNotifications/index.tsx
app/components/RandomQuote/RandomQuote.tsx
app/components/Search/utils.tsx
app/components/TextWithIcon/index.tsx
app/routes/events/components/EventDetail/EventDetail.css
app/routes/events/components/EventDetail/index.tsx
app/routes/frontpage/components/LatestReadme.css
app/routes/frontpage/components/LatestReadme.tsx
app/routes/pages/components/PageHierarchy.tsx
app/routes/users/components/UserProfile.tsx
package.json
packages/lego-bricks/package.json
packages/lego-bricks/src/components/Icon/Icon.module.css
packages/lego-bricks/src/components/Icon/index.tsx
packages/lego-bricks/src/components/Modal/ConfirmModal.tsx
yarn.lock

I have long wanted to replace our icons from ionicons. They are lacking a bunch of icons, and ones they have are in my opinion not very "consistently" designed. Lucide, on the other hand, is heavily maintained with new icons regularly, with much more consistent, "modern", "stricter" and cleaner designs.
Another (more technical) difference is that we now have to import the icons we wish to use. On one side this acts as a safety, preventing us from misspellings names or using deprecated icons. But, best of all, we won't have to fetch the icons seperatly, meaning the icons will always be visible (despite connectivity issues or issues with ionicons) 😍 Lastly, the fact that it's an npm package makes both setting up and updating the package easier compared to ionicons.
I believe it's better …

Introduce Lucide icons

---

app/routes/interestgroups/components/InterestGroup.css
app/routes/interestgroups/components/InterestGroupApplyCreateApplication.tsx
app/routes/interestgroups/components/InterestGroupInfo.tsx
app/routes/interestgroups/components/InterestGroupList.tsx
app/routes/interestgroups/components/InterestGroupMoneyApplication.tsx
app/routes/interestgroups/index.tsx

Merge the interest-group info into the interest-group page and extract the most useful info into separate pages.
The plan is for the money-application and create-applications to become forms down the line - but this first iteration is useful to make the info more available before we make backend-changes to support the other planned features
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>Overview
</td>
<td><img width="1014" alt="image" src="https://github.com/user-attachments/assets/62a44717-c2d5-4f59-92c8-9efa8edaa773">
</td>
<td><img …

Create initial layout of interestgroup portal

---

app/routes/frontpage/components/AuthenticatedFrontpage.tsx
app/routes/frontpage/components/PublicFrontpage.tsx

Also remove banner from public frontpage.
---
Resolves

Update banner for admissions 2024

---

package.json
yarn.lock

Bump lego-editor to v2.4.0

---

cypress/e2e/home_page_spec.js
cypress/e2e/joblistings_specs.js

Wait for errors to disappear before pressing submit
This is the one that was constantly failing after moving to server-room mando.
Have run the test on both mando and hetzner agents.

Improve flaky cypress test

---

app/components/MazemapEmbed/MazemapEmbed.css
app/components/MazemapEmbed/index.tsx
app/routes/events/components/EventDetail/index.tsx
app/routes/interestgroups/components/InterestGroupDetail.tsx
app/routes/meetings/components/MeetingDetail.tsx

They have just bothered me for some time
Looked at, and verified :)

Minor adjustments to some page details

---

app/routes/companyInterest/components/Translations.ts

Requested by Bedkom
Tested that saving the option works. Translation also works.
---
Resolves ABA-1067

Re-add collaboration with revue to company interest form

---

app/styles/variables.css

Looks trash on chrome
> [!CAUTION]
**before**
**after**
---
Resolves ABA-1039

Add dark scrollbars on dark mode

---

app/components/Comments/CommentView.css
app/components/Comments/CommentView.tsx
app/routes/forum/components/ThreadDetail.tsx
cypress/e2e/event_visit_spec.js

Adds comment sorting based on recency and likes/dislikes
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
---

Add comment sorting

---

app/components/UserAttendance/AttendanceModalContent.css

It overflowed weird so I fix
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1086

Fix registration modal pool styling

---

app/reducers/registrations.ts
app/routes/events/components/EventDetail/getWaitingListPosition.ts
app/routes/events/components/JoinEventForm.tsx

Fixes a bug and some small mistakes in the code from #4977 and #4974 
This no longer happens:
Tested that the bug is no longer present, and that it doesn't break regular registrations.

Hide registration countdown button when already admin-registered

---

app/routes/companyInterest/components/CompanyInterestPage.tsx
app/routes/companyInterest/components/Translations.ts

Requested by bedkom
It's now gone.
---
Resolves ABA-1088

Remove bedex 2024 from company interest form

---

app/components/EventItem/index.tsx
app/components/EventItem/styles.css
app/components/EventListCompact/index.tsx
app/components/JoblistingItem/JoblistingItem.css
app/components/JoblistingItem/index.tsx
app/components/Reactions/index.css
app/components/UserAttendance/AttendanceStatus.css
app/routes/events/components/EventDetail/EventDetail.css
app/routes/events/components/EventDetail/UnansweredSurveys.tsx
app/routes/events/components/EventList.css
app/routes/events/components/EventList.tsx
app/routes/events/components/Registrations.css
app/routes/frontpage/components/UpcomingRegistrations.css
app/routes/frontpage/components/UpcomingRegistrations.tsx
app/routes/meetings/components/MeetingDetail.tsx
app/routes/quotes/components/Quotes.css
app/routes/users/components/UserProfile.css
app/routes/users/components/UserProfile.tsx

Mostly regarding event items, but also event and meeting details and quotes. Overall much more consistent.
All changes were tested on smaller viewports as well.

Improve various spacings

---

app/utils/legoAdapter/README.md
app/utils/legoAdapter/buildEntitiesReducer.ts
app/utils/legoAdapter/createLegoAdapter.ts

Adds some documentation explaining what `legoAdapter` does, and how to use it. Also fixes a few type-errors.

Add README file about legoAdapter

---

app/routes/bdb/components/BdbDetail.tsx
app/store/models/Company.ts

Add latest company contact update date display
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves: ABA-1055

Add display of latest update of company contact

---

app/components/Upload/FileUpload.tsx
app/routes/bdb/components/BdbDetail.tsx

Was this ever tested? The button did not trigger anything, and the file upload action did not exist. Icon size is now also correctly set.
Things work
---
Resolves ABA-1117

Fix file upload on company detail

---

app/components/Content/ContentMain.tsx
app/components/TextWithIcon/index.tsx
app/routes/articles/components/ArticleDetail.css
app/routes/bdb/components/BdbDetail.tsx
app/routes/bdb/components/bdb.css
app/routes/company/components/CompanyDetail.tsx
app/routes/events/components/EventDetail/AttendeeSection.tsx
app/routes/events/components/EventDetail/EventDetail.css
app/routes/events/components/EventDetail/index.tsx
app/routes/events/components/EventEditor/EditorSection/Descriptions.tsx
app/routes/events/components/RegistrationMeta.tsx
app/routes/events/components/Stripe.css
app/routes/frontpage/components/UpcomingRegistrations.css
app/routes/frontpage/components/UpcomingRegistrations.tsx
app/routes/surveys/components/AddSubmission/AddSubmissionPage.tsx
app/routes/surveys/components/AddSubmission/AlreadyAnswered.tsx
app/routes/surveys/components/AddSubmission/SurveySubmissionForm.tsx
app/routes/surveys/components/AdminSideBar.tsx
app/routes/surveys/components/SurveyDetail.tsx
app/routes/surveys/components/surveys.css
packages/lego-bricks/src/components/Icon/index.tsx

Various improvements
<table>
<tr>
<td width="15%">Description</td>
<td>After</td>
</tr>
<tr>
<td>Fixed spacing above info text, and the inline link</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td />
<td>
</td>
<td>
</td>
</tr>
<tr>
<td />
<td>
</td>
<td>
</td>
</tr>
<tr>
<td />
<td>
</td>
<td>
</td>
</tr>
</table>
Changes were tested.
---
Resolves ABA-1124

Fix a bunch of various things

---

app/components/Header/Navbar/Navbar.module.css
app/components/JoblistingItem/JoblistingItem.module.css
app/routes/frontpage/components/ArticleItem.module.css
app/routes/frontpage/components/ArticleItem.tsx
app/routes/interestgroups/components/InterestGroup.module.css
app/routes/interestgroups/components/InterestGroup.tsx
app/routes/interestgroups/components/InterestGroupList.tsx
packages/lego-bricks/src/components/Card/Card.module.css
packages/lego-bricks/src/components/Layout/Flex.tsx

Various stuff, all sort of related to cards hehe. Cards now have borders!
Changes seem very minor
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Tested with smaller viewports

Update card look and other card related things

---

app/routes/users/components/UserProfile/AchievementsBox.tsx
app/routes/users/components/UserProfile/UserProfile.module.css
app/routes/users/components/UserProfile/index.tsx
app/store/models/User.ts
app/utils/achievementConstants.ts

The legends and laurels update part 1.
Should email PR for some icons at some point too.
Rarity 0: Common
Rarity 1: Uncommon
Rarity 2: Rare
Rarity 3:  Very rare
Rarity 4: Super  rare (A handful of people will have this)
Rarity 5: Extremely rare (Probably only a couple people will have this)
Rarity 6: Nearly impossible (Requires a lot of dedication)
Rarity 7-9: Legendary (Reserved for rank-based trophies)
Dark mode:
Light mode:
Other profile:
Hover:
UPDATED:
Left-aligned text:
> [!CAUTION]
Resolves: ABA-1125
Depends on: https://github.com/webkom/lego/pull/3657

Implement The Legends and Laurels: Trophies & Triumphs (Part 1)

---

app/routes/events/components/EventEditor/EditorSection/Registration.tsx
app/utils/constants.ts

Add new roles:
- HS-representant
- Kos ansvarlig
- Foto- og filmansvarlig
- Grafisk ansvarlig
- Merch ansvarlig
- SoMe ansvarlig
Backend PR: webkom/lego#3666
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
---
Resolves ABA-1032

Add new roles

---

app/routes/users/components/UserProfile/UserProfile.module.css

Remove enforcing 2 rows on achievement grid
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Minor achievement mobile design update

---

app/routes/brand/components/BrandPage.module.css
app/routes/brand/components/BrandPage.tsx

Defined flex direction by using the column property of the Flex component. Previously defined in the corresponding stylesheet, which gets overwritten by the column property of the Flex component.
-  ✔️ Changes look good on both light and dark theme.
-  ✔️ Changes look good with different viewports (mobile, tablet, etc.).
-  ✔️ Changes look good with slower Internet connections.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Fix
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
- ✔ I have thoroughly tested my changes.
---
Resolves webkom/lego#3674

Correct flex direction on content in brand page (#3674)

---

app/routes/brand/components/BrandPage.module.css
app/routes/brand/components/BrandPage.tsx

Just some minor stuff
It looks better :)

Slight refactor and updates to brand page

---

app/store/models/Event.ts

These fields are now possibly null if the user is unauthenticated

Update event type model

---

packages/lego-bricks/src/components/Layout/Page/Sidebar.module.css
packages/lego-bricks/src/components/Layout/Page/Sidebar.tsx

little nice feature
https://github.com/user-attachments/assets/888dcb57-6e0c-42a5-90ca-f996d33ddb9c
Filtering works 😄

Include a button to clear filter on filter sidebars

---

app/routes/bdb/components/CompanyEditor.tsx
app/routes/bdb/components/bdb.module.css

Removes bubbles and adds labels.
| -- | -- |
| ![image](https://github.com/user-attachments/assets/5487d450-0b63-4ffc-bfdd-fcad11e4a97b) | ![image](https://github.com/user-attachments/assets/f6664650-a166-472f-8637-cd5118879def) |
Resolves [ABA-1191](https://linear.app/abakus-webkom/issue/ABA-1191/improve-company-edit-design-page)

Update company edit design

---

app/actions/CompanyActions.ts
app/routes/bdb/components/BdbPage.tsx

Adds pagination and ordering by query parameters to BDB Pro. Missing ordering options and broken status filtering will be readded and fixed in a different PR.  
[Related back end PR](https://github.com/webkom/lego/pull/3708)
https://github.com/user-attachments/assets/e4639b09-b3e9-4594-9a9b-a3d1c6997b7d
Navigate to BDB Pro and ensure that content is paginated correctly as you scroll down.
Resolves [ABA-1138](https://linear.app/abakus-webkom/issue/ABA-1138/add-pagination-to-bdb)

Add pagination to BDB

---

app/actions/CompanyActions.ts
app/components/UserLink/index.tsx
app/reducers/companies.ts
app/reducers/index.ts
app/routes/bdb/components/BdbDetail.tsx
app/routes/bdb/components/BdbPage.tsx
app/routes/bdb/components/CompanyEditor.tsx
app/routes/bdb/components/StudentContactEditor.tsx
app/routes/bdb/index.tsx
app/routes/bdb/utils.tsx
app/store/models/Company.ts

- Show the student contacts for a company for that semester in the table
- Add the UserLink-component. I think this component can be used for other pages as well
TODO
- You can't currently assign new student contacts
https://github.com/user-attachments/assets/ab6f913d-2510-4897-a01b-1d2b31b0bf2e
https://github.com/user-attachments/assets/9d007625-af7f-42ce-9ab5-73b017c5dbdc
---
Resolves ABA-1100

Add support for multiple student contacts

---

app/routes/bdb/components/BdbDetail.tsx

This site crashes: https://abakus.no/bdb/4640
The site works again
---

Fix undefined company in BdbDetail to prevent crash

---

app/components/EventItem/RegistrationStatusTag.tsx

Please write a summary of the changes, and please include relevant motivation and context. Remember to label your pull request properly; e.g. **bug-fix**, **new-feature** or **docs**.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
TBA and events without registration permission showed the same status before
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1234

Fix tag text on tba events

---

app/routes/bdb/components/companyInterest/components/CompanyInterestPage.tsx
app/routes/bdb/components/companyInterest/components/Translations.ts

Please write a summary of the changes, and please include relevant motivation and context. Remember to label your pull request properly; e.g. **bug-fix**, **new-feature** or **docs**.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Added bed.ex option, removed start-up night option, removed revue option.
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1232

Remove start-up night, add bed.ex to events + remove revue from collabs

---

app/reducers/groups.ts

Defined link path for board groups to make badges clickable
Is clickable
I clicked
---
Resolves ABA-1243

Define link for groups with the board type

---

cypress/e2e/event_payment_spec.js
cypress/support/utils.js

Got the websockets to work out locally, with stripe, so I got the rest of the tests to pass as well.
Had to update some of the intercepts as stripe has evolved.
No visual changes, but it all works out fine when I'm testing it locally
---
Resolves ABA-1247

Fix cypress stripe tests

---

app/routes/achievements/components/Leaderboard.tsx
app/routes/users/components/UserProfile/AchievementsBox.tsx

Update leaderboard to use fullname
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
Tested by writing the code
---

Update leaderboard to use fullname

---

app/components/UserValidator/Validator.module.css
app/components/UserValidator/index.tsx
app/routes/achievements/components/Leaderboard.tsx
app/routes/bdb/components/BdbDetail.tsx
app/routes/users/components/UserProfile/AchievementsBox.tsx
app/routes/users/components/UserSettings/UserSettings.tsx
cypress/e2e/password_change_spec.js

**bug-fix**. In bdb, after clicking on a business and checking their events, the links to the events are undefined and lead to 404 page. This one-liner fixes that
In local development, i went to the BEKK business profile and tried all of the event links. They lead to the correct page instead of 404.
---
Resolves [ABA-1254](https://linear.app/abakus-webkom/issue/ABA-1254/)

Fix bdb undefined event in "bedriftens arrangementer"

---

app/components/Drawer/Drawer.module.css
app/components/Drawer/index.tsx
app/components/UserAttendance/AttendanceModal.tsx
app/components/UserAttendance/AttendanceModalContent.module.css
app/components/UserAttendance/AttendanceModalContent.tsx
app/utils/isMobileViewport.ts
package.json
yarn.lock

The attendance modal was a bit weird on mobile. I think it works better with a sheet/drawer appearing from the bottom, it feels a lot smoother on mobile with a slidable sheet rather than a normal modal.
> [!CAUTION]
Anonymized names:)
Light mode:
Dark Mode:
---
Resolves ABA-1251

Use drawer for attendance modal on mobile

---

README.md
config/env.ts

Add docs on running websockets locally

---

app/utils/isMobileViewport.ts

🤷🏼‍♂️ thought it was kinda cool to support blackberry and iemobile

Improve `isMobileViewport` hook

---

Dockerfile

I forgot to bump node in the Dockerfile in #5350 
Build should work now

Use node 20 in dockerfile

---

Dockerfile
app/actions/AchievementActions.ts
app/actions/ActionTypes.ts
app/routes/achievements/components/Overview.tsx
app/routes/pages/components/PageDetail.tsx
app/utils/achievementConstants.ts

Adds the 2 new achievements.
WARNING:
DONT READ THIS IF YOU DONT WANT SPOILERS!!!
> [!CAUTION]
---
Resolves ABA-1282

[SPOILER] Add 2 new achievements

---

app/routes/quotes/components/Quote.tsx
app/store/models/Quote.d.ts

Removes the button to approve quote on own quote
> [!CAUTION]
Tested manually
Resolves ABA-576

Cannot approve own quote fix

---

app/components/Search/utils.tsx
app/routes/bdb/components/BdbOverview.tsx

Revert BDB PRO badge 😥

---

app/actions/SurveyActions.ts
app/reducers/surveys.ts
app/routes/surveys/components/AddSubmission/AddSubmissionPage.tsx
app/routes/surveys/components/AdminSideBar.tsx
app/routes/surveys/components/Submissions/SubmissionsPage.tsx
app/routes/surveys/components/Submissions/SubmissionsSummary.tsx
app/routes/surveys/components/SurveyDetail.tsx
app/routes/surveys/components/SurveyEditor/AddSurveyPage.tsx
app/routes/surveys/components/SurveyEditor/EditSurveyPage.tsx
app/routes/surveys/components/SurveyEditor/SurveyForm.tsx
app/routes/surveys/components/SurveyList/SurveyItem.tsx
app/routes/surveys/components/SurveysWrapper.tsx
app/store/models/Survey.d.ts

Makes templates not hard coded. This now works.
> [!CAUTION]
---
Resolves ABA-1256

Custom templates for surveys

---

app/actions/AchievementActions.ts
app/utils/achievementConstants.ts

Add success response to achivs
> [!CAUTION]
Tested by looking at the code

Add successmessage to trophies

---

app/utils/achievementConstants.ts

Added an achievement for the number of "genfors" events one has attended. Open to suggestions for better rarity names.

Add genfors count achievement

---

app/routes/events/components/EventAdministrate/Allergies.tsx

Title 
Tested manually
---
Resolves ABA-967

Update canseeallergies frontend

---

app/routes/surveys/components/SurveyEditor/AddSurveyPage.tsx
app/routes/surveys/components/SurveyEditor/SurveyForm.tsx
app/routes/surveys/components/SurveyList/SurveyListPage.tsx

Fixes surveys
Tested it manually it should work
---

Fix surveys click link and infinite fetching

---

app/utils/achievementConstants.ts

Add complete profile achievement

Add complete profile achievement

---

app/components/JoblistingItem/index.tsx
app/routes/joblistings/components/JoblistingDetail.tsx
app/routes/joblistings/components/JoblistingEditor.tsx
app/store/models/Joblisting.ts

Adds rolling recruitment
> [!CAUTION]
---
Resolves ABA-1310

Adds rolling recruitment option

---

app/actions/AchievementActions.ts
app/components/UserAttendance/GroupFilter.tsx
app/reducers/users.ts
app/routes/achievements/components/Leaderboard.tsx
app/routes/achievements/components/Overview.tsx
app/routes/achievements/components/index.tsx
app/routes/users/components/UserProfile/Achievements.tsx
app/store/models/User.ts
app/utils/achievementConstants.ts

Adds filtering to the leaderboard
This will be tested extensively in staging but local testing shows it works well.
> [!CAUTION]
Tested locally.
---
Resolves ABA-1314

Feat add filtering to achievement leaderboard

---

app/routes/bdb/components/CompanyEditor.tsx

The issue was student contacts that expect a company relation, but this does not exists while creating the company duh. Student contacts are now added in a different form, for some reason? This is still a fix ™️ 
It works 👍🏼 and I'm able to add student contacts via the other form

Fix company creation form

---

app/actions/ActionTypes.ts
app/actions/LendingRequestActions.ts
app/reducers/index.ts
app/reducers/lendingRequests.ts
app/store/createRootReducer.ts
app/store/models/LendingRequest.ts
app/store/models/entities.ts

To facilitate for easier parallel development on the lending system, I have added a bunch of redux boilerplate that is needed for some of the other tasks.
It is kinda broken because I have added features that are not yet added to the backend, but it doesn't matter as long as they are unused
- [-] I have thoroughly tested my changes.
If something is broken, it can be fixed in the PR using the function.
---
Resolves ABA-1324

Add LendingRequest redux boilerplate

---

lego-webapp/package.json
yarn.lock

Unused dependency on bun failed installing in docker

Fix docker build

---

lego-webapp/components/Content/ContentSection.module.css

Kind of a hacky workaround, but it works until we find a better solution for loading css in the correct order.
---
Resolves ABA-1342

Fix media query for content section

---

lego-webapp/pages/index/AuthenticatedFrontpage.module.css

The element was changed from `div` to `section`, but the styling was not - causing the authenticated frontpage to look weird
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
...
</td>
<td>
...
</td>
</tr>
</table>
---

Fix selector to match element

---

lego-webapp/pages/bdb/(overview)/+Page.tsx

Misspelling
---
Resolves ABA-1326

Fix searching for student contacts in BDB

---

lego-webapp/pages/lending/+Page.tsx
lego-webapp/redux/actions/LendingRequestActions.ts

Make partial update work
> [!CAUTION]
---
Resolves ABA-1354

Update method to be PATCH instead of PUT so partial updates work

---

lego-webapp/pages/users/registration/+Page.tsx

Seems like this broke in the Vike refactoring
I was able to register a new user in local dev

Fix small issue with registering new users

---

Dockerfile

Docker build worked on my machine, but not appearently not in ci... This fixes it

Remove pnpm cache to fix docker build

---

lego-webapp/components/Search/utils.tsx
lego-webapp/pages/achievements/+Layout.tsx
lego-webapp/redux/actions/AchievementActions.ts

Add trophies to quicktab

---

lego-webapp/pages/achievements/+Layout.tsx
lego-webapp/pages/achievements/+Page.tsx
lego-webapp/pages/achievements/Overview.module.css
lego-webapp/pages/achievements/utils.tsx
lego-webapp/utils/achievementConstants.ts

Group achievements together, and display progress for each group.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Desktop
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Mobile</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1367

Achievements overview redesign

---

lego-webapp/pages/bdb/(overview)/+Page.tsx

The query paramters have different casing in frontend and backend. This will fix it **flawlessly**
---

Fix backend query for student contacts in bdb

---

lego-webapp/utils/constants.ts

Add Booking admin to list of available roles in bedkom 
---
Resolves request from booking admin in bedkom

Add BookingAdmin to bedkom roles list

---

lego-webapp/utils/achievementConstants.ts

* Primarily developed by @karolipb
* Add frontend support for gala achievement.
* The different colours are probably not properly configured.
* See backend PR webkom/lego#3789.

Add gala achievement

---

lego-webapp/pages/lending/+Page.tsx
lego-webapp/pages/lending/LendableObjectList.module.css
lego-webapp/redux/models/LendableObject.ts
lego-webapp/redux/schemas.ts

Make the lendable object cards a little prettier
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
...
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Resolves ABA-1372

Styling lending index page

---

lego-webapp/pages/achievements/+Page.tsx
lego-webapp/utils/achievementConstants.ts

When you don't have an achievement with count it would display X. Now it display the actual number.
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Resolves ABA-1373

Configure Achievement Mapping

---

lego-webapp/pages/users/@username/_components/Achievements.tsx

Problem: When clicking "topplister" user got redirected to achievement, when should be redirected to leaderboard.
Fix: Redirect to leaderboard
---
Resolves ABA-1387

Fix leaderboard link

---

lego-webapp/pages/sudo/achievements/+Page.tsx

Replaced card with button
> [!CAUTION]
---

Fix onclick on card not working on prod

---

lego-webapp/pages/lending/@lendableObjectId/request/@lendingRequestId/+Page.tsx
lego-webapp/redux/models/LendingRequest.ts

Removes comments from lending requests as they will be replaced by timelineentries.
Prevents crash for https://github.com/webkom/lego/pull/3810
---

Removes comments from lending requests

---

Dockerfile

Forgot to change dockerfile in #5496 
Test in staging:)
---

Fix entrypoint in Dockerfile

---

lego-webapp/package.json
pnpm-lock.yaml

See title. There was a bug where redirects didn't work.

Fix redirect issue by bumping vike-server

---

lego-webapp/pages/lending/@lendableObjectId/request/new/+Page.tsx
lego-webapp/pages/lending/LendableObjectEditor.tsx

Add info about responsible users on lending object
> [!CAUTION]
---
Resolves ABA-1402

Clarify the role of responsible users on lending object page

---

lego-webapp/package.json
pnpm-lock.yaml

There was an issue in earlier versions of `vike-server` causing all redirects to break. Fixed in https://github.com/vikejs/vike-server/pull/104:)

Bump vike-server to fix redirects

---

lego-webapp/pages/achievements/+Page.tsx
lego-webapp/utils/achievementConstants.ts

Add winner of easter egg hunt 2025 trophy
> [!CAUTION]
---

Add winner of easter egg hunt 2025 & 2024 trophy

---

lego-webapp/components/Banner/Banner.module.css
lego-webapp/components/Banner/index.tsx
lego-webapp/pages/admin/banners/BannerEditor.tsx

Added a new easter banner 
https://github.com/user-attachments/assets/b0b57cbd-410d-491b-8ddd-abdcc17ede4a
> [!CAUTION]
I have tested them by making a banner and seing if it looks good
---
Resolves ABA-1428

Easter banner

---

app/components/GroupMember/GroupMember.module.css
lego-webapp/components/Chart/Chart.module.css
lego-webapp/components/Content/ContentSidebar.module.css
lego-webapp/components/ErrorBoundary/ErrorBoundary.module.css
lego-webapp/components/EventItem/styles.module.css
lego-webapp/components/Footer/Footer.module.css
lego-webapp/components/Form/CheckBox.module.css
lego-webapp/components/Form/RadioButton.module.css
lego-webapp/components/Header/Header.module.css
lego-webapp/components/InfoBubble/InfoBubble.module.css
lego-webapp/components/Poll/Poll.module.css
lego-webapp/components/RandomQuote/RandomQuote.module.css
lego-webapp/components/Reactions/ReactionPicker.module.css
lego-webapp/pages/announcements/AnnouncementsList.module.css
lego-webapp/pages/articles/articles.module.css
lego-webapp/pages/events/index/calendar/Calendar.module.css
lego-webapp/pages/index/ArticleItem.module.css
lego-webapp/pages/index/AuthenticatedFrontpage.module.css
lego-webapp/pages/index/Pinned.module.css
lego-webapp/pages/index/PublicFrontpage.module.css
lego-webapp/pages/joblistings/_components/JoblistingList.module.css
lego-webapp/pages/pages/_components/subcomponents/Statistic/Statistic.module.css
lego-webapp/pages/photos/Overview.module.css
lego-webapp/pages/surveys/components/surveys.module.css
lego-webapp/pages/users/@username/_components/Penalties.module.css
packages/lego-bricks/src/components/Card/Card.module.css
packages/lego-bricks/src/components/ImageUpload/ImageUpload.module.css
packages/lego-bricks/src/components/Modal/Modal.module.css

I removed line-height: 1.3; in several CSS files (except globals). I think this should be fine, but I'd appreciate if someone else could look it over in case I deleted something that I shouldn't have.
---
Resolves ABA-1221

Remove forced line-height 1.3

---

lego-webapp/pages/sudo/achievements/+Page.tsx
lego-webapp/pages/sudo/achievements/tags/+Page.tsx
lego-webapp/redux/actions/EventActions.ts

Allow adding tags to event to sudo
---
Resolves ABA-1436

Allow add tag from sudo

---

lego-webapp/pages/achievements/leaderboard/+Page.tsx

One guy was being affected by weird bug sorting him lower
> [!CAUTION]
Before:
After:
---
Resolves ABA-1449

Fix small leaderboard bug affecting one guy

---

lego-webapp/pages/users/@username/settings/notifications/+Page.tsx

Added translations to lending request and lending request status update notification types.
**Before:**
**After:**
---
Resolves ABA-1456

Add translations to lending request notification types

---

lego-webapp/pages/events/utils.ts
lego-webapp/redux/models/Event.ts

Please write a summary of the changes, and please include relevant motivation and context. Remember to label your pull request properly; e.g. **bug-fix**, **new-feature** or **docs**.
> [!CAUTION]
Yellow color ^
Galla label^
---
[Backend PR](https://github.com/webkom/lego/pull/3844)
Resolves ABA-1513

Add gala as new event type

---

lego-webapp/components/Form/ImageUploadField.module.css
lego-webapp/components/Form/ImageUploadField.tsx
lego-webapp/pages/lending/@lendableObjectId/+Page.tsx
lego-webapp/pages/lending/@lendableObjectId/LendingRequestEditor.tsx
lego-webapp/pages/lending/@lendableObjectId/Page.module.css
lego-webapp/pages/lending/LendableObjectEditor.tsx
lego-webapp/pages/lending/LendableObjectList.module.css
lego-webapp/pages/lending/LendingStatusTag.tsx
lego-webapp/pages/lending/admin/+Page.tsx

- Make the lending object images square
- Add "ny forespørsel" and "endringer løst" to default status filters on admin page
**before**
**after**
---

Make the lending object images square

---

lego-webapp/components/Header/ToggleTheme.tsx
lego-webapp/components/Header/toggleTheme.module.css

I like animation...
Would like to know if animation looks good on this icon. Maybe the animation should be faster?🤷‍♂️
Add: transition to toggle dark/light. 
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Toggle dark/light mode
</td>
<td>
https://github.com/user-attachments/assets/1282cd17-d8bb-4cb3-8d15-0540113c112b
</td>
<td>
https://github.com/user-attachments/assets/0d300a2e-715c-4c8d-8647-6db492a84db7
</td>
</tr>
</table> …

Add: Animation toggle dark/light mode

---

lego-webapp/components/Header/Header.module.css
lego-webapp/components/Header/ToggleTheme.tsx
lego-webapp/components/Header/index.tsx
lego-webapp/components/Header/toggleTheme.module.css

The animation acted different in the navbar and profile header
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Fix animation
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1539

Fix: Animation toggle dark/light

---

lego-webapp/pages/joblistings/@joblistingIdOrSlug/+Page.tsx

Changed published date to visibleFrom. It was createdAt date. Requested of Torjus (Abakus leader).
> [!CAUTION]
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Changed date
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-1547

Change published date to visibleFrom

---

lego-webapp/pages/companies/+Page.tsx
lego-webapp/pages/companies/CompaniesPage.module.css
pnpm-lock.yaml

Added link to Bedkom page on Company page.
<table>
<tr>
<td>After</td>
</tr>
<tr>
<td>
Added link. Had to remove flex display from styles, but the text still looks good on different devices and sizes.
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
---
Resolves ABA-753

Add link to Bedkom page
