app/config.js, app/index.js, package.json, server/render.js, yarn.lock
This is probably an unnecessary precaution since we're already base64 encoding the state, but at least this makes the script tag escaping and such slightly cleaner.
https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0
=> Use serialize-javascript for initial state

app/actions/ActionTypes.js, app/actions/UserActions.js, app/reducers/auth.js
The token refreshing was completely broke, should work now. I changed the logic a bit too, it now refreshes the token after completing the login to prevent the user from noticing that anything happened. It also refreshes the token once per day, as it doesn't really hurt and it creates a better user experience.
Tested with the server side renderer as well.
=> Fix token refreshing

app/components/Search/utils.js, app/routes/overview/components/LatestReadme.js
Avoids browser warnings (and we just turned HTTPS on for readme.abakus.no in cloudflare)
=> Use https for readme.abakus.no

app/routes/pages/components/PageHierarchy.css
=> Make sure pages with titles >1 line looks like one element in navigation

app/actions/UserActions.js
Previously the cookie would be set as a session cookie, so it'd get deleted when users closed their browsers. This fixes that, and sets it to `secure` in prod as well.
=> Set correct cookie options

app/routes/interestgroups/components/InterestGroupDetail.js
.. instead of counting the memberships we get back, since the membership
API is paginated.
Depends on https://github.com/webkom/lego/pull/902
=> Show the number of group members from the `numberOfUsers` field

app/routes/meetings/MeetingDetailLoginRoute.js, app/routes/meetings/MeetingDetailRoute.js
This fixes the timeout bug with SSR when accepting a meeting invitation,
when the user is already authenticated. Chaining multiple prepare's
seems to create a timeout.
=> Fix timeout issue when accepting meeting invite

app/components/Editor/constants.js, app/components/Editor/index.js
Fix typos that resulted in a crash when setting text underline
=> Fix typos in Editor

app/utils/fetchJSON.js
Can't say for sure, but I'm guessing that all the `Failed to construct 'Request': HEAD or GET Requests cannot have a body.` (https://sentry.abakus.no/webkom/lego-webapp/issues/3796/) errors in IE Edge comes from us passing in `body` as null.
=> Only create body if it exists

app/actions/UserActions.js, app/routes/users/UserProfileRoute.js, app/routes/users/UserSettingsRoute.js, app/routes/users/components/ChangePassword.js, app/routes/users/components/UserSettings.js
Always redirects to `/users/me` for password changes, since you can only change your own password. Redirects to `/users/<username>` otherwise (doesn't really matter if it's `me` or `username`).
=> Redirect to correct page after changing user settings

app/actions/callAPI.js
When callAPI used a cached value, the returned promise never fulfilled,
and therefore all the '.then' functions chained together with the
promise was never executed. This fixes the issue, by returning a promise
that when executed will resolve with the cached value.
Since the action doesn't contain a promise, the `promiseMiddleware` doesn't do it's magic - and therefore the promise isn't fulfilled via `resolve`.
And isn't it closer to `cachedResponse`, instead of `cachedRequest`??
This fixes #847 and fixes #775 :smile:
=> Fix issue where callAPI promise isn't fulfilled

app/reducers/companies.js, app/routes/bdb/AddCompanyContactRoute.js, app/routes/bdb/AddSemesterRoute.js, app/routes/bdb/BdbRoute.js, app/routes/bdb/EditCompanyContactRoute.js, app/routes/bdb/EditCompanyRoute.js, app/routes/bdb/components/BdbDetail.js, app/routes/bdb/components/BdbPage.js
- Order events in bdb by newest first (Fixes #876)
- Scroll to top when navigating to detail view
- Use `prepare` in all the routes
- Autonavigate when search yields only one result (type Bekk -> only one result -> press enter -> get navigated to Bekk's detail view)
- use `fetchAdmin` and `fetchAllAdmin` in all bdb routes instead of `fetch` and `fetchAll`
=> Bdb improvements

app/actions/CompanyActions.js, app/components/Search/utils.js, app/reducers/companies.js, app/reducers/joblistings.js, app/routes/company/CompaniesRoute.js, app/routes/company/CompanyDetailRoute.js, app/routes/company/components/CompaniesPage.js, app/routes/companyInterest/components/CompanyInterest.css
Add pagination for companies. #776
Add link to /companies in the search bar.
Created selectors and actions for fetching the right events and joblistings for each company. Previously, there was a bug were each company would get all events and joblistings available for all companies.
Fixed some small typos regarding error messages.
Fixed a minor style bug in companyInterest by adding flex-wrap: wrap #819
=> Add pagination and fix previous events & joblistings for companies

app/actions/CompanyActions.js, app/components/Modal/ConfirmModal.js, app/routes/bdb/components/AddSemester.js, app/routes/bdb/components/BdbDetail.js, app/routes/bdb/components/CompanyEditor.js, app/routes/bdb/components/SemesterStatusDetail.js, app/routes/bdb/utils.js, app/routes/joblistings/components/JoblistingEditor.js
This adds autoClose functionality, useful when the route isn't changed
in the action executed. The closing is executed when the given promises
resolve.
=> Make confirm modal take promises instead of funcs

app/components/Comments/CommentView.js, app/routes/bdb/components/BdbDetail.js
The prop 'newOnTop' for CommentView allows comments to be sorted (only
the first level in the tree) with the newest comments on top. The
comment form will then also be on the top.
=> Add support for reversed sorting of comments

app/routes/events/EventListRoute.js, app/utils/prepare.js
It is annoying when you as a user stays on a page, and then logges in - and you still can't see any content. This can be achived to add `loggedIn` as a watchProp in all routes, but imo this is a better approach. When a user logges out, we clear the whole state (and then setting it to `initialState`). We could (and probably should) do something similar with login, but this is how far I got today.
Thoughts anyone?
=> Add 'loggedIn' as a default watchProp in prepare

app/components/CommentForm/CommentForm.css
Adds some very simple margin to make the new comments with `newOnTop = true` look better.
Becomes
For the regular comment positioning the margin might be a little out of place, but some extra white at the bottom of a page never hurt anyone 🤷‍♂️
=> Style comments

app/routes/bdb/components/BdbDetail.js, app/routes/bdb/components/CompanyList.js, app/routes/bdb/components/bdb.css
Renames "Kommentar fra bedkom" (`adminComment`) to "Notat" consistently.
Also makes infobubbles more responsive:
=> Bdb tweaks

app/actions/EventActions.js, app/routes/events/components/EventAdministrate/AdminRegisterForm.js, app/routes/events/components/EventAdministrate/index.js
Kinda hacky, but since there is no pool with `id=0` we can use that as an "id" for the waiting list.
Depends on this PR in the backend: https://github.com/webkom/lego/pull/894
=> Add support for admin registration to waiting list

app/components/Modal/ConfirmModal.css, app/components/Modal/Modal.css, app/components/Search/Search.css, app/components/UserAttendance/AttendanceModal.css
Fix #751
Put overflow-y to auto instead of scroll to remove empty scrollbars in modals and search results
=> Remove empty scrollbars in modals

app/routes/events/components/Event.css
The image covers the entire container anyway, so this makes the page more responsive.
=> Remove height from event banner

app/actions/NotificationsFeedActions.js, app/components/Header/index.js, app/components/HeaderNotifications/HeaderNotifications.css, app/components/HeaderNotifications/index.js, app/reducers/notificationsFeed.js, app/routes/app/AppRoute.js
Fixes #832
Hides unread count from notification icon when opening the notification box and marks all notifications as read after closing, removed "Marker alle som sett"
=> Mark notifications as read after opening notification box

app/components/NavigationTab/NavigationTab.css
On pages with short titles in NavigationTab, this does nothing:
However, when the titles and menus both grow long, this PR makes the title split into multiple lines so that the menu can stay intact.
From:
To:
On smaller screens, the title would have gotten split into very many lines, so it reverts to the previous functionality there:
=> Style NavigationTab to give menu items precedence

app/routes/events/components/Toolbar.js, app/routes/interestgroups/components/InterestGroupDetail.js, app/routes/interestgroups/components/InterestGroupList.js, app/routes/meetings/components/MeetingDetail.css, app/routes/meetings/components/MeetingEditor.css, app/routes/meetings/components/MeetingEditor.js, app/routes/meetings/components/Toolbar.css, app/routes/meetings/components/Toolbar.js, app/routes/pages/components/PageDetail.js, app/routes/photos/components/GalleryDetail.js
So the title/header of each page, with its links and buttons are a bit of a mess, to put it mildly.
We got a mix of buttons, uppercase, lowercase, Square brackets, bold font. MeetingDetail has a top-margin, MeetingList does not use NavigationTab + NavigationLink and so forth.
I suggest we make it a bit more coordinated like this, left being the old and right being the new. 
Was supposed to make the same changes to "New Meeting", but for some reason i cant access the page on Staging :(
=> Update the uncoordinated design of the titles/headers

app/components/Content/Content.css, app/components/Content/Content.js, app/routes/events/components/Event.css, app/routes/events/components/EventDetail/index.js, app/routes/joblistings/components/JoblistingDetail.js
Lets you set a `banner` on `Content` to emulate the behavior of the event detail page. Also adds it to job listings (cc @tmsolber) so that the banner covers the entire page like on event.
=> Add a banner prop to <Content />

app/reducers/users.js, app/routes/users/UserProfileRoute.js
Other people's user profiles crash in master now because we removed the `|| {}` from `selectUserByUsername` - this handles that.
=> Handle non-existant users in selectUsersWithGroups

app/components/Form/Captcha.css, app/components/Form/Captcha.js
This fixes the issue when only button text was clickable due to the
captcha.
New:
Old:
Fixes #762
Caused by https://github.com/jgthms/minireset.css/blob/master/minireset.css#L64
=> Fix height of captcha

app/actions/UserActions.js, app/actions/callAPI.js, app/reducers/index.js, app/routes/app/AppRoute.js
Only run logout after getting a 401 response when the user is loggedIn
(has authentication info in the state). The previous behavior resulted
in an infinite loop.
=>  Fix infinite fetch after 401 response

app/reducers/frontpage.js
This didn't work as I thought it would, since we have two sets of IDs (articles and events).
=> Revert "Sort by IDs first in frontpage"

app/reducers/frontpage.js
The functions passed to `lodash.sortBy` are ran on each element,
producing a new list `[f(x), g(x), h(x), ...]`, and it is _this_ list
that is sorted. With the previous attempted solution to this problem we
had the `id` as the first element. This causes the list to only look at
`pinned` and start time, if there are collisions in the IDs (whic is
unlikely). With this change, we first sort by pinned. If there are
multiple items with the same value (which there will be, since `pinned`
is either `true` or `false`), we look at the start time abs thing.
Then, if there are elements that still compare as equals, we look at the
ID. This is the indended semantics of the previous PR (#961).
=> Sort frontpage events by `id`, after `pinned` and start time.

app/actions/UserActions.js
It now handles an invalid jwt token (token that cannot be decoded) as if
no token exists.
This fixes #624
=> Add a safer way to handle jwt decode

app/routes/companyInterest/index.js, app/routes/index.js
What do you think of this approach?
Alternatively we can do something like
```
export const interesse = {
path: 'interesse',
...resolve(..)
}
export companyInterest = {
path: 'companyInterest',
indexRoute: ...
childRoutes: [
{...},
]
}
```
and `import { interesse, companyInterest } from './companyInterest/';`
instead of the spreading and exporting an array. But I am not sure what I prefer.
=> Add support for /interesse

app/routes/events/components/JoinEventForm.js
Notify user that feedback is required (if enabled) after captcha is
updated.
This fixes #904.
=> Notify user about required feedback

app/components/GroupForm/index.js
Make the logo required only for new groups, not on every edit.
=> Fix logo validator

app/routes/users/components/UserProfile.css, app/routes/users/components/UserProfile.js
Makes sure that the profile picture is still left aligned for users with a lot of group memberships.
=> Align user profiles properly

app/components/HeaderNotifications/index.js
Firefox doesn't support `overlay` (and `auto` behaves almost the same anyway). This fixes this:
@hanswilw
=> Use overflow-y auto for firefox compatibility

app/routes/events/EventEditRoute.js, app/routes/events/components/EventEditor/index.js
Due to the 'componentDidMount' hack in ImageUploadFiled, clicking edit
event after the `fetchEvent` cache is invlidated (10sec?), result in a
new form initialize after the event is fetched, and the 'cover' value in
the form is replaced with the original url - resulting in a 404 when
posting the `imageurl`.
This is just as the comment says, a huge and ugly hack that creates bugs that are hard to track down...
https://github.com/webkom/lego-webapp/blob/6c5df1d27e80046508890da9eecd491fdcb7256b/app/components/Form/ImageUploadField.js#L24
Fixes stuff like this:
https://sentry.abakus.no/webkom/lego-webapp/issues/3801/events/1999164/
This works here; but would be nice with some more testing..
=> Disable form reinitialize in eventForm

app/routes/events/components/EventAdministrate/AttendeeElements.js
The flexbox row attr is implicitly set.
This fixes an annoying console error.
=> Remove row prop from Flex container

app/components/Table/index.js
This is "already" used in event administrate
Now:
vs. the old
=> Use lodash get when resolving data for table

app/components/ErrorBoundary/index.js, app/components/Feed/activity.js, app/components/Feed/index.js
This fixes the error caused by feed activities
without the context (eg. the joined group is deleted).
This should therefore be properly fixed in the backend.
We can switch back to a single error boundary per feed when the backend issue is resolved. :smile:
=> Add error boundary to feed

app/components/DisplayContent/DisplayContent.css, app/components/DisplayContent/index.js, app/routes/events/components/Event.css, app/routes/events/components/EventDetail/index.js
- https://github.com/webkom/lego-webapp/commit/c27de0ae8f63a915de4126b058a5fcab046e835c Fix defualt "styling" in DisplayContent. Long urls use to break mobile view.
- https://github.com/webkom/lego-webapp/commit/9d4d3d7106967b73c95f94d59de676526e7c4d57 Make registered thumbnails less obscure on mobile (used to look like only 10 people was registered, since there were two empty spots)
=> Styling fixes

app/components/ErrorBoundary/index.js, app/routes/app/AppRoute.js
Add new prop to error boundary, that resets the error when it is changed. It is useful when a route crashes, because then the router location change can be used to reset the error. :smile:
Also moved the error boundary inside the `AppChildren`, since that fixes the styling issue (the footer is now on the bottom of the page after an error occur)
=> Add support for resetting error boundary

app/components/DisplayContent/index.js, app/utils/__tests__/urlifyString.spec.js, app/utils/urlifyString.js
Add initial support for url rendering when displaying content. It just wraps all urls (including mailto) as normal link tags. This is a temporary solution, since the editor doesn't support links yet. It is kind of a hack, so look at the test to get a brief understanding of the thing, 
It currently removes `:mailto` from the rendered text. It is possible to do the same thing with `https|http` too
=> Add initial support for urls in DisplayContent

app/components/Header/Header.css, app/components/Header/index.js, app/components/LoginForm/ForgotPasswordForm.js, app/components/LoginForm/Login.css, app/components/LoginForm/RegisterForm.js
Made a new pull request for this feature since the old one got a bit outdated compared to prod. 
It appends the ability to create a new user and to reset your password by just pressing the profile icon while not logged in.  
-Mobile-
-Desktop-
=> Add CreateNewUser and ForgotPassword on header

app/reducers/pages.js, app/routes/pages/components/PageDetail.js
This fixes #1041.
Moved the sorting/grouping to the selector instead.
```jsx
const separateRoles = [
'retiree',
'active_retiree',
'alumni',
'retiree_email',
'leader'
];
// Map all the other roles as if they were regular members
const defaultRole = 'member';
```
=> Fix member listing in pages

app/routes/meetings/components/MeetingDetail.js
Now consistent with events sidebar.
Potential bug: I can't see the accept/decline buttons when making my own events, but I can see them when being invited to a meeting by someone else. Can anyone reproduce? Don't know what's the issue.
=> Rework info in meetings sidebar

app/routes/interestgroups/components/InterestGroup.css, app/routes/interestgroups/components/InterestGroupDetail.js, app/routes/interestgroups/components/InterestGroupMemberList.css, app/routes/interestgroups/components/InterestGroupMemberList.js
Fix #989
Adds a modal with all members of interestgroup
Here the leader and co-leader are sorted to the top of the list, and given an icon (with tooltip)
=> Add member list for interestgroups

app/components/Form/DatePicker.js
The containers we run the webapp in use "no" timezone, aka. they just
use +00:00. This results in strange behavior when the server side
renderer formats the date/time on the server. When the datepicker is
re-rendered in the browser, it use out timezone (Europe/Oslo). This
results in a wrong date label, and an annoying flash when clicking
around. :clock1: :clock2: :clock3: 
Source: [youtube](https://www.youtube.com/watch?v=-5wpm-gesOY)
This fixes #1050. Nice catch @ekmartin. This will save all of us (including bedkom & fagkom) from scratching our head, wondering why the hell we shifted all the timestamps with 1 (or 2) hour(s).
**PS**: Do we format time other places, without using the `<Time />` component?? :thinking:
=> Use timezone when formatting date/time in datepicker

package.json, server/server.js, yarn.lock
Use a pretty output instead of json when the server is running in a tty
(valid terminal). Will still output json when piped, written to a file
or just running in headless.
Left: json
Right: pretty-print
This is a way better approach than just using __DEV__ or NODE_ENV,
becuase it also prints pretty when running a containerized version of
the server with an pseudo-TTY.
```bash
$ docker run -t lego-webapp   # pretty
$ docker run lego-webapp      # json
$ node dist/server.js         # pretty
$ node dist/server.js | cat   # json
$ yarn start                  # pretty
$ yarn start | cat            # json
```
This can also be achived using: `yarn start | ./node_modules/.bin/bunyan`, but that is rather annoying. When you have a tty, you will always prefer pretty-print over json. :tada:
=> Add pretty console output for tty

app/reducers/registrations.js
This fixes #1042.
Together with the PR in the lego repo https://github.com/webkom/lego/pull/1029, this will
successfully reduce the response into the registration object.
Maybe we can get this to prod before "Kurs med BEKK, del 1" tomorrow? :smile:
=> Add better reducer for registrations

app/assets/manifest.json, app/components/Form/CheckBox.js, app/components/Form/RadioButton.js, app/reducers/surveys.js, app/routes/surveys/AddSurveyRoute.js, app/routes/surveys/EditSurveyRoute.js, app/routes/surveys/components/Option.js, app/routes/surveys/components/Question.js, app/routes/surveys/components/SurveyDetail.js, app/routes/surveys/components/SurveyEditor.js, app/routes/surveys/components/surveys.css, app/routes/surveys/utils.js, package.json, yarn.lock
This PR continues the Survey project #986, checking the next two todo items:
With this PR, the Editor ( `surveys/add` and `surveys/someId/edit`) should be mostly finished.
In addition, a basic display of the questions in each survey has been added to the detail page.
=> Add and Edit Surveys

app/components/Image/Image.css, app/components/Image/Image.js
I'm not completely sure, but I think we were doing the `componentDidMount` stuff to add an opacity transition to the images, however since we weren't setting `opacity: 0` this wasn't actually happening. This removes it altogether and simplifies the component. That also fixes a bug where we'd try to load an undefined image while the `src` prop was getting ready.
=> Refactor Image component

app/routes/users/components/Penalties.js
Fix issue #1070 so that the title of the penalty section is universal for all users.
=> Title of penalty section

Dockerfile
Looks like the newest `sentry-cli` is acting kinda strange. This should fix all sourcemaps, including server. :smile:
=> Fix sourcemaps - once and for all

app/actions/ActionTypes.js, app/reducers/__tests__/fetchHistory.spec.js, app/reducers/fetchHistory.js
We don't really need to cache stuff on the frontend. This should hopefully fix some of the cache issues, while still keeping the benefits of not having to fetch stuff again after the server side render. 
In the future we could probably replace this altogether with something where we make sure that we never fetch initial data if we have it in the store from before, as that's mostly what we use the cache for anyway.
Also removed the `SET_HISTORY` action, as it's not being used anywhere.
=> Only cache requests on the server

app/routes/admin/email/components/RestrictedMailEditor.js
This depends of https://github.com/webkom/lego/pull/1067 
Adds the front-end support for the creation of tokens with `weekly` and `hide_sender` flags
=> Add weekly and hide_sender flags to Create Restricted Email

app/routes/overview/components/CompactEvents.js
Upon request we should support showing events that are currently happening on the frontpage, this basically just filters by endTime instead of startTime.
Dependant on https://github.com/webkom/lego/pull/1070 to work, but does not break without it 👍
=> Filter by endTime

app/actions/ActionTypes.js, app/actions/EventActions.js, app/reducers/events.js, app/reducers/forms.js, app/reducers/registrations.js, app/routes/events/components/EventAdministrate/Attendees.js, app/routes/events/components/EventDetail/index.js
Fix #1103 🚤
Use user id instead of potential null registration id to distinguish between oneself or other users when registering or unregistering.
=> Fix superannoying event registration bug

app/actions/ActionTypes.js, app/actions/CompanyActions.js, app/reducers/companySemesters.js, app/routes/companyInterest/CompanyInterestEditRoute.js, app/routes/companyInterest/CompanyInterestRoute.js, app/routes/companyInterest/CompanySemesterGUIRoute.js, app/routes/companyInterest/components/CompanyInterest.css, app/routes/companyInterest/components/CompanyInterestList.js, app/routes/companyInterest/components/CompanyInterestPage.js, app/routes/companyInterest/components/CompanySemesterGUI.js, app/routes/companyInterest/index.js, app/routes/companyInterest/utils.js
This PR solves #831. It is now possible to add/activate and deactive semesters used in companyInterestForm. It is not possible to delete semesters, as an overflow of semesters will not be likely. 
The PR also fixes some styling for the companyInterestForm.
=> UI for changing semesters in companyInterestForm

app/components/Table/Table.css, app/components/Table/index.js, app/routes/admin/email/components/EmailLists.js, app/routes/admin/email/components/EmailRoute.js, app/routes/admin/email/components/EmailUsers.js, app/routes/admin/email/components/RestrictedMailEditor.js, app/routes/admin/email/components/RestrictedMails.js, app/routes/admin/email/index.js
Made some changes to the email pages. This page does no longer exist.
So the first email page you arrive at is the list of lists. The page with users can now be filtered with active and inactive as a criteria. The table now has a title and a dedicated button for the creation of whatever the table displays
=> Changes to the email pages + add filter to email accounts

app/actions/EventActions.js, app/components/Form/Field.js, app/routes/events/components/EventAdministrate/AdminRegister.js
This resets the form if the submit succeeds. It also fixes registration
to the waiting list, by sending no poolId; instead of pk=-1. Also add
legoForm <3
Toghether with a change in the backend, this is achived: 
~~There are still a few `statusCode==500` on the endpoint...~~ Fixed in: https://github.com/webkom/lego/pull/1087.
=> Fix minor admin regsitration bugs

app/components/CommentForm/CommentForm.css, app/components/Editor/Editor.css, app/components/Editor/index.js
From
To
Keeps comments without border, and aligns the elements better.
From
and (focus)
To
And
=> Add border to editor

app/components/Time/Time.spec.js, app/components/Time/index.js
:arrow_down: 
if `year === currentYear`, the year will be omitted.
=> Fix date formatting for dates outside current year

app/actions/EventActions.js, app/components/Feed/Feed.css, app/components/Feed/index.js, app/components/LoadingIndicator/index.js, app/reducers/events.js, app/routes/events/components/EventList.js, app/routes/users/UserProfileRoute.js, app/routes/users/components/UserProfile.css, app/routes/users/components/UserProfile.js, package.json, yarn.lock
Fixes #1074.
Now shows the events you're registered for in your own user profile for easy access. Modified the existing EventItem to be able to not show the tags of an event. Also an style update for the message shown in the feed section when there is no feed to show. Extended the existing events endpoint. 
Note: If you have registered for 1000 events, it will show all 1000 events and the page will get quite long. In reality the length won't be able to get unreasonably long though.
With registered events:
Without registered events:
Won't show your registered events when viewing others profile.
=> Your upcoming events in profile

app/actions/SurveyActions.js, app/reducers/events.js, app/reducers/surveys.js, app/routes/surveys/AddSubmissionRoute.js, app/routes/surveys/AddSurveyRoute.js, app/routes/surveys/EditSurveyRoute.js, app/routes/surveys/SubmissionsRoute.js, app/routes/surveys/SurveyDetailRoute.js, app/routes/surveys/SurveyRoute.js, app/routes/surveys/TemplatesRoute.js, app/routes/surveys/components/SurveyDetail.js, app/routes/surveys/components/SurveyEditor/SurveyEditor.js, app/routes/surveys/components/SurveyList/SurveyItem.js, app/routes/surveys/components/surveys.css, app/routes/surveys/index.js, app/routes/surveys/utils.js
Adds the option to load templates in surveys to reduce the amount of repetetive work survey creators have to do.
Does so using url params: `/surveys/add/?templateType=company_presentation` will issue a fetch for the template used for company presentations, and then use that to initialize the form. Regular users do this by clicking a new "Use template" button, which has a dropdown containing each type from the possible event types found in `events/utils`.
Clicking an item simply links to an url on the form above and reinitializes the form.
Because clicking such an item overrides all changes users have made, I figured there should be a confirm modal. However, the confirm modal component didn't seem to cooperate at all, so for now I use the native `if (confirm("er du sikker?")) { ... }`. …
=> Survey templates

app/routes/overview/components/CompactEvents.js, app/routes/overview/components/Overview.js
MAJOR UPDATE. This always annoyed me, especially on mobile where pressing Events required the opening on the menu.
EDIT: Also added links to the Overview items. In the current form you can only press the image or the h3 title, with this change you press the whole headerspace
=> Make frontpage headers to links

app/routes/users/components/UserProfile.js
This fixes the crash when navigating from the event administrate route
to a user profile. The bug occured because we send only the group ids
from the administrate endpoint. When mapping ids to the corresponding
elements, we then get a list full of 'undefined' values.
Maybe we should fix this in the selectors? And if so, we should do it everywhere!
=> Fix user profile bug

app/routes/events/EventDetailRoute.js
The prop is called 'loggedIn', not 'isLoggedIn'. The value `isLoggedIn`
was always undefined, and therefore the initial interest/fav request was
never executed.
=> Fix prop typo in event interest/fav fetching

app/components/Editor/Editor.css, app/components/Form/CheckBox.css, app/components/Form/RadioButton.css, app/components/Toast/ToastContainer.js, app/routes/overview/components/Overview.js, app/routes/quotes/components/Quote.js
- Fixes the z-index of the editor so that it's not visible over modals
- Adds border to the disabled Checkbox
- Removes `cursor: pointer` from disabled radio buttons
- Fixes #1131 
- Removes the dot on the frontpage (meant to separate event info) from articles
- Fixes the z-index of the Toast so that it appears above anything with z-index 1 (radio buttons and checkboxes, for instance)
=> Various style fixes and quote deleting

app/routes/overview/components/CompactEvents.js
Depends on #1149 
This sorting did nothing, and with the new back-end sorting it works without any sorting in the front-end.
=> Sort overview events by time and id

app/components/Header/Header.css, app/components/Header/index.js
fix #839 by uniting the search and menu botton.
before: 
After:
=> Unite search and menu button

app/components/Search/utils.js, app/reducers/allowed.js, app/routes/events/components/Admin.js, app/routes/surveys/AddSurveyRoute.js, app/routes/surveys/components/SurveyEditor/Option.js, app/routes/surveys/components/SurveyEditor/Question.js, app/routes/surveys/components/SurveyEditor/SurveyEditor.js, app/routes/surveys/components/SurveyList/SurveyItem.js, app/routes/surveys/components/surveys.css, app/routes/surveys/utils.js
- Adds surveys to navigation menu
- Adds "Lag spørreundersøkelse" to event detail
- Adds functionality for removing options when creating or editing an event
- Fixes various other small issues outlined in #1165
Deleting options:
With this PR and #1163, I believe Surveys could potentially be launched. Doing so would only involve giving sudo survey permissions to fagkom and bedkom, plus loading the template fixtures in the prod database (@odinuge knows which ones). 
The last four issues in #1165 remain unsolved and will likely stay that way until I return in april (except disabled forms heh @SmithPeder), so you'll have to consider whether they are necessary for launching the feature. In particular, I think #1164 might actually warrant delaying the launch. #1170 and #1171 are also worth …
=> Launch(?) Survey adjustments

app/routes/surveys/AddSubmissionRoute.js, app/routes/surveys/AddSurveyRoute.js, app/routes/surveys/EditSurveyRoute.js, app/routes/surveys/components/SubmissionEditor/AlreadyAnswered.js, app/routes/surveys/components/SubmissionEditor/SubmissionContainer.js, app/routes/surveys/components/SurveyEditor/SurveyEditor.js, app/routes/surveys/components/surveys.css
Adds a note about how mails are sent when a survey activates (for Bedkom and Fagkom). Also adds a separate page for when users try to fetch a survey they have the permissions to answer but that isn't active yet.
=> Survey mail

app/routes/surveys/AddSubmissionRoute.js, app/routes/surveys/SubmissionsRoute.js, app/routes/surveys/SurveyDetailRoute.js
Ever since ActionGrant changed, permissions functionality in surveys has been broken unless you navigate from the list view first every time. This fixes that by using object permissions.
=> Use object permissions in surveys

app/components/NavigationTab/NavigationTab.css, app/routes/surveys/components/Submissions/SubmissionSummary.js, app/routes/surveys/components/surveys.css, app/routes/surveys/utils.js
Removes options with 0 selections from the pie charts and updates colors:
Makes text answers more distinct:
Adds some room between title and menu in NavigationTab (the green on the right):
=> Adjust survey result page

app/routes/events/components/EventDetail/EventDetail.css, app/routes/events/components/EventDetail/index.js
Requires https://github.com/webkom/lego/pull/1183
Replaces the event signup form with an error message with links to surveys when user has unanswered surveys.
Feel free to comment on the wording or styling, this is mostly a quick and dirty version.
=> Disallow event registration when user has unanswered surveys

app/actions/SurveyActions.js, app/actions/SurveySubmissionActions.js, app/reducers/surveys.js, app/routes/surveys/SubmissionsPublicResultsRoute.js, app/routes/surveys/SubmissionsRoute.js, app/routes/surveys/components/AdminSideBar.js, app/routes/surveys/components/Submissions/Results.js, app/routes/surveys/components/Submissions/SubmissionPage.js, app/routes/surveys/components/Submissions/SubmissionPublicResults.js, app/routes/surveys/components/Submissions/SubmissionSummary.js, app/routes/surveys/components/surveys.css, app/routes/surveys/index.js, app/routes/surveys/utils.js, package.json, yarn.lock
Requires https://github.com/webkom/lego/pull/1193/files. 
Adds a button that lets admin users get a shareable link that makes survey results publicly available, mainly for the purpose of allowing companies to see the result of their own events.
Also adds an entirely separate page to view those public results. This looks basically the same as the admin version, except all navigation and other admin-only stuff is gone.
=> Survey token

app/actions/ActionTypes.js, app/actions/SurveyActions.js, app/reducers/surveys.js, app/routes/surveys/AddSurveyRoute.js, app/routes/surveys/EditSurveyRoute.js, app/routes/surveys/SubmissionsRoute.js, app/routes/surveys/SurveyDetailRoute.js, app/routes/surveys/TemplatesRoute.js, app/routes/surveys/components/AdminSideBar.js, app/routes/surveys/components/Submissions/SubmissionIndividual.js, app/routes/surveys/components/Submissions/SubmissionPage.js, app/routes/surveys/components/Submissions/SubmissionSummary.js, app/routes/surveys/components/SurveyDetail.js, app/routes/surveys/components/SurveyEditor/SurveyEditor.js, app/routes/surveys/utils.js
There's a problem when deleting surveys. They are both Persistent and part of a one-to-one relation, which means that when you delete a survey for a particular event, you can never create a new survey for that event again.
There are several solutions to this. One is to remove "PersistentModel" from Surveys, and I strongly considered that option. However, that would mean deleting a survey also deletes all submissions for that survey, which makes a small fuckup pretty devastating. 
Another is to remove the OneToOne aspect of the event-survey relationship, but that's a pretty major change as I've assumed that relationship for several features both backend and frontend.
So while the core problem has yet to be solved, I decided to instead just remove the `delete` functionality from the front …
=> Disable deleting surveys

app/routes/surveys/utils.js
I thought 6 options would be enough, but already in the first 3 surveys, several questions have used more. So we need more available colors for the pie charts.
=> Add more colors to the survey results pie charts

app/routes/bdb/components/bdb.css
The issue of a filenames begin to long in the bdb detail is already fixed by  `{truncateString(name, FILE_NAME_LENGTH)}`, so on refresh Jonathan Eriksen issue would have disappeared. This just limits the width of the span, so on upload the filename will line-break.
=> Fix filename too long 'issue'

app/routes/surveys/components/SubmissionEditor/SubmissionEditor.js
When clearing a textField, all fields get the value undefined...
My guess is that this is a hidden bug in a reducer inside `redux-form` (we use an old version).
=> Fix strange form bug in surveys

app/reducers/frontpage.js
Since our sorting algorithm isn't `O(0)`, we need this. :100: This fixes the flashing on the frontpage when two events have the same date, and the SSR and client sorts with a different pace.
This is the output of `moment().format("x")` (unix-time) inside the sorting algorithm. We cannot give varying constants as input to our sorting algorithm, resulting in strange non-deterministic input. 
Client:
Server side renderer
Result: `node>chrome`
=> Make event sorting stable and deterministic (sort of, atleast)

app/components/Form/EditorField.js
This is because SSR breaks the editor.
=> Disable SSR when using editor fields

app/routes/surveys/components/Submissions/SubmissionPage.js
When you are at "Summary" then "Individual" is bold, and vice versa. This fixes that.
=> Summary and individual are inverted

app/routes/overview/components/LatestReadme.css, app/routes/overview/components/LatestReadme.js
The frontpage readmes had a set `150px` width, which for many smaller viewports would mean that only one readme could fit on each row. Setting the width to a `percentage` fixes this.
**::before**
**::after**
=> Remove fixed width value for readmes on frontpage

app/routes/overview/components/Overview.css, app/routes/overview/components/Overview.js
In light of the wishes of Abakom (and personal agreement to remove it before its useful) to remove "kunngjøringer" from the frontpage (feeds basically, but only announcements as is), I've removed it and replaced it with the prettier Weekly articles section. 
This is not meant as a permanent fix, rather a quick fix to improve upon the existing before we can work more on the structure (which we know it will change in the future).
Announcements can still be viewed from your notifications.
Please approve of this change <3
=> Temporary frontpage fix - remove feeds, insert weekly

app/routes/pages/components/PageDetail.css
=> Change css from object fit cover to scale-down

app/routes/events/EventDetailRoute.js, app/routes/events/components/EventDetail/index.js, app/routes/events/components/RegistrationMeta.js
I'd like to get a spot on the Julebord, but I don't know where I am in the waiting registration list! Here's something to make waiting to get moved out of the waiting registration list a little more exciting.
I have implemented a prop for EventDetail that specifies the position of the current registration in its registration pool. This value is displayed accordingly if the pool is "Venteliste".
=> Display position of registration in waiting registration list

app/components/DisplayContent/index.js
This warning seems to have gone by unnoticed. Looks like a bug introduced in #1130, maybe started showing up with a ReactDOM update?
As far as I know, the ID is only being used for testing the Comment component. For whatever reason, `htmlId` still passes as `id` and the test passes!
```
PASS app/components/Comments/__tests__/Comment.spec.js
● Console
console.error node_modules/fbjs/lib/warning.js:33
Warning: React does not recognize the `htmlId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `htmlid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in div
in DisplayContent
```
=> Use id instead of htmlId

app/routes/events/components/CalendarCell.js, app/routes/events/components/EventList.js
Pills showing "0/0" look slightly ugly in my opinion, so here I have simply removed the pills when the total capacity of the event is zero (which I assume is what qualifies as some event not requiring registration). Showing something else is an alternative - let me know if you would prefer that.
Note that this also applies to the tooltips in the event calendar.
Speaking of events that do not require registration - When researching how to approach this, I stumbled upon similar logic elsewhere in the application from #1293 which does not appear to be correct:
https://github.com/webkom/lego-webapp/blob/be4a72a10df25a9f489e2a86c842909eef271a6d/app/routes/overview/components/EventItem.js#L32-L38
I believe this would result in "Ingen påmelding" when the event has nonzero capacity but no …
=> Don't show 0/0 attendance pills for events

app/routes/brand/components/BrandPage.css, app/routes/brand/components/BrandPage.js
All ul list elements in the webapp got this new ul styling. CSS-modules only hash/scope the custom classNames
=> Remove global css

app/routes/overview/components/EventItem.css, app/routes/overview/components/EventItem.js
Long ago I wrote some bad code that made all events 0/0 or 0/x say Ingen påmelding. This was wrong as all events that were yet to open got this message. Long ago we fixed the serializer so activation time is sent with the event.
This will(should) add a better tooltip under the event. I think I've thought of all scenarios that can happen to an event.
=> Fix Ingen påmelding tag

app/routes/events/components/EventDetail/index.js, app/routes/events/components/EventEditor/index.js, app/routes/overview/components/EventItem.js
This should cover all the cases for events. Checking the `TBA` is a big hack, but it works quite well since `TBA` is the default value for the event, and 99% of `TBA` events say `TBA` as the location.
The TBA check is also the last check. So if you have an open event and write TBA you will get TBA as a tooltip. I think this is fair because if the user writes TBA on the location they can't complain when they get TBA.
=> Fix tooltip for events

app/components/EventItem/index.js, app/components/EventItem/styles.css, app/models.js, app/reducers/events.js, app/routes/events/components/Calendar.js, app/routes/events/components/EventList.css, app/routes/events/components/EventList.js, app/routes/events/components/Toolbar.css, app/routes/events/components/Toolbar.js, app/routes/overview/components/NextEvent.js, app/routes/overview/components/Overview.js, app/routes/users/components/UserProfile.js, app/utils/constants.js
Closes #1334
This will allow events to be filtered on the `/events` route. I've pulled out the `EventItem` component and made it a lot more responsive to props and time differences. I've also fixed a lot of flow, bad code, old js and so forth in many on the files. This includes some bad css when it comes to the mobile view of this page.
It uses the `react-select` component and will choose a filter based on the user selected. I've put in the three most obvious filters:
- Show all
- Available for registration
- Will open soon
It will also sort on the best attribute available. This means that when the user sorts on all events, the events are sorted by they `StartTime`, but when the user sorts on admission opening the events are sorted by their `ActivationTime`.
**Filter selection**
**After …
=> Event filtering

app/components/Form/TextInput.css
The redux-form placeholder text has different color than react-select form placeholders
=> Fix global field placeholder style

app/routes/events/EventCreateRoute.js, app/routes/events/components/Admin.js
Solves https://github.com/webkom/lego/issues/1355
This allows the user to create a new event based on another event (use an old event as template)
This is done via query params.
=> Add function for creating event from template

app/routes/overview/components/CompactEvents.css, app/routes/overview/components/CompactEvents.js, app/routes/overview/components/EventItem.css, app/routes/overview/components/EventItem.js, app/routes/overview/components/Overview.js, app/routes/overview/components/PublicFrontpage.js, yarn.lock
Use word-break: break-word on event titles so that the browser breaks words that cannot fit on one line.  
Add a temporary truncate fix on compactEvent titles for small screens.
=> Fix frontpage width issue on smaller screens

app/routes/admin/groups/components/GroupMembersList.js, app/routes/users/components/UserProfile.js
Adds internal email, if it exists, to profile page and group membership list. Also changes email text to links.
Fix https://github.com/webkom/lego/issues/1374
=> Add internal email to profile & membership list

app/actions/CompanyActions.js, app/routes/company/components/CompanyDetail.js
- Fix URLs to events from CompanyDetail
- Load newest events rather than oldest event for the company
See https://abakus.no/companies/4621 to see both these issues, it has non-working event links and is missing the two newest events.
=> Fix CompanyDetail events display

app/components/Editor/Sides/Buttons.js, app/components/Modal/index.js
- Prevent default on sidebutton click to prevent safari from re-focusing input field and therefore closing modal. 
- Move a prop in Modal to remove warning.
Fixes https://github.com/webkom/lego/issues/1469
=> Fix editor image upload in safari

app/routes/events/components/JoinEventFormCountdownProvider.js
Fikser dette captcha timeren?? Hvis ja, det er litt kjipt når captchaen tar over ett minutt å løse og den først vises ett minutt før påmelding. Hvis feil, please send help
=> Change time for captcha to show from 1 minute before event opens to 90 seconds

app/routes/events/components/EventEditor/index.js
Fix über annoying sentry error: https://sentry.abakus.no/webkom/lego-webapp/issues/6433/?referrer=slack
Also make atttendanceStatus clickable in event editor. 10/10
=> Add button on attendance status on event editor

Dockerfile, package.json
This makes it a lot funnier for external contributors to debug code when running on abakus.no.
Would make stack traces like seen here https://github.com/webkom/lego/issues/1481 way more human readable.
=> Enable sourcemaps in prod (aka. ship them in prod)

app/models.js, app/routes/events/components/EventAdministrate/Abacard.css, app/routes/events/components/EventAdministrate/Administrate.css, app/routes/events/components/EventAdministrate/Attendees.js, app/routes/events/components/EventAdministrate/RegistrationTables.js
- Add the admin registration count to the attendance list header, as seen below.
- Add orange color to the registrations in the waiting list, and also add a seperate icon for admin registrations (with message if you hover over the icon), as seen below.
=> Change wait-list icon color and add a separate icon for admin registrations in the attendance list

app/models.js, app/reducers/forms.js, app/routes/events/EventCreateRoute.js, app/routes/events/EventEditRoute.js, app/routes/events/components/EventEditor/EventEditor.css, app/routes/events/components/EventEditor/index.js, app/routes/events/components/EventEditor/renderPools.js, app/routes/events/utils.js
> Dependent on https://github.com/webkom/lego/pull/1488
- Each event has a field named `eventStatusType` that sets specific criteria for that event.
- Types [`TBA`, `NORMAL`, `OPEN`, `INFINITE`]
When selecting **TBA** the event will automatically be set to `pools = []` and `location: 'TBA'`.
This is to be used when only the time and date of an event is known, but not any specifics about pool sizes and locations.
When selecting **NORMAL** the event will act like a normal event, and all the normal fields will appear.
When selecting **OPEN** the event will set `pools = []`, but it will allow the user to set location. This is to be used for events like _LaBamba Fest_ and other events that require no registration.
When selection **INFINITE** the event will set `pools = [...one-pool]` and allow …
=> Event status type

app/models.js, app/routes/events/EventDetailRoute.js, app/routes/events/components/Event.css, app/routes/events/components/EventAdministrate/Abacard.js, app/routes/events/components/EventDetail/index.js, app/routes/events/components/JoinEventForm.js, app/routes/events/components/RegisteredSummary.js, app/routes/events/components/RegistrationMeta.js, app/routes/events/components/StripeElement.css, app/routes/events/components/StripeElement.js, app/routes/events/utils.js
Depends on https://github.com/webkom/lego/pull/1512
- Add a few more payment statuses
- Disable payment button during payment
- Show stripe payment button after event has started
- Update payment status real time
- Simplify registration form
- Move registration form to right side of screen
=> Event detail changes

app/Root.js, app/styles/globals.css, package.json, yarn.lock
* Fixes https://github.com/webkom/lego/issues/1520
Quick fix for v3, but when upgrading to v4 this won't work anymore. But the people at React Router has provided an alternative so no biggie. 
This is the package used (plug and play): https://github.com/taion/react-router-scroll
Further reading for v4 solutions and reasoning for removing it (tldr: browsers are starting to implement it):
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md
https://reacttraining.com/react-router/web/guides/scroll-restoration
Note: Removed global `scroll-behavior: smooth` css, since it makes the screen jump when navigating, and while this property is nice for admin pages like lego form and searching in those pages (groups, email etc), I think …
=> Add scroll-to-top/scroll restoration on route change.

app/components/Poll/index.js, app/components/Tooltip/Tooltip.css, app/components/Tooltip/index.js, app/routes/events/components/JoinEventForm.js, app/routes/events/components/RegistrationMeta.js
Modify tooltip compenent in order to make it look good regardless of where it is placed without the need for inline styling, as well as make it easier to customise how it is displayed.
Demonstration of being able to choose direction for the tooltip to render.
Before:
After:
Tooltips are now centered by default:
Able to specify the start of tooltips as well:
=> Tool tip fix

app/routes/company/components/CompanyDetail.js
'Address' is written with one d in Norwegian: https://www.naob.no/ordbok/adresse
=> Typo fix on CompanyDetail page

app/components/EventItem/index.js, app/models.js, app/routes/events/components/EventList.js, app/routes/overview/components/EventItem.js, app/routes/overview/components/Overview.js, app/routes/users/components/UserProfile.js, app/utils/eventStatus.js
`event.activationTime` is `null` if a user is not a member of the groups that are in a pool for an event.
This caused issues with displaying the attendance count correctly.
This fixes webkom/lego#1378 and fixes webkom/lego#1381.
**Before:** 
**After:**
**Before:** 
**After:**
**Before:**
**After:**
=> Correctly handle cases where activation time is null

app/routes/events/components/EventEditor/index.js
This fixes https://github.com/webkom/lego/issues/1552.
=> Remove option to require feedback on OPEN events

app/routes/events/components/EventDetail/index.js, app/routes/events/components/JoinEventForm.js
There is no point in showing registrations or information related to who has registered on `OPEN` and `TBA` events. Hide this and show a simple message instead.
Will continue on with https://github.com/webkom/lego/issues/1526 once this has been merged.
=> Hide registration part of the event details on OPEN and TBA events

app/actions/PageActions.js, app/reducers/events.js, app/reducers/meetings.js, app/reducers/pages.js, app/utils/__tests__/createEntityReducer.spec.js, app/utils/createEntityReducer.js
This will remove ish. `50%` of our reducers; aka. remove quite a lot of duplicate code. Most of the stuff we do is CRUD anyways.
PS: DO NOT MERGE INTO MASTER NOW. This should be merged into the `immer` branch when done (after we agree about the design of it :smile:)
Also some small adjustements to CER.
=> CreateEntityReducer delete

app/routes/overview/components/PublicFrontpage.js
Update link on frontpage to refer to fadderopplegg for 2019
=> Update link on public frontpage

app/routes/events/utils.js, app/routes/photos/components/GalleryPictureModal.js, package.json, yarn.lock
Fix lodash-es security alert by bumping to `4.17.15`
<hr>
Resolves https://github.com/webkom/lego-webapp/pull/1569
This is unused?? I can't find one import using this, and everything seems to be working good without it. Removed the dependency.
<hr>
Resolves https://github.com/webkom/lego-webapp/pull/1531
Bump to v5. Some small migrations with prop changes. The latest version is 5.4.0, but anything above 5.0.0 created some unwanted behavior(aka no behavior at all, cant swipe). I could not figure out the reason behind this, as all the breaking changes stated in the changelog was from v4 to v5, and not from 5.0.0 to 5.1.0... 😢
=> ༼ つ ◕_◕ ༽つ

app/models.js, app/routes/events/EventCreateRoute.js, app/routes/events/EventEditRoute.js, app/routes/events/components/EventDetail/index.js, app/routes/events/components/EventEditor/EventEditor.css, app/routes/events/components/EventEditor/index.js, app/routes/events/components/JoinEventForm.js, app/routes/events/components/JoinEventFormCountdownProvider.js, app/routes/events/components/__tests__/JoinEventFormCountdownProvider.spec.js, app/routes/events/utils.js
Event should have a dynamic registration close time.
Now it needs instant change of `registration_close_time` when user types hours in field and perhaps some styling.
Event:
Edit event:
=> Add registration close time

app/components/UserAttendance/AttendanceStatus.css
Fixes: https://github.com/webkom/lego/issues/1588
=> Fix styling for long pool names

app/routes/events/EventCreateRoute.js
Want to have the unregistration deadline 24 hours before event instead of 12
=> Change unregistration deadline to 24 hours before event

app/routes/company/components/CompaniesPage.js
Going to `/bdb` loads a ton of companies, with a slightly different schema than that of `/companies`. The backend calls are different. You might argue it would be better to remove these different company objects from state and then re-fetching the correct call, but this PR at least keeps the website from crashing when you navigate from `/bdb` to `/companies`.
=> Quickfix for navigation between bdb and companies

app/routes/bdb/components/SemesterStatusContent.js, app/routes/bdb/components/bdb.css
Fix oversized checkmark in bdb, and redesign bdb dropdown.
Fixes webkom/lego/issues/1678
Before: 
After:
=> Fix checkmark in bdb

app/actions/AnnouncementsActions.js, app/components/Feed/renders/announcement.js, app/models.js, app/routes/announcements/components/AnnouncementItem.js, app/routes/announcements/components/AnnouncementsCreate.js
Adds the option to send an announcement from a group. If specified, the selected group replaces the user as the sender. The user who creates the announcements is still shown in the timeline.
Resolve https://github.com/webkom/lego/issues/1389
=> Send announcement from a group

app/actions/PollActions.js
The action did not dispatch error codes to redux before, so the page would just endlessly load...
=> Render pagenotfound when accessing a poll with invalid id

app/routes/events/components/Event.css
Currently you are allowed to resize the text-area horizontally, which can yield quite weird results. This fixes that.
=> Add `resize: vertical` to .feedbackText

app/components/InfoBubble/index.js
If I've done this correctly it should prevent https:// company links from being prepended with http://. Alternatively import httpCheck from bdb utils?
=> Add check for https:// in company website link from backend.

package.json, yarn.lock
* Updated data to IANA TZDB `2019b`
* Fix: stabilize Array.sort [#762](https://github.com/moment/moment-timezone/pull/762)
* Fix `moment.tz.dataVersion` to return `2019a` [#742](https://github.com/moment/moment-timezone/issues/742)
* Update path in bower.json
* Updated data to IANA TZDB `2019a` [#737](https://github.com/moment/moment-timezone/issues/737)
* Start shipping both a 1970-1930 file and a rolling 10-year file [#614](https://github.com/moment/moment-timezone/issues/614) [#697](https://github.com/moment/moment-timezone/issues/697)
* Fixed bug where `_z` time zone name was not cleared with `.local()` or `.utcOffset(offset)` [#738](https://github.com/moment/moment-timezone/issues/738)
=> Bump moment-timezone for security vulnerability

app/routes/admin/email/EmailListsRoute.js, app/routes/admin/email/EmailUsersRoute.js
The admin/email route bugs out after a previous bugfix
=> Fix loading indicator in email routes

app/actions/QuoteActions.js, app/components/RandomQuote/RandomQuote.js
Depends on the backend in https://github.com/webkom/lego/pull/1715.
Adds a local state to Random Quote (through hooks 😎) that keeps track of what random quotes the user already has seen. This prevents getting duplicates when repeatedly clicking ♻️to browse multiple random quotes, which of course is a behaviour we want to support.
When all quotes have been seen, the backend falls back to providing "stale" quotes.
=> Ensure the Freshness™ of random quotes

app/components/EventItem/index.js, app/components/Poll/Poll.css, app/components/Poll/index.js
With this change, users have to click before giving their vote. A blur effect is applied when the user hovers over the poll. 
Solves https://github.com/webkom/lego/issues/1712 (Needs to be marked as closed manually)
=> Require all poll options be visible before being able to vote

app/components/Image/Image.css, app/routes/overview/components/ArticleItem.css
Fixes an issue where images using the `<Image/>` component did not retain aspect ratio. As well as the article component on the frontpage.
Resolves https://github.com/webkom/lego/issues/1733
Resolves https://github.com/webkom/lego/issues/1732
=> Fix image aspect ratio

app/components/RandomQuote/index.js
Since the quote is fetched during ssr, it doesn't have to be fetched on
the client. Only fetch using prepare when there is no quote. The "new
random quote" button will still work.
This fixes the annoying flicker when the random quote change during
first client render.
=> Fix double/triple fetching of random quote

app/Root.js, app/components/NavigationTab/NavigationLink.js, app/routes/photos/components/GalleryDetail.js, app/routes/photos/components/GalleryPictureModal.js, app/routes/photos/components/Overview.js, app/routes/photos/index.js
Changes:
91db5ec1 (Odin Ugedal, 75 seconds ago)
Fix scrolling to the botton when viewing photos
onKeyDown is shitty
393f0d25 (Odin Ugedal, 2 minutes ago)
Add hack that retains the scroll position
When clicking "Back", it will use history.back in case there is something
in the hash. This is only the case if the previous page was
/photos
87a2fdda (Odin Ugedal, 3 minutes ago)
Don't scroll when navigating inside gallery
=> Fix a shitload of gallery scrolling issues

app/routes/quotes/QuotesRoute.js
Fixes an issue where the quotes route did not fetch approved/unapproved routes upon changing the query params.
=> Refetch quotes on query change

app/routes/pages/PageDetailRoute.js
I know the for loop is not ideal, yet none of the array.prototype was able to execute the dispatches in the correct order. Fixing this sentry error.
https://sentry.abakus.no/webkom/lego-webapp/issues/8198/?referrer=slack
=> Fetch groups before memberships on pages

app/actions/FileActions.js
Per the mail regarding image upload issues. The problem was that the filename has `Å` in it (on mac). This was parsed as **JS** as as ["a", "<030a>", "a", "<030a>"], which is a `offset upper rounded` char. This will cause the backend to reject the image.
Example, running split on a string "ååå.png" gives:
To solve this we can swap the the `regex` so it removes all chars we dont want.
=> Don't send UPPER ROUND char to backend

app/components/Form/SelectInput.js, app/components/Search/withAutocomplete.js, app/routes/bdb/components/OptionsBox.js, app/routes/bdb/components/SemesterStatusContent.js, app/routes/bdb/utils.js, app/routes/companyInterest/CompanyInterestEditRoute.js, app/routes/companyInterest/components/CompanyInterestList.js, app/routes/companyInterest/components/CompanyInterestPage.js, app/routes/companyInterest/utils.js, cypress/integration/company_interest_spec.js
Implements several updates to company-interest and BDB as per requests from bedkom:
- Adds functionality for selecting registered BDB companies when submitting a company interest form. If the company has not been registered previously, submitting with any name is still supported too. When a BDB company is chosen, the appropriate semester in the BDB table is updated to "Interested".
- Adds phone number as mandatory fields to company-interest.
- Updates the static text on the company-interest page.
- Additionally, the PR implements a "fix" to the BDB that made it crash in strict mode (didn't affect prod; made localhost crash).
Depends on backend in https://github.com/webkom/lego/pull/1794
=> Company interest / BDB requests

app/components/ProgressiveImage/index.js, app/routes/photos/components/GalleryPictureModal.css
https://github.com/webkom/lego/issues/1821
Before:
After:
=> Fix aspect ratio in gallery images

app/components/SpecialDay/index.js
When the follwing code runs in prod
```js
<SpecialDay>
{config.environment !== 'production' && (
<div
style={{
backgroundColor: 'red',
color: 'white',
fontWeight: 'bold',
padding: '10px'
}}
>
This is a development version of lego-webapp.
</div>
)}
```
it returns a `false`, making React.close go deaddead
=> Fix the bad code

app/utils/themeUtils.js
Discovered that the checks needed to include document as well, in order to load the darkMode-modifided logos properly. Should be merged asap, as the logos will sometimes be loaded as their light-mode variant without this fix.
=> Fix: Improve client/ssr-side checks.

package.json, server/index.js, server/pageRenderer.js, yarn.lock
This will hopefully fix sourcemaps on sentry.
`source-map-support` is not compatible with sentry and will mess up sourcemap matching.
=> Fix sourcemaps on sentry

app/routes/pages/components/PageEditor.js
Since the form for creating a new page does not have any initialvalues, we have to include a bypass the check on whether or not the form is loaded when creating a new page.
=> Fix editor in pagecreation route

app/routes/overview/components/ArticleItem.css, app/routes/overview/components/Overview.css
Tags were not wrapping properly, so articles with alot of tags or long tags looked weird.
**Before**:
**After**:
=> Fix some edge-case css on frontpage articles

app/routes/events/index.js
Fixes a bug where the events/attendees route results in 404 by removing the 404 route component. While this results in an empty sub page when trying to access an invalid sub url of events/eventid/administrate, this is the way it has been done on the rest of the routing, and I do not consider it a massive problem
=> Fix bug where attendees route results in 404

app/routes/photos/GalleryPictureRoute.js, cypress/integration/home_page_spec.js
Makes website not crash when going directly to a picture url, as in not going via the gallery route. To test simply to a specific picture and hard refresh. Fixes [this](https://sentry.io/organizations/abakus/issues/1657741862/?project=5018548&referrer=slack) sentry error.
=> Fix crash when accessing a picture url directly

app/routes/surveys/components/Submissions/Results.js, app/routes/surveys/components/Submissions/SubmissionPage.js, app/routes/surveys/components/Submissions/SubmissionPublicResults.js, app/routes/surveys/index.js
Fixes https://github.com/webkom/lego/issues/1880
Also fixes an issue where the public results route had the option to change chart type, but that crashes the page since the user does not have edit permissions. For now I just removed the options, but there are some issues where the user is logged out when navigating there which should be fixed. (Super minor issue without side-effects).
=> Fix some survey bugs

.drone.yml
Testing adding yarn caching to drone. This is such a simple way to improve build time, I don't know why we haven't done it before :upside_down_face: 
> Tested with very high load on the server! (all cores 90-100%)
**Before:**
**After:**
The time difference won't be as dramatic under more forgiving circumstances, but it should improve total time by ~1 min I think.
=> Drone caching

app/components/CommentForm/index.js, app/components/DisplayContent/index.js, cypress/integration/create_event_spec.js, cypress/integration/event_visit_spec.js, package.json, server/index.js, yarn.lock
- Updated editor to v1.2.0. This update allows the editor to be server-side rendered when disabled (aka. fixes ssr currently broken in staging). The fix here is just to use jsdom to serialize the string value to HTML if it is rendering on node.
- Finally fixes ssr on event detail when logged in :100:! No more `undefined_render_error` from sentry! (or much less at least).
The fix is :1st_place_medal: imo. We just render the comment form in the `disabled` state, and use whatever events we can to re-render it in the `editable` state.
Tested on mobile and desktop. (on mobile it should trigger on `scrollEvent` 99% of the time as the comments are always at the bottom of the page, but I added an `onPointerDown` for safety. So if someone has a tablet or some large touch-screen feel free to test …
=> Update editor to 1.2.0 & fix events ssr

app/routes/overview/components/Overview.css, app/routes/overview/components/Pinned.js
Revert and fix this https://github.com/webkom/lego-webapp/pull/1848
Just allocate x amount of space for tags, don't allow them to wrap all over the place.
=> Fix this ugly ****

app/routes/events/index.js
Fixes an issue where user information was missing from event list and calendar routes.
This caused the "you must be logged in register" text showing up even though the user is registered
and the add to calendar missing from the bottom of both pages.
=> Fix issue with missing user info in event routes

app/routes/events/components/StripeElement.js, server/pageRenderer.js
This was a PITA to test locally, but I'm 90% sure it's good now.
Note: To test payment request API (google pay, apple pay) you need to add a test card from https://stripe.com/docs/testing in order for the payment request button to show! (atleast for google pay).
=> Fix stripe payment request form

app/routes/events/components/StripeElement.js
The new stripe integration only attached user info to payment request payments, so payments using
the card form does not have a user attached. This means that you can not see who made the payment,
which is pretty dumb.
=> Add user data to stripe card payments

app/reducers/pages.js, app/routes/pages/PageDetailRoute.js
As we need a place for privacy information about abakus.no, a "personvern" category is needed.
=> Add Personvern to pages

app/routes/joblistings/JoblistingRoute.js
When a joblisting has workplaces: [], they are not included when filtering workplaces=Annet.
Before:
After:
=> Include joblistings where workplaces is [] when filtering for "Annet"

app/components/Form/DatePicker.js, app/components/Form/TextInput.js
Fix a bug where the datepicker field is not loaded with the correct initialvalue. This bug would result in the datepicker being initialized to the current date when editing an old meeting, which is rather annoying. Also remove an error with a field intended as read only not being set as read only
=> Fix bug in editor datepicker

app/routes/companyInterest/components/CompanyInterest.css, app/routes/companyInterest/components/CompanyInterestPage.js, app/routes/companyInterest/utils.js
Closes webkom/lego#1942
Added "Digital presentation" as an event option, edited "BedEx" as requested and corrected header colors in dark theme
=> add/edit event options and fix color of headers in dark-theme

app/routes/users/UserConfirmationRoute.js, app/routes/users/components/ChangePassword.js, app/routes/users/components/PasswordField.js, app/routes/users/components/PasswordStrengthMeter.css, app/routes/users/components/PasswordStrengthMeter.js, app/routes/users/components/UserConfirmation.js, app/routes/users/components/UserResetPassword.js, app/routes/users/components/UserSettings.js, app/routes/users/components/passwordStrengthVariables.js, app/utils/validation.js, cypress/integration/password_change_spec.js, package.json, yarn.lock
Implement ZXCVBN password validator from Dropbox
https://github.com/dropbox/zxcvbn
https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/
Missing: Get user data to validator for reset password. Decided this is ok.
I also added confirm password fields to create user and reset password. 
Create user:
Reset password:
Change password:
=> zxcvbn password validation

app/routes/events/components/EventList.js
to avoid clearing the field so that the change handler does not set state to null
video : https://drive.google.com/file/d/12hgDxQ5FTN8rGj5q8HCTVkti7n3quB9n/view?usp=sharing
=> Added backspaceRemoves and deleteRemoves props to EventList Select

app/actions/FrontpageActions.js, app/components/RandomQuote/index.js, app/routes/app/AppRoute.js, app/routes/events/EventDetailRoute.js, app/routes/overview/IndexRoute.js, package.json, yarn.lock
Stop waterfall fetching stuff in ssr. This cleans up a bit, but require
the fixes in @webkom/react-prepare to properly speedup stuff...
My simple testing gives when running ssr locally (compared to abakus.no):
- `/` (authenticated as me) 0.80s - 1.20s vs 3-4-5sec (and constant timeouts, since 4sec is ssr timeout).
This also fixes some crazy double fetching of quotes...
(might be some rough edges, so I guess we can try it on staging first...)
=> Speedup ssr by a s***ton

app/routes/events/components/JoinEventForm.js
Only show penalty notice when event is actually using penalties. By doing this we avoid saying that the registration has been postponed for the user, even though that is not the case.
=> Check if event is using penalties when displaying penalty notice

.drone.yml
Yesterday @odinuge and I talked about **prod**, and that prod can be a little misleading branch name, as it doesn't actually mean that anything will go into production. The real action is that a **docker build** will occur, and the result will be an **image**
This has always been difficult to explain to new members, as we say things like:
> 1. Push the master to prod??
> 2. Then push the prod to staging??
> 3. Then push the prod to prod??
It's obvious for us what it means, but it doesn't really make sense when you try to talk about it, and/or explain it.
Rename the prod branch to **docker** as this is what actually happens. Then we can more easily explain the process like:
> 1. Push master to the docker branch in order to trigger a new build
> 2. Deploy this new build staging to check …
=> [DISCUSSION] Rename prod -> docker

app/components/RouteWrapper/index.js, app/routes/contact/index.js, app/routes/index.js
Makes it a bit easier to find the route. And a lot of people (me including) forget that it is
`/contact` and not `/kontakt`. This makes both of these valid.
=> Add /kontakt path to contact form path

app/routes/brand/components/BrandPage.js
There have been colour updates to the wiki not reflected on abakus.no, this commit gets the standard colours up to date.
https://wiki.abakus.no/display/pr/Grafisk+profil:
https://abakus.no/brand:
=> Update brand colours to be consistent with wiki

app/routes/overview/components/PublicFrontpage.js, app/routes/pages/components/LandingPage.js, app/routes/pages/components/subcomponents/TextWithTitle/index.js
Change "Kommunikasjonsteknologi" to "Kommunikasjonsteknologi og digital sikkerhet" on public pages. Image on om Abakus page needs an update as well.
=> Changed Komtek name in public pages

config/webpack.server.js, package.json, yarn.lock
Reverts webkom/lego-webapp#1949
Failed cypress tests after merge :eyes:
=> Revert "Bump webpack-node-externals from 1.7.2 to 2.5.2"

app/components/Header/index.js, app/routes/app/AppRoute.js, app/routes/overview/IndexRoute.js, app/routes/overview/components/Overview.js
Moved the front pages' loading icon from pinned article to website logo.
Before:
After:
=> Move loading indicator

app/components/Header/index.js
Changes in #2033 was not properly tested in dark mode
fix #2033
Before
After
=> Fix darkmode logo in header

.babelrc, app/index.js, package.json, server/index.js, yarn.lock
`@babel/polyfill` is deprecated. The latest version of `@babel/polyfill` also uses `corejs2`, so this should fix the `(...).flat` is undefined errors we are getting:tm:. As `flat` and `flatMap` are stable as of corejs3 (is my understanding at lest)
=> Replace @babel/polyfill with corejs directly

app/routes/interestgroups/InterestGroupEditRoute.js, app/routes/interestgroups/InterestGroupListRoute.js
As the [sentry error](https://github.com/webkom/lego/issues/1945) states, a user that is not logged in and tries to edit or view the interest groups, receives a 401 error. Therefore, the user is now displayed the login page instead.
https://github.com/webkom/lego/issues/1945
Btw, the commit message references another PR by mistake :upside_down_face:
=> Route users to login page from interest groups when not logged in

app/components/Search/withAutocomplete.js
We pass filtered options with the autocomplete action. If we use
react-select default filtering, the already filtered results will be
filtered once again, removing some of the results that we want.
With some changes I am making to the postgres search backend, this will greatly improve the searching experience.
F.ex if there is a person with the name `Bob Carl Johnson`, searching `Bob John` on LEGO will return this user (with the new search), but react-select will filter it out :-1:.
=> Remove react-select filtering for autocomplete

.drone.yml
The CI trigger on PR does nothing, it just starts a bunch of backend containers and is annoying.
=> Don't run CI on PR

app/routes/overview/components/Overview.js
This is at least a temp solution to the "Pinned articles show up in both the _pinned_ component and the article list" problem.
=> Dont show pinned article twice on articles

app/routes/interestgroups/components/InterestGroupDetail.js
Fix webkom/lego#2152 
Now will all leaders of an interest group be shown, also if there are multiple leaders.
E.g. if there are 5 leaders in an interest group:
Before:
After:
=> Show multiple leaders of interest groups

app/routes/events/components/Event.css, app/routes/events/components/EventDetail/EventDetail.css, app/routes/events/components/EventDetail/index.js, app/routes/interestgroups/components/InterestGroupDetail.js
Fix webkom/lego#2151
Have the same style for warnings when you have unanswered surveys and penalties.
Before:
After:
After (dark theme):
=> Set nice style on unanswered surveys warning

app/routes/events/components/Toolbar.css, app/routes/events/components/Toolbar.js
NavLink need an exact prop, in order for it not always be active (see images)
*Before:*
*After:*
=> Fix active NavLink

app/components/Header/index.js, app/routes/users/components/UserSettings.js, app/utils/themeUtils.js, server/pageRenderer.js
Solves https://github.com/webkom/lego/issues/2000
See https://github.com/webkom/lego/pull/2197 for backend PR
Added option for auto theme where the theme is chosen based on device settings. This is now the default theme option (does not affect existing user preferences) and is applied when not logged in.
'Light' and 'Dark' options take precedence and will ignore OS theme.
=> Auto theme option

app/components/Poll/Poll.css, app/components/Poll/index.js, app/reducers/polls.js, app/routes/polls/PollsDetailRoute.js, app/routes/polls/components/PollEditor.js
As requested by Glorious Leader @AdrianAndersen, this PR will enable a poll to hide the number of votes cast for each option if the corresponding backend-PR is accepted. See PR [webkom/lego#2196](https://github.com/webkom/lego/pull/2196) for more details.
=> Enable hiding number of votes cast for individual poll options

app/components/Form/RadioButton.css, app/components/Form/RadioButton.js, app/components/Table/Table.css, app/components/Table/index.js, app/routes/events/EventAdministrateRoute.js, app/routes/events/components/EventAdministrate/Attendees.js, app/routes/events/components/EventAdministrate/RegistrationTables.js, app/routes/events/components/EventAdministrate/index.js
Fixes https://github.com/webkom/lego/issues/1993
Added: 
- column with a number for every attendee (the number is the index of the attendee in the array of all registered attendees, ie. the numbers will be arranged so that number 1 is the first who signed up for the event, number 2 is the second and so on)
- column with the pool of the attendee
- ability to choose which column to show given a set of possibilities (for example i have used this for the columns grade and pool, because they're normally the same (so you don't want to show them both), but in the few cases when they aren't it's nice to be able to choose which one you want to see)
- ability to search in the name column (functionality was already implemented, just added the ability for this specific column)
- ability to sort the …
=> Improve event administrate table

app/routes/overview/components/Overview.js, app/routes/overview/components/PublicFrontpage.js
The banner is shown both on the public frontpage and the logged in page.
I felt like the lightBlue color was fitting and stood out nice:
=> Change link to FP on public frontpage & add banner to FP info

app/components/Header/index.js
This broke SSR for users with theme set to `auto` (default).
We already set the theme in the pagerenderer. So this was redundant
anyways.
=> Don't set theme unless on client side.

app/components/Banner/Banner.css, app/components/Banner/index.js, app/routes/overview/components/Overview.js, app/styles/variables.css
Text is longer to make sure people notice the change:)
Also removes 'revyBlue' and '--color-blue-revy' variables, as they were only used by the banner
=> Change banner to revyopptak

app/routes/users/UserProfileRoute.js, cypress/integration/profile_spec.js
cypress attempted to enter usersettings with the "Instillinger"-button before the given profilepage was fully loaded. 
This lead to cypress loading a page containing `... /users/undefined/settings/profile`, which does not exist. The button will now appear after all necessary props are loaded.
=> prevent cypress test from entering usersettings too early

app/components/Table/index.js
Fix webkom/lego#2322
By setting the container for the overlays to a container div that contains the table, they are no longer hidden by the tables overflow rules.
Before:
After:
=> Set container for table overlays to a div that contains the table

app/components/Table/index.js, app/routes/events/components/EventAdministrate/RegistrationTables.js
`Array.prototype.sort` has different implementations in Node and on
browsers, meaning that the resulting list was inverted on the browser,
leading to undefined behaviour. Returning 0 should quick fix this small
issue.
Fixes https://github.com/webkom/lego/issues/2318
=> Fix inconsistent admin registration list

app/routes/users/components/UserProfile.js
Fix webkom/lego#2333
Filters the badges for past memberships in interest groups, to only show interest groups where the user has been a member for more than two weeks.
=> Hide past interest group memberships with duration under two weeks

app/components/Form/RadioButton.css
Fixes webkom/lego#2315
Before:
After:
Tested with chrome, firefox and safari on macos, and chrome and firefox on linux.
=> Fix radio button alignment

app/components/Footer/index.js
Contact forms have reportedly been difficult to find, which is why we're adding an additional link in the footer. The link is only visible when a user is logged in, as the form itself can currently only be used by them (see https://github.com/webkom/lego/issues/2345). 
The word "Anonymt" is temporary, and may be removed with the new frontpage or when the form becomes accessible to outside individuals.
mobile:
=> Add temporary link to contact form in footer

app/actions/GroupActions.js, app/components/GroupForm/index.js, app/models.js, app/routes/interestgroups/InterestGroupCreateRoute.js, app/routes/interestgroups/components/InterestGroup.css, app/routes/interestgroups/components/InterestGroup.js, app/routes/interestgroups/components/InterestGroupList.js
> Also fix showBadge field that used by the action
This PR makes it possible to mark groups as active/inactive. For now, all I use it for is to differentiate between active and inactive interestgroups.
=> Add active field for groups

app/components/LoadingIndicator/LoadingIndicator.css, app/components/LoadingIndicator/index.js, app/reducers/forms.js, app/routes/events/components/Event.css, app/routes/events/components/JoinEventForm.js
This component will show between a REGISTRATION.REQUEST_REGISTER_SUCCESS and a
SOCKET_REGISTRATION.SUCCESS or FAILURE. The normal loading component
will still show between the registration initition and the request
register success. Note that since there is no coupling between the
registration and events, this logic is only stored in state and we cannot
determine whether to show the component based on the registration alone.
It's a _bit_ weird to store the `pendingRegistration` status in the form state, but it was where it sort of made the most sense to put it, and it should not affect any other form logic.
Solves https://github.com/webkom/lego/issues/2346
=> Add a more informative loading component when waiting for a pending registration.

app/routes/joblistings/components/JoblistingEditor.js
fixed add job listing so that it requires into and text fields before it makes a job listing. 
closes webkom/lego#1569
=> fix add joblisting so that it requires into and text

.babelrc, app/render.js, app/routes/events/index.js, app/routes/index.js, app/routes/users/components/ChangePassword.js, app/routes/users/components/UserConfirmation.js, app/routes/users/components/UserResetPassword.js, app/routes/users/utils.js, app/utils/validation.js, config/webpack.client.js, config/webpack.server.js, package.json, server/pageRenderer.js, server/ssr.js, yarn.lock
Also adds some tree-shaking and webpack optimization tweaks.
~The vendors chunk is still quite large. With zxcvbn using \~700KiB and recharts using \~500KiB. We should find a way to split these out from the main vendor chunk, and load async. (looking at this now).~
In the mean time, this should be alot better.
**Before:**
```
[1] WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
[1] This can impact web performance.
[1] Assets: 
[1]   a10340ceb228c90cbeb6.ttf (8.95 MiB)
[1]   app.20320511.js (6.44 MiB)
[1]   c2bd9cd4b22ff17d91c4.jpg (280 KiB)
[1]   5c3185a787083623adb4.png (348 KiB)
[1]   fa60fac19a5deb240e84.png (819 KiB)
[1]   45b8e04fc7022ab64c11.png (331 KiB)
[1]   vendors.ef812859.js (5.78 MiB)
[1]   styles.c6b02716d66620b130e6.css (272 …
```
=> Codesplitting on all routes using loadable-components

config/webpack.client.js, server/pageRenderer.js
The introduction of loadable-components and chunk-splitting broke the
development server. This fixes it by ignoring loadable-components
SSR, limiting chunk count to 1, and manually processing stats.
In the process of fixing SSR and the static build, I broke the dev build and HMR. Sadly,
loadable-components is not compatible with HMR, but we can just force webpack to only use one bundle
and we essentially bypass loadable-components and HMR works as intended.
=> Fix development build

.github/dependabot.yml
Dependabot has been awfully quiet on the webapp lately, so I suggest changing the schedule back to daily
=> Change dependabot schedule to daily

config/webpack.client.js, config/webpack.server.js, package.json, yarn.lock
Remove the unused immutable-js dependency
As far as I know, this has never been used, but it is definitively not used now.
=> Remove immutable-js dependency

.drone.yml
As we recently enabled the autoscaler for drone, we can remove the limit. As the limit hurts us with
the autoscaler enabled. We can turn this limit on again if needed and we decide not to use the
autoscaler.
=> Remove drone concurrency limit

app/actions/SearchActions.js, app/utils/configureStore.js, config/env.js, package.json, yarn.lock
Okay, \*Record Scratch* \*Freeze Frame\*, you're probably wondering how I ended up here ... so, it all started with my Wappalyzer showing Google Analytics on abakus.no. What? Yes, indeed. This made me go through our codebase in great rage and despair, but instead, all I found was traces of segment. That was _odd_, I thought to myself, in the dawn of night. I ended up removing the traces, but my curiosity led me elsewhere. Deep down in `pass old/pws` I found an ever forgotten username and password combination for no other than segment.io. And, well, you can bet your ass I went and checked it out. Surprisingly enough, two destinations had been set up ... one postgres database pointing to leia.abakus.no ... I checked it out, it was empty. The second, however, Google Universal Analytics™️. …
=> Remove traces of segment

cypress/integration/create_event_spec.js, cypress/integration/event_editor_spec.js, cypress/integration/event_payment_spec.js, cypress/integration/event_visit_spec.js, cypress/integration/joblistings_specs.js, cypress/support/commands.js, cypress/support/utils.js
As of Cypress v5.5 the type() command works fine with the slate editor so our workarounds are no longer needed. This also allows the editor test to be run on all browsers, not just Firefox, so i moved it into the same file as all the other event tests (event_editor_spec.js)
I also removed all editorFocus() commands, as it seems that clicking the editor also focuses it.
Closes webkom/lego#2353
=> Remove slate-editor cypress workarounds

Dockerfile
Mazemap needs to run a script in order to install correctly, and yarn
does not allow us to only ignore some scripts.
See https://github.com/yarnpkg/yarn/issues/7338
=> Remove --ignore-scripts from yarn in Dockerfile

app/components/Content/Content.css, app/components/Content/Content.js, app/components/EventItem/index.js, app/components/Gallery/index.js, app/components/GroupMember/index.js, app/components/Image/CircularPicture.js, app/components/Image/Image.css, app/components/Image/Image.js, app/components/Image/ProfilePicture.js, app/models.js, app/reducers/articles.js, app/reducers/pages.js, app/routes/articles/components/ArticleDetail.js, app/routes/articles/components/Overview.css, app/routes/articles/components/Overview.js, app/routes/company/components/CompaniesPage.js, app/routes/events/EventListRoute.js, app/routes/events/components/EventDetail/index.js, app/routes/interestgroups/components/InterestGroupDetail.js, app/routes/joblistings/components/JoblistingList.js, app/routes/overview/components/ArticleItem.js, app/routes/overview/components/EventItem.css, app/routes/overview/components/EventItem.js, app/routes/overview/components/Pinned.js, app/routes/overview/components/PublicFrontpage.js, app/routes/pages/components/LandingPage.js, app/routes/pages/components/PageDetail.js
Modifies the Image component to be able to take an object as the src
prop, rendering a low-res placeholder image while waiting for the
full-res image to load.
This is a first draft, and does not use the existing `<ProgressiveImage/>` component at all (it's not used). As this PR will automatically make use of progressive images if the format follows a standard (subject to change). If anyone has any ideas or changes feel free to share!
This makes use of some backend changes to provide low-res images from thumbor: https://github.com/webkom/lego/pull/2479
**Example with throttling set to _Regular 3G_ in Firefox (which is quite slow)**
<details>
<summary>_See updated screens in new comment_</summary>
Frontpage:
https://user-images.githubusercontent.com/42850232/149673651-9d5a5dee-e39a-44a0-b700 …
=> Add automatic progressive image loading when possible

app/actions/ActionTypes.js, app/actions/UserActions.js, app/routes/users/UserSettingsRoute.js, app/routes/users/components/DeleteUser.css, app/routes/users/components/DeleteUser.js, app/routes/users/components/UserSettings.js
Fixes https://github.com/webkom/lego/issues/2340.
Linked to https://github.com/webkom/lego/pull/2369
It is only possible to delete your **OWN** user, meaning the JWT token + password of a user is used to authenticate the delete action.
Added lot of steps (password auth) to make sure you do not delete your user on accident: 
1.
2. 
3.
=> Add button to delete user

app/models.js, app/reducers/events.js, app/reducers/forms.js, app/reducers/index.js, app/reducers/registrations.js, app/routes/events/EventDetailRoute.js, app/routes/events/components/EventDetail/index.js, app/routes/events/components/JoinEventForm.js
The previous logic just relied on state stored in the JoinEventForm form
state, often causing problems with the form mounting and unmounting, clearing the form state etc. It was generally a really bad idea and stupid. I blame only myself :3rd_place_medal:.
This **new** logic makes use of https://github.com/webkom/lego/pull/2539, and keeps the current status of the registration in it's proper place in redux, making it more robust. With the changes, the status of any pending registrations are always fetched together with the event as well, making it persistent across reloads and devices.
**Better loading component in action**:
https://user-images.githubusercontent.com/42850232/155623632-5a7a539e-c26e-447e-9d46-769278979c49.mp4
**And now also loading unregistration**: …
=> Make registration pending component more robust

app/routes/events/components/EventDetail/index.js
Hide the registration deadline when heedplenalties is false. This deadline only determines when you should get a penalty for unregistering too late.\nWhen an event does not heed penalties, this deadline is redundant.
=> Hide registrationDeadline when heedPenalties is false

app/components/Modal/Modal.css, app/routes/photos/components/GalleryPictureModal.css, app/routes/photos/components/GalleryPictureModal.js
Fixed the `z-index` for the gallery picture dropdown to make it actually clickable...
Also fixed the color for the dropdown and modal buttons to match the text color.
_Before_:
-|-
_After_:
-|-
=> Fix gallery photo dropdown

.github/dependabot.yml
As of now, the current schedule collides with our daily backup at 6 AM, which prevents dependabot's PR to be delivered to drone due to drone locking its database during backup.
I propose changing the schedule to 10 AM. Side benefit, it'll be nice to not be awaken at 6 AM by 14 dependabot messages on slack 🙃
=> Change dependabot schedule to 10 AM

app/routes/admin/groups/components/AddGroupMember.js, app/routes/events/components/EventAdministrate/AdminRegister.js, app/routes/events/components/EventEditor/index.js, app/routes/joblistings/JoblistingCreateRoute.js, app/routes/joblistings/JoblistingEditRoute.js, app/routes/joblistings/components/JoblistingEditor.js, app/routes/pages/PageEditRoute.js, app/routes/pages/components/PageEditor.js, app/routes/surveys/EditSurveyRoute.js, app/routes/surveys/components/SurveyEditor/Question.js, app/routes/surveys/components/SurveyEditor/SurveyEditor.js
The very old version we were using for react select used an old prop that made us able to simply use a string for the value, instead of an object. This was removed quite a few versions about. This is a fix that simply takes modifies the value sent in `onSubmit`. A more sophisticated alternative would be to implement the old `simpleValue` prop ourselves, but the only way I saw that working was by adding internal state to our react select field.
=> Fix fields using deprecated simpleValue prop

.github/auto-merge.yml, .github/workflows/auto-merge.yml
I enabled it for dev-deps `minors`. This might a bit much. If it works we can maybe enable it for `patch` on normal deps :o
=> Automatically merge devdeps PR's from dependabot

package.json, yarn.lock
I did some dumb shit, so this cleans away that from the log
Bumps [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) from 26.1.3 to 26.1.4.
- [Release notes](https://github.com/jest-community/eslint-plugin-jest/releases)
- [Changelog](https://github.com/jest-community/eslint-plugin-jest/blob/main/CHANGELOG.md)
- [Commits](https://github.com/jest-community/eslint-plugin-jest/compare/v26.1.3...v26.1.4)
---
updated-dependencies:
- dependency-name: eslint-plugin-jest
dependency-type: direct:development
update-type: version-update:semver-patch
...
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump eslint-plugin-jest from 26.1.3 to 26.1.4

app/components/Form/SelectInput.js, app/components/Reactions/ReactionPicker.css, app/components/Reactions/ReactionPickerContent.css, app/components/Reactions/ReactionPickerFooter.css, app/components/Reactions/assets/AddReactionEmoji.css, app/routes/companyInterest/components/CompanyInterestList.js, app/routes/events/components/EventList.js, app/routes/surveys/components/Submissions/Results.js, app/routes/surveys/utils.js, app/styles/variables.css
This is my proposition for a **new** and **better** dark mode :art:! (I.e. just switching the main colors)
This also fixes some annoying stuff, like react-select components and input fields.
IMO this looks 1000 times better. Notably, the blue hint in the foreground colors are gone, and the foreground is lighter than the background. The current, opposite style where the foreground is darker than the background, is just jarring and makes no sense to me :slightly_smiling_face:  You notice this especially on event details and the info pages.
Generally, the foreground is lighter, with a bit less contrast. This means the whole page is lighter on the eyes.
Of course, everything is subjective though, so let me know what you think. (Maybe we could ask some users as well?) Personally, this is a …
=> Change (fix) dark theme

app/routes/surveys/components/AdminSideBar.js, package.json, yarn.lock
The entire package could be replaced with **1** line of code. We are losing IE11 support, but I think that's fine, especially since it's in an admin page.
=> replace react-copy-to-clipboard with custom code

app/components/Image/Image.js
Fixes a bug where progressive images don't update when the src prop is changed. I also rewrote `ImageComponent` to be a functional component.
Also fixes https://github.com/webkom/lego/issues/2558
=> Fix progressive images showing wrong image

app/routes/users/components/StudentConfirmation.js, app/routes/users/components/UserConfirmation.css, app/routes/users/components/UserConfirmation.js
Also cleans up the registration and student confirmation forms a bit by
changing some text to buttons, adding some tooltips, and some
explanatory text.
If anyone feels it can be cleaned up a bit more or change any of the text, let me know!
**Register**
Before: (dont have it, but it's jsut without the text, and the button was as the text below)
After:
**Student confirmation**:
=> Add option to verify as two year masters student

app/actions/QuoteActions.js, app/components/Search/utils.js, app/reducers/__tests__/quotes.spec.js, app/reducers/quotes.js, app/routes/quotes/QuotesRoute.js, app/routes/quotes/components/QuotePage.js, app/routes/quotes/utils.js, cypress/integration/router_spec.js
This will as a side effect remove the "random quote" from the list, make
pagination cleaner and easier, as well as reuse code => less code.
Otherwise, this works as before. I'm unable to test the 'approved=false' flow since I'm no longer an admin, but I can test if you give me access to it on staging. I caaaaaaaaaaan start the backed, but my xps still only has 8GiB of memory :rip:
This will also as a sideeffect do as @LudvigHz suggested here; https://github.com/webkom/lego-webapp/pull/2567#pullrequestreview-915770283 to fix the issue https://github.com/webkom/lego/issues/2587 :eyes: 
@LudvigHz:
> - Or some other way.
=> Start using paginationNext in quotes

app/models.js, app/routes/events/EventCreateRoute.js, app/routes/events/EventEditRoute.js, app/routes/events/components/EventEditor/index.js, app/routes/events/utils.js, cypress/integration/create_event_spec.js
Currently in the event editor, the only way to create non-obligatory questions is to check the box for "Obligatorisk spørsmål", add the question, and then uncheck "Obligatorisk spørsmål" again. Although this hides the text field, the question is still in form-state, so it works fine. But it's not very intuitive.
1. <img width="357" alt="Screenshot 2022-04-26 at 12 45 04" src="https://user-images.githubusercontent.com/8343002/165314097-3ad3bf70-d0ce-4744-8b03-1dd39a69eac5.png">
2. <img width="357" alt="Screenshot 2022-04-26 at 12 45 11" src="https://user-images.githubusercontent.com/8343002/165314180-f9399b76-8b0a-43cd-9e3b-c99644ecf077.png">
Because of this people often set questions as obligatory when they shouldn't be. (of course allergies shouldn't be in this question field anyways, I …
=> Allow adding non-obligatory questions in event-editor

app/routes/events/EventCreateRoute.js, app/routes/events/EventEditRoute.js, app/routes/events/components/EventEditor/index.js, app/routes/meetings/MeetingCreateRoute.js, app/routes/meetings/MeetingEditRoute.js, app/routes/meetings/components/MeetingEditor.js, cypress/integration/create_event_spec.js
It turns out we don't need the `useState` for `useMazemap` in the meeting or event editors as this is already saved in form state. 
I also set `useMazemap` to `true` by default in the hope that it will be used a bit more often.
=> Remove useMazemap state from meeting and event editors

app/routes/users/components/ChangePassword.js, app/routes/users/components/PasswordStrengthMeter.js, app/routes/users/components/UserConfirmation.js, app/routes/users/components/UserResetPassword.js, app/routes/users/utils.js, app/utils/__tests__/asyncValidator.spec.js, app/utils/asyncValidator.js
We use `zxcvbn` for checking strength of new passwords in the frontend, and it's a pretty large package (400kb minified). It is currently loaded on all pages, and makes up about 20% of loaded javascript on the front page.
Luckily we have code-splitting and dynamic imports, so with some refactoring it is now only loaded once you actually need to use it 😁 
I've never used dynamic imports before, so please tell me if I'm doing something dumb or not following best practice. But it seems to work well.
=> Avoid loading zxcvbn unneccesarily

app/actions/ActionTypes.js, app/actions/GroupActions.js, app/reducers/frontpage.js, app/reducers/groups.js, app/routes/overview/IndexRoute.js
This will be the first of many PRs into `new-frontpage-2022-release`, created to avoid my fellow webkomers to suffer the awful 3000 line PR :hot_face:  . More details about the project will be added once this is merged.
Add three randomly selected interestgroups to frontpage state. Achieved with the new endpoint in webkom/lego#2594. 
These will later be used to display some interestgroups on the frontpage, see #2311 for a preview^^
=> Add randomly selected interestgroups to frontpage

server/pageRenderer.js
Setting `maximum-scale` to a value <= 1 will make prevent users to zoom
on several mobile browsers.
=> Don't block user zooming on mobile

app/routes/users/components/GroupChange.js
Use normal dark mode for the component used when selecting grade for a user. Without this, it is very hard to use the component in dark mode.
=> Use css-theme on velg-klasse

.drone.yml
This will also run with `lego-cypress-helper:latest` which is already v.12 
The lego-cypress-helper PR is retroactive, as the image is already pushed https://github.com/webkom/lego-cypress-helper/pull/1
=> Bump postgres to 12.3 to match LEGO

app/components/Feed/activity.css, app/components/HeaderNotifications/HeaderNotifications.css
Added word-break to timeline to prevent horizontal overflow.
Also added white-space: pre-line; to display newlines, turning
into
=> Made timeline and notifications show newlines and prevented timeline overflow

app/components/NavigationTab/NavigationTab.css, app/components/NavigationTab/index.js, app/components/Tags/Tag.css, app/routes/articles/components/ArticleDetail.js, app/routes/articles/components/Overview.js, app/routes/meetings/components/MeetingList.js, app/routes/pages/components/PageDetail.css, app/routes/quotes/components/Quotes.css, app/routes/users/components/UserProfile.js
* Add links to the tags in the bottom of articles to other articles with
the same tag.
* Flex-wrap and word-break in headers and profile badges
* Change color of active tag in /articles/ to the same color as hovered
tag, as it feels unintuitive to have them be different colors when it is
not a multi-select
* Change :hover to :active to prevent it displaying as if it were active
when disabling on mobile.
=> Prevent page overflow on mobile devices and small style changes

README.md
Add link to the deployment section in the webkom/lego README.md, and added a top-level table of contents for the README.md of this repo
=> Add link to deployment in webkom/lego to README.md

app/components/AnnouncementInLine/index.js, app/routes/announcements/components/AnnouncementsCreate.js, app/routes/events/components/Admin.js, app/routes/interestgroups/components/InterestGroupDetail.js, app/routes/meetings/components/MeetingDetail.js
This was started in #2319 , but seemed to be abandoned.
Changes the "Ny kunngjøring" button on event, meeting and interest group pages to send you to the announcement creation form, instead of the inline form. Also fills in the correct group, meeting, or interest group automatically.
I fixed the prettier and flow issues, and some other issues that were left unsolved.
=> Route new announcement from event to detailed page view

.eslintrc.js, .gitignore, app/components/Button/Button.css, app/components/Form/CheckBox.css, app/routes/joblistings/components/JoblistingEditor.css, app/routes/joblistings/components/JoblistingEditor.js, app/routes/joblistings/components/JoblistingList.css, app/routes/joblistings/components/JoblistingList.js, app/routes/joblistings/components/JoblistingPage.css, app/routes/joblistings/components/JoblistingPage.js, app/routes/joblistings/components/JoblistingRightNav.css, app/routes/joblistings/components/JoblistingRightNav.js
- Replace JoblistingEditor header with `NavigationTab`
- Add a rotation animation to the dropdown caret in `JoblistingRightNav`
- Clean up `JoblistingRightNav`
- Rewrite `JoblistingsRightNav` to a functional component
- Prevent active effect on Button when disabled
- Redesign `JoblistingList`. Notice that the entire item functions as a link, as opposed to the current situation in which the link is only accessible on the title and the image.
- Untrack mazemap.min.* files and ignore them when running eslint
=> Implement styling changes, particularly on the Joblistings page

app/components/NavigationTab/NavigationLink.js, app/reducers/quotes.js, app/routes/quotes/QuotesRoute.js, app/routes/quotes/components/QuotePage.js
This PR fixes a few things that has been bugging me about the quotes page. First and foremost this PR fixes the issue where the page would show all the quotes in the redux state, regardless of approved status. So approved quotes would be shown when viewing unapproved quotes, and vice versa.
This PR also fixes the NavLink component so that it takes query params into account. Why react-router does not do this by default is beyond me, but at this point I have come to believe that the maintainers of that repo makes changes just to mess with people. 
In addition it adds a loading indicator to the quotelist. 
I am not sure if I did the selector stuff correctly, so feel free to correct me if it is wrong.
=> Fix quotes

app/routes/meetings/components/MeetingEditor.js, app/utils/validation.js
Fix a bug in the meeting editor where new meetings cannot be created without filling in the "location"-field, even if a mazemap location is entered.
=> bug fix: don't require meeting "location" if useMazemap is selected

app/components/Banner/Banner.css, app/components/Banner/index.js, app/routes/overview/components/Overview.js
As requested by the PR committee, the banner on the front page should employ the same background-color as the chosen "buddy week" color for 2022.
=> Change color of front page banner

app/routes/contact/components/ContactForm.js
Alva requested that we update the text in the contact form to make it easier for new members to understand what it can be used for, and I totally agree that this was needed. I only added a part stating that this is where we want to receive "avvik", and restructured the text a bit to make it tidier.
=> Update text in contact form

app/routes/events/EventCreateRoute.js, app/routes/events/components/Admin.js
Resolves https://github.com/webkom/lego/issues/2380
Apparently it seems the location of where props are passed through react-router-dom have changed. I didn't find the changelog for exactly when the change occured, but in my search for answers I found [this StackOverflow answer](https://stackoverflow.com/questions/38085893/react-router-link-pass-in-params) that used `match.params` for react-router-dom v2, and the other sources I visited (e.g. [this guide](https://ui.dev/react-router-v5-pass-props-to-link)) used `location.state` for v5 which we currently use.
=> Update path to find eventId of event to copy

app/components/Content/ContentHeader.css, app/components/Content/ContentHeader.js, app/components/InfoList/index.js, app/components/Time/Time.spec.js, app/components/Time/index.js, app/routes/events/components/Admin.css, app/routes/events/components/Admin.js, app/routes/events/components/EventDetail/EventDetail.css, app/routes/events/components/EventDetail/index.js, app/styles/globals.css, cypress/e2e/create_meeting_spec.js
It has finally come! The redesign of the sidebar. 
It is rather simple, mostly rearranging of code.
Move some of the information and add some icons 'cause people like icons.
And move the name of the company and put the event type to the coloured bar under the header.
Also, the mazemap thing is now something that opens and close when hitting the link.
Before:
After (the faces dont show, but now there is _one_ row of faces rather than two!):
And with payment and mazemap:
=> Minimal redesign of event details

app/components/DisplayContent/index.js, app/components/Form/EditorField.js, cypress/e2e/event_editor_spec.js, package.json, yarn.lock
As you can see from the release notes of lego-editor, this should fix alot of issues that have been plaguing us for a while.
Notably we have:
- Android support
- Fixing (hopefully) all the editor crashes everywhere
- General bugfixes and increased smoothness
These should not be any visual or functional changes with this release.
=> Update lego-editor to v2.0.1

app/reducers/followers.js
This fixes an issue where the event detail page would crash for some events that you follow.
Now quite sure why this was happening, and I couldn't find when `follower` was undefined when
debugging.
Anyways, this seems to fix the issue :shrug:.
=> Fix event detail crashing

app/routes/admin/email/components/EmailUserEditor.js
Recruitment-season do be closing in, and as it's not unheard of to write the wrong name when creating new emails I decided it could be nice to give a helping hand.
Set æøå to be replaced by ae, oe and aa. Seemed to be kinda standard, but if anyone has any objections I'll do it.  
Set to remove any characters except a-z, 0-9, - and . after the three above are replaced.
=> Update create new email form to autofill the new email

app/components/Content/ContentHeader.css, app/components/Content/ContentHeader.js, app/components/UserGrid/index.js, app/routes/events/components/EventDetail/index.js
Only change here is that the list of participants has no height if there are no participants.
List of participants has no height if there are no participants  
Title and event-type wraps so none overflow and the title gets to use the entire width
=> Fix event-detail title overflow, make participants-list fit content

app/actions/callAPI.js, app/routes/surveys/SubmissionsRoute.js, cypress/support/commands.js
This is related to https://github.com/webkom/lego/pull/2801.
[`drf-jwt`](https://styria-digital.github.io/django-rest-framework-jwt/#usage) requires Bearer, instead of `djangorestframework-jwt`'s JWT scheme.
I've spent the last week contemplating and trying to figure out why the JWT auth was not behaving correctly ...... 😣 Check your header schemes kids
**This must be merged together with https://github.com/webkom/lego/pull/2801.**
=> Change HTTP auth scheme from JWT to Bearer

app/routes/events/components/EventDetail/index.js, cypress/e2e/create_event_spec.js
During the redesign it was concluded to remove the unregistre/register deadline, on the grounds that it would be confusing to have both "avregistreringsfrist" and "avregistrering stenger".
I argue that these premisses have changed, as we no longer have "avregistreringsfrist", but "frist for prikk" - which in my opinion has a different meaning.  
In addition, "påmelding åpner" makes no sense after the registration has already opened.  
We also have some events that close the day before before to be able to order food, and it would be nice to show that as everyone might not realize that before it is too late to unregister.  
Aaand not all events use the prikk-system, but they still have times where the registration closes.
Preview:
=> Convert registration-start to registration-end after registrations open

app/routes/events/components/EventFooter.css, app/routes/events/components/EventFooter.js
We should probably do more to ensure people know this exists, but this a bare minimum. I honestly don't understand why it was hidden on mobile at all.
Before: 
After:
=> Show ical and google calendar integration on mobile

app/routes/overview/components/PublicFrontpage.js
We probably should have updated this _before_ the "buddy week" started. But hey, better late than never!
=> update "Nyttige linker" link to this years buddy week

app/routes/events/components/Event.css, app/routes/events/components/JoinEventForm.js
Co-authored-by: @EliHaugu.
The white space is now removed from the event pages.
Resolves [#2865 ](https://github.com/webkom/lego/issues/2865)
before fix:
after fix:
=> remove white space from event details

app/routes/surveys/utils.js
Small fix to do what is described here: https://github.com/webkom/lego/issues/1998
> It is currently the time that you make the survey. We should set it to something like 24h in the future, so that people don't accidentally create it and send it out immediately, when it is not ready.
=> Set survey default activation time to noon the day after

app/components/Content/Content.css, app/components/EventItem/styles.css, app/components/Upload/UploadImage.css, app/routes/articles/components/Overview.css, app/routes/company/components/CompaniesPage.css, app/routes/joblistings/components/JoblistingList.css, app/routes/overview/components/ArticleItem.css, app/routes/overview/components/EventItem.css, app/routes/surveys/components/surveys.css
Makes it easier to see dark logos with transparency in dark mode. In light mode it is invisible as all the backgrounds were already white.
I also changed `height` to `max-height` a few places, this was to avoid unneccesary white background around the images. The only layout change i noticed was that job-listings became slightly thinner.
before:
after:
before:
after:
before:
after:
=> use white background behind company and event images

app/components/UserAttendance/AttendanceStatus.css, app/routes/events/EventEditRoute.js, app/routes/events/components/EventDetail/index.js, app/routes/events/components/EventEditor/index.js, app/routes/events/components/JoinEventForm.js, app/routes/events/components/RegistrationMeta.js
- [Clean up registration meta info](https://github.com/webkom/lego-webapp/commit/59f745a0e3be3dc5456985de3e4812f1993f17e4)
- Don't show "Du er ikke påmeldt" when registration has not yet opened (but if you're admin registered before, it will show that you're registered).
- Don't show "Du er påmeldt" when event has ended.
- Fix alignment of icons and text whenever the text overflows.
- [Small improvements to the event page and event editor](https://github.com/webkom/lego-webapp/commit/75ebf3e5da08dea72dcf7455c1e2d46fa1c16d0c)
- Fix responsible group link (see https://github.com/webkom/lego/pull/2886).
- Fix the showing of event type color in the editor (and thus also the event creator)
- Relocate price field to come after location, as it will usually be a shorter value.
- Add a …
=> Improve event page and event editor

app/routes/users/components/UserSettingsNotifications.js, cypress/e2e/router_spec.js
Add and rewrite translations for the different notification settings. A few were missing, and some were hard to understand. Suggestions are very welcome.
Hopefully, once the weekly emails are being sent, people will actually visit this route, so the settings should be understandable
=> Rework translations for notification settings

app/components/Modal/index.js
😡😠😠 This took waaaaay too long to debug
The styling needs to be on the modal-element, not on the div inside it...
fixes https://github.com/webkom/lego/issues/2841
=> fix bug where opening a modal scrolls to bottom of page

app/components/Header/Header.css, app/components/Header/ToggleTheme.js, app/components/Header/index.js, app/components/Header/toggleTheme.css, app/components/Search/Search.css, app/components/Search/index.js, app/routes/app/AppRoute.js, app/routes/pages/components/PageDetail.js, app/styles/globals.css
The button is an icon that switches based on the current theme. If the
user is logged in, the theme will also be persisted to the
backend.
=> Add button to toggle theme in header

app/actions/CommentActions.js, app/components/CommentForm/index.js, app/components/Comments/Comment.js, app/components/Comments/CommentTree.js, app/components/Comments/CommentView.js, app/components/Form/EditorField.js, app/components/Form/LegoFinalForm.js, app/components/Form/SubmissionError.js, app/routes/meetings/components/MeetingEditor.js, cypress/e2e/create_meeting_spec.js, cypress/e2e/event_visit_spec.js
While converting the comment form to use `react-final-form` I did some cleanup and refactoring.
- Converted `CommentForm` to a function-component
- For connecting the `CommentForm` and `EditorField` to redux state, I have replaced `connect` with `useDispatch` and `useSelector`. This makes the code a lot more readable imo. and works better with flow.
- Replaced `redux-form` with `react-final-form` in `CommentForm`. Most of what I changed is related to this, as it changes the way we read the form-state and also required some changes to `CommentActions`. I also made use of `LegoFinalForm` to handle errors from the API which further simplified
`CommentActions`.
- Changed the workaround to make ssr work with the editor. I haven't quite figured out why it works like this, but the editor needs …
=> Refactor comment form (migrate to react-final-form)

app/components/CommentForm/index.js
LegoEditor is uncontrolled, so we cannot set the editor text from our code. What we can do though, is make sure that each separate comment uses a separate editor-instance by setting a unique key. As each new editor is intially empty, this will clear the comment form whenever the form changes to a new comment.
For the key i just used Math.random(), as we don't have a UUID library. I assume this will be good enough.
Fixes https://github.com/webkom/lego/issues/1464
=> fix bug where comment form would not clear after submit

app/components/Tooltip/Tooltip.css
=> fix: add a z-index to Tooltip

app/routes/events/components/EventEditor/index.js
As requested from Arrkom it is now not possible to have the payment deadline within the first 24 hours after the unregistration deadline for events using prikker.
Invalid payment deadline:
Valid payment deadline:
=> ABA-31: Add validation so payment due date is minimum 24 hours after unregistration deadline

app/routes/events/components/EventAdministrate/RegistrationTables.js
Loong description, but I want the background for this bug to make sense(:
Lately there has been a problem where the admin-view for events crashes for some users.
After doing some debugging in the prod browser (editing the JS files that the browser caches, awesome way to test frontend changes in prod in your local environment with bugs that are hard to reproduce in dev/staging), as I wasn't able to reproduce in staging, it seems that in https://github.com/webkom/lego-webapp/blob/master/app/routes/events/components/EventAdministrate/RegistrationTables.js#L79 there are certain cases where the user object contains all it's properties, except `abakusGroups` (which is used by `hasWebkomGroup`).
Exactly why this happens I'm not sure, but it might be related to the following;  
When the list of …
=> Add safeguard to disable reading of assumed existing key

app/components/Poll/index.js
The name attribute would make it so the default tooltip whenever you
hovered over an ion-icon element.
Before:
After:
=> Fix poll info icon & remove tooltip with icon names

cypress/e2e/create_event_spec.js
When `tomorrowDate` would for example be "8", cypress would falsely try to click on "28" (from the previous month) because this comes before "8" in the DOM. The dates from the previous month would, for obvious reasons, be disabled and thus cause the tests to fail.
This was solved by simply utilizing a regex.
=> Fix cypress tests by finding the correct date

app/routes/events/components/EventEditor/index.js
The first typo, "Manuell betaling kan også av i etterkant" does not really make sense, and the second one is using the wrong term "avmelding" instead of "avregistrering".
=> Fix typos in tooltip and validation in the event editor

app/routes/events/components/EventAdministrate/Attendees.js
Introduced in #3107.
People that had paid "manual" were not taken into account, and instead of comparing the stats to capacity it should be compared to registration count.
=> Fix attendees stats bug on admin page

server/pageRenderer.js
This adds an analytics snippet to start tracking some analytics again!
This points to our self-hosted plausible instance, so all data is stored in the same method as our
other data.
Additionally, this analytics snippet is GDPR-compliant and does _not_ store any cookies, saving us
from the dreaded cookie-popup hell.
Fixes ABA-93
=> Add analytics snippet

app/components/EventItem/index.js, app/components/EventItem/styles.css, app/routes/users/components/UserProfile.js
Just making the components for previous events more compact.
Planning on using pagination in a later PR
=> Make Past Events on Profile Page Extra Compact

app/routes/events/components/EventDetail/index.js
It would sometimes work though, because these things work in mysterious ways after build ...
**Before**
**After**
=> Import correct css file to get the desired styling

app/components/Icon/index.js
When clicking icons in Tables the icon would become invisible. Turns out this is because ion-icons sets classnames on itself when initializing, that would then be overwritten when we change the className in react.
I fixed it by wrapping each icon in a div, and applying style to that instead. This however caused some icons to take up too much vertical space, so I removed "lineHeight: 2" from the style, which seems to have fixed it. Not sure why that was there in the first place, as I have looked around a bit and not found any icons that look different from before.
=> Fix bug where icons disappear after interacting with them

app/routes/events/components/EventList.css
This looks better on mobile or when zooming.
Also removed the width change on mobile from 200px to 100px, now its always 200px. Since 100px makes it very short and difficult to read, and it is space enough for 200px anyways
Changed from:
To:
Last changes:
=> Aligned Select And Filtericon With Filterbuttons

app/models.js, app/reducers/pages.js, app/routes/pages/PageDetailRoute.js
To better showcase the Abakus Revue it will now be displayed in its own tab, in the same way as the committees.
Depends on: https://github.com/webkom/lego/pull/3010
=> Add the Abakus Revue to pages

app/routes/events/utils.js
Another teeny tiny bug here.
The reduce function would return true if we passed in an empty array,
which does not make sense when there are no consents that could have
been answered.
=> Make `allConsentsAnswered` => false for empty array

app/routes/users/UserProfileRoute.js
This is to make the "Åre"-photo consent experience better. When viewing an event with photo-consent for an upcoming semester, the photo-consent objects are created in backend, but not updated in frontend. By refetching user when viewing the profile page the new objects will be fetched.
Without this you would need to reload the page in order to register photo-consent.
=> Refetch me-user when viewing profile page

cypress/e2e/create_event_spec.js, cypress/support/utils.js
At the end of the month, the cypress tests selected the date from the previous month instead of the date tomorrow, if it was visible. I added ":not(:disabled)" to the selector, which works because the previous month's dates are all disabled.
I also moved the date picking code into a function as it was duplicated.
=> Fix cypress bug where it selects wrong date at end of month

app/routes/overview/components/ArticleItem.css
Before:
After:
It doesn't look great to break words without a hyphen, but that is surprisingly hard with only css.
closes ABA-103
=> Fix mobile page overflow with long words in articles

app/routes/events/components/EventAdministrate/RegistrationTables.js
Two things are fixed:
* It is now possible to sort attendees based on payment status.
* The sorting of feedback is done with localeCompare so that the sorting is done alphabetically instead of based on ASCII values.
[Sorting in action :nerd_face:](https://user-images.githubusercontent.com/43182025/198133744-9bb917d5-8d07-4f37-b327-2c40aad7c277.webm)
=> [ABA-109] Add sorting option for payment status on attendees page

app/components/Form/Captcha.js
Couple of minor issues: 
* The light version seems to be loaded before being replaced when running with csr (not an issue with ssr).
* When switching themes, the Turnstile widget remains the old theme (I don't know how to cascade this🤷).
Closes https://github.com/webkom/lego/issues/3036
=> Fix Turnstile theme discrepany

app/routes/users/components/UserProfile.css, app/routes/users/components/UserProfile.js
The FRAME has some whack styling that caused this visual mishap. Did not spot this in the original PR, since profile pictures are not loaded in the staging environment. 
In my LEGO PR [#3041](https://github.com/webkom/lego/pull/3041) I made it so that the default (placeholder) profile picture is always used in staging. This makes it easier to spot these kind of issues.
=> fix(UserProfile): FRAME styling

cypress/e2e/create_meeting_spec.js
The test fails on the two days a year we set the time because of daylight savings, because the default values of the form will be an hour off. Setting the time explicitly in the test fixes it, and I don't really see a need to test the default values.
ABA-115
=> Set end time explicitly in cypress meeting test

app/components/Search/SearchPage.js, app/components/UserValidator/index.js, app/routes/events/components/EventAdministrate/Abacard.js
[This](https://github.com/webkom/lego-webapp/pull/3017/commits/0053f16b4360d5cc00b6463ba5af5e34a6dc42da) commit from https://github.com/webkom/lego-webapp/pull/3017, accidentally broke all `handleSelect`-calls when searching for other things than users, making links unclickable in the search-page.
If only we had working type-checking...
=> Fix clicking links on /search page

app/components/Modal/Modal.css, app/routes/users/components/PhotoConsents.js
=> Dark mode fixes

app/components/GroupMember/index.js, app/routes/pages/components/PageDetail.js
As the leader of readme is called editor ("Redaktør") and not leader, this is now updated on the flatpages.
Fixes ABA-132
=> Change group leader name to editor for readme

server/pageRenderer.js
URLs with `/plausible.js` are blocked by most adblockers, and the
`analytics` subdomain is also susceptible to blocking. Changing to a URL
that avoids this should make sure we get more accurate analytics.
Fixes ABA-126
=> Use proxied url for plausible script.

app/components/Form/CheckBox.css, app/components/Form/CheckBox.js, app/routes/bdb/components/OptionsBox.js, app/routes/events/components/EventList.css, app/routes/events/components/EventList.js, app/routes/joblistings/components/JoblistingRightNav.css, app/routes/joblistings/components/JoblistingRightNav.js, app/routes/surveys/components/AdminSideBar.js
The `<Checkbox />` component is in great need of an improvement. It now also looks much better in dark mode.
It now works to pass a `label` into the component as a prop, making it align to the checkbox. It is now also clickable, but only if an `id` is given.  
The CSS is completely rewritten, so no need to compare the diffs.
Keep in mind that the .gif is laggy, causing the transitions to seem slow and less smooth. 
Closes ABA-133
=> Improve Checkbox component

app/routes/joblistings/components/JoblistingEditor.tsx
=> Fix back link on joblisting edit page

app/routes/events/components/EventDetail/index.tsx
Now that interest groups are more regularly creating events, I think it's fitting to link to their page.
**Before**
**After**
---
To help in review, this is what `resolveGroupLink` does:
```tsx
export const resolveGroupLink = (group: { type: string; id: ID }) => {
switch (group.type) {
case GroupTypeInterest:
return `/interest-groups/${group.id}`;
case GroupTypeCommittee:
return `/pages/komiteer/${group.id}`;
default:
return null;
}
};
```
---
Closes ABA-136
=> Support interest group links on events

app/reducers/groups.ts
Thanks to #3152, every group in the revue has its own page on abakus.no. That means that we now can link the revue badges on your profile to their respective page, like what we've done for committees and interest groups. This PR adds that feature.
For example, I have a Teknikk-badge on my profile. Previously, nothing would happen if you clicked on it, but now it will route you to the Teknikk-page under Revy.
=> Fix Link For Revue Badges

app/routes/users/components/UserProfile.tsx
Currently, the badges on my profile are ordered like this:
In my opinion, it would look better if the red badges were grouped together (i.e. the revy badge is next to the webkom badge). This PR will change the order to the following (from most prioritized to least):
1. Styrer (e.g. Hovedstyret and Fondsstyret)
2. Committee, Revue (i.e. the rest of the red badges)
3. Interest groups (i.e. yellow badges)
4. Inactive groups (i.e. gray badges)
I'm open for any feedback/changes :)
=> Improve Badge Order

app/reducers/events.ts
When a user does not have perms to register on an event, websocket registration messages in the `Event.SOCKET_REGISTRATION.SUCCESS` action will use the `RegistrationAnonymizedReadSerializer` containing the fields `("id", "pool", "status")`. This is done to make those user able to watch registrations real time, without seeing who the users are.
For those events, we don't hit this code path, since it will only use counters. However, if the user has normal access to an event and can see the registrations, the frontend will currently crash if one such websocket event (for another event without access) has occurred.
We could in theory handle the case here as well, but it will currently not be hit unless other code is refactored; and in that case even more code has to support it.
Fixes …
=> Fix registration selector when user is missing

app/components/Image/CircularPicture.tsx, app/components/Image/Image.tsx, app/components/Image/ProfilePicture.tsx, app/components/UserAttendance/AttendanceStatus.css, app/components/UserGrid/UserGrid.css, app/components/UserGrid/index.tsx, app/routes/events/components/EventDetail/index.tsx
To prevent the register button from moving once people start registering (which we've recieved a ton of feedback on). The skeleton will, however, only be visible once there's less than 5 minutes until activation.
---
Closes https://github.com/webkom/lego/issues/3004 and closes ABA-122
=> Implement a registration skeleton on event page

app/routes/events/components/EventDetail/index.tsx
Previously if you had an unanswered survey you could not unregister from an event.
Added so that if you are registered for the event it will show the unregister button and not the warning that you have unanswered surveys.
=> Fix Unregistration With Unanswered Survey

app/components/Upload/ImageUpload.tsx
Additionally, you can specify what file types to allow on other file upload forms.
https://github.com/webkom/lego/issues/2876
=> Only allow images for image uploads

.git-blame-ignore-revs
I religiously use `git blame`, and the recent bulk changes in regards to our transition to Typescript has made it awful. But [this](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt) makes everything better! `git blame --ignore-revs-file .git-blame-ignore-revs` will now output a useful `git blame`. The flag must always be passed, so I recommend setting a config for this;
`git config blame.ignoreRevsFile .git-blame-ignore-revs`. Note that this needs to be set per-project, as `git blame` will raise an error if it cannot find the file.
This also works if you use `GitLens` (but you still need to configure it the same way).
This is entirely optional to use, but I've now used it a couple of days and it does wonders!
=> Introduce a `.git-blame-ignore-revs` file

app/components/Button/Button.css, app/components/Chart/utils.tsx, app/components/Dropdown/Dropdown.css, app/components/Form/DatePicker.css, app/components/Header/toggleTheme.css, app/components/NavigationTab/NavigationLink.css, app/components/PhotoUploadStatus/PhotoUploadStatus.css, app/components/Poll/Poll.css, app/components/Poll/index.tsx, app/components/Search/Search.css, app/components/Table/Table.css, app/components/Table/index.tsx, app/routes/admin/groups/components/GroupMembersList.tsx, app/routes/events/components/EventAdministrate/Administrate.css, app/routes/events/components/EventAdministrate/AttendeeElements.tsx, app/routes/events/components/EventAdministrate/Attendees.tsx, app/routes/events/components/EventAdministrate/RegistrationTables.tsx, app/routes/events/components/EventDetail/EventDetail.css, app/routes/polls/components/PollsList.tsx, app/routes/surveys/components/surveys.css, app/routes/users/components/UserSettingsNotifications.css, app/styles/globals.css, app/styles/variables.css
I believe it was in great need of a retouch.
---
[Improve color palette](https://github.com/webkom/lego-webapp/commit/922c8ead20dfeda10b02ba8a934e830c04f3b82d)
I think we should support far more shades of each color. I'm going to change the other colors as well and go more thoroughly through our webapp, but that should be a seperate PR. Here I've only changed colors used by the event table (gray, red, green, blue and orange).
---
[Give the table component a retouch](https://github.com/webkom/lego-webapp/commit/07ec000d6d9354373aac3f49a1e131d6f0fc08d9) 
This is mostly in regard to the table used on the event details page.
- Fix issue with `event.isPriced` being undefined and causing the "paid column" to vanish. 
See https://github.com/webkom/lego/pull/3155
- Align cells in the body and …
=> Improve the table component

app/components/Modal/ConfirmModal.css, app/components/Modal/ConfirmModal.tsx, app/components/Modal/Modal.css, app/components/Modal/index.tsx, app/components/NavigationTab/index.tsx, app/components/Upload/ImageUpload.tsx, app/components/Upload/UploadImage.css, app/components/UserAttendance/AttendanceModal.css, app/components/UserAttendance/AttendanceModal.tsx, app/routes/admin/groups/components/GroupMembersList.tsx, app/routes/interestgroups/components/InterestGroupMemberList.css, app/routes/interestgroups/components/InterestGroupMemberList.tsx, app/routes/photos/components/GalleryDetail.tsx, app/routes/photos/components/GalleryDetailsRow.tsx, app/routes/photos/components/GalleryPictureModal.css, app/routes/photos/components/GalleryPictureModal.tsx, app/styles/variables.css
Hah, you thought I was done!?
---
[Improve the general modal component](https://github.com/webkom/lego-webapp/commit/7211258db5a9036d9ac4968f609554c61b704c40) 
Only in terms of styling. It's now smaller, yet prettier.
---
[Utilize the back prop on gallery pages](https://github.com/webkom/lego-webapp/commit/28a0ed70444fc89f5cc6b60c9bf6ff2ff8d547bb) 
Also move the routing hack to this navigation link. The hack ensures
that the user ends up where it left off in the y-axis.
[Improve the image upload modal](https://github.com/webkom/lego-webapp/commit/39c73b4b0b5e1a9be1a90bd8c080a33d042de248) 
Mostly just styling changes.
[Make upload area react to change](https://github.com/webkom/lego-webapp/commit/69c5affc3a26d165b383b0b94133d17bf51b3793) 
It will give feedback when it's focused, or …
=> Improve all modals

app/components/Modal/Modal.css, app/components/Table/Table.css, app/routes/users/UserSettingsOAuth2Route.ts, app/routes/users/components/UserSettingsOAuth2.css, app/routes/users/components/UserSettingsOAuth2.tsx, app/routes/users/components/UserSettingsOAuth2Form.tsx
As mentioned in #3407, there was some clean ups that I wanted to make. There are two remaining tables in the BDB that I've started to work on, but whilst doing so I realized that the entire BDB codebase needs a retouch, not just the tables. Since I'm not sure when I'll finish that, it's nice to get this in before.
---
[Clean up oauth2 tables](https://github.com/webkom/lego-webapp/commit/6ed34027a0726b537e3eec680c4e7a290f3d782c) 
Most notably, they now use the `<Table/>` component, but I've also made some minor adjustments/improvements.
A feature that is very much not needed, but I had some spare time ..
https://user-images.githubusercontent.com/69514187/212474849-adbb9dd5-f2e2-4aec-b7cf-6082df05b2bf.mov
---
[Make the table selectors more …
=> Clean up tables

app/routes/users/components/UserSettingsNotifications.css
This was overlooked since it is not an issue in the local build ..
I have not been able to test it, since it is not a bug locally 🤔, but this will most likely fix it. I have, however, tested that it does not break the notifications table, so it can't get any worse ..
=> Make table CSS more specific

app/components/Reactions/index.tsx
It is currently impossible to close the reactions modal, because `this.node` will be undefined.
Introduced in https://github.com/webkom/lego-webapp/pull/3262/files#diff-8d572e7c201a00b5932067713ac2f6df7f84f11cf3ccbbdd4d87ac6bdd3945e0R84.
You can now close it, either by reacting or by clicking outside.
=> Handle outside clicks properly on reactions modal

app/routes/events/components/EventDetail/index.tsx
Deep copy activationTimeMoment to prevent wrong displaytime
Now it works as intended
Works on my machine :tm:
=> Deep copy activationTimeMoment to prevent wrong displaytime

app/components/Header/index.tsx
Changed the meeing icons from a calendar to two people. I think the calendar icon is a bit confusing as it does not lead to the clandar page. The two people is not an ideal icon, but I think it is an improvement and can't really think of any icon that screams meeting.
I did consider something like this:
but I don't think it looks quite right.
Before: 
After:
=> Change meeting icon from calendar to people

app/routes/events/components/EventAdministrate/RegistrationTables.tsx
When an admin registration has no creator, the status would show "Venteliste", since that's the default status. This fix corrects the status on such cases to show "Påmeldt".
I didn't even know an admin registration could have no creator, so this was never tested for before.
**Before**
**After**
It now shows the correct status. See images above.
=> Correct the registration info status on the pills

app/routes/overview/components/utils.tsx
The tags under "Festet Oppslag" weren't proper links, so you couldn't click on them and be redirected to the tag page. Now this is fixed.
=> Fix Tag Links On "Festet Oppslag"

app/routes/events/components/Calendar.css, app/routes/events/components/Calendar.tsx, app/routes/events/components/CalendarCell.tsx, app/routes/events/utils.ts, app/utils/createMonthlyCalendar.ts
- Changed design of the event entry to a pill design
- Added time and place for the event in the popover
- Events that last over multiple days will be shown on each day they take place.
- Made the calendar taller and decreased the font size for the day numbers and weekend heading.
In addition to many minor changes like centering the registration pill in the popover, improving variable names, changing colors etc.
- [sort of ] I have thoroughly tested my changes.
I have scrolled through the calendar and all the months look fine.
- I mentioned that I wanted to improve the styling of the calendar on phones. That will be implemented in a separate PR.
- I realize that the Pill-component can be used for the event pills instead of implementing it myself. I remember trying to do that when I first …
=> Improve styling of the calendar

app/components/Card/Card.css, app/components/Card/index.tsx, app/components/Footer/index.tsx, app/components/Header/toggleTheme.css, app/components/Poll/Poll.css, app/components/Poll/index.tsx, app/components/RandomQuote/RandomQuote.css, app/components/RandomQuote/RandomQuote.tsx, app/reducers/quotes.ts, app/routes/overview/components/ArticleItem.css, app/routes/overview/components/ArticleItem.tsx, app/routes/overview/components/EventItem.css, app/routes/overview/components/EventItem.tsx, app/routes/overview/components/LatestReadme.css, app/routes/overview/components/LatestReadme.tsx, app/routes/overview/components/Overview.css, app/routes/overview/components/Overview.tsx, app/routes/overview/components/Pinned.css, app/routes/overview/components/Pinned.tsx, app/routes/overview/components/utils.tsx, app/routes/polls/components/PollsList.css, app/routes/polls/components/PollsList.tsx, app/routes/quotes/components/AddQuote.tsx, app/routes/quotes/components/Quote.tsx, app/routes/quotes/components/Quotes.css, app/routes/users/components/UserProfile.css, app/styles/variables.css
[Enhance the Card component](https://github.com/webkom/lego-webapp/pull/3488/commits/7bc069db346a3a7b62dec86c9a00b56dc8381b4c)
Also make all "cards" actually employ the component. The cards now have
a much more modern look and they all share the same styling.
---
[Iterate on the introduction of Inter](https://github.com/webkom/lego-webapp/pull/3488/commits/56dec53c7d4a6f5a0423424e408395d16891eaba)
Small styling changes here and there. Among other things, the background is now less "blue".
**Before**
**After**
**Before**
**After**
The cards looks much better here once the content background is gone.
I've tested all use cases of the component.
---
Resolves ABA-225
=> Enhance the Card component

server/pageRenderer.ts, server/ssr.tsx
The helmet component has been set after the `readyHtml(app)` now. This is just because helmetContext is based on the existing scripts and styles that 'readyHtml' produces.
Helmet should work now, with properly updated / overwritten `og` tags.
- I have tested that different routes all successfully have inserted Helmet tags into Head
How testing was done:
Simply:
- Build the components using `yarn build`
- Run SSR frontend with 'yarn ssr' (local backend)
- Inspect that different pages have their correct `<meta>` tags in `<Head>`
---
Resolves [ABA-181](https://linear.app/abakus-webkom/issue/ABA-181/fix-helmet)
=> Fix Helmet for Server Side Rendering

app/components/Chart/Chart.css, app/components/Chart/ChartLabel.tsx, app/components/Chart/PieChart.tsx, app/routes/events/components/Event.css, app/routes/events/components/EventAttendeeStatistics.tsx
Event Statistics on mobile had major overflow issues. This PR makes the stats look prettier on mobile.
Tested with responsive mode in the web browser, down to a size of iPhone 8 Plus, which is a quite small phone nowadays. 
---
Resolves ABA-216
=> Fix Event Statistics Overflow Issues

app/components/Banner/Banner.css, app/components/Banner/index.tsx, app/components/HeaderNotifications/HeaderNotifications.css, app/styles/overlay.css
[Make Dropdown and Popover components resemble Card](https://github.com/webkom/lego-webapp/commit/3afb6512ede27c89b80c9e0e1c3b9d9cae9932c3)
I kept the border, since these are overlays.
---
[Wrap Banner in the Card component](https://github.com/webkom/lego-webapp/commit/3a87cac5accef7c49a26d85da66192ddaf2c37c7)
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
Checked all places where they are used.
=> Iterate on the recent Card changes

app/routes/events/components/EventAdministrate/Attendees.tsx, app/routes/events/components/EventAdministrate/RegistrationTables.tsx, app/routes/events/components/EventAdministrate/index.tsx
The EventAdministrate pages do not have the same structure as other pages regarding title and navigation, such as e.g. articles and meetings. It is also now possible to navigate from each of the sub-pages back to the event. The tables with registered and unregistered students are also hidden if there are no registrations yet.
The old link is removed and the back-link is added to the title.
**Before**
**After**
The back-link is also visible on all the sub-pages.
**Before**
**After**
The tables are hidden when there are no registered/unregistered students.
**Before**
**After**
---
Resolves ABA-239
=> EventAdministrate design improvements

app/routes/overview/components/CompactEvents.css, app/routes/overview/components/Overview.tsx, app/styles/utilities.css
Also adds left margin for headings on mobile
Fixes the y-alignment of pinned element & poll component. Also note that I removed the left margin of the top headers on desktop.
And adds some margin to the left of heading on small screens so there's some space between the screen edge.
**before**
**after**
**before**
**after**
=> Fix alignment of left/right overview columns

app/components/Image/ProfilePicture.tsx, app/components/Reactions/ReactionPicker.css, app/styles/overlay.css, app/styles/utilities.css
Fix dropdown overflow.
Add border to reactionpicker popover to get more depth and contrast.
|before|after|
|----|--------|
| ![image](https://user-images.githubusercontent.com/42850232/216821785-a2481aee-150c-4005-ba9b-2452c5680012.png) |![image](https://user-images.githubusercontent.com/42850232/216821742-e8a18c8d-8d77-4a76-834d-34b6bcd6a4fc.png)  |
|  ![image](https://user-images.githubusercontent.com/42850232/216821801-d9749be5-40dc-492a-83c3-4e3804fdf959.png)  |![image](https://user-images.githubusercontent.com/42850232/216821769-91297f6a-ed36-4649-bdc9-72c1f68bc05a.png) | 
---
Resolves ABA-242
=> Fix dropdown overflow & add border to reactionpick

app/routes/overview/components/LatestReadme.tsx, app/routes/overview/components/Overview.tsx
- refactor(LatestReadme): class component => functional
- feat(LatestReadme): animated collapse
Use the Collapse element from "react-select" to animate the LatestReadme component. This makes it much smoother to look at, as it does not jump from collapsed to expanded.
https://user-images.githubusercontent.com/26925695/216996880-0bac0748-3082-43c4-9b45-2950496f6725.mov
https://user-images.githubusercontent.com/26925695/216996393-b108e511-d472-44c2-8f95-140d57df5d77.mov
---
Resolves ABA-251
=> Add Collapse Animation To LatestReadme

app/routes/announcements/components/AnnouncementsList.tsx, app/routes/articles/ArticleCreateRoute.ts, app/routes/articles/components/ArticleEditor.tsx, app/routes/events/components/EventFooter.tsx, app/routes/interestgroups/components/InterestGroupList.tsx, app/routes/meetings/components/MeetingDetail.tsx, app/routes/meetings/components/MeetingEditor.tsx, cypress/e2e/router_spec.js
As described in https://github.com/webkom/lego/issues/3203, the back-link when creating a new article is not longer broken. The Cancel buttons in the meeting and article editors, while creating new instances of these, are now canceling the action and routing the user back to the meetings/articles page. Also, the back-link from the interest groups page is removed, as it isn't consistent with the other pages.
Additionally, the wording of the webapp is now consistently using "your" instead of "my" (e.g. your meetings). If someone has a strong opinion on having "my" instead of "your", don't hesitate to let me know :) 
This video shows the broken back-link and the Cancel button that is not working.
[Screencast from 06. feb. 2023 kl. 22.09 …
=> Fix navigation through back-links and cancel buttons

app/components/Modal/Modal.css, app/components/UserAttendance/AttendanceModal.css, app/routes/photos/components/GalleryPictureModal.css, app/styles/variables.css
The new modal, although very pretty, was really small on smaller devices. This PR increases the height for screens that are shorter than 900px high, so that there is less whitespace on top and more visible contents.  
It is also in general made a little bit wider.
|  | Before | After |
:------------------:|:-----------------------------:|:-----------------------------:
iPhone 12 Pro (390x844) | ![image](https://user-images.githubusercontent.com/13599770/217305625-a3a5ea78-c71a-4ec2-a149-dd44c8875780.png) | ![image](https://user-images.githubusercontent.com/13599770/217304486-79e5efb2-177f-4b49-9d3d-033632700e50.png)
Surface Duo (540x720)  | ![image](https://user-images.githubusercontent.com/13599770/217305500-a1617203-0207-44d4-af31-833b51d9dc93.png) | …
=> Increase size of modal on smaller screens

app/routes/pages/components/PageDetail.css, app/routes/pages/components/Sidebar.css
The text in the sidebar on mobile wasn't visible on dark mode due to white text on white background. I also changed the color of the sidebar button to red.
**Before:**
**After**
Sidebar button:
**Before**
**After**
Not much to test here.
=> Fix sidebar background color

app/routes/articles/components/ArticleEditor.tsx
Saving articles is broken in staging. It was simply an argument that was mistakenly removed from the `onSubmit` function in https://github.com/webkom/lego-webapp/pull/3526.
Articles can once again be saved!
I successfully saved an article in staging.
=> Fix article editor submit function

app/actions/EventActions.ts, app/models.ts, app/reducers/__tests__/events.spec.ts, app/reducers/events.ts, app/routes/events/EventDetailRoute.ts, app/routes/events/components/EventDetail/index.tsx, app/store/models/Event.d.ts
Depends on https://github.com/webkom/lego/pull/3214
There is a bug where the webapp does not correctly load the following status of the current user if an event has a large number of followers. It is caused by pagination on the event follower endpoint, but I figured a better solution than loading all pages in the webapp was to just include the single relevant follow in the event object.
The bug is no longer there.
I have tried following and unfollowing events multiple times. I have also tested that event detail page still works fine in logged out state.
---
Resolves https://github.com/webkom/lego/issues/2521
=> Fix event following bug by fetching follow-status through event object

app/routes/events/EventListRoute.ts, app/routes/events/components/EventList.tsx
Currently on /events, you'll get a loading indicator even though you have events stored. This is for obvious reasons unnecessary, and is fixed here.
**Before**
https://user-images.githubusercontent.com/69514187/218099688-faaacea5-44e9-4445-800a-431ae77b2d11.mov
**After**
Whenever the theme changes, that's me doing a hard refresh. Notice that I do a hard refresh on two different routes.
https://user-images.githubusercontent.com/69514187/218099269-ea8c28de-14c3-446c-87df-843a27094ec6.mov
Navigated between routes and did hard refreshes. This should not affect anything else.
---
Resolves ABA-267
=> Only show loading indicator when necesarry

app/routes/joblistings/JoblistingDetailedRoute.ts
Add helmet props to joblistings. This fixes the generic meta that  is displayed when sharing
joblistings urls on facebook, slack etc.
I tested that the properties are present when SSRing, and tested that it looks okay in an opengraph
debugger.
---
Fixes ABA-265
=> Add helmet og properties to joblistings

app/components/Card/Card.css, app/components/Card/index.tsx, app/routes/company/components/CompaniesPage.css, app/routes/company/components/CompaniesPage.tsx, app/routes/overview/components/EventItem.tsx, app/routes/overview/components/Pinned.tsx, app/routes/polls/components/PollsList.tsx
The cards now employ the `<Card />` component, making them resemble the rest of the webapp more. Also some other minimal styling changes. Finally, the whole card is a link, and not just the image, which has been an annoying bug for a really long time.
`CompaniesPage` is rewritten to a functional component.
`isHoverable` prop is added for cards that work as links.
**Before**
https://user-images.githubusercontent.com/69514187/218262039-63f5871d-414a-4c4e-8f1e-3428489a9dc8.mov
**After**
https://user-images.githubusercontent.com/69514187/218261983-40312029-efa0-4d6e-a58e-bc2eb7ec54a6.mov
Tested on light and dark mode, and on mobile (some minimal changes here to the expanded text functionality).
---
Resolves ABA-270
=> Improve /companies page

app/components/Chart/BarChart.tsx, app/components/Chart/PieChart.tsx, app/routes/surveys/components/Submissions/Results.tsx
Chart colors were wrong when some options had no responses. In this example all respondents responded with 4 or 5.
Before:
After:
The charts now show the correct colors even if some options are not included in the graph.
I have looked at the graphs, and compared with the individual responses.
---
=> Fix chart colors

app/components/Button/Button.css, app/components/Card/Card.css, app/components/CommentForm/CommentForm.css, app/components/Comments/Comment.css, app/components/Form/PhoneNumberInput.css, app/components/Modal/Modal.css, app/components/PhotoUploadStatus/PhotoUploadStatus.css, app/routes/events/components/Event.css, app/routes/events/components/EventAdministrate/Administrate.css, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/EventEditor/EventEditor.css, app/routes/events/components/JoinEventForm.tsx, app/routes/events/components/Stripe.css, app/routes/overview/components/Feed.css, app/routes/pages/components/Sidebar.css, app/styles/utilities.css, app/styles/variables.css
4 shadows of proportionally different sizes have been introduced, which all use the same color. I've not added shadows to any new places.
Not really any major visual changes. The shadow on the cards remain the same, so you can check them out.
Went through all uses of `box-shadow`. Since I've not added any new shadows anywhere, this should not affect anything else.
=> Standardize our shadows

app/routes/pages/PageDetailRoute.ts, app/routes/pages/components/PageHierarchy.tsx, app/routes/pages/components/Sidebar.tsx
You can now visit any page and the correct category will be expanded.
This is done by using the url pathname to determine which category we're currently in, instead of it being passed down as prop.
https://user-images.githubusercontent.com/69514187/218572725-f30825a0-b921-4363-bcb2-3c000e11201c.mov
Tested for "info-om-abakus" (which is an edge case), and for when you're not logged in.
=> Expand sidebar element based on pathname

app/components/UserAttendance/AttendanceModal.css, app/components/UserAttendance/AttendanceModal.tsx, app/components/UserAttendance/withModal.tsx, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/EventEditor/index.tsx, app/routes/meetings/components/MeetingDetail.tsx
[Include waiting list to summary pool tab](https://github.com/webkom/lego-webapp/commit/445fa3ab8b67b4698733d815fb788dac148a5238) 
It makes more sense to include everyone in this tab, and it's annoying to
have to check multiple tabs when looking for someone.
People on waiting list are given an opacity to their row as a visual label.
`isMeeting` prop had to be added, because meeting registrations don't
have pools the same way events does.
---
[Rewrite AttendanceModal to a functional component](https://github.com/webkom/lego-webapp/commit/2c5428b4b0d04332db728ba41557faa30b2158fc)
Please check out the changes locally, as I'm not going to show the names of registered users.
The attendance modal is used on events and meetings, and I've tested for both. Also tested for when there is no waiting …
=> Include waiting list to summary pool tab

cypress/e2e/event_visit_spec.js
Fixes two errors with the comment testing in the event_visit_spec. The first is not waiting after cypress.get() which caused an error. The second is the cypress tests sometimes missing the comment form. Due to using a hook rather than having the props passed down, the send announcement button will get its actiongrant after the page has been loaded. This causes the button for sending an announcement to appear after the page has been loaded. This *sometimes* caused the cypress test to fail as the comment is pushed a bit down between selecting and clicking. This is "solved" by waiting for a little bit after loading.
If the cypress tests actually passes, this works
=> Fix cypress tests failing for event_visit_spec

app/routes/users/components/UserSettings.tsx, app/utils/validation.ts
It's surprisingly common for people to write "ingen/nei".
Tested with and without valid inputs.
=> Validate user allergy input

app/routes/overview/IndexRoute.ts, app/routes/overview/components/Overview.tsx
When fetching the frontpage, its length would be `0` causing the card to be expanded. This made it look buggy.
**Before**
https://user-images.githubusercontent.com/69514187/218763093-8b427a89-a6b0-4d36-985a-3820ab91f399.mov
**After**
https://user-images.githubusercontent.com/69514187/218762686-648e0800-9262-4d02-815c-f5f9cf3817e2.mov
See result above.
=> Stop latest readme card from expanding during fetch

app/routes/pages/components/LandingPage.css, app/routes/pages/components/LandingPage.tsx, app/routes/pages/components/PageDetail.css, app/routes/pages/components/subcomponents/EmailItem/EmailItem.css, app/routes/pages/components/subcomponents/TextWithTitle/TextWithTitle.css, app/routes/pages/components/subcomponents/TextWithTitle/index.tsx
Key points:
* Prevent overflow
* Fill available space
* Add more responsive breakpoints.
* Prevent padding on top caused by a not specific enough selector
It requires a loot of pictures to showcase every edge case of this change, so to check every screen size you'd rather have to pull this and test it locally.
Before: unnecessary padding on top + overflow on the right side
After
Before: doesn't fill the entire page
After: equal paddings on the right and left side
Before: the breakpoints are either desktop or mobile, where mobile is a single row even if its pretty wide
After: three breakpoints, with 3, 2 and 1 columns depending on the screen size
=> Small fixes on infopage design

app/routes/pages/components/PageHierarchy.css, app/routes/pages/components/PageHierarchy.tsx
They would disappear on hover, and act weirdly.
https://user-images.githubusercontent.com/69514187/219899321-69f9b30b-ab82-460a-9c38-4bca7e1dadec.mov
Tested on Safari and Google Chrome.
=> Stop arrow icons from disappearing on Safari

app/routes/events/components/StripeElement.tsx
`submit` prop was missing, causing  `handleSubmit` to never be triggered.
I tested that the button now triggers the handle function, unlike before.
=> Make sure payment button is a submit button

app/components/CollapsibleDisplayContent/CollapsibleDisplayContent.css, app/components/CollapsibleDisplayContent/index.tsx, app/components/DisplayContent/index.tsx, app/routes/company/components/CompanyDetail.tsx
Make company descriptions over a certain length collapsible, making the succeeding components more accessible.
**Before**
**After**
Long description: 
Forgot to record in light theme, but here's how that looks^
Short descriptions will not have the option to expand the content
Ensured that the component does not perform any unnecessary animation while loading into the page with short or long content. Made sure the interactions works nicely on mobile as well:)
---
Resolves [ABA-294](https://linear.app/abakus-webkom/issue/ABA-294)
=> Make company descriptions collapsible

app/components/Form/Field.css, app/reducers/companyInterest.ts, app/routes/bdb/EditCompanyRoute.ts, app/routes/companyInterest/CompanyInterestEditRoute.ts, app/routes/companyInterest/CompanyInterestRoute.ts, app/routes/companyInterest/components/CompanyInterest.css, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/companyInterest/utils.tsx, app/store/models/CompanyInterest.d.ts, package.json, yarn.lock
Edited company interest page with long awaited features that were requested by "interkom".
- Added company survey checkboxes
- Relocated about company field to the top of the form
- Added description fields for each event type
- Added accomodating radio button
The backend side of all above charges have been implemented and there already exists  a pull request for them.
- And lastly made some minor changes to the styling of check boxes to improve the alignment
**after**
We have thoroughly tested our changes on the webside. We tested that the newly created field and checkboxes work properly and actually push the data to the backend. And also that the newly edited data show up after reopening the form
=> Edit company interest

app/components/Form/LegoFinalForm.tsx, app/components/Form/utils.ts, app/routes/quotes/QuoteDetailRoute.ts, app/routes/quotes/QuoteEditorRoute.ts, app/routes/quotes/components/AddQuote.tsx, app/utils/formSpyUtils.tsx
Rewrote from redux-form to react-final-form. Also changed from `TextAreas` to `TextInput`.
Before:
After:
I added a quote
---
Resolves ABA-55
=> Rewrite quote form to react-final-form

app/components/EventItem/index.tsx, app/components/TextWithIcon/TextWithIcon.css, app/components/TextWithIcon/index.tsx, app/routes/company/components/Company.css, app/routes/company/components/CompanyDetail.tsx, app/routes/events/components/Calendar.css, app/routes/events/components/CalendarCell.tsx, app/routes/events/components/EventDetail/EventDetail.css, app/routes/events/components/EventDetail/index.tsx
Text is displayed with icons throughout the whole webapp. However, there is no component or common way of doing this. With the `<TextWithIcon />` component there is now a generalized component that can be used for this purpose. An example of usage can be seen here:
There should be no visual changes to the text with icons.
Also fixes some TS errors and moves the tooltip on `<EventDetail />` to be on the icon rather than the text.
**Before**
**After**
Tested by clicking through where changes have been done.
---
Resolves ABA-293
=> Create TextWithIcon component

app/routes/companyInterest/components/CompanyInterest.css, app/routes/companyInterest/components/CompanyInterestPage.tsx
Moved interest form event type field describers from below the description to above the description as requested by "interkom"
before: 
before:
I have thoroughly tested my changes on window and app
=> Edit interest form event type field describers

app/routes/events/EventAllergiesRoute.ts, app/routes/events/components/EventAdministrate/Allergies.tsx, app/routes/events/components/EventAdministrate/Attendees.tsx, app/routes/events/components/EventAdministrate/RegistrationTables.tsx, app/routes/events/components/EventAdministrate/index.tsx, app/routes/events/index.tsx
As discussed previously, I have now created a seperate tab for allergies in EventAdministrate. Currently anyone can still see all the allergies, but we can add an anonymized list later on.  
Before:
After:
Newst version:
Most of the code in Allergies.tsx and EventAllergiesRoute.ts was copied and slightly altered from Attendees.tsx and EventAttendees.ts. Unsure if everything is necessary or if there is anything I should have done differently, please let me know if so. 
Resolves ABA-175
=> Created Allergies Tab

app/components/UserAttendance/AttendanceModal.tsx
This broke SSR on events. lodash-es does some special stuff with
aliasing that is not supported on SSR (see config.client.js), thus
breaking the dynamic importing of loadable.
SSR on eventDetail works.
---
Resolves ABA-297
=> Fix "cannot load before initialization" error

app/routes/events/EventAbacardRoute.ts, app/routes/events/components/EventAdministrate/Abacard.tsx
Must have been mistakenly removed in a recent commit. This removes the
`?` prefix from the query.
Fix abacard search.
=> Add missing `ignoreQueryPrefix` to abacard route

app/routes/articles/components/ArticleEditor.tsx
At the moment, pressing the delete button in the ArticleEditor results in directly deleting the article. This is not consistent with the rest of the webapp, as a modal or some kind of confirmation is usually needed to delete elements. Therefore, to avoid an article being deleted without confirmation, the delete button is wrapped in a `<ConfirmModalWithParent />` component.
**Before**
[Screencast from 27. feb. 2023 kl. 16.39 +0100.webm](https://user-images.githubusercontent.com/43182025/221609287-6d251bf9-f0ae-4b8f-8a5a-cc3390a93963.webm)
**After**
[Screencast from 27. feb. 2023 kl. 16.41 +0100.webm](https://user-images.githubusercontent.com/43182025/221609795-ba5254f9-b75e-47c2-b020-be252926b209.webm)
Tested manually by deleting an article in staging.
---
Resolves ABA-309
=> Wrap delete button in ArticleEditor in ConfirmModal

app/components/CollapsibleDisplayContent/index.tsx, app/components/EventListCompact/EventListCompact.css, app/components/EventListCompact/index.tsx, app/routes/company/components/Company.css, app/routes/company/components/CompanyDetail.tsx, app/routes/users/components/UserProfile.tsx
After the redesign of `<CompanyDetail />` there are some small issues to address. As can be seen in the image below, the fonts for "Ingen kommende arrangementer" and "Ingen tilgjengelige jobbannonser" are different. Also, for companies without info in the sidebar, the vertical line can be seen without any content on the right side. These issues are now solved, as well as moving the `<LoadingIndicator />` inside `<EventListCompact />` instead of wrapping the loading indicator around all of the event lists separately. Not that many visual changes, other than the font and the vertical line.
In addition, the company description is not longer italic.
**Before**
**After**
**Before**
**After**
Changes have been tested visually both with light and dark mode.
---
Resolves ABA-310
=> Redesign CompanyDetail v2

app/utils/eventStatus.ts
Someone pointed out an event with infinite number of places showed x/0 in the listrings-views
Used code from the same file (line 78)
Before:
After:
Inspected images above, and made sure the other event-items looked the same:)
---
=> Use correct symbol on EvenStatus-component

app/components/Form/TextInput.css, app/components/Form/TextInput.tsx, app/routes/companyInterest/components/CompanyInterest.css
[Fix bug where border was gone from text inputs](https://github.com/webkom/lego-webapp/commit/43e7c84c9f893a6b6371d1ed88cc3297173e0009) 
`border: initial` didn't work.
:------------------:|:-----------------------------:
---
[Do not override all icons to be 20px ..](https://github.com/webkom/lego-webapp/commit/8828e983eacdeac3c7646dcbaf4214bc6893cd27) 
This unspecific styling cascaded to all other ion icons.
Introduced in #3608. I even pointed it out 😠
:------------------:|:-----------------------------:
See results above.
---
Resolves ABA-315
=> 2 bugs 1 pr

app/components/Form/TextArea.tsx
I don't get the difference between the two ...
**Before**
**After**
=> Compose text area styling from text editor

app/reducers/events.ts, app/routes/events/components/EventList.tsx, app/routes/events/utils.ts, app/routes/overview/components/CompactEvents.tsx, app/routes/surveys/EditSurveyRoute.ts, app/utils/eventStatus.ts
There was problems with storing non-serializable `moment` objects in the redux store. Issue is fixed by turning event dates into ISO strings.
Multiple places used the dates directly as `moment` objects, which now needs to be wrapped in a `moment()` function. This is the way it's done elsewhere in our codebase.
https://user-images.githubusercontent.com/69514187/224502008-9c1cf9a8-9e89-4462-ae7c-f39358eac162.mov
See video above. 
More testing is needed, as I was experiencing some weird behaviour.
Pages will crash if you try to perform `moment` related functions on a string, so I need to make sure there's no such thing left.
=> Stop event editor from breaking in dev

app/components/Form/SelectInput.tsx
When on mobile react-select would call onBlur on select. This caused the value to change, but very soon after that it would change back to the original value (empty for new fields/events)
The actual fix is only on the new line 141, the rest is improved types.
Now it doesn't blur on select (which it didn't do on desktop and now doesn't on mobile either)
I have only tested it on the edit event view, but I assume that it will work the same way everywhere it is used.
It is not actually tested on mobile, only on chrome devtools, but the bug was there to begin with so I hope this will also resolve it for mobile.
---
Resolves ABA-328
=> Fix bug where select blurred on select for mobile

app/routes/overview/components/Overview.tsx
The frontpage would sometimes show past events if they were loaded in from a different route. This fixes it by filtering out all past events.
The following images are taken after entering the event-calendar page, and then navigating to the front page.
**before**
The circled dates are in the past, and should not be there.
**after**
This is now equivelant to how it would look if you entered straight to the frontpage
Clicked around a lot, trying to load many events then observed the results in my dev environment vs production.
---
Resolves ABA-331
=> Filter out past events from frontpage

app/components/Content/ContentSidebar.tsx, app/components/Form/Field.tsx, app/routes/events/components/EventDetail/EventDetail.css, app/routes/surveys/AddSurveyRoute.ts, app/routes/surveys/EditSurveyRoute.ts, app/routes/surveys/TemplatesRoute.ts, app/routes/surveys/components/AdminSideBar.tsx, app/routes/surveys/components/SubmissionEditor/SubmissionEditor.tsx, app/routes/surveys/components/SurveyEditor/Option.tsx, app/routes/surveys/components/SurveyEditor/Question.tsx, app/routes/surveys/components/SurveyEditor/SurveyEditor.tsx, app/routes/surveys/components/SurveyList/SurveyList.tsx, app/routes/surveys/components/SurveyList/SurveyPage.tsx, app/routes/surveys/components/surveys.css, app/routes/surveys/utils.tsx
[Minor changes to surveys pages](https://github.com/webkom/lego-webapp/commit/1b0b1558dd73e7769068127ff5c5eb6a3d2829c3) 
Add a "cancel" button to the editor and a "back" navigator.
Other than that just styling changes.
---
[Rewrite survey editor to a functional component](https://github.com/webkom/lego-webapp/commit/745180a8e33f5c1d41ca4f032a2b95c2b6a1e59c)
---
[Migrate survey editor to react-final-form](https://github.com/webkom/lego-webapp/commit/a9f0f246b0ac11b00bf768dbf8a3ec687c7abd7a)
The changes to the `<Field />` component has been checked with fields in `redux-form` forms using the `onChange` prop.
Editing works for the three different options; radio buttons, check boxes and text areas.
---
Related to ABA-54 (`redux-form` is still used on the actual survey form)
=> General changes to surveys

package.json, yarn.lock
Bumps lego-editor to support no overflow, linethrough and correct coloring for link input fields.
Seems to work(:
Long ass dividers no longer overflow<3
=> Bump lego-editor from 2.0.3 to 2.1.0

app/models.ts, app/reducers/index.ts, app/reducers/meetings.ts, app/routes/meetings/MeetingDetailRoute.tsx, app/routes/meetings/components/MeetingDetail.css, app/routes/meetings/components/MeetingDetail.tsx, app/store/models/Meeting.d.ts
=> Add reactions to meetings. Rewrote meeting from class component -> hook.

app/routes/quotes/components/AddQuote.tsx
People keep adding a dash at the beginning of a quote source, even though a dash is added automatically when submitting. This PR will resolve this issue by removing a dash if it's the first non-space character of the source.
**Before**
**After**
I've tested for numerous sources. Notably, you can still have a source like "Ola-Nordmann" without the "Ola-" part being cut out. Again, it will only remove the dash if there are ONLY spaces in front of the dash.
---
Resolves ABA-338
=> Filter out unnecessary dash at the start of a quote source

app/components/LoginForm/LoginForm.tsx, app/routes/companyInterest/CompanyInterestEditRoute.ts, app/routes/companyInterest/CompanyInterestRoute.ts, app/routes/companyInterest/components/CompanyInterestPage.tsx
They did not work due to `type="radio` being passed, since this causes, `react-final-form` to include a `checked` prop as well.
There was also a seperate bug with the "office in Trondheim" question not working, since you the object keys were booleans.
I created and edited interest forms. I especially tested the "office in trondheim" question.
=> Make radio buttons in interest form work

.drone.yml
=> Exclude `setup` step from `build` CI pipeline

app/components/Form/ObjectPermissions.tsx, app/reducers/index.ts, app/reducers/users.ts, app/routes/articles/ArticleCreateRoute.ts, app/routes/articles/ArticleDetailRoute.ts, app/routes/articles/ArticleEditRoute.ts, app/routes/articles/ArticleListRoute.ts, app/routes/articles/components/ArticleDetail.tsx, app/routes/articles/components/ArticleEditor.tsx, app/routes/articles/components/Overview.tsx, app/routes/events/utils.ts, app/store/models/Article.d.ts, app/types.ts
Option to add multiple/other users as author on articles.
Before:
After:
Before:
After:
After:
- [ X] I have thoroughly tested my changes.
---
Depends on: https://github.com/webkom/lego/pull/3220
Resolves: https://github.com/webkom/lego/issues/3195
=> Allow multiple and other authors on articles

app/reducers/companyInterest.ts, app/routes/companyInterest/CompanyInterestListRoute.ts, app/routes/companyInterest/components/CompanyInterest.css, app/routes/companyInterest/components/CompanyInterestList.tsx, app/routes/companyInterest/components/CompanyInterestPage.tsx, app/routes/companyInterest/utils.tsx
- Implemented filtering company interests by event type, one similar to the filtering by semester.
- Implemented interface for exporting company interests to csv file. The exporting is filtered by semester and event type
- The backend implementation was done in here: [#3231](https://github.com/webkom/lego/pull/3231)
=> Export company interests to csv

app/routes/companyInterest/components/CompanyInterestList.tsx
Integrate the latest css changes to the companyInterestList page with the newly implemented csv export button.
before:
after:
=> Fix css of companyInterest export button

app/routes/surveys/components/SurveyEditor/SurveyEditor.tsx, app/routes/surveys/utils.tsx
The `error` object was not a valid child of the span. Since it did not work as intended and I do not see the value in fixing it, I simply removed it.
Also add a navigation tab back to the survey list, as it was much needed.
It now does not crash.
=> Stop survey creator page from crashing on load

app/components/UserAttendance/withModal.tsx, app/models.ts, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/JoinEventForm.tsx, app/routes/events/utils.ts
We don't check if the event uses penalties before calculating the
activation time. Also the calculation subtracted hours instead of adding
for some reason.
Also fixes random type errors in the mix here.
The correct time is shown
---
Resolves ABA-356
=> Only calculate penalty reg time if heedPenalties

app/components/Search/Search.css
readme overflows on the quicklinks dropdown menu on my iphone 12 pro (in google chrome):
This pull request adds a bit more padding to the bottom of the menu (32px->48px), a safe margin is ~50px https://developer.apple.com/documentation/apple_news/margin
=> add more padding to bottom of quicklinks

app/actions/GalleryPictureActions.ts, app/components/Card/Card.css, app/components/Card/index.tsx, app/routes/events/components/Event.css, app/routes/events/components/EventAttendeeStatistics.tsx, app/routes/events/components/EventDetail/index.tsx, app/routes/events/components/JoinEventForm.tsx
Replaces our current use of the `eventWarning` css class across the webapp.
Probably going to iterate on the styling later when extending the component further soon with `info`, `success` and `warning`.
Top card is the current look, while the bottom is with the change.
<p align="center">
</p>
Went through all uses of `styles.eventWarning`. The danger card might be applicable to other places, but that can come later.
=> Extend Card component with a `danger` prop

app/components/Form/Field.css, app/components/Form/SelectInput.tsx, app/routes/admin/email/components/RestrictedMailEditor.tsx, app/routes/articles/components/ArticleEditor.tsx, app/routes/surveys/components/SurveyEditor/Question.tsx, app/routes/surveys/utils.tsx, app/styles/variables.css
They now share the styling of all the other input fields in all ways. This makes them feel much more at home, and they no longer stick out much.
Also, add the custom styling to the select used for tags (specified by the `tags` prop), since that was missing.
I don't feel like the images do its justice. They are now muuch better.
<details>
<summary>Overview</summary>
They are especially improved on dark theme.
**Before**
**After**
</details>
---
<details>
<summary>Open dropdown</summary>
**Before**
**After**
</details>
---
<details>
<summary>Error</summary>
**Before**
**After**
</details>
---
<details>
<summary>Bug?</summary>
**Before**
**After**
</details>
Tested that they still work. Multi selectors were tested after the removal of their `tags` prop.
=> Make selectors feel more at home

app/routes/index.tsx, app/routes/interestgroups/index.tsx
Some time ago "interestgroups" were changed to "interest-groups", which caused broken links. These are fixed by recognizing both "/interest-groups" and "/interestgroups" as being valid paths.
https://user-images.githubusercontent.com/69514187/230785932-e12d5221-0d63-4f0a-8d9c-c66d3513fe90.mov
See video above.
=> Recognize broken interest groups links as valid

app/components/Card/index.tsx
Kind of an ugly fix imo., but it'll be cleaned up in the soon-to-be iteration. Nevertheless good to get this fixed in the meantime.
`danger` card still works.
=> Stop default card content from being flex aligned

app/components/Form/CheckBox.tsx, app/components/Form/Field.tsx, app/components/Form/RadioButton.tsx
On the server, the component name would be undefined, resulting in the label not being inline. But, on the client side this would actually work, resulting in an error stating that the rendered content did not match what was server-rendered.
The labels still align as expected.
<p align="center">
</p>
For some reason I don't get to test this through `yarn ssr`, but the cypress test passed without errors so we're all good.
=> Render fields correctly on the server

app/components/Tags/Tag.css, app/components/Tags/Tag.tsx, app/routes/surveys/components/Submissions/Results.tsx, app/styles/variables.css
The colors in the tags are more "supported", and the design on the pills are outdated.
"orange" had to be introduced as a tag color.
Also fix an issue where it would print "NaN" during fetching.
=> Replace pill in survey result with tag

app/components/Form/RadioButton.css, app/components/Form/RadioButton.tsx, app/routes/bdb/components/OptionsBox.tsx, app/routes/joblistings/components/JoblistingRightNav.tsx, app/routes/users/components/UserConfirmation.tsx
It now shares the same transition time and "bounce" as the
CheckBox, which makes them resemble each other far more.
Its label now aligns itself better as well.
**Before**
https://user-images.githubusercontent.com/69514187/232163632-6b5f5248-a62a-4a29-897d-a0b6ef509847.mov
**After**
https://user-images.githubusercontent.com/69514187/232163455-a8f69e3d-6613-492c-baff-459f4293b989.mov
https://user-images.githubusercontent.com/69514187/232163444-4a2bdfb1-d0a4-4fe2-ba7d-0ad65b8a0b1d.mov
Tested radio buttons in and outside of forms.
=> Give our RadioButton a retouch

app/actions/ActionTypes.ts, app/actions/GroupActions.ts, app/components/GroupForm/index.tsx, app/components/Table/index.tsx, app/models.ts, app/routes/admin/email/EmailListRoute.ts, app/routes/admin/groups/components/AddGroupMember.tsx, app/routes/admin/groups/components/GroupMembers.css, app/routes/admin/groups/components/GroupMembers.tsx, app/routes/admin/groups/components/GroupMembersList.css, app/routes/admin/groups/components/GroupMembersList.tsx, app/routes/admin/groups/components/GroupPermissions.tsx, app/routes/admin/groups/components/GroupSettings.tsx, app/routes/interestgroups/components/InterestGroupDetail.tsx, app/routes/interestgroups/components/InterestGroupMemberList.tsx, app/store/models/Membership.d.ts, app/store/models/PastMembership.d.ts, app/store/models/User.d.ts, app/utils/constants.ts
[Minor changes to (interest) groups page](https://github.com/webkom/lego-webapp/pull/3757/commits/e469ee2c8ce41b4f67b04a0058efcef50b47208e)
---
[Support changing group roles in the membership table](https://github.com/webkom/lego-webapp/pull/3757/commits/e9956ced3c931e9b7aa378679fd69e5f521f4216) 
Previously, you had to remove the user from the group and re-add them
back with a different role. You may now simply change the user's role
directly in the membership table.
---
[Type group roles correctly](https://github.com/webkom/lego-webapp/pull/3757/commits/00dff1856cbb61f7d178a7e359ee77cf7c47ef71)
**Before**
**After**
https://user-images.githubusercontent.com/69514187/230737973-c19d4003-72e3-4ec2-bf9d-64e00d22c788.mov
I have tested it thoroughly, but I plan on testing it even more ... Might …
=> Support changing group roles in the membership table

app/routes/photos/components/GalleryPictureModal.css
The media query was not needed.
Tested on mobile view, as shown above.
=> Stop gallery modal from overflowing on mobile

app/routes/overview/components/LatestReadme.tsx, app/routes/overview/components/PublicFrontpage.css, app/routes/overview/components/PublicFrontpage.tsx
Fix readme sizing on public frontpage.
**before**
**after**
Tested public and logged in pages on desktop and different mobile sizes.
---
Resolves ABA-397
=> Fix readme sizing on public frontpage

app/routes/users/components/PasswordStrengthMeter.tsx, package.json, yarn.lock
Use the new version of react-meter-bar I just merged here: https://github.com/webkom/react-meter-bar/pull/2
We no longer install React 16, as the peer-dependency in react-meter-bar is updated to support React 18. We also get the new typescript types for react-meter-bar.
The meter bar component still works.
---
Resolves ABA-398
=> Update react-meter-bar to v2

app/reducers/events.ts, app/routes/events/EventDetailRoute.ts, app/routes/events/EventEditRoute.ts, app/routes/events/index.tsx
To make links prettier, show the slug of the event in the url bar instead of the id. Currently, /events/id will be redirected to /events/slug and /events/slug will work and the url will not change.
Feedback appreciated, backend is here: https://github.com/webkom/lego/pull/3260
https://user-images.githubusercontent.com/64247965/227374605-57846b4a-7429-41e8-be51-19988787e905.mov  
###
Before, url would be `http://localhost:3000/events/14`
Seems to work fine 🤷 
---
=> Add slugs to events

app/components/UserAttendance/AttendanceStatus.tsx
For the overview of registrations on events we add an anonymous pool when a registered user has been deleted (so that one can get accurate numbers for registrations for old events without breaking any GDPR rules). This PR just adds a tooltip explaing that this anonymous pool represents deleted users.
Before (when hovering over the anonymoys-text):
*Exactly the same as after, just without the tooltip*
After (when hovering over the anonymoys-text):
- [ x] I have thoroughly tested my changes.
---
Resolves ABA-404
=> Add tooltip explaining anonymous attendees events
